### ISSUE TITLE
New license request: EPICS [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by matwey** [spdx/license-list-XML#1012]
**1.** License Name: EPICS Open License
**2.** Short identifier: EPICS
**3.** License Author or steward: 
**4.** Comments: 
**5.** Standard License Header: 
**6.** URL: https://epics.anl.gov/license/open.php
**7.** OSI Status: Not Submitted

**Comment by jlovejoy** [comment]
@matwey - do you have some examples of where this license is used?

**Comment by matwey** [comment]
> @matwey - do you have some examples of where this license is used?

https://github.com/pyepics/epicsapps
https://git.launchpad.net/epics-base

**Comment by johnmhoran** [comment]
I'll take this.

**Comment by swinslow** [comment]
EPICS Open License -- see https://launchpad.net/epics-base

Discussed on 2020-06-04 legal team call, in favor of adding, link above gives EPICS Open License as name. @jlovejoy to submit bug to launchpad account for epics-base to ask them about preference for name + ID, including whether we should include a version number.

**Comment by jlovejoy** [comment]
add bug there to link to here and make license steward aware: https://bugs.launchpad.net/epics-base/+bug/1882120

**Comment by jlovejoy** [comment]
Note that the canonical URL for the license is https://epics.anl.gov/license/open.php with some discussion and history at https://epics.anl.gov/license/index.php

**Comment by anjohnson** [comment]
I am a lead developer and co-chair of the EPICS Core Developers Group, the software developers responsible for maintaining the core of the EPICS Control system toolkit. I maintain the [EPICS website](https://epics.anl.gov/) at Argonne National Laboratory where the license links @jlovejoy and @matwey posted point to. The EPICS community also maintains a more polished public website at [epics-controls.org](https://epics-controls.org/).

Some background on the license itself: Development of the EPICS software started in the late 1980s with a closed distribution managed by Los Alamos National Laboratory. From 2000 to 2004 EPICS Base could be obtained from the Argonne National Laboratory subject to US EAR99 restrictions under the closed-source EPICS Base License. The code was relicensed and made publicly available under the EPICS Open License in 2004. The license wording was developed by the legal department at Argonne, who mandated the inclusion of paragraphs 5, 6 and 7.

I have been responsible for handling EPICS licensing since 2001, and should be named as the license steward. There is no need for a version number; If we do ever decide to relicense the EPICS Base code we would almost certainly adopt one of the more common BSD-like licenses instead of modifying this one. EPICS is an acronym (Experimental Physics and Industrial Control System), so the identifier for this license should preferably be just `EPICS`.

**Comment by jlovejoy** [comment]
Thanks @anjohnson ! It's always helpful to have the background on a license. 

looks like the original suggestion for the full name and short identifier from @matwey is correct and in line with the usage, so we'll go with that. 

You might want to have a look at https://spdx.dev/ids/ if you are not familiar with how the short ids can be used in source code (if you want any additional info on that, probably easier to use mailing list to answer more general questions)

**Comment by anjohnson** [comment]
I will look at adding the short ID to our sources. Should we wait to do that until after this request has been approved, presumably when this GitHub issue gets closed?

**Comment by swinslow** [comment]
Hi @anjohnson, this has now been merged in #1053. 

It won't show up on the main SPDX license list at https://spdx.org/licenses until the next release (likely end of July), but you can feel free to start using the `EPICS` license identifier anytime since it has now been merged. 

Thanks! And thank you @matwey for reporting and @johnmhoran for submitting the PR.
