### ISSUE TITLE
A code for "Missing license"

### ISSUE THREAD

**Issue by GeertJohan** [spdx/license-list-XML#1013]
Could we assign a code to "Missing License"?

The code could be used to indicate to systems that no license has been assigned yet. In a project I'm working on we're now using "FIXME" as a license code, but it is quite unspecific and not present on the SPDX list. I believe it would help if there was consensus on a code to use for when no license is present. Perhaps there can also be some linked information about what the effects are (legally) when an author has not selected a license.

**Comment by swinslow** [comment]
Hi @GeertJohan, thanks for reaching out. When no license is present, this is defined by the underlying SPDX specification (rather than an entry on the license list). The correct code to use would be `NONE`. 

This is described in various parts of the spec, depending on the context, but here is an example from [the File level "Concluded License" section](https://github.com/spdx/spdx-spec/blob/development/v2.2/chapters/4-file-information.md#45-concluded-license-):

> The options to populate this field are limited to:
> . . .
> NONE, if the SPDX file creator concludes there is no license available for this file; or
> . . . 

There is also a related value for NOASSERTION that you can also read about there, if you feel that is more applicable to your situation.

**Comment by GeertJohan** [comment]
Thanks!

I didn't see that specs and assumed if the value would exist it would be in the list of allowed values. Thanks for the fast reply and clear answer :smiley:

**Comment by swinslow** [comment]
No worries at all, glad I could help  :)
