### ISSUE TITLE
Update Fair License link

### ISSUE THREAD

**Issue by themaxdavitt** [spdx/license-list-XML#1024]
The [first link listed for the Fair License](https://github.com/spdx/license-list-XML/blob/76072fc48c2b97df008b989fbb96c52c9296c178/src/Fair.xml#L5) was seemingly [taken over by domain squatters](http://fairlicense.org). [Here](https://web.archive.org/web/20171019221525/http://fairlicense.org/) is the last good version I could find of it on the Wayback Machine. I understand that [inactive URLs aren't removed](https://spdx.org/spdx-license-list/license-list-overview#fields), but what should we do in this scenario? It's the same content that was at that link originally, it's just technically a different URL, so personally I think it would just make sense to swap the links.

I'd be happy to submit a PR after hearing your guys' thoughts.

**Comment by swinslow** [comment]
Hi @themaxdavitt, thanks for reaching out.

We include links to other websites for the licenses on the license list not just to provide a source for the license text (since the SPDX License List contains the license text itself). Instead, one key reason is because often people may use URLs in their code to refer to licenses. Whether or not that's a good practice, it is one that often happens, and so by including the URLs on the license list it can aid both humans and automated tools in tying together a URL in source code with the corresponding license.

That's one of the main reasons why we don't remove old URLs, even when their websites are no longer active or relevant.

**Comment by themaxdavitt** [comment]
That's makes sense, I had only thought about the links being used for conveying additional information about the licenses. Closing the issue!
