### ISSUE TITLE
HPND template may be broken

### ISSUE THREAD

**Issue by alandtse** [spdx/license-list-XML#1054]
Was testing something and noticed the HPND template is missing at least one `<<endOptional>>`.

I've cut out everything that passed until the double `<<beginOptional>>`

```
 copyright notice and this permission notice appear in supporting documentation<<beginOptional>> , and that the name<<beginOptional>> of<<endOptional>> 
```

I couldn't find the matching guidelines on `beginOptional` so perhaps there's nesting behavior that's allowed that I missed?

**Comment by swinslow** [comment]
Thanks @goneall and @alandtse. Looks like this one is nested because of the original bracketing on the OSI site: https://opensource.org/licenses/HPND

Not sure we should really remove the nesting, given the OSI-approved definition here, if there's a way that we can appropriately accommodate it.

@goneall I'm not sure if I understood your suggestion, but I defer to you on what's feasible here...

**Comment by goneall** [comment]
@swinslow The LicenseListPublish and the Java tools do accommodate this nesting already.  The spec, however, doesn't allow it.  I would recommend updating the spec.

If there are other's who are implementing the license matching templates, it may well complicate their design and implementation.

I submitted an issue against the spec to track: https://github.com/spdx/spdx-spec/issues/429

**Comment by pmadick** [comment]
@goneall Can we close this issue or since it is being handled as an issue in the spec?  If not, we should have a short conversation to discuss path forward.

**Comment by goneall** [comment]
@pmadick Yes - I'll go ahead and close this since the spec issue is already submitted
