### ISSUE TITLE
New license request: OGDL-Taiwan-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by liuxinyu970226** [spdx/license-list-XML#1112]
**1.** License Name: Taiwan Open Government Data Licence
**2.** Short identifier: OGDL-Taiwan-1.0
**3.** License Author or steward: Taiwan National Development Council
**4.** Comments: This is useful to identify Taiwanese free and open access government works. See more examples at https://data.gov.tw/about
**5.** Standard License Header: Open Government Data License, version 1.0
**6.** URL: https://data.gov.tw/license
**7.** OSI Status: Not Submitted

**Comment by mlinksva** [comment]
I'd suggest a short name of `OGDL-Taiwan-1.0` as similar to `OGL-Canada|UK-version` licenses already cataloged.

The licensor is stipulated to be a government agency, and the governing law is Taiwan, so it's fairly specific.

FWIW it was submitted to https://discuss.okfn.org/t/license-approval-request-open-government-data-license-taiwan-1-0/4593 which has roughly equivalent to OSI criteria for open [data] licenses. (Clearly it should not be marked as OSI approved, it isn't.)

**Comment by liuxinyu970226** [comment]
@mlinksva +1

**Comment by audreyt** [comment]
@mlinksva +1

As Taiwan’s digital minister and originator of the OKFN request, I’m happy to echo this proposal.

I changed the `License` in the name from the `Licence` spelling to agree with the name used in the original text; otherwise kept verbatim.

1. License Name: Taiwan Open Government Data License
2. Short identifier: OGDL-Taiwan-1.0
3. License Author or steward: Taiwan National Development Council
4. Comments: This is useful to identify Taiwanese free and open access government works. See more examples at https://data.gov.tw/about
5. Standard License Header: Open Government Data License, version 1.0
6. URL: https://data.gov.tw/license
7. OSI Status: Not Submitted

**Comment by swinslow** [comment]
Thanks for the submission, @liuxinyu970226 and @audreyt!

In looking at whether or not to add a license to the [SPDX License List](https://spdx.org/licenses), we evaluate them in light of the [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). Here's my quick run-down of thoughts from holding those up to the OGDL-Taiwan-1.0:

**Definitive factors**: The license does appear to meet all of these, with the note that it is not OSI-approved. I am assuming that the license text for this version is fixed and will not be modified, and that any modifications in the future would receive a different version number.

**Other factors**: Given that, we look at the totality of the "other factors" listed in the inclusion principles:
1. OGDL-Taiwan-1.0 is approved by the Open Knowledge Foundation as conformant with their Open Definition; see [here](http://opendefinition.org/licenses/).
2. It is structured to be used by government and administrative legal entities, not by any licensors generally. However, this is understandable given its context as a government data license, and is in line with patterns in some other government data licenses that have been added to the list (e.g. [OGL-Canada-2.0](https://spdx.org/licenses/OGL-Canada-2.0.html)).
3. With apologies, I'm not able to tell from https://data.gov.tw/about how broadly it is used, but based on @audreyt's comments it appears to be widely used by Taiwanese government agencies for release of open access data / works.
4. Not applicable or necessary, since it is already approved as conformant with the OKFN Open Definition.
5. @audreyt indicated that the license steward approves its inclusion on the list.

Based on the above, I would be in favor of adding OGDL-Taiwan-1.0 to the SPDX License List. I'd ask if others involved in the SPDX legal community can add their +1 here or else comment if they have different thoughts.

@liuxinyu970226 and @audreyt, one question for you: I note that https://data.gov.tw/license includes both the Chinese and English translations of the license. I assume that you would want to include both of these in the license text, for the entry on the SPDX License List? That has typically been our practice if both translations of a license are considered "canonical" and if both are typically included in a "LICENSE" file (e.g., [MulanPSL-2.0](https://spdx.org/licenses/MulanPSL-2.0.html). Would you agree that both translations should be included here?

**Comment by audreyt** [comment]
Re bilingual canonical text inclusion, yes that sounds good to me.

**Comment by jlovejoy** [comment]
+1 to adding

**Comment by johnmhoran** [comment]
+1 to adding

**Comment by swinslow** [comment]
Discussed on 2021-01-07 legal team call, agreed to add.
