### ISSUE TITLE
Clarify that ImageMagick is a modified Apache-2.0

### ISSUE THREAD

**Issue by silverhook** [spdx/license-list-XML#1125]
I just plowed through `ImageMagick` and the license looked surprisingly familiar.

Upon diffing it against `Apache-2.0` I found out that it is the exact same text with some small changes:

- ImageMagick introduces a lengthy 69-line preamble
- ImageMagick, for whatever reason, omits the “(except as stated in this section)” part from the _§3. Grant of Patent License_
- (and the name of the license)

That’s it.

Since the omission in the patent clause is the only actual difference and I don’t see any good reason why they changed that, and whether that’s simply a bug on their side (maybe a script misfired when they changed `(a.)` to `<em>a.</em>` etc.) and it actually should be just Apache-2.0…

**Comment by silverhook** [comment]
Enquired the copyright holders about this: https://github.com/ImageMagick/ImageMagick/discussions/2758

**Comment by silverhook** [comment]
ImageMagick has updated their license text to fix the missing text in §3, so the text is now identical to Apache-2.0 (plus the preamble).

https://github.com/ImageMagick/ImageMagick/commit/45e5d2493c08e7cb49f7268c01d847e88f78fd6c

**Comment by swinslow** [comment]
Thanks @silverhook! I assume that we should keep `ImageMagick` as a standalone license, rather than deprecating it, since prior versions of the ImageMagick license will have the old text? Or are you suggesting that we modify the `ImageMagick` markup to make "(except as stated in this section)" an optional field?

Either way, I'm not sure the new license would match to Apache-2.0, since they are using a different standard license header (referring to the "ImageMagick License" and URL rather than Apache-2.0.

Would you be good with this if we make "(except as stated in this section)" optional, and then add an explanatory note in the `ImageMagick` entry explaining the above?

**Comment by jlovejoy** [comment]
discussed on March 4th legal call - no need for markup b/c ImageMagick was used and is different. 

Add note to ImageMagick re: similarity to Apache-2.0

**Comment by silverhook** [comment]
Sorry for the late reply. I’m OK with the implemented solution.
