### ISSUE TITLE
New license request: NAIST-2003

### ISSUE THREAD

**Issue by armijnhemel** [spdx/license-list-XML#1136]
It might be worthwhile to add the following license:

https://enterprise.dejacode.com/licenses/public/naist-2003/#license-text

*edited by @swinslow 2021-02-14: edited issue title to change ID from `NAIST` to `NAIST-2003`, see comments below*

**Comment by jlovejoy** [comment]
@armijnhemel - can you add the info as per https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md 
thanks!

**Comment by swinslow** [comment]
Since I've picked this up, I'll include a more detailed response later, just noting that I've come across this one in the wild as well from code that I'm looking at.

**Comment by swinslow** [comment]
Here's the "more detailed response" I promised a while back.

In looking at whether or not to add a license to the SPDX License List, we evaluate them in light of the [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). Here's my quick run-down of thoughts from holding those up to this license:

**Definitive factors**: The license does appear to meet all of these, noting that it is not OSI-approved. I do not see any version number indicated, but where I have seen this in use (see below) it is with a 2003 copyright date, so I would propose using `NAIST-2003` as the identifier.

**Other factors**: Given that, we look at the totality of the "other factors" listed in the inclusion principles:

1. Although this license does not appear to be on any of the indicated lists, it appears to substantially comply with the OSD and the Free Software Definition. It appears to be a broadly permissive license with a lengthy warranty disclaimer notice.
2. It is structured to be used specifically by NAIST, and appears to be specific to a particular piece of software (note the third paragraph of the license).
3. I have encountered this license in the wild -- specifically, it is used by a component in [NodeJS ](https://nodejs.org/) and is listed in their [LICENSE file](https://github.com/nodejs/node/blob/4a19cc8947b1bba2b2d27816ec3d0edf9b28e503/LICENSE#L343). NodeJS is extremely widely used, and on that basis I think this easily meets the "substantial use" criteria.
4. Not applicable, as item 1 above is met.
5. I do not see any indication that the license steward is aware of this submission. Given that this is a historical license (with copyright date 2003), I do not know if we will have much luck tracking down a present steward for the license.

Looking at the balance of the factors, although this is structured to be used primarily by NAIST themselves, given the other factors -- particularly its use in NodeJS -- I am in favor of adding this license to the SPDX License List.

As mentioned above, I think it should use the identifier `NAIST-2003`, so that there is at least some element of versioning in case we later learn about other versions of the license.

@jlovejoy @kestewart Would you be able to take a quick look and give your +1? Thanks!

**Comment by jlovejoy** [comment]
+1 to add, I agree the wide use overcomes factor #2

@swinslow  - you already prepared a PR for this, correct?

**Comment by swinslow** [comment]
Discussed on 2021-02-18 legal team call, no objections, agreed to add.
