### ISSUE TITLE
New license: MIT-Modern-Variant

### ISSUE THREAD

**Issue by StefanBruens** [spdx/license-list-XML#1161]
1. License Name: ABC
2. Short identifier: ABC
3. License Author or steward: Unknown
4. Comments: Seems to be only used by ABC. This is a permissive license, but not maching any registered ones in wording (checked BSD-n-*, ISC, MIT, zlib)
5. Standard License Header: -
6. URL: https://people.eecs.berkeley.edu/~alanmi/abc/
7. OSI Status: Not Submitted

**Comment by StefanBruens** [comment]
> Copyright (c) The Regents of the University of California. All rights reserved.
> 
> Permission is hereby granted, without written agreement and without license or royalty fees, to use, copy, modify, and distribute this software and its documentation for any purpose, provided that the above copyright notice and the following two paragraphs appear in all copies of this software.
> 
> IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

**Comment by sankha555** [comment]
Hello!
I would like to work on this issue if it's open for contribution. If so, could anyone please assign it to me? Also, is it required that the license text be added to the list of xml files in the repo as a new license? If there are any more requirements to be worked upon, it would be really helpful if someone could please guide me since this would be my first issue in the repo. Thanks!

**Comment by jlovejoy** [comment]
@sankha555 - Thanks! we need to first decide if it will be added to the SPDX License List, and if so, then we would generate a PR with the XML and text files - at which point your help would be greatly appreciated.
@swinslow and I will keep an eye out for any other licenses that may be at that point in the process as well. 
check out: https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md for a detailed (and perhaps needs-to-be-updated a bit) overview of the process.
Thanks!

**Comment by sankha555** [comment]
Thanks for the details @jlovejoy. I just went through the workflow and also through the list of licenses in the repository. I found that the ABC license is not present there. So, in that case would you want me to go ahead and make a PR with the txt and xml files or shall I wait for some time for your analysis? I would move ahead according to your instructions. Thanks!

**Comment by jlovejoy** [comment]
Looks like the closest match is to PostgreSQL License, with differences in order of wording and omission of "lost profits" in the disclaimer text.
Given that this is only used by one project and I'm not sure how active that project is, I'd be inclined not to add it. 

@pmadick @swinslow @johnmhoran - comments?

**Comment by swinslow** [comment]
I'm finding a number of other projects that use this same text:
* https://ptolemy.berkeley.edu/copyright.htm
* http://groups.csail.mit.edu/graphics/lapis/doc/legal/Jacl-license.html
* https://pirlwww.lpl.arizona.edu/resources/guide/software/PerlTk/Tixlic.html

The first two (and the original submission) are University of California, but the third one isn't (and uses "authors of this software" in place of "University of California" in several places).

The Fedora wiki lists this text on their MIT page under "Modern Variants": https://fedoraproject.org/wiki/Licensing:MIT#Modern_Variants

I would vote in favor of adding it. I think the harder question is what to call it. I wouldn't go with `ABC` here, since it looks like that's just one project using it. Perhaps `MIT-Modern-Variant` since that's how the Fedora wiki folks originally catalogued it?

**Comment by jlovejoy** [comment]
thanks for the closer look and analysis, @swinslow ! In light of that, I'm changing my vote to +1 to add

Agree on naming of MIT-Modern-Variant - we have always tried to align with existing naming - see https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md , part B :)

**Comment by MarkAtwood** [comment]
Ill take it

**Comment by swinslow** [comment]
@jlovejoy taking to get this in before 3.12 release

**Comment by swinslow** [comment]
@jlovejoy, I took this one so that we could go ahead and get it in for 3.12 -- see #1218
