### ISSUE TITLE
update solderpad entry

### ISSUE THREAD

**Issue by moedn** [spdx/license-list-XML#1266]
Just wanted to use the SPDX-ID of the current [solderpad license](http://solderpad.org/licenses/SHL-2.1/) and saw that the latest entry refers to version 0.51 ([SHL-0.51](https://spdx.org/licenses/SHL-0.51.html)), while version 2.1 is available on their website, also stating `SHL-2.1` as it's SPDX-ID.

Would be great if we could update the SPDX list here. Let me know how I can help :)

**Comment by seabass-labrax** [comment]
@moedn, welcome to the SPDX Licence List repository!

Have you read the [new license workflow](https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md) page? It describes the steps to submitting a license to this list, including new versions of existing licenses.

In short, the first thing would be to submit the licence request using the [online tools](https://tools.spdx.org/app/submit_new_license/), but you can also make a GitHub issue with the same information manually if you'd prefer.

You are most welcome to come to the Legal Team meeting on the 27th of this month if you would like to be involved, although we may not be able to discuss your license request that soon.

Thanks for your interest in SPDX; please let us know if you have any further questions! :)

**Comment by swinslow** [comment]
Hi @moedn, thanks for submitting this question!

SHL-2.1 is on the SPDX list, but as an exception rather than as a standalone license. It is structured as essentially a set of added permissions / exceptions to license conditions, for use with the Apache-2.0 license. You can see this in the [SHL-2.1 entry](https://spdx.org/licenses/SHL-2.1.html) (and the full exceptions list is [here](https://spdx.org/licenses/exceptions-index.html)).

Note that as indicated in the license's Appendix, this means that for SHL-2.1, the right way to use the identifier would be:

`Apache-2.0 WITH SHL-2.1`

rather than `SHL-2.1` just standalone.

The reason this is different from `SHL-0.51` is because [SHL-0.51](https://spdx.org/licenses/SHL-0.51.html) was itself a standalone license, rather than wrapping around Apache-2.0.

I hope this is helpful!
Steve
