### ISSUE TITLE
Unicode License Agreement - Data Files and Software 2016

### ISSUE THREAD

**Issue by sameer1046** [spdx/license-list-XML#1269]
The copyright getting year updated every year.
2016 should be changed to present

**Comment by swinslow** [comment]
Note also potentially-related discussion at #1169

**Comment by jlovejoy** [comment]
@sameer1046  - are you talking about the copyright year in the copyright notice on this license: https://spdx.org/licenses/Unicode-DFS-2016.html ?

If so, copyright notices are considered replaceable text for purposes of matching (annotated by red text in the webpage), thus a change to the copyright year doesn't matter.

The inclusion of 2016 in the license was to differentiate from the license version that came prior, since there was no numbered versioning.

**Comment by jlovejoy** [comment]
I think we can close this one, as the copyright notice is not properly noted as replaceable, thus we don't need to keep updating the year
