### ISSUE TITLE
New License Request: COIL-1.0 - Copyfree Open Innovation License 

### ISSUE THREAD

**Issue by yogurtearl** [spdx/license-list-XML#1273]
**License's Full Name:** Copyfree Open Innovation License
**Short Identifier:** COIL 
**Source / URL:**
https://coil.apotheon.org/plaintext/00.6.txt
https://coil.apotheon.org/about/

**OSI status:** not submitted
**Certified "copyfree":** yes -> https://copyfree.org/policy

**Standard License Header:**
From https://coil.apotheon.org/notice/
> This content Copyright <YYYY>, and may be redistributed under the terms of the Tesla COIL.

**License Text**

> # Copyfree Open Innovation License
> 
> This is version 0.6 of the Copyfree Open Innovation License.
> 
> ## Terms and Conditions
> 
> Redistributions, modified or unmodified, in whole or in part, must retain
> applicable notices of copyright or other legal privilege, these conditions, and
> the following license terms and disclaimer.  Subject to these conditions, each
> holder of copyright or other legal privileges, author or assembler, and
> contributor of this work, henceforth "licensor", hereby grants to any person
> who obtains a copy of this work in any form:
> 
> 1. Permission to reproduce, modify, distribute, publish, sell, sublicense, use,
> and/or otherwise deal in the licensed material without restriction.
> 
> 2. A perpetual, worldwide, non-exclusive, royalty-free, gratis, irrevocable
> patent license to make, have made, provide, transfer, import, use, and/or
> otherwise deal in the licensed material without restriction, for any and all
> patents held by such licensor and necessarily infringed by the form of the work
> upon distribution of that licensor's contribution to the work under the terms
> of this license.
> 
> NO WARRANTY OF ANY KIND IS IMPLIED BY, OR SHOULD BE INFERRED FROM, THIS LICENSE
> OR THE ACT OF DISTRIBUTION UNDER THE TERMS OF THIS LICENSE, INCLUDING BUT NOT
> LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
> AND NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS, ASSEMBLERS, OR HOLDERS OF
> COPYRIGHT OR OTHER LEGAL PRIVILEGE BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER
> LIABILITY, WHETHER IN ACTION OF CONTRACT, TORT, OR OTHERWISE ARISING FROM, OUT
> OF, OR IN CONNECTION WITH THE WORK OR THE USE OF OR OTHER DEALINGS IN THE WORK.
> 

**Who is the license author or license steward?** 
No email address.
https://coil.apotheon.org/

Example projects: 
https://github.com/palominolabs/metrics-guice

**Comment by jlovejoy** [comment]
Can you please provide any missing info that would have been submitted by way of https://tools.spdx.org/app/submit_new_license/
It's fine if you don't use the form, but we still need all the same info!
Thanks!

**Comment by jlovejoy** [comment]
@yogurtearl - are you the license steward or author?

**Comment by mlinksva** [comment]
I'm pretty sure @apotheon is the steward/author.

**Comment by apotheon** [comment]
Yes, that's me.

**Comment by jlovejoy** [comment]
Thanks @apotheon - mostly we just want to make sure the license steward is aware of the submission and doesn't have any objections, etc. 

a quick search on Github - https://github.com/search?q=%22Copyfree+Open+Innovation+License%22&type=code - shows some use by a variety of repos, so I'm generally in favor of adding it.

**Comment by swinslow** [comment]
Discussed on 2021-08-05 legal team call. Noting that this request is for version 0.6 of the license, and the versions at the link from @jlovejoy above appear to be for prior versions (0.3, 0.4, 0.5).

@apotheon the following might be questions that you can weigh in on:
* Are there other projects using v0.6?
* And/or, is there a request to add prior versions 0.3-0.5 as separate entries?

For SPDX, we aim to be as specific as possible about versioning licenses so that they can be identified accurately. Grateful for your thoughts here.

**Comment by apotheon** [comment]
I wouldn't necessarily recommend adding versions prior to 0.6 at this time, unless maintaining historical record of prior versions in SPDX is somehow desirable for the SPDX core goals.  There are other projects using 0.6, but I don't have a catalog of them other than some of my own projects.  I'll get back to you on that, at least with links to a couple of mine.  I'll check with others who might have some projects to suggest as well.

**Comment by mlinksva** [comment]
Should the short identifier be `COIL-0.6`?

**Comment by apotheon** [comment]
That works for me, and fits the pattern I recall from other licenses on the SPDX list.

**Comment by apotheon** [comment]
I should probably just list some projects of mine now rather than wait for others to report back on whether they have some worth sharing:

* [Droll](https://rubygems.org/gems/droll)
* [FossGit](https://fossrec.com/u/apotheon/fossgit/index.cgi/file?name=LICENSE&ci=tip)
* [q](https://fossrec.com/u/apotheon/q/index.cgi/file?name=LICENSE&ci=tip)
* [RedRug](https://rubygems.org/gems/redrug)
* [Versionize](https://rubygems.org/gems/versionize)

**Comment by apotheon** [comment]
info about the legal form of the COIL-0.6 license:

The current patent clause reflects changes suggested to me on an occasion a few years ago when a patent lawyer I know (a former engineer who specializes in tech/engineering patent law) looked over the license.  Apart from the comment that prompted the changes (a matter of making potential users' lawyers less nervous more than a matter of substantive legal consequences per se), and he gave it his (unofficial) seal of approval as a patent clause for a software license.

I recently asked a lawyer who deals with copyright, patent, contract, and licensing law to review the license.  The results were promising.  In her analysis, she explained it in terms that matched the intentions in drafting it (without having been told those intentions in advance), described it as being fairly standard/straightforward in the context of legal interpretation and term usage, generally appearing to conform to the requirements of the Copyfree
Standard Definition and Open Source Definition, presenting no obvious difficulties for license compatibility purposes, and being very safe for recipients as far as copyright law is concerned (though of course the disclaimer language comes with the standard lawyer caveat about how if something bad happens because of your use of the covered work you're legally on your own).

I did not establish a lawyer-client relationship with either of them, though they gave me best-effort analyses, and the second of them was a paid consultation.  As a result, I'm not prepared to refer to them by name (given legal issues involved and the fact I don't want to get sued by a lawyer for inadvertently implying a lawyer-client relationship) at this time, though I'm considering establishing such a relationship with the second of the two for purposes of further license related work.

**Comment by apotheon** [comment]
info about other projects using the COIL-0.6 license:

I asked around among people I know, and came up with a few projects using this
license.  Each comes with links to project and license information.

* finance-visualizer: HTML visualization tools for CSV financial data

    * [GitHub](https://github.com/pbrunner/finance-visualizer)

* libstdgb: C library for Game Boy development

    * [GitHub](https://github.com/delwink/libstdgb)

* ttt: arbitrary size Tic Tac Toe implementation

    * [GitHub](https://github.com/2mac/ttt)

This is a project whose creator/maintainer told me he's likely to update the
license to use COIL-0.6 soon, probably this week.

* serverless-cf-vars: JavaScript library

    * [GitLab](https://gitlab.com/kabo/serverless-cf-vars)
    * [npm](https://www.npmjs.com/package/serverless-cf-vars)
    * [Yarn](https://yarnpkg.com/package/serverless-cf-vars)
    
I know of some other projects using older COIL versions where I'm informing the 
maintainers of the legal analysis of the 0.6 version and suggesting they update 
the license to that version.  That may result in the number of users of
COIL-0.6 increasing in the near future as well.

**Comment by apotheon** [comment]
(Someone let me know if I shouldn't dump so much text here.)

**Comment by swinslow** [comment]
Thanks @apotheon for adding the details here! Greatly appreciated.

I'm not doing a full write-up of this license under the [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) at the moment, but from a quick look my view is that this license likely complies with the OSD. Given that, the license being structured to be generally usable by anyone, and the demonstrated use by various third parties, I'm a +1 to add COIL-0.6 to the license list. I'll plan to bring this up during the SPDX legal team call today.

**Comment by swinslow** [comment]
Discussed on 2021-08-19 legal team call. 

Some comments about curiosity on why the license has a 0.6 version number (which could be interpreted as being pre-release), but SPDX generally defers to license stewards on the versioning they choose to use. @apotheon Does the version 0.6 numbering signal that the license is still in the midst of drafting, or is the text finalized for use with this version number? And/or, if this is planned to be the final stable version, is there a plan to bump it to 1.0?

If text is final, then good to add; but future versions (such as a 0.7 or 1.0) would need to be evaluated on their own for whether they meet the inclusion principles.

**Comment by apotheon** [comment]
I'm inclined to actually bump it to 1.0 at this point, thanks to (very recent) review by a lawyer and SPDX consideration.  Is there any reason this would cause any concern or difficulty with relation to the SPDX process, or should I just declare this 1.0 to settle formal concerns over version numbering?

**Comment by swinslow** [comment]
@apotheon I'd say, once you publish it as 1.0 and confirm that the text is fixed and won't change for that version number, let's go with that on the license list and add it to the list as `COIL-1.0`. Thanks!

**Comment by apotheon** [comment]
The license version number has been updated to 1.0 with no changes to license terms from the 0.6 version as shared here and legally reviewed.  No changes to the license are planned, expected, or considered at this time, and if at some point a modified version becomes desirable I do not see any reason for it to be applied without a version number change.  I believe its current form is about as good as it can get, given current legal climate and other information available to me at this time.

Thank you for your feedback and patience.

(I'll update the license version mentions on my own projects to 1.0 now.)
