### ISSUE TITLE
New license (note) request: man-pages-GPL-object-code-note

### ISSUE THREAD

**Issue by alejandro-colomar** [spdx/license-list-XML#1326]
The title is something I came up with right now; feel free to improve it.  Also, I used lowercase for the first letter, as the man-pages project is named with lowercase, but if you feel that it should start with uppercase for consistency, I'm okay with that.

Many man pages that use GPL come with this note (and for those that don't come with it, it is implied anyway):

```
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
```

Actually, the full license used by those pages is usually:

```
.\" Copyright (c) <year>, <copyright holder>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
```

I think that note about interpreting the GPL is useful, so I'd like to keep it, maybe as:

```
SPDX-License-Identifier: GPL-2.0-or-later with man-pages-GPL-object-code-note
```

or something like that.  What do you think?

See discussion in linux-man@:
https://lore.kernel.org/linux-man/20210905132542.245236-1-alx.manpages@gmail.com/T/#t

**Comment by pombredanne** [comment]
Does this change anything about the GPL or is this just a clarification note in a specific context? are these extra terms?

**Comment by alejandro-colomar** [comment]
Just a clarification note in a specific context

**Comment by pombredanne** [comment]
@alejandro-colomar My 2cents: if this is `Just a clarification note in a specific context.` I wonder if it deserve having its own exception id.

**Comment by alejandro-colomar** [comment]
How would you do it then?

**Comment by swinslow** [comment]
Identifiers that will be used in a "WITH" expression are intended to go on the [SPDX Exceptions List](https://spdx.org/licenses/exceptions-index.html). Currently, that list is intended for exceptions that "grant an exception to a license condition or additional permissions beyond those granted in a license."

For this note, I don't think it's unarguably clear that it grants an exception or an additional permission. Given that, I would not support adding it to the Exceptions List for use in a "WITH" expression (again, given the current/historical meaning of the Exceptions List).

If this were to be added, it would likely be on the License List with a separate identifier, e.g. something to indicate that it is a different license than GPL-2.0. I'm not sure I would support that, I tend to agree with @pombredanne (or what I think he's saying) that it's more a particular project's interpretation of GPL-2.0, rather than a different license.
