### ISSUE TITLE
Missing machine-readable License info for this repo

### ISSUE THREAD

**Issue by hoijui** [spdx/license-list-XML#1345]
There is neither a `LICENSE*` file, nor is the repo [REUSE](https://reuse.software/) compliant.
Is it an oversight or what is the reason for this?

**Comment by jlovejoy** [comment]
we would not add license info in every file, assuming by every file are you including the .xml and .txt files for all the licenses. That bleeds into the revolving what-is-the-license-of-the-license topic which has been raised and closed multiple times (we need to do a write-up on that one of these days, so we don't keep having that conversation). Short answer, there isn't one and it doesn't matter. 

We did update license info for all the software files some time ago, so that should be clear.

There is another issue for adding some general explanation.

**Comment by swinslow** [comment]
Not included in 3.19, so moving forward to 3.20.

**Comment by swinslow** [comment]
@jlovejoy and @swinslow to collaborate on drafting an FAQ to clarify the existing understandings around this.
