### ISSUE TITLE
OpenSSL exceptions analysis

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1356]
there are multiple issues open related to variants of the OpenSSL exception. This issue is attempt to bring them all together to one issue. (I'm going to close the other issues, so we have all info here, but for reference see: #1324 #1058 #1007 #720 )

Here is a list of the where the variants have been found (and a shortname that corresponds with attachment)
- openvpn-debian - https://tracker.debian.org/media/packages/o/openvpn/copyright-2.4.0-6%2Bdeb9u2
- psycopg - https://github.com/psycopg/psycopg2/blob/master/LICENSE#L14-L24
- deluge - https://git.deluge-torrent.org/deluge/tree/LICENSE
-  cryptsetup (GPL) - https://gitlab.com/cryptsetup/cryptsetup/-/blob/master/COPYING#L342
- siege - https://github.com/JoeDog/siege/blob/master/README.md
- naxsi - https://github.com/nbs-system/naxsi/blob/951123ad456bdf5ac94e8d8819342fe3d49bc002/naxsi_src/naxsi_raw.c
- incinga2 (Lesser) - https://github.com/Icinga/icinga2/blob/master/README.md
- cryptosetup (Lesser) - https://gitlab.com/cryptsetup/cryptsetup/-/blob/master/COPYING.LGPL#L505

I made a text file with the different variants and highlighted the relevant text in different colors - will try to attach here.

Below are the questions the legal team needs to answer in terms of what is legally substantive differences

**Comment by jlovejoy** [comment]
[openssl-exceptions.pdf](https://github.com/spdx/license-list-XML/files/7507273/openssl-exceptions.pdf)

**Comment by jlovejoy** [comment]
1) can we consider any of these (in the context of describing the permission to link) as equivalent / not legally substantively different:

- the code of this program with the OpenSSL Library (or with modified versions of OpenSSL that use the same license as OpenSSL), 
- the code of this program with any version of the OpenSSL library which is distributed under a license identical to that listed in the included COPYING.OpenSSL file, 
- this program with the OpenSSL library (or with modified versions of OpenSSL that use the same license as OpenSSL),
- the code of portions of this program with the OpenSSL library under certain conditions as described in each individual source file, 

Note: Deluge uses another variant - "the code of portions of this program with the OpenSSL library." and is different once again in omitting the last line of the first paragraph stating "and distribute linked combination including the two." - which all other variants use

**Comment by jlovejoy** [comment]
2. can we the difference in describing the files to which the license applies (which may vary depending on location)
- If you modify _file(s) with this exception_, you may extend this exception to your version of the file(s), but you are not obligated to do so. 
- If you modify _this file_, you may extend this exception to your version of the file, but you are not obligated to do so.

**Comment by jlovejoy** [comment]
3. is the omission or inclusion of the last line of the second paragraph, substantively different? (line in italics is sometimes present and sometimes missing)

"You must obey the GNU General Public License in all respects for all of the code used other than OpenSSL.  
If you modify file(s) with this exception, you may extend this exception to your version of the file(s), but you are not obligated to do so.  
If you do not wish to do so, delete this exception statement from your version. 
_If you delete this exception statement from all source files in the program, then also delete it here._"

**Comment by jlovejoy** [comment]
there is also an exception that applies to the LGPL - so that will surely need its own exception. 

legal team - please comment separately on each numbered question (and identify which one)!

**Comment by swinslow** [comment]
@jlovejoy Thanks for organizing all of this and getting the conversation moving forward!

Here are my gut reactions to your questions. I don't have strong feelings on them and could be persuaded otherwise.

### Responding to [question 1](https://github.com/spdx/license-list-XML/issues/1356#issuecomment-964437122):

I feel pretty comfortable considering these two to be equivalent for SPDX ID purposes:

* the code of this program with the OpenSSL Library (or with modified versions of OpenSSL that use the same license as OpenSSL),
* this program with the OpenSSL library (or with modified versions of OpenSSL that use the same license as OpenSSL),

Those two are identical other than "code of this program" vs. "program" -- I think that's substantively identical.

The following two I feel less comfortable considering to be equivalent to the above (or to each other):
* the code of this program with any version of the OpenSSL library which is distributed under a license identical to that listed in the included COPYING.OpenSSL file,
* the code of portions of this program with the OpenSSL library under certain conditions as described in each individual source file,

That's because both of these punt on which other license needs to be matched, for the first one whatever is in "the included COPYING.OpenSSL file" and for the second whatever "certain conditions" are "described in each individual source file."

### Responding to [question 2](https://github.com/spdx/license-list-XML/issues/1356#issuecomment-964438702):

So, unlike my response to 1, for these I actually feel fine treating these as equivalent.

I tend to distinguish (A) changes that might modify the effect of the license or exception, vs. (B) changes that might modify knowing which software or other content the license or exception applies to.

Question 1 is about changes of type A: it modifies what the effect of the exception is. Question 2 is about changes of type B: it's just about knowing which files the exception applies to.

Given that, I tend to think that for question 2, we treat changes of this type as equivalent, and it would be a matter of e.g. whoever is creating an SPDX document to determine which files they're going to say are under this license ID.

### Responding to [question 3](https://github.com/spdx/license-list-XML/issues/1356#issuecomment-964439798)

This is about the line: _"If you delete this exception statement from all source files in the program, then also delete it here."_

Personally I feel like this is not about the license / exception itself -- more about how to apply the license / exception to your work. (Or, more precisely, how to _not_ apply the exception to your work...)

I'd compare this more to something like the "appendix" language at the end of licenses like Apache-2.0 or GPL-2.0. I think we typically treat those as optional, so I'd also lean towards saying that it should be treated as equivalent whether or not this line is present.

## Responding to [comment about LGPL](https://github.com/spdx/license-list-XML/issues/1356#issuecomment-964441540)

ugh

how would we feel about making the portion of the exception that names the license, into replaceable text? And/or, just making "Lesser" into optional text there?

Since it's an exception, in any case where it's used it's going to be including the appropriate license as part of the license expression. E.g., `GPL-2.0-or-later WITH Whatever-OpenSSL-exception` -- so could we just match the exception text itself without caring which license is named within the exception's text?

**Comment by jlovejoy** [comment]
discussed on 12/9 call - went through @swinslow comments, agreed with analysis - need to make xml files

**Comment by jlovejoy** [comment]
#1448 fixes part of this

**Comment by swinslow** [comment]
@jlovejoy I just left one comment in #1448 to hopefully address the failing test there...

**Comment by swinslow** [comment]
Updates:
* #1448 closed (unmerged) in favor of #1436
* Leaving this issue open as it appears #1436 fixes _part_ of this, but also there may be other OpenSSL exceptions that are appropriate to add; rolling forward to 3.18

**Comment by jlovejoy** [comment]
@swinslow - should we just close this and open a new issue (or wait for someone else to)? I'm not sure what the remaining bits are!

**Comment by jlovejoy** [comment]
#1436 addressed a number of variations.

The variants that didn't address include:

- deluge: "In addition, as a special exception, the copyright holders give permission to link _the code of portions of this program with the OpenSSL library_.
- openvpn: "In addition, as a special exception, the copyright holder gives permission to link _the code of this program with any version of the OpenSSL library which is distributed under a license identical to that listed in the included COPYING.OpenSSL file_, and distribute linked combinations including the two.
- cryptsetup / siege / naxsi: "In addition, as a special exception, the copyright holders give permission to link _the code of portions of this program with the OpenSSL library under certain conditions as described in each individual source file_, and distribute linked combinations including the two.

Leaving this open and moving to later release to address later (if needed)

**Comment by rikylescak** [comment]
Hi,
has been any decision made about the vsftpd license yet ?
Is any of the already existing exceptions applicable or you plan to make a new one, since it's quite briefer compared to other OpenSSL exceptions? 
Thanks for the info.

**Comment by jlovejoy** [comment]
hi @rikylescak - we updated the templates to accommodate a bunch of variations we had found. The idea being, we could then address additional variants later on.

I"m not sure which one vsftpd is (I don't see it listed above in my comment as to which ones we didn't think we addressed). Can you provide a link and I'll have a look?

**Comment by jlovejoy** [comment]
ah, thanks - there was two variants in that issue, so I got confused.

yes, this is a different one altogether than the other variations I had found in this thread. I'm going to close this and move to a new issue to track there at #1870
