### ISSUE TITLE
Make x11 licence generic

### ISSUE THREAD

**Issue by sameer1046** [spdx/license-list-XML#1389]
The x11 license text contain x11 terms which is not replaceable.

It should be made generic just like ISC licence

**Comment by swinslow** [comment]
Hi @sameer1046, can you share any examples of projects in the wild that are using the [X11 license text](https://spdx.org/licenses/X11.html) for their license, with something different in place of "X Consortium" in the last paragraph or two? Specifically in this part of the license:

> Except as contained in this notice, the name of the X Consortium shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization from the X Consortium.
> 
> X Window System is a trademark of X Consortium, Inc.

**Comment by sameer1046** [comment]
Hi @swinslow 

I found this in ncurses
https://github.com/mirror/ncurses/blob/master/COPYING

**Comment by silverhook** [comment]
> I found this in ncurses https://github.com/mirror/ncurses/blob/master/COPYING

Just diffed it and it sure looks like a un-/re-branded X11, the only substantial difference is the addition of _“distribute with modifications“_

**Comment by swinslow** [comment]
Thanks @sameer1046 and @silverhook! Given that, I'd be +1 at least to make the trailing part generic (e.g., making the reference to X Consortium replaceable text).

Adding "distribute with modifications" to the X11 license as optional text is harder. Typically the position that SPDX has taken is that any change to a license's text that is arguably substantive should get its own separate license ID. Although I'd personally interpret "distribute with modifications" as being implied within the scope of the permitted rights in current X11, that's me interpreting the language. See [HPND-sell-variant](https://spdx.org/licenses/HPND-sell-variant.html) and [HPND](https://spdx.org/licenses/HPND.html) for a similar example.

So for this particular example, I'd be fine with making "X Consortium" into replaceable text in the X11 template; but for adding "distribute with modifications", I'd lean more towards it getting its own ID. Maybe "X11-distribute-mods-variant"? Or "ncurses" if this is something specific to only ncurses?

**Comment by silverhook** [comment]
Personally, I would prefer cramming both into the _X11_ template, since I can’t see how “distribute with modifications“ adds anything that is not already covered by X11 as is. … but can see how that might not be totally in line with our guidelines. Would like to hear someone else’s thoughts as well.

Other than that, I agree with @swinslow

**Comment by sameer1046** [comment]
I agree with @silverhook .

@pombredanne What do you think?

**Comment by pombredanne** [comment]
@sameer1046 there are a few variations alright so I agree a template would make sense. :+1: 

You wrote:

> I found this in ncurses https://github.com/mirror/ncurses/blob/master/COPYING

FWIW, this is tracked as https://scancode-licensedb.aboutcode.org/x11-fsf in ScanCode 

And we track also several variants:
- SPDX X11 proper is tracked as https://scancode-licensedb.aboutcode.org/x11-xconsortium
- https://scancode-licensedb.aboutcode.org/index.html?search=x11 has many other variations
- and even more examples used for detection at https://github.com/search?q=x11+repo%3AnexB%2Fscancode-toolkit+extension%3Ayml+path%3Asrc%2Flicensedcode%2Fdata%2Frules%2F&type=Code
- https://scancode-licensedb.aboutcode.org/x11-xconsortium_veillard seen in libxslt and docbook and more https://github.com/search?q="IN+NO+EVENT+SHALL+THE+DANIEL+VEILLARD"&type=code is a fairly popular one, in addition tto the FSF one with or without the "distribute with modifications"

Based on these, these names are seen used:  the Free Software Foundation, X Consortium, IBM Corporation, Hewlett-Packard, "copyright holder(s)", "copyright holders", XFree86 Project and Xilinx

**Comment by sameer1046** [comment]
Scancode licence database is the perfect database I have ever seen.

**Comment by swinslow** [comment]
> Personally, I would prefer cramming both into the _X11_ template, since I can’t see how “distribute with modifications“ adds anything that is not already covered by X11 as is. … but can see how that might not be totally in line with our guidelines. Would like to hear someone else’s thoughts as well.

If I were interpreting this for myself personally, I agree with you 100%. Personally I would have zero problems treating the MIT/X11-style preamble "deal in the Software without restriction" as encompassing "distribute with modifications", whether or not it's called out explicitly.

Historically, I _think_ SPDX has taken a much stricter view of this for purposes of deciding whether or not two licenses are the "same" for matching and license list identifier purposes. I _think_ this one is right on the line for how the SPDX participants have looked at this in the past.

Given that, I've flagged this to discuss on an upcoming legal call (perhaps the next one in a couple of hours if possible) so that we can perhaps have a short discussion and get other folks' thoughts on this.

**Comment by liuxinyu970226** [comment]
Or probably we need to also discuss if our "MIT License" can be renamed to "MIT Expat License" or not? "MIT License" is really confusing words per gnu.org and some Wikimedia Commons discussion.

**Comment by swinslow** [comment]
Discussed on 2022-02-03 legal team call, agreed on the following:
* X11 license text should be made generic w/r/t references to "X Consortium"
* For the particular ncurses instance, because of the separate additional explicit "distribute with modifications" grant, there should be a separate ID on the license list for this.

For the latter, I'd suggest "X11-distribute-modifications-variant" in line with the approach previously taken for [HPND-sell-variant](https://spdx.org/licenses/HPND-sell-variant.html).

**Comment by capfei** [comment]
@swinslow I can do the markup changes for X11, if you want to assign it to me.

**Comment by swinslow** [comment]
Fantastic, thanks @capfei! If you're able to get this in before this coming Sunday (Feb. 6), I'll include it in the 3.16 release. If not, no worries at all.

**Comment by pombredanne** [comment]
@liuxinyu970226 re:

> Or probably we need to also discuss if our "MIT License" can be renamed to "MIT Expat License" or not? "MIT License" are really confusing words per gnu.org and some Wikimedia Commons discussion.

Do you mind to create a separate issue if you feel strongly about it

**Comment by capfei** [comment]
I submitted the changes at #1408. Please let me know if I need to correct anything.
