### ISSUE TITLE
Your page wasn't helpful

### ISSUE THREAD

**Issue by DataJuggler** [spdx/license-list-XML#1390]
I clicked on Create / Submit a liccense, you sent me to tools.

Nothing in Tools had Upload License.

I want a license that has one line:

Data Juggler Open-Source No Legalese License
Provided as is. Do whatever you want. If you like it, show gratitude by listing in credits and / or giving stars or likes where possible.

To save me all the time of going through the hoops to learn how to do this, would this license be submittable? After reading your FAQ and looking at your tools, I still don't know where to begin.

Thank you, I don't know how this works, but I have read many types of open-source licenses, and none are simple as mine.

**Comment by seabass-labrax** [comment]
Hello @DataJuggler, and welcome to @spdx! I think the page you might have been looking for is <https://tools.spdx.org/app/submit_new_license/>, where you can fill out a form to request that a license be added to the SPDX License List.

Please correct me if I'm wrong, but I believe that the Data Juggler Open-Source No Legalese License is not used much 'in the wild', so to speak. Given our License Inclusion Guidelines, at <https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md>, I would guess that, for that reason, it would probably not be a good fit for the SPDX License List. We generally include licenses that are used by a lot of open source projects (e.g.[`MIT`](https://spdx.org/licenses/MIT.html)), or are important for historical reasons because they were used in early software projects that more modern programs are based on (e.g. [`CDDL-1.0`](https://spdx.org/licenses/CDDL-1.0.html)).

If you would like to go ahead with the request nonetheless, please try the form I linked to above and let us know if there are any problems! We'll then do our usual review, which is performed by three SPDX Legal Team volunteers - two lawyers and one non-lawyer.

Have you considered maybe using the [`0BSD` license](https://spdx.org/licenses/0BSD.html) (which is already in the SPDX License List) for your projects? It grants the same permissions as your license plus it includes the all-caps disclaimer which is important in US law.

In any case, a license not being in the SPDX License List doesn't mean you can't use it with SPDX! We have a `LicenseRef-` prefix just for this reason ([see clause 10 of the SPDX specification](https://spdx.github.io/spdx-spec/other-licensing-information-detected/)). As such you could reference your license as `LicenseRef-DataJuggler-1.0`, for instance.

Plesae tell me if I've left any questions unanswered! :)

**Comment by DataJuggler** [comment]
That is why I wrote you here.

It might help others if you put that, but as far as ‘you only help projects that are used in the wild, then you help popular people, and you are just as bad as Git Hub and everyone else. Git Hub only lets shows projects in Explorer that get to 25 stars. Projects can’t get to 25 stars if no one knows about them, and only popular people can market open source projects, and your group is part of the problem.”

Maybe others could find people’s projects if you didn’t have your policy.

Good day.

**Comment by silverhook** [comment]
I also doubt your license would be included as is right now – I searched GitHub and could not find even one instance of this license. The reason why the inclusion guidelines require the license to be either have wide-spread use or at least be used by some important projects is that otherwise the list and the small team maintaining it would be swamped.

A major goal of SPDX License List is to provide UIDs and (canonical) texts and to reduce the licensing chaos. There are already hundreds of popular FOSS licenses out there, so maintaining a list of just those is already a huge undertaking. And when it comes to some older ones (GPL and BSD families come to mind) they have so many variations in the wild, the effort to standardise their templates is already very high. I hope you understand.

As @seabass-labrax , no-one prevents you from using the SPDX identifier such as `License-Ref-DataJuggler-1.0`, and if you do, it might make sense for you to also check out https://reuse.software

**Comment by DataJuggler** [comment]
I just invented it 10 minutes ago, of course it isn’t on Git Hub.

My only option has been items like MIT, so I create my own in a text file.

I don’t see any point to your organization then.

Bye

**Comment by silverhook** [comment]
> I don’t see any point to your organization then.

Just to understand your PoV better …what were your expectations of SPDX then?

**Comment by DataJuggler** [comment]
An upload button. It doesn’t take a staff, to add a file with an a text file that would even fit on twitter.

If it takes a staff to add a text file, you have unnecessary personnel.

**Comment by silverhook** [comment]
BTW, three popular options that seem to do what your license does are:

- [Unlicense](https://spdx.org/licenses/Unlicense.html)
- [0BSD](https://spdx.org/licenses/0BSD.html)
- [WTFPL](https://spdx.org/licenses/WTFPL.html)

**Comment by DataJuggler** [comment]
They have more lines of text, and they are not mine.

Why do you want to control information so bad? Do you work for Google?

**Comment by silverhook** [comment]
> An upload button. It doesn’t take a staff, to add a file with an a text file that would even fit on twitter.

There is a field where you should copy-paste the license text: https://tools.spdx.org/app/submit_new_license/

**Comment by silverhook** [comment]
To get this thread back on topic, I cannot replicate your issue – please specify where you get stuck.

If I follow your steps correctly this is how it works:

1. go to https://spdx.org (or https://spdx.dev, same page)
2. click menu _Tools ↦ SPDX Online Tools_ which brings you to https://tools.spdx.org/app/
3. click menu _License requests ↦ Submit New License_, which brings you to https://tools.spdx.org/app/submit_new_license/

In that tool there is a textbox field labelled as **License Text** where the license text should be copy-pasted in.

**Comment by DataJuggler** [comment]
You told me I wouldn’t get submitted to the list, so why would I bother?

Just close this, you were not what I thought you were.

**Comment by silverhook** [comment]
@DataJuggler you still haven’t told us what your expectations were.

**Comment by jlovejoy** [comment]
Please note, there are various links on the main SPDX License List page (https://spdx.org/licenses/) explaining the purpose, inclusion guidelines and other pertinent information related to the SPDX License LIst, which is a part of the larger SPDX project. One of those links goes to the Contributing page (https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md) which also/again points a newcomer to various recommended resources to start with. I would recommend that you start there, as it seem like perhaps you may not understand the overall purpose of the project. 

On a side note, I'm not clear why you feel the need to write a new license which is generally not looked well upon in the broader open source community. Something to consider.

I will close this issue in the meantime and mark it as not-accepted (as to the license request), As for the license submission tool - we will look further into that and raise an issue in that repo to fix anything that is not working. 

Thanks
J
SPDX legal co-lead

**Comment by DataJuggler** [comment]
Why can’t anyone create a license is all I am saying. You seem to be saying ‘It’s a closed club, and you ain’t in it’.

**Comment by jlovejoy** [comment]
Regarding open source license proliferation, perhaps you should check out https://opensource.org/proliferation

**Comment by silverhook** [comment]
@DataJuggler , I guess the big misunderstanding here is that in SPDX _do **not** create_ licenses, we merely archive, document and categorise existing ones.

**Comment by DataJuggler** [comment]
How do existing ones get in your list?

**Comment by silverhook** [comment]
> How do existing ones get in your list?

Several people sent you the relevant links to this already. Feel free to read the documentation :)
