### ISSUE TITLE
New license request: Hippocratic-3.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Tyler887** [spdx/license-list-XML#1393]
**1.** License Name: Hippocratic License 3.0
**2.** Short identifier: Hippocratic-3.0
**3.** License Author or steward: @EthicalSource on GitHub
**4.** Comments: Ended up with a skip.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/138
**7.** URL(s): https://firstdonoharm.dev/version/3/0/license/license.txt
**8.** OSI Status: Pending
**9.** Example Projects: http://tidyblocks.tech/, https://github.com/vcr/vcr

**Comment by jlovejoy** [comment]
Note - Hippocratic-2.1 is already on the SPDX License List

**Comment by bkuhlmann** [comment]
Hello. :wave: I was about to log an issue for 3.0 when I saw this issue already open. Will it be possible to add support for the Hippocratic 3.0 license? I ask because I'm the maintainer of [Gemsmith](https://www.alchemists.io/projects/gemsmith) and am currently getting the following error when building new [RubyGems](https://rubygems.org) because 3.0 isn't registered yet. Here's what the error message looks like:

``` 
WARNING:  license value 'Hippocratic-3.0' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'Hippocratic-2.1'?
```

it would be really nice to support 3.0 because it's what I support by default when creating new Ruby gems.

**Comment by swinslow** [comment]
Hi @Tyler887, thanks for submitting this request.

The two example projects that you listed don't actually appear to be using Hippocratic version 3.0, at least from what I'm seeing -- [tidyblocks appears to be 2.0](https://tidyblocks.tech/license/) and [vcr appears to be 2.1](https://github.com/vcr/vcr/blob/master/LICENSE).

Can you provide examples of other projects in the wild that are using version 3.0, since that's what's requested here? This is relevant as it's one of the factors in the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) for evaluating whether to add a license to the SPDX License List.

@bkuhlmann thanks for flagging Gemsmith as a project that is [using version 3.0](https://www.alchemists.io/policies/license/), that's helpful to know for the evaluation. Do you know of any other projects out there that are on 3.0?

**Comment by bkuhlmann** [comment]
> Do you know of any other projects out there that are on 3.0?

 I'm afraid I don't. I'd probably have to write I mostly work in Ruby and am trying to promote good, ethical, practices, with the Gemsmith gem. I'm not sure if this helps answers your question but all [30 projects listed and maintained on my site](https://www.alchemists.io/projects) all use the Hippocratic 3.0 license.
 
 There is a way to search for projects with the Hippocratic License in GitHub using GitHub's advanced search. Example:
 
![2022-02-09_06-49-31-Firefox](https://user-images.githubusercontent.com/50245/153214476-851ee944-b65c-41e8-a22e-bd69268b6fbb.png)
 
The only problem is that you can't enter a custom search, you only get what is listed in the drop down selection which is a bummer. There might be a way to do this by making a custom API call but haven't tried.

All of that said, it just means we need to help promote this better by making easier for people to use this license. 😅

**Comment by Pizza-Ria** [comment]
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

- No
 
## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

- Yes, it is unique - no matches running the SPDX tool.  Also a substantial restructuring + new substance from the [Hippocratic 2.1](https://firstdonoharm.dev/version/2/1/license/).

### If a software license, does it apply to source code and not only to executables?

- Yes - Section 1.4:  “Software” means any copyrighted work, including but not limited to software code, authored by Licensor and made available under this License.  

### Does the license have identifiable and stable text, and is not in the midst of drafting?

- Yes.

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

- Unknown but have contacted the Organization for Ethical Source.

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

- No - the free/open definitions include variations of the theme such as that in the [Open Source Definition] (https://opensource.org/osd) at 6 - `The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.`  Hippocratic 3.0 contains **many** such restrictions.

### 2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one significant project satisfies this*

- Previous comments in this thread have not shown a substantial use.
- Ran the following search on GitHub:  '"hippocratic license" and "3.0"  filename:LICENSE language:Text language:Markdown path:/' and did not see any top hits for the 3.0 version.

### 3. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

- No - per previous note - there are many field of use restrictions so this license is not structured to be usable by anyone.

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

- No - the restrictions are not limited.

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

- Unknown but have contacted the Organization for Ethical Source.

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

- Given the substantial restructuring/substance changes and lack of alignment with the License Inclusion Principles, I am not in favor of adding this even though the prior [Hippocratic 2.1 version](https://firstdonoharm.dev/version/2/1/license/) was included on this list.

**Comment by jlovejoy** [comment]
I agree with @Pizza-Ria analysis - this does not meet the license inclusion guidelines enough to be added

**Comment by swinslow** [comment]
Thank you @Pizza-Ria!

Discussed on legal team call 2022-03-10. One comment on the analysis above -- for item 3 (the "generally usable by anyone" point), this is meant to address whether the license was drafted to be specific / limited to a particular *licensor* -- e.g., if it names just one project or one company as the licensor. So for that item, I would tend to say that Hippocratic-3.0 *does* meet that criteria, since it appears to be drafted where anyone can use the license as a licensor.

That said, I otherwise agree with the analysis, and agree that the balance of factors tilts against adding it to the SPDX License List at this time. In particular, given that the license does not meet the [various open content definitions referenced in the inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md), and also not currently seeing substantial use by a significant number of projects from different licensors / contributors, I don't think the balance of factors comes out the same way that it did for [Hippocratic-2.1](https://github.com/spdx/license-list-XML/issues/959). If there is subsequently shown to be significant uptake of -3.0 across the community, then that might warrant revisiting this later.
