### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1439]
Review and update FAQs in markdown

Update link on webpage to direct here

**Comment by jlovejoy** [comment]
maybe add a FAQ re: "Why are the primary SPDX license files in XML format and what's up with all those weird tags?"

**Comment by jlovejoy** [comment]
discussed with and agreed to by SPDX Steering Committee that it's ok to move license list FAQs to DOCS folder here and put a link to this from website page.

@seabass-labrax - I think you have the current FAQs in markdown already somewhere?? were you going to submit a PR to move them? (I know we discussed this

**Comment by seabass-labrax** [comment]
Yup, I added the FAQs in PR #1437 :)

**Comment by jlovejoy** [comment]
now merged so need to 

- [ ] remove from website, link to here
- [ ] add edits and updates - PR for team to review

**Comment by jlovejoy** [comment]
now merged so need to 

- [ ] remove from website, link to here
- [ ] add edits and updates - PR for team to review

**Comment by jlovejoy** [comment]
@Pizza-Ria has added a ToC and re-ordered

**Comment by jlovejoy** [comment]
I've updated the web page so that it's just a header link that goes to the page here. It makes that page look a bit lopsided, but I suppose we can worry about that later (especially if we have bigger web updates in the making, @seabass-labrax :)

**Comment by swinslow** [comment]
Now in this repo at https://github.com/spdx/license-list-XML/blob/main/DOCS/faq.md

Open for folks to do:
* Can submit PRs for updating current text
* Can add new questions (and answers)

@jlovejoy and @swinslow happy to review and weigh in on contributions!

Specific additions:
* [ ] @bsdimp will add `-only` for GPL identifiers
* [ ] @copernicat will update links in FAQ to spec

* [ ] @copernicat and @bgoldring and @johnmhoran will review list of questions and suggest others to add => suggestions to be added in comments in this thread for team discussion

**Comment by copernicat** [comment]
Hi team, 
> * [ ]  @copernicat will update links in FAQ to spec
Done

> * [ ]  @copernicat and @bgoldring and @johnmhoran will review list of questions and suggest others to add => suggestions to be added in comments in this thread for team discussion

Suggestions for FAQ discussion: 
How does one represent a package that has components licensed separately under two or more licenses? Example: OS project has so-called "core" files under LGPL-3.0-only, but "non-core" files under BSD-3-Clause. https://github.com/zeromq/pyzmq

Does retaining a SPDX short identifier in a file satisfy OS license requirements? No. The short identifier is not intended to serve the purpose of license compliance, only license identification.

Does the OS license text need to be exactly the same as the text at spdx.org in order to apply the SPDX short identifier correctly? There are some non-substantive variations formally allowed, unique to each license. Please see the matching guidelines at https://spdx.dev/license-list/matching-guidelines/

**Comment by johnmhoran** [comment]
Possible FAQ:

How does one represent that one has searched for a file's/package's license but has been unable to find any relevant information (e.g., `unknown`, `unidentified`, `undisclosed`, `TBD`, `not found`)?

**Comment by jlovejoy** [comment]
@johnmhoran @copernicat - these look like good additions!

I started to do an update on existing questions here: #1679

**Comment by jlovejoy** [comment]
- [ ] adding a license - suggest pulling out and summarizing + adding more: How do I request? => higher-level answer not just link

- [ ] What are the general criteria? (summarize the inclusion principles briefly)

- [ ] Why was my license rejected?
- [ ]  Add more detail or another question on "Why not include every single license?"

- [ ]  What's involved in maintaining the license list? (explaining why effort is involved and why some aren't included)
- [ ]   Explain LicenseRef- more in non-listed licenses question
- [ ]   Concluded / Declared license - explain or clarify more re: SPDX documents
- [ ]   What does the blue text and red text mean in the license list entry?
- [ ]    What is a Standard License Header?

**Comment by copernicat** [comment]
As discussed, some wordsmithing of the proposed new FAQs, feedback welcomed. I have likely forgotten some of the good suggestions made in the legal team meeting; apologies in advance. I removed the "OS" adjectives, answered question 1 and reworded the answers for questions 2 and 3:

How does one represent a package that has components licensed separately under two or more licenses? The License Expression operator "AND" should be placed in between the applicable SPDX short identifiers. See Annex D SPDX license expressions (Normative) of the Specification for details.

Does retaining a SPDX short identifier in a file satisfy license requirements? The short identifier is intended to serve the purpose of license identification. If you need help with license compliance, seek the advice of an attorney.

Does the license text need to be exactly the same as the text at spdx.org in order to apply the SPDX short identifier correctly? There are some non-substantive variations formally allowed, unique to each license. See the matching guidelines at Annex B License matching guidelines and templates (Informative) of the Specification for details.


As an aside, I checked the links for the hypertext "License Expression" on these pages https://spdx.org/licenses/ and https://spdx.org/licenses/exceptions-index.html. It directs to https://spdx.dev/specifications/. Is it supposed to direct to a more specific location, like https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/? Or is it intended to let individuals search the spec themselves?

**Comment by jlovejoy** [comment]
@jlovejoy to add above comments and re-order in Google doc and then email everyone for review early next week

**Comment by swinslow** [comment]
I'm assuming this was completed for purposes of 3.19 as part of https://github.com/spdx/license-list-XML/pull/1692, so I'm going to go ahead and close this one. If there is more to be done, feel free to re-open and we can move it to 3.20 or a future release.
