### ISSUE TITLE
Update notes for the 389 Directory Server Exception

### ISSUE THREAD

**Issue by seabass-labrax** [spdx/license-list-XML#1450]
The '389 Directory Server Exception' has a note of which license it applies to:

https://github.com/spdx/license-list-XML/blob/4aa40837aa5a86f98b5324db1086922a0c265f65/src/exceptions/389-exception.xml#L7

However, that note uses the old SPDX License Identifier for the GPL version 2. Should this be updated to `GPL-2.0-only`? Unfortunately, the cross-reference to the Fedora wiki is a broken link now, so I couldn't find any further information from that.

**Comment by jlovejoy** [comment]
good catch @seabass-labrax ! agree on updating the identifier for GPL

I see what I can find re: the Fedora link, stay tuned...

**Comment by jlovejoy** [comment]
hmm... comments and actions seem to being duplicated here - odd

Anyway, we could add this URL: https://web.archive.org/web/20080828121337/http://directory.fedoraproject.org/wiki/GPL_Exception_License_Text
which has this actual text. Looks like the exception has changed over the years since then and when that link was still working.

**Comment by jlovejoy** [comment]
hmm... comments and actions seem to being duplicated here - odd

Anyway, we could add this URL: https://web.archive.org/web/20080828121337/http://directory.fedoraproject.org/wiki/GPL_Exception_License_Text
which has this actual text. Looks like the exception has changed over the years since then and when that link was still working.

**Comment by jlovejoy** [comment]
added link in #1540 
going to leave GPL-2.0 since this exception could apply to -only or -or-later
