### ISSUE TITLE
historical explanations

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1544]
we tracked the history of the license inclusion guidelines when we updated those, but what other topics would it be beneficial to have some kind of historical explanation of??

Here are a couple ideas:

- approved OSI licenses and history of alignment (since this has come up here and there)
- general history and timeline of SPDX License List (at a high-level)
- ??

**Comment by bsdimp** [comment]
I'd document when / how existing licenses are updated:
1. To correct errors in original submission (eg, the wrong version was submitted or a slightly corrupted version was submitted and not caught until afterwards).
2. To add new optional text
3. To add variations seen in the wild
4. To split a license when variations are deemed to be too much???? (not sure this has happened post commit)
5. Policy changes require changes??? (not sure this has happened post commit...)
6. ???? Not sure what other times things are changed.

It might also be useful to know what changed between releases, but that can be pretty low level and duplicates `git log` history.

**Comment by jlovejoy** [comment]
I think this is more process-related stuff, than historical, but some food for thought here:
- not sure what you mean by 1
- 2 and 3 would be good things to have documented in terms of process - maybe make new issue for that
- 4 has not happened
- 5 depending on what you mean by policy changes, I would think the timeline would hit on some of this
changes for releases is now capture in release notes, people can looks there ;)

**Comment by jlovejoy** [comment]
creating list here:

- [ ] general history and timeline of SPDX License List
- [ ] history of OSI alignment (and other communities alignment or involvement)
- [ ] history of license list fields (e.g., how full names and guidelines there and short identifiers came about, reality of evolution - this may end up being included in first item?)

consider: 
* should all of this live in once document? (start that way then re-consider)
* license inclusion background also exists, move that or leave where is?
* anything from wiki that would be useful to move to this? or link to stuff there

**Comment by bsdimp** [comment]
> I think this is more process-related stuff, than historical, but some food for thought here:
> 
> * not sure what you mean by 1

Have we ever had a case where we published a license text and then later adjusted that text because the original submission had the wrong version of the license. Given the large variation of MIT/BSD licenses, I'd think that might be possible in that space since there's no canonical source for these, or the canonical source is unclear.  This happened with OSI's inclusion of the BSD license, since they made changes to it (contributor -> author) that left the whole community scratching their heads...

> * 2 and 3 would be good things to have documented in terms of process - maybe make new issue for that

Did you want me to do this? I'm happy to...

> * 4 has not happened
> * 5 depending on what you mean by policy changes, I would think the timeline would hit on some of this
>   changes for releases is now capture in release notes, people can looks there ;)

OK. I'm happy with that answer.

**Comment by swinslow** [comment]
> Have we ever had a case where we published a license text and then later adjusted that text because the original submission had the wrong version of the license. 

I think that where this has occurred, it has been by deprecating a license ID that may have caused confusion. For instance, one that I'm sure will be relevant to you  :)  -- when [`BSD-2-Clause-FreeBSD`](https://spdx.org/licenses/BSD-2-Clause-FreeBSD.html) was deprecated in favor of [`BSD-2-Clause-Views`](https://spdx.org/licenses/BSD-2-Clause-Views.html), both to have a more general template and also due to confusion over whether this was "the license of FreeBSD".

As far as adjusting the text of an existing license ID, I _think_ this more typically happens where non-substantive variations are identified in the wild. For instance, similar to what you suggested, for [`MIT`](https://spdx.org/licenses/MIT.html) at some point we added the optional text "(including the next paragraph)" due to that occasionally showing up in the wild, but I don't think I'd view it as the "wrong" license either with or without that bit.

> > 4. To split a license when variations are deemed to be too much???? (not sure this has happened post commit)
>  4 has not happened

Similar to the above, the places where something like this has happened is usually where a variation of an existing license is identified and where the legal team determines it is substantively different.

For instance, [`HPND`](https://spdx.org/licenses/HPND.html) is an OSI-approved license that came with markup to handle a lot of minor variations. Later on, a variant was identified which explicitly added the right to "sell" the software to the license grant at the beginning. Because that additional license grant is _arguably_ substantively different, [`HPND-sell-variant`](https://spdx.org/licenses/HPND-sell-variant.html) was added as a separate license ID. I'm not sure if this is the sort of thing you mean by "splitting" a license based on variations, but this does happen from time to time.

**Comment by swinslow** [comment]
@jlovejoy Do we think there's anything here that we will get in for 3.19, or should I bump this forward?

**Comment by jlovejoy** [comment]
@swinslow - I've started to work on this, but bumping it forward as I won't have the PR ready to merge this week!

**Comment by jlovejoy** [comment]
moving this forward, as I'm still working on OSI history. (I should have created separate issues/tasks...)

**Comment by jlovejoy** [comment]
@swinslow - I'm going to close this one. I've done 2 of the 3 items and the 3rd one I don't think is really that critical!
