### ISSUE TITLE
New license request: Bitstream-Charter [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1557]
**1.** License Name: Bitstream Charter Font License
**2.** Short identifier: Bitstream-Charter
**3.** License Author or steward: Bitstream Inc.
**4.** Comments: The license is used in at least one Fedora package and is an allowed font license in Fedora.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/153
**7.** URL(s): https://fedoraproject.org/wiki/Licensing/Charter#License_Text, https://raw.githubusercontent.com/blackhole89/notekit/master/data/fonts/Charter%20license.txt
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/blackhole89/notekit/tree/master/data/fonts

**Comment by richardfontana** [comment]
Note that the version of the license text embedded in the font files and also the version Tom Callaway copied from one of the TeX-related packages does not have quotes around the trademark acknowledgement sentence.

**Comment by swinslow** [comment]
Given the name I was optimistically hoping that it might be similar to [`Bitstream-Vera`](https://spdx.org/licenses/Bitstream-Vera.html), but nope, not even remotely a match... sigh.

I'm +1 to add, this is a simple, broadly permissive and "attribution"-style font license, and recognizing that it is currently in use in Fedora.

I note that some of the linked examples refer just to "the 4 Bitstream Charter (r) Type 1 outline fonts" while others refer to "the 4 Bitstream Charter (r) Type 1 outline fonts and the 4 Courier Type 1 outline fonts". So for matching purposes in the template, we'll either want to have that whole part marked as an `<alt>` section, or else mark the "Courier" portion as `<optional>` so that it matches in either case.

**Comment by jlovejoy** [comment]
+1 to add

**Comment by OliverFendt** [comment]
I had a look at the license text and have some small remarks
1. The line 
> Copyright 1989-1992, Bitstream Inc., Cambridge, MA. 

shall be exlcluded from the license text, it is not part of the license.
2. The phrases

> the 4 Bitstream Charter (r) Type 1 outline fonts and the 4 Courier Type 1 outline fonts

and
> 4 Charter Type 1 fonts: 

shall be marked as not to be considered by the matching algorithms.
Besides that, I am in favor of adding the license

**Comment by LeChasseur** [comment]
How ist the relationship to https://scancode-licensedb.aboutcode.org/x11-bitstream.html? Same license (or part of it)?

**Comment by swinslow** [comment]
@LeChasseur I don't know the history of either license, but just from doing a comparison it looks like the bottom part of what Scancode calls x11-bitstream matches with the Bitstream-Charter license proposed here (including the optional "4 Courier Type 1" bit).

Everything in x11-bitstream prior to the copyright notice appears to be almost a second license, and doesn't appear in the Bitstream-Charter example that @richardfontana submitted for what was found in Fedora. Given that, I'm inclined for this one to stick with just the proposed Bitstream-Charter text.

**Comment by jlovejoy** [comment]
# License Inclusion Decision
## Decision: 
* approved 
## Full name:
* Bitstream Charter Font License
## Short id: Bitstream-Charter
* record final decision on short id to be used
## XML markup:
* yes for variations in variations in named fonts, see comments above
## Additional rationale or notes on decision:
* none

**Comment by richardfontana** [comment]
Fedora priority: Low
