### ISSUE TITLE
One-liner permissive statement

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1566]
This is a new issue stemming from #1292 for the "one-liner" version of this seen at https://sources.debian.org/src/armci-mpi/0.3.1~beta-1/COPYRIGHT/?hl=11#L11 
"Permission is hereby granted to use, reproduce, prepare derivative works, and
to redistribute to others."

Holding off on this for larger issue of more of these kinds of one-liners (permissive or public domain) that may surface as part of larger Linux distro use

**Comment by swinslow** [comment]
+1 to add this as a separate license.

There might be a broader discussion to be had about general identifiers or categories for "this is in the public domain", but for this one, this is a specific articulation of a license grant (without obligation or condition). I think it should be added as a separate entry.

I'm hitting a bit more of a stumbling block on the name / identifier. Perhaps `mpi-permissive-no-disclaimer` since this is basically [mpi-permissive](https://spdx.org/licenses/mpi-permissive.html) without the disclaimer?

**Comment by jlovejoy** [comment]
moving this out, as I need to remind myself on the background and where this was found

**Comment by jlovejoy** [comment]
this type of conditionless license is being captured in Fedora as "ultra-permissive" - closing this issue for now
