### ISSUE TITLE
potential updates to license submission tool

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1572]
some ideas, for further discussion:
- remove question re: OSI review/approval
- update or add info re: license steward name/author

**Comment by richardfontana** [comment]
Having used this tool a few times with some minor frustrations, I have a few additional suggestons:

- clarify that the submitter should suggest a license name since there often won't be an existing one
- clarify what to do for "Source URL" if there is no "official version" of the license, as that concept often won't exist
- clarify re 'who is the license author/license steward' should be "if known" or "if applicable", since most licenses have none
- "URLs" for example projects should be generalized to listing informion on projects where the license can be found. This question seems to assume that someone can find the license easily using a web interface to a source repository, but there are actually many widely-found licenses for which that is not true. 

The basic problem the points above are aimed at: Many of the current questions asked in the current version of the tool seem to assume a set of facts that apply to well known/well established licenses, commonly chosen today for new project code, but are less likely to be applicable to many of the other licenses found throughout community project code such as packages widely distributed by community Linux distributions. I have found it a little frustrating using the submission tool recently (and to the point of discouragement in the past) for this reason.

**Comment by jlovejoy** [comment]
thanks for the feedback, @richardfontana 

I've marked this as "discuss" as I think it's a worthy topic of having a look at the submission form (picture paints a thousand words) in light of the various feedback above and then coming up with a set of proposed changes. Then we can recruit someone with the requisite skills to make the updates :)

**Comment by richardfontana** [comment]
One other issue: I've submitted a number of licenses now through the tool and I have no idea what "Email" is supposed to mean. I've been putting my email address in, but it has recently occurred to me that, given where the field occurs in the form and the possible oddity of asking the license submitter to supply an email address, the form might intend for this to be an email address for the license steward. There's no tooltip or the like explaining what this field is for.

**Comment by goneall** [comment]
> One other issue: I've submitted a number of licenses now through the tool and I have no idea what "Email" is supposed to mean.

@richardfontana - there is a [partially complete pull request](https://github.com/spdx/spdx-online-tools/pull/379) to remove the email field entirely.

Once the PR is complete and unit tested, I'll merge in for the next release.

**Comment by jlovejoy** [comment]
we now have https://github.com/spdx/spdx-online-tools/issues/388 to track some of this 

PR https://github.com/spdx/spdx-online-tools/pull/389 deals with removing the email address (needs to be merged with the one @goneall  mentions above)

https://github.com/spdx/spdx-online-tools/pull/387 for some of the stuff we discussed on call

posed on mailing list idea of removing Standard Header field altogether - waiting decision on that

**Comment by jlovejoy** [comment]
@goneall and @jlovejoy are working on this, need to test PR and then can merge for next tools release.

**Comment by swinslow** [comment]
Thanks @jlovejoy, are you expecting this is something that the 3.19 release should wait on?

**Comment by swinslow** [comment]
@jlovejoy from your prior comment it sounds like this is still pending, so I'm moving this forward to 3.20.

**Comment by goneall** [comment]
@swinslow @jlovejoy Jilayne's changes were merged and a new release of the online tool has been moved to production.

You can check out the license submission tools at https://tools.spdx.org/app/submit_new_license/

**Comment by swinslow** [comment]
Thanks @goneall! In that case I'll go ahead and close this as part of 3.19.
