### ISSUE TITLE
0BSD license in Python-2.0.1.txt

### ISSUE THREAD

**Issue by capfei** [spdx/license-list-XML#1583]
Using the SPDX License Diff, I noticed that it is including the 0BSD license as part of the match, even though it is not included in the xml file. I did see that it is in the test file. Is it supposed to be there?

https://github.com/spdx/license-list-XML/blob/15b3ed7b817b39005d307072d9becb51d6f7b624/test/simpleTestForGenerator/Python-2.0.1.txt#L195-L207

**Comment by swinslow** [comment]
Hmmm -- that's very strange. I would have expected the matching checks to fail, with the text you indicated there in the end of the Python-2.0.1 test text file but not present (as optional or otherwise) in [the XML](https://github.com/spdx/license-list-XML/blob/main/src/Python-2.0.1.xml).

@goneall -- is this something you've seen previously? Given that it's at the end of the license text, I wonder if it's being silently ignored by the checker?

@capfei -- to your question about this specific one, I'm inclined to say that the 0BSD text is correctly _not_ included in the XML (as optional or otherwise). I note that [the Python 2.0.1 license text page from python.org](https://www.python.org/download/releases/2.0.1/license/) doesn't include it. Given that, I'd be inclined to leave it out from Python-2.0.1 -- and that way, items where it is present can be designated as `Python-2.0.1 AND 0BSD`.

**Comment by richardfontana** [comment]
I noticed this too FWIW.

**Comment by goneall** [comment]
> is this something you've seen previously? Given that it's at the end of the license text, I wonder if it's being silently ignored by the checker?

From looking at the XML and the test file, I agree these should not match.  In looking at the [matching code in the SPDX Java Library](https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java), the code is ignoring any text after a matching license text.

I created [a pull request with a fix](https://github.com/spdx/Spdx-Java-Library/pull/97).  However, the fix is causing other issues when there is optional text at the end of a license XML.  It could be a rather complex fix to some very complex code.

It will be interesting if other license XML tests will fail once this fix is made.  I'll run a test against the entire repo before merging the PR.

**Comment by swinslow** [comment]
Thanks @goneall! Really appreciate you digging into this. I saw that you opened an issue in Spdx-Java-Library for the broader technical issue. Let me know if I can help with taking a look at anything here.

For this one I think we can switch back to the specific Python-2.0.1 issue that @capfei flagged. Any concerns with just removing that from the end of the test text, since it appears to be there in error? If not, @capfei, would you want to submit a PR for that? Thanks!

**Comment by capfei** [comment]
@swinslow I'll get a PR submitted tomorrow. 👍

**Comment by capfei** [comment]
Sorry for the delay! Here is the PR: #1615
