### ISSUE TITLE
Fair Source License

### ISSUE THREAD

**Issue by 89z** [spdx/license-list-XML#1604]
- https://fair.io
- https://fair.io/v0.9.txt

**Comment by 89z** [comment]
https://github.com/fairsource/fairsource/issues/7

**Comment by richardfontana** [comment]
@89z why do you feel this license meets the SPDX [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md)?

**Comment by 89z** [comment]
why do you feel that it does not?

**Comment by silverhook** [comment]
@89z , please read [Request new licenses](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md) document and use the [new license submit workflow](https://tools.spdx.org/app/submit_new_license/).

**Comment by richardfontana** [comment]
@89z I am not sure if it does or not but I am not the one submitting the license :)

**Comment by 89z** [comment]
I feel this license meets the SPDX License Inclusion Principles, because I have reviewed the linked page.

**Comment by jlovejoy** [comment]
@89z - while you do not have to use the online form to submit a license for review (see https://tools.spdx.org/app/submit_new_license/ ) - we do need all submitters to provide the equivalent information in their submission. 

I'd also note that there is already an OSI-approved license with this name https://opensource.org/licenses/Fair (external links to it seem to be broken, but something to consider in terms of naming and short identifier)

**Comment by 89z** [comment]
I went with this one:

https://polyformproject.org/licenses/noncommercial/1.0.0

so I don't really care about this anymore. I will leave this open, as I still think it would be useful to have a healthy selection of non-commercial licenses. In researching this I found some troubling animosity toward NC licenses, with both GitHub and the Go programming language blocking them in one context or another. If moderators want to close issue, so be it. However I would encourage support of NC licenses. Not as an only choice, but as one respected path among many that a project might choose to take. It seems some business interests, including the OSI have skewed the perspective of what open source even means.

So by SPDX and others continuing support of NC licenses (among others), people can have an unbiased and informed choice, instead of one tilted towards business interests.

**Comment by jlovejoy** [comment]
@89z - so do I understand correctly that you (only?) submitted this license b/c you wanted to use it on your own project and since you've now gone with a different license, you are not caring about its submission any longer?  If so, I'll likely close it as we have a lot of open issues and if there isn't much interest to take this further, it can always be re-submitted at another time if there is interest. 

Please understand that SPDX doesn't "support" any particular license form in the usual sense of the word support. We have license inclusion principles that we use to determine if licenses should be on the SPDX License List or not. That helps keep the list a useful representation of licenses "found in the wild" while balancing some form of review and not having the list be so long as to lose value or usefulness. That being said, if you read the historical background on those principles, up until recently, the main criteria to be met was that the license met the Open Source Definition as defined by the OSI. This was all consistent with the mission and goals of the overall SPDX project.

Consider that historically, it has been well understood for several decades that a license that prohibits any particular field of use (e.g., commercial use) was not "open source" (as defined by the OSI) or "free software" (as defined by the FSF 3 freedoms). That is not about "animosity" or a "respected path" but about how those concepts and terms came to be defined. All forms and flavors of non-open source or non-free licenses have long existed and will continue to exist!

Then there are certainly some projects may have a policy of only allowing licenses that meet a certain criteria - that is up to them!

Anyway, hope that helps.

**Comment by 89z** [comment]
> so do I understand correctly that you (only?) submitted this license b/c you wanted to use it on your own project and since you've now gone with a different license, you are not caring about its submission any longer?

This table [1] was helpful to me. I have always used copyleft, but I came to realize that even with those, nothing is stopping a business from taking my software as is, and charging for it. I don't like that. So I went out looking for a non-commercial license. I first checked GitHub's list [2], but I noticed that every single license allows commercial use, and they even refuse to add non-commercial licenses [3]. So then I found the SPDX list [4], which seems to be a unbiased collection of licenses. I found the Fair Source License, which I thought would be a good addition, as currently it seems the only NC options on SPDX are CC-BY-NC and PolyForm-Noncommercial.

However I don't really want to go into a long battle just to have Fair Source License added. Its a license that aligns with my needs, and seems like it would be a good fit for the SPDX site. The SPDX people want me to put more effort into this than I am willing to, so I just choose one of the NC licenses that are already on the site. Maybe someone else can fight this battle at a later time.

1. <https://wikipedia.org/wiki/Free-software_license#Comparison>
2. https://choosealicense.com/appendix
3. https://github.com/github/choosealicense.com/issues/1015
4. https://spdx.org/licenses

**Comment by jlovejoy** [comment]
Thanks for the background. I had not seen that wikipedia table (and actually think it's a bit misleading, but that's a bit off-topic!)

Anyway, I don't think it's a battle to get a license submitted, we ask for people to contribute to the process equally :) but given the name issue (for obvious reasons, each license needs a unique id!), it might be better if the license steward/author was involved, so we can leave it to a later time/their involvement.

Thanks!
