### ISSUE TITLE
New license request: TPDL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1611]
**1.** License Name: Time::ParseDate License (name given by Tom Callaway)
**2.** Short identifier: TPDL
**3.** License Author or steward: David Muir Sharnoff (presumably)
**4.** Comments: The license occurs in at least one Fedora package.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/162
**7.** URL(s): https://metacpan.org/pod/Time::ParseDate#LICENSE
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/muir/Time-modules

**Comment by richardfontana** [comment]
I'm not sure "TPDL" isactually the best identifier to use but it is the one Fedora used prior to the recent adoption of SPDX short identifiers. 

Some source files have different contact information in the final "Please feed useful changes" sentence.

**Comment by jlovejoy** [comment]
+1 to add as this is a very short, permissive license statement. XML markup to the name in the last line

As to short identifier: TPDL doesn't conflict with anything already on the list, so unless you have a better idea, I'm inclined to go with that.

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by jlovejoy** [comment]
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/25

**Comment by bsdimp** [comment]
Makes me wonder if we should mark all 'email' addresses as 'optional' for matching purposes. Likewise for entity names?

+1 from me for what that's worth. Fedora name is fine. I have nothing better.

**Comment by copernicat** [comment]
Question: Because the license is so short, would allowing variation in the email address potentially cause this identifier to be applied in ways that don't make sense, e.g. to something that is not Time::ParseDate? On one hand, reuse is an advantage for a license identifier, but on the other, the name could be misleading. It differs from the license IDs BSD and MIT, for example, because it describes this particular package.

**Comment by jlovejoy** [comment]
generally, we have not added markup unless or until we find a real variation, for example in this case, this license with a different email address. I think that's probably fine for this license

**Comment by swinslow** [comment]
+1 to add. 

I don't have a particular preference for the identifier either, but I do note that it appears that it has been used by David Muir Sharnoff for several other Perl packages:
* https://sources.debian.org/copyright/license/libnet-netmask-perl/1.9015-4/
* https://github.com/muir/Net-SMTP-Receive
* https://metacpan.org/release/MUIR/File-Slurp-2004.0904/view/lib/File/Slurp.pm
Each of these also uses a different email address from the TPDL example, and additionally doesn't have a Google copyright (though both of these can be accommodated by markup of course).

Since this license appears to be used by David Muir Sharnoff for a variety of projects, I could be convinced to use his name in the ID in the same manner that we did for [libutil-David-Nugent](https://spdx.org/licenses/libutil-David-Nugent.html) in 3.19. But if that would be disruptive to Fedora, then I could also be persuaded that just going with TPDL is fine.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## License full name

Time::ParseDate License 

## Short ID

TPDL

## XML markup

for email address only, markup for variations of:
cpan@dave.sharnoff.org
and 
muir@idiom.org

(do alt for now, then can generalize if need be?)
