### ISSUE TITLE
New license request: Thor Public License (TPL-1.0)

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1612]
License text: https://fedoraproject.org/wiki/Licensing:ThorPublicLicense

License steward: Thomas Richter

Suggested short identifier: TPL (used by Fedora under the pre-SPDX system, and also apparently favored by the license author)

This license appears in one Fedora package (atari++, upstream project: http://www.xl-project.com/ [apparently no web-visible source repo]). It is an MPL 1.1 derivative differing substantively from MPL 1.1 only in the choice of law provision.

**Comment by jlovejoy** [comment]
Note, the the only differences in this license from MPL-1.1 (and CUA-OPL-1.0) is in the name and the choice of law (Germany for TPL, instead of California)
While we do not have markup in either MPL-1.1 or CUA-OPL-1.0 for name variations, that wouldn't solve this due to choice of law difference.

Choice of law is a substantive difference, thus I think we can 1) consider this a different license and 2) it certainly meets the inclusion guidelines due to it being otherwise the same as a well-known and already OSI-approved license

+1 to add

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by jlovejoy** [comment]
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/26

**Comment by jlovejoy** [comment]
I would go with Fedora shortname given the comments above and no conflict with anything already on SPDX License List

**Comment by bsdimp** [comment]
+1 to add. Choice of law might make it open source unfriendly due to different defaults in law (or it might not), but I'm not even qualified to offer this much of an opinion. On its surface, though, it looks good to  me.

**Comment by jlovejoy** [comment]
thanks @bsdimp!

**Comment by copernicat** [comment]
I agree with @jlovejoy 's analysis. +1 to add

**Comment by swinslow** [comment]
+1 to add.

One note on the identifier: The Exhibit A indicates that this is "Thor Public License Version 1.0". Given that, I would lean towards using "TPL-1.0" rather than "TPL" as the identifier. I recognize that this is a one-off license and unlikely to have multiple versions, but if the author has chosen a version number then I think we would usually include that in the identifier.

**Comment by jlovejoy** [comment]
good point on name and short identifier, @swinslow

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## License full name

Thor Public License v 1.0

## Short ID

TPL-1.0

## XML markup

none

## Additional rationale or notes on decision:

might be helpful to add a note along the lines of:
"This license is the same as MPL-1.1 (and CUA-OPL-1.0) except for the name and the choice of law"

**Comment by swinslow** [comment]
@jlovejoy good point on the 'v' vs. 'version' in the name! I had missed that in the license fields documentation, will keep that in mind in the future.

**Comment by swinslow** [comment]
Also, for whoever is preparing the markup (maybe me), note that Exhibit A should likely be tagged as a standard license header, similar to [MPL-1.1](https://github.com/spdx/license-list-XML/blob/main/src/MPL-1.1.xml).
