### ISSUE TITLE
New license request: W3C IPR SOFTWARE NOTICE

### ISSUE THREAD

**Issue by ghost** [spdx/license-list-XML#1646]
The OpenJDK (e.g., Eclipse Temurin) ships with ./src/jdk.xml.dom/share/classes/org/w3c/dom/xpath/COPYRIGHT.html

Relates to:

* https://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
* https://www.w3.org/Consortium/Legal/copyright-software-19980720

See attached:

[COPYRIGHT.html.txt](https://github.com/spdx/license-list-XML/files/9667534/COPYRIGHT.html.txt)

**Comment by swinslow** [comment]
This one is a near-exact match for [`W3C-19980720`](https://spdx.org/licenses/W3C-19980720.html), but with a couple of relevant differences:
* Instead of "Permission to use, copy, modify, and distribute" in W3C-19980720, this one says "Permission to use, copy, and modify"
* This one has an additional preamble talking about how clause 3 applies to "The DOM bindings", and could be read as imposing a different or additional specific requirement

@DaveJarvis Do you have any idea or context on why this is slightly different from the [W3C-19980720](https://www.w3.org/Consortium/Legal/copyright-software-19980720) version?

**Comment by DaveJarvis** [comment]
Sorry, I haven't any ideas why they differ. Perhaps the Eclipse team would have some insights?

**Comment by swinslow** [comment]
Thanks @DaveJarvis. I've tagged this one to be discussed at one of the upcoming legal team calls, to discuss the differences and also see if we have good contacts from Eclipse or W3C to ask about the history here.

**Comment by jlovejoy** [comment]
discussed on Jan 26th call - "and distribute" is different enough, but would like to communicate with W3C for awareness of how/why this difference is here and if it was intentional (before we add it to SPDX License List)

**Comment by jlovejoy** [comment]
@swinslow - moving this to 3.21 as it had a follow-up action that I think you were going to take

**Comment by jlovejoy** [comment]
@swinslow - did you post on the W3C mailing list ever get any response?

**Comment by swinslow** [comment]
Very belated reply on my part here  :)

I did receive a response in April 2023 stating that they would research this, but I never heard anything further from them. Given that the original requester appears to no longer be participating (it looks like their GitHub account is disabled), I'm going to go ahead and close this issue.
