### ISSUE TITLE
New license request: MIT-Wu [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1652]
**1.** License Name: MIT Tom Wu Variant
**2.** Short identifier: MIT-Wu
**3.** License Author or steward: Unknown (possibly Tom Wu)
**4.** Comments: This is a simple FOSS permissive license; the permission statement is taken from the MIT license but it uses a different warranty/liability disclaimer paragraph. It appears on certain source files related to benchmarking of JavaScript in V8 which has found its way into multiple packages in Fedora and other Linux distributions.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/171
**7.** URL(s): https://github.com/chromium/octane/blob/master/crypto.js
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://hg.mozilla.org/mozilla-central/file/5144d608cc2f43bf6b35742773ef0c7d2579ec27/js/src/octane/crypto.js

**Comment by richardfontana** [comment]
This is now the subject of a Fedora package maintainer's (@omajid) efforts to use SPDX identifiers for their package license metadata: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/102
Therefore we consider this to be a high-priority Fedora issue.

**Comment by jlovejoy** [comment]
Given this is very similar to MIT, used and allowed in Fedora, I'd say we should add it

**Comment by bsdimp** [comment]
+1 to allow. Could almost be variation in MIT license...
Not sure why it needs "In addition, the following condition applies: All redistributions must retain an intact copy of this copyright notice and disclaimer." at the end, but maybe that's enough of a condition difference to not try to make it a MIT variant via markup.

**Comment by swinslow** [comment]
The first two paragraphs (permission grant and condition) are from [MIT](https://spdx.org/licenses/MIT.html), while the disclaimer of warranties is from [libtiff](https://spdx.org/licenses/libtiff.html).

The additional condition at the end doesn't appear to be a match to anything currently on the license list (though as noted above I doubt it has any practical distinction from the main obligation).

Given the above, I'm +1 to add as a separate license. Clearly a permissive-style license and appears in a significant number of projects and commercial products, so meets the license inclusion guidelines.

This makes 3 +1's and no objections since the issue was filed on Oct. 1, so I'm marking this as accepted (particularly in the light of this being marked high priority for Fedora).

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## License full name

MIT Tom Wu Variant

## Short ID

MIT-Wu

## XML markup

none

**Comment by jlovejoy** [comment]
@richardfontana - given this is an easy one, do you want to give the PR for the xml and txt files a try on this one?

**Comment by richardfontana** [comment]
I will attempt to do so!
