### ISSUE TITLE
GPL-3.0-only template text: extraneous whitespace around philicenses var near end

### ISSUE THREAD

**Issue by pmonks** [spdx/license-list-XML#1697]
On [line 255 of GPL-3.0-only.template.txt](https://github.com/spdx/license-list-data/blob/master/template/GPL-3.0-only.template.txt#L255) (v3.18) there's a variable element within a URL, but the `<<var>>` is surrounded by whitespace, causing matches to fail:

**GPL-3.0-only.template.txt:**

`But first, please read <https://www.gnu.org/ <<var;name="philicenses";original="licenses";match="philosophy|licenses">> /why-not-lgpl.html>.` (note whitespace around the \<\<var\>\>)

[**Canonical License text:**](https://www.gnu.org/licenses/gpl-3.0.txt)

`But first, please read <https://www.gnu.org/licenses/why-not-lgpl.html>.` (note no whitespace around "licenses")

Note: it appears that this may be an issue with the logic that converts the source license list XML to the template text format, since this whitespace is not apparent in the [source XML](https://github.com/spdx/license-list-XML/blob/main/src/GPL-3.0-only.xml#L855).

**Comment by goneall** [comment]
There are attributes on the `<alt` tags that control spacing - to remove these spaces the the attribute `space=none`.

**Comment by pmonks** [comment]
Thanks @goneall. Would you like me to submit a PR, or (as a complete SPDX license list XML noob) would that be unhelpful?

**Comment by goneall** [comment]
@pmonks - I went ahead and created a PR.  Just read your comment above - in the future, do feel free to submit a PR when you across similar issues.  I didn't fully test that the PR removed the spaces, but it is now showing duplicate licenses for some of the other listed licenses where we would expect duplicates - so I think it did work.  I had to update the expected-warnings file so that it would pass the CI.
