### ISSUE TITLE
New License: QPL-1.0 variant (QPL-1.0-INRIA-2004)

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1722]
This is a match but for the copyright notice (not matchable) and the choice of law of France instead of Norway.

Would we accommodate the latter with markup or would this be a different license?

**Comment by jamesjer** [comment]
I have discovered that the hevea package in Fedora also uses a QPL license modified to choose France instead of Norway.

- [Project home page](http://hevea.inria.fr/)
- [License file](https://github.com/maranget/hevea/blob/master/LICENSE)

**Comment by jlovejoy** [comment]
@swinslow - I'm thinking that choice of law needs to be a different license, agree? 
In which case, we could call it: QPL-1.0-France ?

But I also noticed this exception text at the top:
` As a special exception to the Q Public Licence, you may develop
  application programs, reusable components and other software items
  that link with the original or modified versions of the Software
  and are not made available to the general public, without any of the
  additional requirements listed in clause 6c of the Q Public licence.`

@jamesjer - have you seen that before?

**Comment by jlovejoy** [comment]
I've added the exception as a separate request #1746

**Comment by swinslow** [comment]
@jlovejoy I'm confused by this still being called "Q Public License 1.0", but modified (apparently by someone other than Trolltech) to change the choice of law. (And also to remove the "Oslo City Court" venue requirement.)

I would tend to think of a change to choice of law being something substantive enough to warrant a different identifier.

I don't love the idea of still calling it "Q Public License" in the name or identifier. Maybe "HEVEA" License, or else "QPL-1.0-HEVEA"?

**Comment by richardfontana** [comment]
@swinslow For the identifier, I would argue for either "QPL-1.0-OCaml" or "QPL-1.0-INRIA". 

Some background: OCaml is a project stewarded by INRIA. HEVEA is apparently also an INRIA project written in OCaml. The LICENSE file for HEVEA is kind of confusing but without checking I think they may have just copied over the old LICENSE file of the OCaml implementation. It is not clear whether HEVEA chose to use the (modified) QPL because of the familiar tendency to use the license of the language ("same as Ruby" and so forth) or because of some perceived copyleft obligation, or both; maybe it doesn't matter. OCaml itself ceased using the (modified) QPL a number of years ago, but there are apparently a number of OCaml projects using old, pre-license-change source code from OCaml. I am pretty sure HEVEA is not the only remaining project using the OCaml QPL. It may be the only remaining project that appears to use the OCaml QPL as a main project license as opposed to a license for isolated source files, but no one has done the research into this. 

It seems most appropriate for the identifier to refer to the original project that used this QPL variant (OCaml, which is a fairly well known project, whereas I suspect HEVEA is relatively obscure) or to the license steward, if you will, for the QPL variant or the project steward for OCaml (both past and preent) as well as for HEVEA: INRIA. On the other hand, having the identifier refer to one minor project that may only be using it because they didn't know that OCaml had relicensed (I mean, this seems possible), seems less justifiable to me. Ultimately it doesn't matter too much given this is now a legacy license in two respects (because Qt and OCaml no longer use the respective variants) but I have a special interest in SPDX license identifier name choices. :smiley:

**Comment by swinslow** [comment]
Thanks @richardfontana! Appreciate the details here  😄 

This sent me digging a bit deeper, and it looks like the OCaml compiler went through [several license iterations itself](https://github.com/ocaml/ocaml/commits/cc0f32b05439bb7018e8ad62a54d6371b01aab9f/LICENSE). Here's a brief run-down of the major points, though I'm not sure this is even a complete list:
* [1995](https://github.com/ocaml/ocaml/blob/59cf50795583b4308a541ab85bd636ddfc9042ce/LICENSE): earliest license in Git commit history. INRIA custom license, limiting modifications to personal use and containing some other restrictions
* [1999](https://github.com/ocaml/ocaml/blob/cc0f32b05439bb7018e8ad62a54d6371b01aab9f/LICENSE): switched to QPL + LGPL. Note that this QPL instance has France for choice of law _and Versailles specified as venue for disputes_; it looks like [HEVEA also had this clause at the time](https://github.com/maranget/hevea/commit/e925fbe53a42751a585b3fa448684349530368c7).
* [2001](https://github.com/ocaml/ocaml/commit/02ef950033b81fe371759f024faa55f361ba83a6): added an LGPL exception (I haven't looked at this closely; it is modified in later commits)
* [2004](https://github.com/ocaml/ocaml/blob/c3a39fc8c84698aa4985c779e16493c2409a0285/LICENSE): added a note about changing the QPL's choice of law; added a QPL exception; and removed Versailles venue. _At this point, I believe it now matches the HEVEA license we're discussing in this thread. HEVEA seems to have made corresponding changes [in 2005](https://github.com/maranget/hevea/commit/ae61e4da4d895d2f312fc3901da31d86e55b8845)._
* [2016](https://github.com/ocaml/ocaml/blob/7fc2d214c4ee8853615fc3e5649f45e11d85378d/LICENSE): removed QPL and QPL exception; modified LGPL exception (which is currently on the SPDX License List as [`OCaml-LGPL-linking-exception`](https://spdx.org/licenses/OCaml-LGPL-linking-exception.html), discussed in #649)

This might all be a bit of a needless tangent :grin: but it suggests to me that perhaps the right ID and name could be:

* ID: QPL-1.0-INRIA-2004
* name: Q Public License 1.0 - INRIA 2004 variant

because it's possible that someone will want the 1999 variant someday...

**Comment by richardfontana** [comment]
> perhaps the right ID and name could be:
> 
> * ID: QPL-1.0-INRIA-2004
> * name: Q Public License 1.0 - INRIA 2004 variant
> 
> because it's possible that someone will want the 1999 variant someday...

:+1:

**Comment by swinslow** [comment]
@jlovejoy You had marked this earlier as "discuss on legal call". Given the details above, are you good with my proposed name and ID in order to give a +1 for this, or do you still want to discuss on a call?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [x] approved
- [ ] not approved

## License full name

Q Public License 1.0 - INRIA 2004 variant

## Short ID

QPL-1.0-INRIA-2004

## XML markup

none

## Additional rationale or notes on decision:

none

**Comment by jlovejoy** [comment]
@jamesjer - would you have time to prepare the PR for the files for this license in the next few days, by any chance?!?
 :)

as per: https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md
