### ISSUE TITLE
Add XML markup: HPND (for pngcheck) [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by musicinmybrain** [spdx/license-list-XML#1725]
**1.** License Name: pngcheck
**2.** Short identifier: pngcheck
**3.** License Author or steward: Unknown
**4.** Comments: This is the license of the pngcheck utility. The license appears to date to the 1990's, and has been stable for many years. The pngcheck utility is packaged in a number of Linux distributions (https://repology.org/project/pngcheck/packages), which suggests it should be considered a significant project. It is an extremely permissive license similar to NTP-0, but with different phrasing. Upstream describes it as an “MIT/X11-style license,” which seems accurate. Fedora Linux has found it to be an acceptable open source license in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/85.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/187
**6.** URL(s): http://www.libpng.org/pub/png/src/pngcheck-3.0.3.LICENSE
**7.** OSI Status: Not Submitted
**8.** Example Projects: http://www.libpng.org/pub/png/apps/pngcheck.html

**Comment by swinslow** [comment]
I think this is nearly a match for [HPND](https://spdx.org/licenses/HPND.html), which has several "optional" and "replaceable" elements as shown in the colors on the license list page.

From a quick review, the only difference I'm seeing is in the last sentence, where pngcheck uses "_This software_ is provided..." and HPND uses "_It_ is provided..." -- this may be something that we can accommodate in HPND via templating, rather than creating a new license ID just for pngcheck.

**Comment by jlovejoy** [comment]
Good catch, @swinslow - I thought I looked at this on the Fedora side, but didn't catch the HPND variations to this extent.

I agree with your analysis and that we can accommodate "It..." v. "This software..." - will add a PR shortly for that and change the labels on this one.

**Comment by jlovejoy** [comment]
Fixed by #1728
