### ISSUE TITLE
New license request: FPA-Code [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by William-McGonagle** [spdx/license-list-XML#1739]
**1.** License Name: FPA General Code License
**2.** Short identifier: FPA-Code
**3.** License Author or steward: The Fairfield Programming Association Inc.
**4.** Comments: This license is a branch off of the MIT/X11 license, with slight alterations to the guidelines that must be followed to use the license. Created by the Fairfield Programming Association to be the license used in an upcoming project with Unity Technologies, it enables open-source use in personal and educational spaces, but not in commercial settings (unless the modifications significantly change the code and/or project). This restricts asset ripping, or taking open-source code and uploading it to stores for profit, while still allowing the code to be open for collaboration.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/192
**6.** URL(s): https://about.fairfieldprogramming.org/programs/opensource-legal/fpa-general-code
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/fairfield-programming/fairfield-programming.github.io

**Comment by jlovejoy** [comment]
Hi there,
Not speaking to/separate from SPDX inclusion principles assessment - I am wondering what this phrase is supposed to mean:
"adding, removing, or modifying large parts, shall be developed in the Software. Reorganizing logic in the software does not warrant a substantial change."

"shall be developed in the Software" in particular, doesn't make much sense.

Looks like you all just started up your non-profit and have a very cool mission. But it seems a bit odd to say you are " are dedicated to the open-source mission" and then not use an already established and OSI-approved license. What you have drafted would not meet the OSD.

**Comment by NeilChaudhari** [comment]
> Hi there,
> 
> Not speaking to/separate from SPDX inclusion principles assessment - I am wondering what this phrase is supposed to mean:
> 
> "adding, removing, or modifying large parts, shall be developed in the Software. Reorganizing logic in the software does not warrant a substantial change."
> 
> 
> 
> "shall be developed in the Software" in particular, doesn't make much sense.
> 
> 
> 
> Looks like you all just started up your non-profit and have a very cool mission. But it seems a bit odd to say you are " are dedicated to the open-source mission" and then not use an already established and OSI-approved license. What you have drafted would not meet the OSD. 



Hey jlovejoy,

If you look above, the piece of text that you highlighted, you can see that it is a requirement for another requirement.

"Permission is granted to sell and/ or distribute copies of the Software in a commercial context, subject to the following conditions:"

The following condition is the piece of text that you highlighted.

As for our license not meeting OSD conditions, would you care to elaborate on where it wouldn't satisfy the conditions?

Our license limits how software is used, but not who uses it. Additionally, it doesn't violate free distribution because it states you can redistribute software if there is modification.

**Comment by jlovejoy** [comment]
Hi @William-McGonagle 
Yes, I understand how to read a license :)  - the condition itself (quoted above) is the part that is not clear. 

As for the OSD - it is not my place to comment on that definitively (that is for the OSI to do, if you submit it), but it seems that the license is purporting to have a field of endeavor.  In any case, the more key consideration is - why draft a new, not easy-to-understand license, rather than using something well-understood and accepted. The former may frustrate your overall intentions and wide use of the software under it.

But again, just an observation from someone who has read many, many licenses :)

**Comment by William-McGonagle** [comment]
Hi @jlovejoy- 

I'm sorry that you have frustration in reading the license, but we feel that the document should have a legal backing rather than focus on being readable (a license is built to protect both the contributors and copyright holders). That being said, it was written by the former legal council of Cendant, a mergers and acquisitions firm, for the exact reasons that we laid out. We do not feel that any other license covers the areas that this one does, and that is why we at the FPA chose to submit it.

Cheers,
Will

**Comment by jlovejoy** [comment]
Hi @William-McGonagle

As a lawyer with extensive experience related to open source software and licenses, I'm well acquainted with legal drafting and the need for a license to be easily understood - especially in the case of open source software, where the licenses are most commonly read and used, and thus need to be easily understood, by non-lawyers :)

Your license is not as clearly drafted as it could be - your explanation of the intent on your FAQ explains the intent, but that is not legally binding. Even if I read-in the intended meaning that the condition for commercial use relies on substantial changes - neither "commercial context", nor "substantial changes" are defined, leaving a lot open for interpretation.

As to the references to open source on your website, including in reference to this license: you might want to read up on the various newer licenses over the past 4-5 years containing restrictions on commercial use (e.g., SSPL, Commons Clause, Elastic license changes) that tried refer to themselves as "open source" and the ensuing controversies. Suffice to say, "source available" is the more relevant term used now for a license that puts these kinds of restrictions on a certain types of use. Indeed, there are existing licenses that are source available and have restrictions on commercial use, e.g., NPOSL-3.0, CC-BY-NC-4.0, BUSL-1.1, PolyForm-Noncommercial-1.0.0

In any case, I was trying to be helpful to someone and an organization which is obviously new. Of course, you can do what you like with free input. :)

Back with my SPDX legal team hat one and as for submission to the SPDX License List, under our inclusion guidelines:

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [X] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [X] No
This license is a modified MIT that limits use to "educational or personal context" and adds specific condition(s) to "commercial context".
1. **If a software license, does it apply to source code and not only to executables?**
    - [X] Yes
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - not really - As per the information on the license website at https://about.fairfieldprogramming.org/programs/opensource-legal/fpa-general-code, the license is "designed so that copyright owners can input different conditions that software users must fulfill". Yet, there is no versioning or method suggested for tracking such changes. 
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - not really? See comment above

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [X] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [X] Yes
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [ ] Yes
    - [X] No - only use is by this newly created non-profit at https://github.com/fairfield-programming
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - yes, but somewhat unclear
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [X] Yes - submitted by steward
    - [ ] No

## Summary of factors, outcome, comments

Given the lack of substantial use (and somewhat unlikelihood of pick-up of use of this license due to some drafting issues) and the intent of people to modify the license, I am leaning toward not approving for submission to SPDX License List.

While not an explicit factor for SPDX inclusion, using an existing, well-known open source license (MIT) to then modify to make non-open source by way of additional restrictions on fields of use, is not an advisable approach or good for the overall open source software ecosystem.

**Comment by William-McGonagle** [comment]
Hi @jlovejoy

I'm very sorry to hear that you do not recommend this license for approval and we do understand your concerns. 

We feel that under a less constricted definition this license is open-source, but do understand that you feel the term source-available is a more apt description. We feel that such a description takes away from the freedom and use that the license permits but nonetheless will take it into consideration.

As for the defining of "commercial context" and "significant changes", we feel that they are somewhat defined in their own wording, but especially on the latter do understand some confusion. We will have the open-source legal team put this into consideration.

For the modification of the MIT license, we do disagree. The only visible remainders of the MIT license is the text in the warranty, which appears in many other licenses including the ISC and BSD-style licenses (to name a few). So, we do not feel that it should prohibit inclusion. 

We do understand that you do not recommend this license because of these points, and please do understand that we will take them into consideration. As per our submission, we thank you for your time reviewing it. 

Do note: A vote was held in our monthly board meeting three days ago and a board vote (1-6) decided that, after POBF, we will no longer be seeking submission to the SPDX, further, we will not be allowing the inclusion of any future licenses in said SPDX registry.

Thank you for your time,
William McGonagle

**Comment by swinslow** [comment]
Hi all, given the response in the latest comment it sounds like @William-McGonagle and FPA as the license steward do _not_ want this license to be added to the license list, so I'll close this issue.

Adding a few comments below just for the record:

I'm generally in line with @jlovejoy's review comments [above](https://github.com/spdx/license-list-XML/issues/1739#issuecomment-1371748364). I would note that for the first "Definitive factor," I think this should be a "yes" rather than a "no" (because the license does not actually match to [MIT](https://spdx.org/licenses/MIT.html) or, I'm assuming, anything else on the list). But otherwise, I agree in full with the review.

On the "open source" label for the first "Other Factor," I know that there are discussions in the broader ecosystem about what "open source" should or shouldn't mean. For SPDX's purposes, we look primarily to the Open Source Initiative's [Open Source Definition](https://opensource.org/osd-annotated). 

I agree with @jlovejoy that the actual language of the license ("shall be developed in the Software") is ambiguous to me, but the FPA [FAQ](https://about.fairfieldprogramming.org/programs/opensource-legal/fpa-general-code) appears to indicate that commercial users / "companies" may not redistribute the code as-is. Based on this and on OSI's annotated version of the OSD, personally I think that the combination of factor 1 (requiring a license to permit free redistribution) and factor 6 (requiring a license not to exclude commercial users) means that this license wouldn't meet the OSI criteria.

In light of that and the lack of substantial use, I agree with the review above. In any case, given that FPA no longer wants this to be added to the license list anyway, I'll go ahead and close this issue.
