### ISSUE TITLE
New license request: QPL-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1746]
**1.** License Name: Q Public License exception
**2.** Short identifier: QPL-exception
**3.** License Author or steward: unknown
**4.** Comments: This is a special exception to a variant of the QPL-1.0

It has been approved as "allowed" for Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/84
**5.** License Request Url: http://tools.spdx.org/app/license_requests/194
**6.** URL(s): https://git.frama-c.com/pub/frama-c/-/blob/master/licenses/Q_MODIFIED_LICENSE, https://github.com/maranget/hevea/blob/master/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: http://hevea.inria.fr/

**Comment by jlovejoy** [comment]
related to #1722  (note @jamesjer and @richardfontana )

**Comment by richardfontana** [comment]
Since this is an exception to the INRIA variant (or one of the INRIA variants) of the "real" QPL, perhaps the exception shouldn't be named "QPL-exception" but perhaps something along the lines of "QPL-INRIA-exception" or whatever identifier is chosen in #1722 (or somethiing else entirely - I don't think any of the GPL/LGPL exceptions have *GPL in their name).

**Comment by swinslow** [comment]
So I'm going back and forth a little bit on whether:

1. the new QPL-1.0-INRIA-2004 in #1722 should _include_ this exception text -- such that we wouldn't need a separate entry on the exception list for this exception; or
2. QPL-1.0-INRIA-2004 should be _just_ the modified QPL text, and this exception should be a separate entry (so that the HEVEA software would be "QPL-1.0-INRIA-2004 WITH QPL-1.0-INRIA-exception" or whatever).

I'm _leaning_ towards option 2, for a couple of reasons:
* INRIA has apparently framed their version of the "Q Public License" text as being a separate license, and this exception as being an exception to it; and
* in practice, INRIA has put a different LGPL exception in the middle of the QPL exception and QPL text -- so having it as just a single license entry would probably be harder for license scanning tools to match correctly.

So I'm +1 to adding this as a separate exception, even though in practice QPL-1.0-INRIA-2004 might always only occur together with this exception. And I suppose a downstream licensee _could_ perhaps strip away the exception if they chose to do so.

As far as name and ID, I agree with @richardfontana above that I would incorporate INRIA into the name as with #1722. I'd suggest the following based on where we're aligning in that issue and on some of the other names on the [exceptions list](https://spdx.org/licenses/exceptions-index.html):

* ID: QPL-1.0-INRIA-2004-exception
* name: INRIA QPL 1.0 2004 variant exception

but I'm not tied to these and could be persuaded otherwise.

**Comment by jlovejoy** [comment]
+1 to add

**Comment by swinslow** [comment]
Discussed on 2023-02-09 legal team call, agreed to add with this ID and name.

**Comment by jlovejoy** [comment]
ummm... @swinslow @richardfontana - the two links to the text of the exception are not the same and I'm not seeing anything in the comments or recalling anything in our discussion about that??

https://github.com/maranget/hevea/blob/master/LICENSE - uses "versions of the Generator" and is one paragraph

https://git.frama-c.com/pub/frama-c/-/blob/master/licenses/Q_MODIFIED_LICENSE - uses "version of the Software" and has a second paragraph (which is OCaml-LGPL-linking-exception )

Should we just add the one paragraph and markup for Software/Generator?

**Comment by richardfontana** [comment]
@jlovejoy FWIW, the one that @jamesjer submitted for Fedora is the frama-c one. Though hevea is also in Fedora.

I would treat the two one-paragraph OCaml exceptions as equivalent and make Software/Generator substitutable.

**Comment by swinslow** [comment]
I'm also +1 on treating them as identical for these purposes, and marking Software / Generator as substitutable.

@jlovejoy I'll look at #1821 to see why the tests are failing, and will look at adding in the substitution for this too.
