### ISSUE TITLE
New license request: OPL-UK-3.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by robbiemorrison** [spdx/license-list-XML#1788]
**1.** License Name: United Kingdom Open Parliament Licence v3.0
**2.** Short identifier: OPL-UK-3.0
**3.** License Author or steward: UK Parliament
**4.** Comments: It is very similar to the approved OGL-UK-3.0 license, so I presume it complies with the necessary principles
**5.** License Request Url: http://tools.spdx.org/app/license_requests/203
**6.** URL(s): https://www.parliament.uk/site-information/copyright-parliament/open-parliament-licence/
**7.** OSI Status: Unknown
**8.** Example Projects: https://www.parliament.uk

**Comment by robbiemorrison** [comment]
Please see also Wikipedia:

* https://en.wikipedia.org/wiki/Parliamentary_copyright#Open_Parliament_Licence
* https://en.wikipedia.org/wiki/Open_Government_Licence#Open_Parliament_Licence

**Comment by richardfontana** [comment]
A better link for example projects might be https://developer.parliament.uk/ (though I haven't looked at this closely).

**Comment by swinslow** [comment]
+1 to add. This is a broadly permissive license, similar to [OGL-UK-3.0](https://spdx.org/licenses/OGL-UK-3.0.html) as @robbiemorrison noted, but sufficiently different that it shouldn't be combined with OGL-UK-3.0 via markup. (For example, this one appears to omit the OGL-UK-3.0 additional provision beginning with "If the Information Provider does not provide a specific attribution statement..")

We've generally been less stringent for looking to degree of usage when it comes to adding officially-blessed governmental licenses, so I'm +1 to add even though this is drafted so as to be used solely by the UK Parliament as licensor ("'Information Provider' means either House of Parliament.")

I'm good with the ID @robbiemorrison proposed.

Although I don't feel strongly about it, I would probably omit "United Kingdom" from the name, since the license author doesn't use that and we currently don't have another "Open Parliament License" on the list that it would be confused with. We also don't currently include "United Kingdom" in the names for the various OGL-UK- licenses.

**Comment by jlovejoy** [comment]
note: a PR has been made for this license (ahead of a decision) as practice for GSoC students. if we accept, then we can use the PR :)

**Comment by jlovejoy** [comment]
+ 1 to add

**Comment by swinslow** [comment]
I see +1's from myself and @jlovejoy. Since this isn't a "used in major distro" submission, can we get at least one more +1 from another legal team participant? @pmadick @copernicat @bsdimp or others feel free to weigh in  :)

**Comment by copernicat** [comment]
Hi, I am +1 for this based on Steve's observation: "We've generally been less stringent for looking to degree of usage when it comes to adding officially-blessed governmental licenses..."
