### ISSUE TITLE
Wrap Lines In MIT-License Output

### ISSUE THREAD

**Issue by ghost** [spdx/license-list-XML#1799]
Currently the MIT.txt, generated from the MIT.xml, has large horizontal bounds that make the document tedious to edit in many text-editors.

Here’s an example of a [preferred output](https://choosealicense.com/licenses/mit/#).

The lines don’t necessarily have to wrap, as constraint of 80 characters per-line would also do the job.

**Comment by meg-io** [comment]
I’ll familiarize myself with XML, and submit a pull-request within the week, if the request is too specific.

**Comment by jlovejoy** [comment]
when you say, "MIT.txt" - which repo are you referring to?

**Comment by meg-io** [comment]
The “spdx/license-list-data” repo, it being [this file][MIT] in particular.

I’ve used five licenses so far (Apache-2.0, CC0-1.0, CC-BY-4.0, GPL-3.0+, and MIT) and have noticed that they all have this issue; **this may be a repo-wide thing.**

I am unsure if I should change the scope of this issue or file a new one.

[MIT]: https://github.com/spdx/license-list-data/blob/main/text/MIT.txt

**Comment by seabass-labrax** [comment]
Thanks for opening this issue, @meg-io! There's an open issue covering a similar topic: https://github.com/spdx/license-list-XML/issues/1452.

Because the SPDX License List started out to improve automatic detection and identification of licences, the text files have always been more of an 'extra' to the XML files, so they are very inconsistent in formatting. However, there are now quite a few projects using the SPDX License List to download licence texts, including the [REUSE tool](https://github.com/fsfe/reuse-tool) and [Gitea](https://gitea.io/en-us/). Am I right in thinking that this is also the reason why you're interested in better line-wrapping, @meg-io?

(ping @sschuberth from previous discussion)

**Comment by jlovejoy** [comment]
this could also relate to how .txt files are generated if that step gets incorporated into the online tooling https://github.com/spdx/spdx-online-tools/issues/399

**Comment by bsdimp** [comment]
The [FreeBSD Project](https://www.freebsd.org) would like to use the .txt files, and one of the bits of feedback I've received is that they look sloppy, not least due to the long line issue. It's a minor issue, but since it's being discussed anyway, I'd thought I'd leave that feedback in case it moves the needle.

**Comment by meg-io** [comment]
> However, there are now quite a few projects using the SPDX License List to download licence texts, including the [REUSE tool](https://github.com/fsfe/reuse-tool) and [Gitea](https://gitea.io/en-us/). Am I right in thinking that this is also the reason why you're interested in better line-wrapping, @meg-io?

@seabass-labrax you are correct, I am currently using REUSE-tools to manage licensing in my projects.
However, often, I would rip the license-text from the GitHub-repo and add it to my project - for sake of convenience.

The text-editors I use do not wrap-lines, so reading and editing the license (i.e. copyright holder info) becomes an inconvenience.

The SPDX has a large-repository of licenses, a lot of which frankly are a pain to find other places. Being able to rip licenses as-is from the “license-list-data” repo is a huge boost from a usability perspective. From what I understand this, the “rip-ability”, is the primary selling-point of [ChooseALicense](https://choosealicense.com).

I’m not entirely familiar with XML but, if it is possible to constrain each line to ~80 characters during the txt-generation process, I believe this tweak will be very welcomed by a lot of people.

**Comment by meg-io** [comment]
> this could also relate to how .txt files are generated if that step gets incorporated into the online tooling [spdx/spdx-online-tools#399](https://github.com/spdx/spdx-online-tools/issues/399)

Agreed. However if online-tools rip from the '.txt'-files, instead of the '.xml'-files, I think the default should be ~80 characters per line as this benchmark is the most portable between text-viewers.

This also gives viability for using the '.txt'-files, generated by SPDX. I currently have to do manual-rips from different websites for the actual license, which is a shame since SPDX is the most comprehensive license-standard I currently know

**Comment by jlovejoy** [comment]
I'm not entirely sure how https://github.com/spdx/license-list-data/tree/main/text files are generating now, and I do not have the expertise on how to implement an automatic character-per-line limit, but I'm all for that if someone else knows how and wants to submit something.

in the bigger scheme, I feel like we should direct this discussion to the over-arching question at #1452 and then decide on implementation. I think this was also discussed via the mailing list in the past, so we could resurrect that thread, and also earmark for a future SPDX-legal call

**Comment by goneall** [comment]
Just FYI - the [LicenseListPublisher](https://github.com/spdx/licenselistPublisher) is the utility that generates the license-list-data repo.

For the .txt files, this is handled by the [LicenseTextFormatWriter](https://github.com/spdx/LicenseListPublisher/blob/master/src/org/spdx/licenselistpublisher/licensegenerator/LicenseTextFormatWriter.java).

**Comment by bsdimp** [comment]
> For the .txt files, this is handled by the [LicenseTextFormatWriter](https://github.com/spdx/LicenseListPublisher/blob/master/src/org/spdx/licenselistpublisher/licensegenerator/LicenseTextFormatWriter.java).

are we passing 'true' for the wordWrapText parameter?

**Comment by goneall** [comment]
> are we passing 'true' for the wordWrapText parameter?

This is set to false based on previous issues reported where they wanted verbatim text of the license including line breaks.  

More information can be found here: https://github.com/spdx/LicenseListPublisher/pull/90

**Comment by meg-io** [comment]
@goneall thank you for the insight.

After reading the related issue,

> More information can be found here: [spdx/LicenseListPublisher#90](https://github.com/spdx/LicenseListPublisher/pull/90)

I do understand keeping licenses marked as canonical "as-is".

However I also believe that disregarding the technical limitations, or in this instance railguards, during the licenses’ publishing would be too heavy-handed.

I cannot speak for every license-maker but, from my understanding, ***they were not anticipating the reading-boundary from the license-text to escape the reader’s viewport***. In these instances, they were using the railguards of HTML formatting.

Time does march forward though and, in more-and-more instances, the license-text is being consumed outside of their original HTML-medium (including in non-wrapping terminals and text-editors).

**I do not believe in these instances, which are most of them, that we should use a verbatim-interpretation - because it would be disregarding the HTML-viewport bounds.**

**Comment by meg-io** [comment]
My proposed solution to this would be to tag specific licenses as 'canonical' within the XML, which can then be interpreted by the Java-program and not be wrapped.

> I am not familiar with HTML so the solution may not be possible. But I’ve seen other tags, so I am assuming it is.

It is my understanding that only a few licenses have this trait, so it will be easier to implement.

We do have to remember that many license-makers aren’t computer-savvy; not in a bad way, but in the sense that they are likely not scrutinizing their HTML-formats.

**Comment by goneall** [comment]
> My proposed solution to this would be to tag specific licenses as 'canonical' within the XML, which can then be interpreted by the Java-program and not be wrapped.

In general, I'm OK with this proposal and it would be easy to implement in the LicenseListPublisher.  

I would add one detail to the proposal that the value for the tag is `true`, `false` or `unspecified`.  `true` and `false` would be set and reviewed by humans.

This is information we would need to collect on license submittal and the legal team may have additional work to review.  Since I don't actively participate in the curation of the license list, I'll defer to the active legal team members as to whether reviewing this field is a reasonable trade-off of effort / benefit.

One issue I suspect will be contentious is the default value if the field is `unspecified`.  Would we interpret a missing value as `true` which would yield the current result with the current license list, or should it be interpreted as `false` which would word wrap all of the text.

I would propose the default be `true` to minimize disruption to the existing users.

**Comment by meg-io** [comment]
> I would add one detail to the proposal that the value for the tag is `true`, `false` or `unspecified`. `true` and `false` would be set and reviewed by humans.

Agreed.

> I'll defer to the active legal team members as to whether reviewing this field is a reasonable trade-off of effort / benefit.

Very reasonable. My final arguments to the team is:

"This change doesn’t have to be applied to every license overnight and can be gradual, like via issue-requests. In the long-run the repository will be of great use to ***anyone*** looking to viably apply raw-licenses to their project(s).”

> I would propose the default be `true` to minimize disruption to the existing users.

Agreed. Defaulting to 'true' causes the least amount of disruption, all of the licenses that need can be flipped to 'false' via issue-request/PR. 'unspecified' should also be treated as 'true'.

This way the legal-team's resources aren’t expended all at once over this change and it can be rolled-out gradually.

**Comment by Pizza-Ria** [comment]
+1 to the preceding comment.

**Comment by jlovejoy** [comment]
@ghost @goneall - do I understand this would mean that the default of `true` would result in constraining each line to ~80 characters during the txt-generation
- if so, this sounds good to me!

and if set to `false` it would wrap the lines in whatever way is done so in the text file as here https://github.com/spdx/license-list-XML/tree/main/test/simpleTestForGenerator (or is it generated from the xml file?)
- in this case, the legal team would decide to change from the default of true to false when adding the license to the repo

I'm not clear on what `unspecified` is for, though?

**Comment by goneall** [comment]
> @ghost @goneall - do I understand this would mean that the default of true would result in constraining each line to ~80 characters during the txt-generation

Actually, the reverse - true would indicate the license is "canonical" and the text would come from the text files

> I'm not clear on what unspecified is for, though?

This would be represented by no value being in the XML file.  The text generated would be the default.  The reason I would like to have an unspecified value is to enable us to quickly determine if a human has reviewed and set a value.  In the scenario when setting the value to something other than the default, you would be able to tell if you are changing a decision someone previously has made.

**Comment by swinslow** [comment]
@jlovejoy @goneall I note that the original creator of this issue has deleted their GitHub account, so I think the original request can be treated as no longer relevant.

For the moment I'm going to change the milestone to 3.23 in prep for the 3.22 release, but unless there is anything in the request here that you would still be in favor of doing, I think we can close this.

**Comment by goneall** [comment]
@swinslow Unless someone volunteers to implement the suggestions by creating a PR to the XML Schema file and the LicenseListPublisher, I would close this issue.
