### ISSUE TITLE
Consider adding omitable text to Unicode-DFS-2016

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1853]
This is following from the discussion on the spdx-legal mailing list at https://lists.spdx.org/g/Spdx-legal/topic/97116566

The current text at https://www.unicode.org/license.txt is a close, but not identical, match for [`Unicode-DFS-2016`](https://spdx.org/licenses/Unicode-DFS-2016.html). Differences appear to include:
1. the added URL `<https://www.unicode.org/copyright.html>` after "See Terms of Use" at the beginning
2. the omitable text between that paragraph and the "NOTICE TO USER" being absent
3. different copyright date
4. "http" vs. "https"

Items 2, 3 and 4 above do not require changes to the template given the [SPDX matching guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/).

For item 1, though, I would be in favor of adding the URL (with angle brackets) as additional optional text in the XML markup file, so that it would match to the current version of that text hosted by Unicode.

Any reasons not to do this? And anything else between Unicode-DFS-2016 and https://www.unicode.org/license.txt that I'm missing?

**Comment by jlovejoy** [comment]
@swinslow - isn't the url in the part that is already marked as optional? in which case, it wouldn't matter??

**Comment by BrianInglis** [comment]
The current [*Unicode License*](https://www.unicode.org/license.txt) now references the current *Unicode* [*Copyright and Terms of Use*](https://www.unicode.org/copyright.html), which differs from *SPDX* [*Unicode ToU*](https://spdx.org/licenses/Unicode-TOU.html), adding sections *B Definitions*, which now explicitly incorporates and specifies the paragraphs that may previously have been considered *optional* text (though not I would have thought **optional** terms or conditions, *syntactic* rather than *semantic* options, depending on the sources to which the licence applied), including directory paths (some of which now differ), and section *C Terms of Use*, which incorporates some terms of use from the previous section *A Unicode Copyright*, and adds additional terms of use. 
This new *Unicode* *Copyright and Terms of Use* should probably be a newly created *SPDX* licence, and perhaps the new *Unicode License* should also be a new *SPDX* *Unicode Licence*. 
All *Unicode* data file releases from `4.1` onwards all and only refer (in their `Readme...`s) to *http[s]://www.unicode.org/terms_of_use.html* which now redirects to *https://www.unicode.org/copyright.html* the current *Unicode* *Copyright and Terms of Use*.

**Comment by jlovejoy** [comment]
given the text at [https://www.unicode.org/license.txt](https://www.unicode.org/license.txt) has changed again since this discussion and issue, do we still need to address this?

**Comment by BrianInglis** [comment]
Has it been reverted to close enough to DFS-2016 to close here, or does some action still need to be taken?

**Comment by jlovejoy** [comment]
I think we have resolved this (as much as we can, given the way Unicode maintains its URLs)
