### ISSUE TITLE
Why CC0-1.0 "isOsiApproved" false?

### ISSUE THREAD

**Issue by Sozialarchiv** [spdx/license-list-XML#1868]
https://github.com/spdx/license-list-data/blob/main/json/details/CC0-1.0.json#L22

See: https://opensource.org/license/unlicense/

**Comment by swinslow** [comment]
From SPDX's perspective, the [Unlicense](https://spdx.org/licenses/Unlicense.html) is not [CC0-1.0](https://spdx.org/licenses/CC0-1.0.html).

I'm not sure why that OSI page is showing Unlicense as if it was the same as CC0-1.0, but you may want to check with them. To my knowledge CC0-1.0 was submitted to OSI for their review but was not approved by them (see [here](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2018-October/003619.html) for one discussion where this was noted).

**Comment by swinslow** [comment]
Ah -- this was my mistake, and misunderstanding of the OSI's page for Unlicense. I think it's saying that _the license of the text of The Unlicense_ is itself under CC0-1.0. I don't know what the source is for that assertion, but I think that's what it's saying.

As noted elsewhere on that OSI page, the SPDX identifier for the Unlicense is `Unlicense`.

In any case, to my knowledge CC0-1.0 is not OSI-approved. Closing this issue, but feel free to re-open if you have a source from OSI stating otherwise.

**Comment by Sozialarchiv** [comment]
Thanks a lot for clarifying.
