### ISSUE TITLE
add markup for name to 389-exception

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1874]
https://spdx.org/licenses/389-exception.html

so that "this Program" is replaceable with actual name of program, like "FRYSK" in this example: 
https://sourceware.org/git/?p=frysk.git;a=blob;f=frysk-top/Makefile.am;h=d852fba8998a2dfc709c6b3e5168231b7425cc69;hb=HEAD

**Comment by jlovejoy** [comment]
@swinslow - I think this one is pretty straightforward/doesn't need discussion - agree?

**Comment by richardfontana** [comment]
Related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/171

**Comment by richardfontana** [comment]
BTW it's not obvious because of link rot but this page shows they were trying to use the exception in use by the project that came to be known as 389.
https://sourceware.org/frysk/questions/
(Also I have to note, given Red Hat's association with the exception language, we'd never use an exception like this nowadays. :)

**Comment by cagney** [comment]
@richardfontana nice digging, but s/trying to use/using/ - the text came from Red Hat legal.
The text also predates the initial release of Fedora Directory Server by several months, which might help explain the slight wording differences.
