### ISSUE TITLE
TEST-New license request: SGP4-Unlicense [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by BanulaKumarage** [spdx/license-list-XML#1885]
**1.** License Name: SGP4 unlicense with attribution
**2.** Short identifier: SGP4-Unlicense
**3.** License Author or steward: Unknown
**4.** Comments: Test licence request
**5.** License Request Url: http://tools.spdx.org/app/license_requests/213
**6.** URL(s): https://celestrak.org/publications/AIAA/2006-6753/faq.php
**7.** OSI Status: Unknown
**8.** Example Projects:  https://github.com/SWI-Prolog/packages-clib/blob/master/sha1/brg_endian.h

**Comment by BanulaKumarage** [comment]
@jlovejoy This is a test request I submit through the portal to test the process.

**Comment by jlovejoy** [comment]
@BanulaKumarage - great! If you think there is anything on the submission side of the tool that can be improved, please consider that for your project plan and make an issue in the tools repo, if applicable. 

Since you've already done the other end of the process - creating the xml and txt files - with other examples, I will probably close this issue shortly.

**Comment by jlovejoy** [comment]
closing as was for testing
