### ISSUE TITLE
TEST-New license request: TT [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by BassCoder2808** [spdx/license-list-XML#1889]
**1.** License Name: Test License
**2.** Short identifier: TT
**3.** License Author or steward: 
**4.** Comments: Test License
**5.** License Request Url: http://tools.spdx.org/app/license_requests/214
**6.** URL(s): 
**7.** OSI Status: Approved
**8.** Example Projects: https://fedoraproject.org/wiki/Licensing/LBNLBSD

**Comment by jlovejoy** [comment]
@BassCoder2808 - excellent! Do you think there is anything on the submission side of the tool that can be improved? If so, consider that for your project plan and make an issue in the tools repo, if applicable.

it would be good to see the "other side" of the tool - that is when a license that was submitted via the online tool is accepted and then the xml file and a PR are created.  Instead of doing a "test" one for that, let me find an open issue that you can try out - that way, you can test it and contribute to the project at the same time!

**Comment by BassCoder2808** [comment]
Thanks @jlovejoy, I would like to work open issue and would be really grateful for your help.
Yes, actually for when I was using the tool, once a license has been successfully submitted, it gets redirected to the same new license page itself, instead of that if we can make it redirect to 'https://tools.spdx.org/app/license_requests/{id}/' so that user can review it once as well and check whether everything entered was correct or not.
I have also created the issue in the SPDX-Online-Tools and if you think this would be helpful to the user, I will start working on it and then will update my proposal as well

**Comment by jlovejoy** [comment]
Hello @BassCoder2808 - once there are some "accepted" licenses (which should be soon) - I'll tag you and then maybe you can work on a "real" issue/license. 

Re: where you land once a license has been submitted - this is an interesting point. I thought it took you to the Github issue? I think this is more useful than bringing you to the page/listing in the tool. This is interesting because it makes me realize that the online tool serves as the "entry point" for submitting the license, then discussion and decisions happen in the Github issue, then the online tool is useful again as an "entry point" for creating the files to add the license to the SPDX License List. There is a bit of back-and-forth.. maybe this could be smoother? Open to ideas, I think I took this back-and-forth for granted!

**Comment by BassCoder2808** [comment]
No actually the callback is set to submit license page only, I have checked the code for that. For the time being, if we want that to direct to issues page, I will make the changes and the pr for the same in the spdx-license-tools. To reduce back and forth, we can kind of create a new tab which will be like a small window of github issues wherein the user can comment  to the discussions and the user will be inside the tool itself and would need not go to github specifically for the discussion

**Comment by BassCoder2808** [comment]
Hi @jlovejoy I was thinking of an approach to the above problem, and have come up with a potential solution, please let me know about your thoughts on the same and how to improve it.
1. Create a new page on your website or application where you want to display the GitHub issues.

2. Use the GitHub REST API to retrieve the list of issues for the repository we want to display. For this we can use the GET /repos/:owner/:repo/issues endpoint to retrieve a list of issues, and you can specify various query parameters to filter the results.

3. Display the list of issues on your page, including any relevant metadata such as the issue title, description, and labels.

4. Use the GitHub Issues API to allow users to create new issues or comment on existing issues. We can use the POST /repos/:owner/:repo/issues endpoint to create a new issue, and the POST /repos/:owner/:repo/issues/:issue_number/comments endpoint to add a comment to an existing issue.

5. Use the GitHub API to allow users to upload files as attachments to issues or comments. You can use the POST /repos/:owner/:repo/issues/:issue_number/attachments endpoint to upload a file as an attachment to an issue or comment.

6. To ensure that the page is visible to GitHub users when they log in, you can create a GitHub App that uses the GitHub API to authenticate users and retrieve their access tokens. We can then use these access tokens to make API requests on behalf of the user and display the relevant GitHub data on the page.

Also I was thinking to add this as a potential idea for my gsoc application, so if you think this can be a relevant contribution I will add it in my application about the same

**Comment by BassCoder2808** [comment]
Hi @jlovejoy, I also had another suggestion for the UI which I think could improve the user experience for the website, like currently we can only login in the website only using Github, so instead of first taking them on the signing page where they are eventually clicking on login using github option, we can directly redirect to the github login page when they click on the login tab at start.

**Comment by jlovejoy** [comment]
ok... this is a lot of ideas to process and I'm not sure that this is the best place to discuss!

We do want to direct "traffic" in terms of any discussion/comments on a given license submission to the Github issue. The online submission tool is really just an entry point. 

That is a good point as to if they don't have a GitHub account, though. And yeah, when you hit "submit", not much happens which is not very engaging.  

I've captured some better thoughts on this in a Gdoc - will post in Gitter for all GSoC contributors shortly!

**Comment by jlovejoy** [comment]
closing as this was for testing
