### ISSUE TITLE
New license request: CC-BY-SA-3.0-IGO

### ISSUE THREAD

**Issue by Doctor-love** [spdx/license-list-XML#1895]
### Introduction

Variant of the "CC-BY-3.0-IGO" license that was [somewhat recently included](https://github.com/spdx/license-list-XML/pull/1547). Like with most Creative Commons' licenses, there exist a "Share Alike" version that requires derivative work to be released under the same license. 

### License Name

Creative Commons Attribution-ShareAlike 3.0 IGO

### Suggested short identifier

CC-BY-SA-3.0-IGO

### URL to license text

https://creativecommons.org/licenses/by-sa/3.0/igo/legalcode

### OSI Status

I don't know

### License author or steward

Creative Commons

### URL to project(s) that use license

-

**Comment by Doctor-love** [comment]
More information about the IGO license variants: https://wiki.creativecommons.org/wiki/Intergovernmental_Organizations

**Comment by swinslow** [comment]
@Doctor-love Thanks for submitting. As a general practice, we will add special-purpose Creative Commons licenses to the SPDX License List when there is evidence of at least one substantial project or organization making use of it. Can you provide links to some projects or resources that are using CC-BY-SA-3.0-IGO?

**Comment by Doctor-love** [comment]
Thanks for your great work with this project, @swinslow !

My own use-case is including [photos from the European Space Agency](https://www.flickr.com/photos/astro_alex/30029883687/in/album-72157673903921058/) in presentations and UIs, which are often IGO licensed.

I find the reasoning for selectively adding CC licenses a bit odd - considering the release cycle for the SPDX license list and the time it takes for it to trickle down into tools like [REUSE](https://reuse.software/), seems like it would be easier for everyone (this project and its users) to just add the remaining ones - it's not like the few extra bytes is gonna hurt anyone and the chance for works being credited/properly reused increases. Could you elaborate a bit?

**Comment by swinslow** [comment]
Thanks @Doctor-love!

As a general matter for CC licenses, I gather there are a pretty staggering number of potential combinations of CC licenses, if all of the different possible country codes were implemented for each pre-4.0 variant. I believe https://wiki.creativecommons.org/wiki/CC_Ports_by_Jurisdiction is a list of the various jurisdictions, each with the various different versions and license attribute variations.

The main reason for the "wait until someone asks for it" informal policy is that the vast majority of use cases are already covered by the licenses that are currently on the list. Many of the combinations of the jurisdiction-specific older versions may not actually be used by anyone at present. When we become aware of an actual use, it's pretty easy at that point to get it added for the next release.

In this particular case, thanks for flagging the use by ESA of CC-BY-SA-3.0-IGO. I'm definitely +1 to add it here. @jlovejoy would you agree that we can go ahead and mark this as approved, given the above?

@Doctor-love after it is approved, would you be willing to submit a PR with the XML file and test text file? Some details are available [here](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process) for after this issue is marked as approved.

**Comment by Doctor-love** [comment]
Thanks for explaining your reasoning. Sure, I could submit a PR in that case! :-)

**Comment by jlovejoy** [comment]
yes, +1 to add and +1 to @swinslow  excellent explanation re: the CC licenses and how they get added.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Creative Commons Attribution ShareAlike 3.0 IGO

## License ID

CC-BY-SA-3.0-IGO

## XML markup

none

## Notes:

none

**Comment by jlovejoy** [comment]
@Doctor-love - could you make a PR for this, as per https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process ?

**Comment by Doctor-love** [comment]
> @Doctor-love - could you make a PR for this, as per https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process ?

Will do!
