### ISSUE TITLE
CAL-1.0 and CAL-1.0-Combined-Work-Exception

### ISSUE THREAD

**Issue by karsten-klein** [spdx/license-list-XML#1919]
Please review or clarify the modeling of CAL-1.0 and CAL-1.0-Combined-Work-Exception. The licenses where added 2 years ago and are basically semantically the same. CAL-1.0 already contains the exception and therefore I wonder why an additional exception was derived.

Regards,
Karsten

**Comment by swinslow** [comment]
This was discussed when the license was added, see https://github.com/spdx/license-list-XML/issues/953

**Comment by karsten-klein** [comment]
Thank you Steve. However even in #953 there is no particular reason mentioned for providing the exception variant. But now I understand better. It's yet another case of not identifying a license, but incorporating the usage context in the license identification (such as -only, -or-later, -invariants, -no-invariants, -RFN, -no-RFN), which I regard as (usage context) modifiers to the original license and not as separate identifiable license. The fact that the id uses the exception keyword is - as [jlovejoy](https://github.com/jlovejoy) pointed out unfortunate.
I'd like to also point out that I see using the SPDX identifiers within the license text is not a practice SPDX should promote. This reduces the degree of freedom in modeling licenses.

**Comment by jlovejoy** [comment]
is there an action item here? Could a Note be added to help clarify anything?

**Comment by jlovejoy** [comment]
@karsten-klein - note that we do not have control over the way people draft licenses. It'd be a lot easier if different variants on a particular license were drafted as separate and distinct versions, rather than a clause that allows some form of variant or modification to the terms of the license by way of some special marking. IN this case, the license itself instructs the licensor to mark files with "Combined Work Exception" so that is not language that was up to SPDX to choose. 

If you want to make a PR to add a Note to `CAL-1.0-Combined-Work-Exception`, along the lines of like we did for https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html that would be a nice contribution.

**Comment by jlovejoy** [comment]
there is a note as described above in the xml already via #1035 so closing this issue
