### ISSUE TITLE
Deprecation notice for AGPL-1.0 doesn't make any sense

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1922]
The line https://github.com/spdx/license-list-XML/blob/main/src/AGPL-1.0.xml#L13
states:
`      <notes><p>DEPRECATED: Use the license identifier AGPL-1.0-only instead of APL-1.0, and use AGPL-1.0-or-later instead of AGPL-1.0.</p></notes>`

The `APL-1.0` is presumably a typo (APL-1.0 is the unrelated Adaptive Public License). But if it's a typo for `AGPL-1.0`, the corrected statement
`DEPRECATED: Use the license identifier AGPL-1.0-only instead of AGPL-1.0, and use AGPL-1.0-or-later instead of AGPL-1.0.` still seems to not make any sense, because it is not specifying whether to use AGPL-1.0-only or AGPL-1.0-or-later instead of AGPL-1.0. 

I am not sure what was actually intended here. But I notice that there is no counterpart deprecation note for GPL-2.0 and GPL-3.0. Why should AGPL-1.0 need such a deprecation note if there isn't one for the closest textual counterpart (GPL-2.0)?

Furthermore, though perhaps this is a separate or larger issue, to the extent this was an outgrowth of some earlier effort to treat AGPL-1.0 similarly to the legacy GPL-family identifiers, AGPL-1.0 was not an FSF-stewarded license. The [commit message](https://github.com/spdx/license-list-XML/commit/96f8f6489f4bded6df4a8ca05a641e11dddeb118) that introduced this `DEPRECATED` note says:

`On Thu, Dec 28, 2017 at 09:56:54AM -0800, Jilayne Lovejoy wrote [1]:
> I am conferring with the FSF as to AGPL-1.0 - I will make the
> appropriate changes as needed when I get feedback there. No further
> discussion needed at this point.

On Thu, Jan 11, 2018 at 09:56:18PM +0000, Jilayne Lovejoy wrote [2]:
> ... I have confirmed that we should treat AGPL-1.0 that same) as we
> suspected.
`

Why would the opinion of the FSF have mattered at all here, given that AGPL-1.0 was not an FSF license?

**Comment by jlovejoy** [comment]
looking at the Notes for AGPL v. GPL-* - we put a general note about updates for SPDX License List v3.0 on the main page, stating, "Release 3.0 replaced previous Identifiers for GNU licenses with more explicit Identifiers to reflect the "this version only" or "any later version" option specific to those licenses. As such, the previously used Identifiers for those licenses are deprecated as of v3.0." - so I think that is why the individual licenses don't have notes. Since AGPL was updated for 3.1 it got a note. Not saying this is necessarily a good explanation, but I think that is why it's different.

That being said, if it's helpful to add a note on the GPLs, that's not much work to do so.

**Comment by jlovejoy** [comment]
I"m not really sure how this is a "larger issue" and as for what or how we even got feedback from the FSF on this question specifically, I don't really remember and not sure it's worth the time to dig back... :)
