### ISSUE TITLE
New license request: Xfig

### ISSUE THREAD

**Issue by zmiklank** [spdx/license-list-XML#1926]
**1.** License Name: MIT Xfig Variant
**2.** Short identifier: MIT-Xfig
**3.** License Author or steward: Unknown
**4.** Comments: MIT-Xfig is a variant of the MIT license, used in Fedora[1].
This variant has already been approved by Fedora legal[2].

[1] https://fedoraproject.org/wiki/Licensing:MIT#Xfig_Variant
[2] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/190
**5.** License Request Url: http://tools.spdx.org/app/license_requests/225
**6.** URL(s): https://github.com/Distrotech/transfig/blob/master/transfig/transfig.c, https://fedoraproject.org/wiki/Licensing:MIT#Xfig_Variant
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/Distrotech/transfig

**Comment by swinslow** [comment]
I'm +1 to add, as a short permissive / historical notice in use in Fedora.

For the name / ID, I would probably suggest "Xfig License" and `Xfig` as ID rather than `MIT-Xfig`. Although it might bear some practical similarities to `MIT`, there are also differences (such as the lack of the liability disclaimers paragraph at the end of `MIT`). Perhaps best to just call it `Xfig`.

From a bit of poking, it looks like https://sourceforge.net/p/mcj/xfig/ci/master/tree/src/Makefile.am is one example of use from the original Xfig project, so might be worth including this URL (or another one from that repo) in the cross-references.

**Comment by jlovejoy** [comment]
+1 to add as well. I'm surprised we didn't add this back in 2014 when we did a review of some of these for Fedora, actually. Back then we tended to adopt the Fedora shortname where possible since it was already in use, but I guess that's not critical now. I'm good with @swinslow suggestion. 

@richardfontana any opinions as to name? or can we call this accepted using `Xfig` ?

**Comment by richardfontana** [comment]
I prefer `Xfig` over `MIT-Xfig`, as recommended by @swinslow.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name
Xfig License

## License ID

Xfig

## XML markup

n/a

## Notes:

none
