### ISSUE TITLE
New license request: Linux-man-pages-copyleft-2-para (was: Latex2e-no-translation [SPDX-Online-Tools])

### ISSUE THREAD

**Issue by adobes1** [spdx/license-list-XML#1947]
**1.** License Name: Latex2e without translation permission
**2.** Short identifier: Latex2e-no-translation
**3.** License Author or steward: Unknown
**4.** Comments: Latex2e variant without the last paragraph about translation distribution.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/229
**6.** URL(s): https://github.com/mkerrisk/man-pages/blob/4f060b54679bcdfa3c1709ff6a984d8d85924fc2/man2/move_pages.2#L5-L12, https://github.com/mkerrisk/man-pages/blob/4f060b54679bcdfa3c1709ff6a984d8d85924fc2/man2/migrate_pages.2#L8-L15
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mkerrisk/man-pages

**Comment by adobes1** [comment]
Link to related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/201

**Comment by jlovejoy** [comment]
+1 to add as another variation that is (annoyingly just different enough from https://spdx.org/licenses/Latex2e.html and #1888 

can I get some other eyes on this? @swinslow @copernicat @richardfontana

**Comment by Pizza-Ria** [comment]
It would be nice to be able to just make that clause optional in Latex2(e) as I'm generally opposed to minting all of these variants but I guess there really isn't a path to do that.  So, count me as an annoyed +1.

**Comment by swinslow** [comment]
+1 on adding and +1 on wishing it wasn't another variation  :)

I'm not sure I would go with `Latex2e-no-translation` as the identifier, though. That could be misread as saying that translations are not permitted -- and probably wouldn't make sense to someone seeing it on its own, separate from `Latex2e`.

Maybe something like `Latex2e-2-Paragraph`, similar to `BSD-2-Clause`? That also kind of reflects the `VERBATIM_TWO_PARA` tag in the sample file.

**Comment by adobes1** [comment]
The URLs I included in this request as the URLs of the license text point to outdated mirror site which I unfortunately didn't realize. 
The correct ones should be: https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/move_pages.2#n5 and https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/migrate_pages.2#n8. 
Sorry for the confusion :)

**Comment by jlovejoy** [comment]
how about: 

1. License Name: Latex2e without translation permission
2. Short identifier: Latex2e-2-para
and a note saying "This license is similar to Latex2e and Latex2e-translated-notice, but omits the entire third paragraph

@swinslow @Pizza-Ria @adobes1 - thoughts?

**Comment by alejandro-colomar** [comment]
This license can also be though of as a 2-paragraph version of Linux-man-pages-copyleft.  Probably, the origin of both licenses is a common root (@g-branden-robinson suggested that Latex is the true origin of the Linux man-pages license, and that it was forked for the man-pages project[1]).  Since it's only used in the context of the man-pages project, I think we can name this one as `Linux-man-pages-copyleft-2-para` (with a full name of: `Linux man-pages Copyleft (2-paragraph version)`).  Then the 1-paragraph version would have a name consistent with this one.


[1]: <https://lore.kernel.org/linux-man/20210926060318.pypfwwido5log7ss@localhost.localdomain/T/#u>

**Comment by richardfontana** [comment]
I like @alejandro-colomar's suggestion as to the name.

**Comment by g-branden-robinson** [comment]
I kind of _don't_ like @alejandro-colomar's suggestion as to the name, because (1) as @bsdimp pointed out, it gives a hostage to fortune.  Once someone comes up with another 2-paragraph license resembling this one, this identifier will become ambiguous.  Someone might do so out of sheer perversity, but they might have a better reason, like this actually being a pretty good license for its intended purpose.

(2) Perhaps more importantly, this tag/full-name elevates material of less importance to most SPDX consumers over material of more importance, that being, what does the license permit or prohibit?

The main problem with this license as I see it is that it doesn't _mention_ translation, so translations are neither expressly permitted nor prohibited.  My vague understanding, which Real Copyright Lawyers can surely correct or revise, is that translations of literary works enjoy somewhat special status under copyright laws and treaties and involve complications that generally aren't applied to software, either statutorily or in case law.  (Roughly, if someone translates R. F. Kuang's recent novel _Yellowface_ into Quechua, the translator enjoys certain rights in the translation but the work is nevertheless not independent of Kuang's copyright.)

I think @jlovejoy is nearer the desired mark here.

I therefore propose `Linux-man-pages-copyleft-no-translation-grant` (with a full name of: Linux man-pages Copyleft (translations prohibited)`.  Or if that "short" tag is too long, `Linux-man-pages-copyleft-no-trans`.

If "translation" is not a form of "modification" under law in major jurisdictions relevant to the SPDX project, then this 
license is not Free Software or Open Source, and the best remedy might be to get the work in question (`move_pages(2)`) relicensed.   The copyright holders are Silicon Graphics, Inc., which was acquired by HP in 2016, and Christoph Lameter.  I've met Christoph, though it's been a while.  Bdale Garbee surely still has contacts at HP.

If even that fails (more likely due to people deciding they don't have the authority, or a command of the work's provenance, rather than sullen opposition, I would expect), then the document is 264 lines of _man_(7) macro source, a language with lines tending to shortness.  The page also has 5 `FIXME` comments, a pretty high ratio for a page of this length, I think.  So rewriting the thing might not be a bad idea.

**Comment by alejandro-colomar** [comment]
@g-branden-robinson

I agree.  We have all this mess with BSD-* licenses, where there are
many variants with the same number of clauses, so probably counting
paragraphs is not the best thing to do.  I like your suggestion for
full name and short identifier.

**Comment by jlovejoy** [comment]
hey all, the reason for using "Latex2e" in the id is due to the very close similarity to existing licenses on the SPDX License List that use that name. I think this is helpful for people in terms of association, so I'm inclined to go with what I suggested above. Although 2-para could also be 2-clause 

In any case, we do need to make decisions more quickly!  :)

**Comment by alejandro-colomar** [comment]
Hi @jlovejoy ,

Would you please comment in the Linux man-pages mailing list?  Here on github we have 4 or 5 issues and corresponding PRs (and the 4 or 5 links to the corresponding Fedora issues), and I have a mess in my head of all of the licenses we're discussing.  In the man-pages mailing list we have a single thread for all of these, where we're discussing them all together.

If you're in a hurry, I suggest reverting anything already done, and not committing anything again until we have some consensus.

I didn't do this before myself because I wasn't decided on how to do it, and I still have doubts, so I would very much prefer to do it slowly and carefully.

Please join this thread: <https://lore.kernel.org/linux-man/CADeQ=2-ZsaSCEPfTHUO6AAZ_+H8ob4LJ5x5MuGaX=jdOVpdCog@mail.gmail.com/T/#u>.

Thanks,
Alex

**Comment by jlovejoy** [comment]
Let me try to do a "reset" on each of these issues individually :)

This issue is for the license text:
`Permission is granted to make and distribute verbatim copies of this manual provided the copyright notice and this permission notice are preserved on all copies.

Permission is granted to copy and distribute modified versions of this manual under the conditions for verbatim copying, provided that the entire resulting derived work is distributed under the terms of a permission notice identical to this one.`

This is the same as the existing license on the SPDX License List `Latex2e` https://spdx.org/licenses/Latex2e.html - the difference being that license has a third paragraph that this submission omits. Likewise it is similar to `Latex2e-translated-notice` https://github.com/spdx/license-list-XML/blob/main/src/Latex2e-translated-notice.xml which adds a bit more to the third paragraph.

We are not changing the existing ids and we usually use a similar id for similar license as that is helpful for people.

Question for @alejandro-colomar - is this license still being used? (there was some talk on the linux-man mailing list of updating/changing some of the licenses)

If yes, then we will proceed to add it to the SPDX License List using the name and id as identified above unless anyone can come up with a better id in by Friday morning that still used Latex2e- in the id

(I appreciate wanting to take care, but we can't spend unlimited time on license id naming :)

**Comment by alejandro-colomar** [comment]
On 6/8/23 06:33, Jilayne Lovejoy wrote:
> Let me try to do a "reset" on each of these issues individually :)
> 
> This issue is for the license text:
> `Permission is granted to make and distribute verbatim copies of this manual provided the copyright notice and this permission notice are preserved on all copies.
> 
> Permission is granted to copy and distribute modified versions of this manual under the conditions for verbatim copying, provided that the entire resulting derived work is distributed under the terms of a permission notice identical to this one.`
> 
> This is the same as the existing license on the SPDX License List `Latex2e` https://spdx.org/licenses/Latex2e.html - the difference being that license has a third paragraph that this submission omits. Likewise it is similar to `Latex2e-translated-notice` https://github.com/spdx/license-list-XML/blob/main/src/Latex2e-translated-notice.xml which adds a bit more to the third paragraph.
> 
> We are not changing the existing ids and we usually use a similar id for similar license as that is helpful for people.
> 
> Question for @alejandro-colomar - is this license still being used? (there was some talk on the linux-man mailing list of updating/changing some of the licenses)
> 
> If yes, then we will proceed to add it to the SPDX License List using the name and id as identified above unless anyone can come up with a better id in by Friday morning that still used Latex2e- in the id
> 
> (I appreciate wanting to take care, but we can't spend unlimited time on license id naming :)
> 


Yep, this license is still being used.  And after reconsidering,
Latex2e-no-translation LGTM.

Acked-by: Alejandro Colomar ***@***.***>

Cheers,
Alex

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5

**Comment by jlovejoy** [comment]
discussed on 6/8 call: re: id name, @swinslow  pointed out that these two paragraphs are (also) the same as Linux-man-pages-copyleft variants and that for consistency with that name, maybe we should use that (instead of Latex2e-) 

Also discussed -2-para v. -short and thought maybe simply "short" would be better as it leaves room for # of paragraphs or other names if we happen to find further variants later (I hope not, though!)

Thus, final (hopefully) id would be: `Linux-man-pages-copyleft-short`

@alejandro-colomar and @adobes1 - sorry for all the back and forth! If you could +1 this, then I'll make the PR!!
