### ISSUE TITLE
New license request: Linux-man-pages-1-para [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by adobes1** [spdx/license-list-XML#1955]
**1.** License Name: Linux man-pages One Paragraph
**2.** Short identifier: Linux-man-pages-one-para
**3.** License Author or steward: Unknown
**4.** Comments: This license appears in several Linux man-pages under the name of VERBATIM_ONE_PARA
**5.** License Request Url: http://tools.spdx.org/app/license_requests/231
**6.** URL(s): https://github.com/mkerrisk/man-pages/blob/master/man2/getcpu.2#L4-L7
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mkerrisk/man-pages

**Comment by adobes1** [comment]
Related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/207

**Comment by swinslow** [comment]
Text of license from URL, adding here for convenience:

Permission is granted to distribute possibly modified copies of this page provided the header is included verbatim, and in case of nontrivial modification author and date of the modification is added to the header.

**Comment by swinslow** [comment]
I'm +1 to add this to the list, as a simple, historical license which appears to be broadly permissive / meet the OSI definition.

I'm not sure what to use for the name and identifier. I'm inclined not to use "one-para" or "One Paragraph" since there are likely other man pages that also have just one paragraph. But I take your point about VERBATIM_ONE_PARA being the tag used at https://github.com/mkerrisk/man-pages/blob/ae6b221882ce71ba82fcdbe02419a225111502f0/man2/getcpu.2#L3. Open to others' thoughts on this as well!

**Comment by jlovejoy** [comment]
+1 to add and probably safe to use the longer name/id version that @adobes1 suggested as we also have to resolve #1959

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Linux man-pages One Paragraph

## License ID

Linux-man-pages-one-para
## XML markup

none

## Notes:

none



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by BrianInglis** [comment]
Should not even be looking at [man7](https://github.com/mkerrisk/man-pages/blob/master/man2/getcpu.2#L4-L7) pages except as possible *examples* as they are **years** outdated compared to the current [Linux kernel.org](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/getcpu.2#n4) pages (or the bleeding edge [maintainer](http://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/tree/man2/getcpu.2#n4) pages which feed that). 
It might also be worth discussing on the [man-pages mailing list](mailto:linux-man@vger.kernel.org?cc=Alejandro%20Colomar%20%3Calx.manpages@gmail.com%3E), or at least mentioning and referring back with links to these issues, and updating Alex @alejandro-colomar (or possibly just referring to him if he monitors these) on licence name changes to maintain consistency. 
He is very responsive especially when man page patches are included. ;^>

**Comment by alejandro-colomar** [comment]
@jlovejoy @swinslow 

Please reopen this issue.  The PR shouldn't have been merged.

Here goes some review:

> 1. License Name: Linux man-pages One Paragraph

For consistency with Linux-man-pages-copyleft (https://spdx.org/licenses/Linux-man-pages-copyleft.html),
this should be `Linux man-pages Copyleft one paragraph` (or similar).

> 2. Short identifier: Linux-man-pages-one-para

Should be `Linux-man-pages-copyleft-one-para` (or -paragraph, as you prefer).

> 3. License Author or steward: Unknown

Author is unknown.  I'm the steward, as maintainer of the Linux man-pages.

```
Alejandro Colomar <alx@kernel.org>
```

> 4. Comments: This license appears in several Linux man-pages under the name of VERBATIM_ONE_PARA
> 5. License Request Url: http://tools.spdx.org/app/license_requests/231
> 6. URL(s): https://github.com/mkerrisk/man-pages/blob/master/man2/getcpu.2#L4-L7

As @BrianInglis pointed out, that mirror is just a mirror (if you follow the link, it says so several times), and is outdated by years.
The correct URL should be <https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/getcpu.2#n4>


> 7. OSI Status: Unknown
> 8. Example Projects: https://github.com/mkerrisk/man-pages

Same here:

<https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git>

**Comment by jlovejoy** [comment]
@alejandro-colomar - thanks for having a look! and thanks @BrianInglis for making the connection.

I'm fine to update the name and ID as per your suggestion since you are the maintainer. Please see #1978 

@adobes1 - this is one of those rare situations where there is a change in the id of a merged license, please note for your Fedora package review and sorry for any inconvenience!

**Comment by alejandro-colomar** [comment]
> @alejandro-colomar - thanks for having a look! and thanks @BrianInglis for making the connection.

Cheers!

> 
> I'm fine to update the name and ID as per your suggestion since you are the maintainer. Please see #1978

I changed my mind yesterday after learning about yet another license request.  I'll suggest that we use -1-para instead of -one-para, since there's also a -2-para.

> 
> @adobes1 - this is one of those rare situations where there is a change in the id of a merged license, please note for your Fedora package review and sorry for any inconvenience!

Did you release already to the website?  We already modified the Linux-man-pages-copyleft after merged but before release, so I expect no problems there, except maybe if Fedora already started using it before the release, but I guess they didn't.

Thanks!

**Comment by jlovejoy** [comment]
re: timing on release - we have not pushed 3.21 yet and aim to do so in a week or so. Note that once a release is finalized we do NOT change ids lightly and try to avoid doing so. As it is, it's not optimal that we are having this name debate after the license was merged, but since it's before the release it's okay-ish.  In any case, spending lots of time on naming of one license does take time from getting other work done - and I know, naming is hard! But we do need to be decisive and move on ;)

**Comment by BrianInglis** [comment]
If dropping suffixes *-1-para*/*-2-para* as less meaningful, maybe suffix this one something like *-verbatim*, as that is understood, and we have meaningful names?

**Comment by jlovejoy** [comment]
@alejandro-colomar - please confirm that your last suggestion is good to go:
Id = `Linux-man-pages-copyleft-1-para`
name = "Linux man-pages Copyleft (1 paragraph)"

**Comment by alejandro-colomar** [comment]
On 6/8/23 06:46, Jilayne Lovejoy wrote:
> @alejandro-colomar - please confirm that your last suggestion is good to go:
> Id = `Linux-man-pages-copyleft-1-para`
> name = "Linux man-pages Copyleft (1 paragraph)"
> 

You probably know more about copyleft/right than I do.  I'll leave
the consideration of if this license should carry "copyleft" in the
name or if it's less of a copyleft than Linux-man-pages-copyleft
up to you.
<https://github.com/spdx/license-list-XML/pull/1978#issuecomment-1563167772>

For consistency with BSD-N-Clause and others, I suggest using -1-
instead of -one-.  Since no better suggestion has been made, -1-para
makes sense to me.

Thanks,
Alex

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5

**Comment by jlovejoy** [comment]
Thanks @alejandro-colomar - as for "copyleft" or not - after closer inspection of all these variants, it's the second paragraph that contains the copyleft-like obligation, so it probably makes sense to NOT use "copyleft" in this one since it omits the second paragraph

that would make it `Linux-man-pages-1-para`

FYI @swinslow  and @richardfontana (not sure we got to this one on the call today)

**Comment by alejandro-colomar** [comment]
On 6/8/23 19:25, Jilayne Lovejoy wrote:
> Thanks @alejandro-colomar - as for "copyleft" or not - after closer inspection of all these variants, it's the second paragraph that contains the copyleft-like obligation, so it probably makes sense to NOT use "copyleft" in this one since it omits the second paragraph

Agree.

> 
> that would make it `Linux-man-pages-1-para`

Sounds good.  :)

Acked-by: Alejandro Colomar ***@***.***>

> 
> FYI @swinslow  and @richardfontana (not sure we got to this one on the call today)
> 

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5
