### ISSUE TITLE
New license request: Man-pages-copyleft-var [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by adobes1** [spdx/license-list-XML#1959]
**1.** License Name: Linux man-pages Copyleft Variant
**2.** Short identifier: Man-pages-copyleft-var
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in several Linux man-pages. It is very similar to Linux-man-pages-copyleft.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/233
**6.** URL(s): https://github.com/mkerrisk/man-pages/blob/master/man2/set_mempolicy.2#L5-L20
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mkerrisk/man-pages

**Comment by adobes1** [comment]
The only difference between this license and Linux-man-pages-copyleft is that this license does include the following sentece:
> The author(s) may not have taken the same level of care in the production of this manual, which is licensed free of charge, as they might when working professionally.

Related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/212

**Comment by jlovejoy** [comment]
I'd like to hear others thoughts on this - the sentence that is omitted in this variant is kind of informational... could we justify just marking it as optional?

**Comment by BrianInglis** [comment]
Should not even be looking at [man7](https://github.com/mkerrisk/man-pages/blob/master/man2/set_mempolicy.2#L5-L20) pages as they are **years** outdated compared to the current [Linux kernel.org](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/man2/set_mempolicy.2#n5-n20) pages (or the bleeding edge [maintainer](http://www.alejandro-colomar.es/src/alx/linux/man-pages/man-pages.git/tree/man2/set_mempolicy.2#n5-n20) pages which feed that).

**Comment by BrianInglis** [comment]
A quick log analysis confirms the majority of contributors email addresses are from what `psl` renders as *professional* commercial orgs:
```
     50  redhat.com
     29  google.com
     12  suse.com
     10  intel.com
     10  ibm.com
      9  suse.de
      8  suse.cz
      8  fujitsu.com
      7  oracle.com
      5  intel.com
      5  canonical.com
...
```
whereas the largest number of *volunteer* contributors 145 have `gmail.com` addresses.

**Comment by jlovejoy** [comment]
@BrianInglis - when you say you shouldn't be looking at these man pages b/c they are old... but apparently they are still around and distributed 

@adobes1 - I presume you created this request b/c these man-pages are included in Fedora (as per Fedora license policy)?

**Comment by BrianInglis** [comment]
> @BrianInglis - when you say you shouldn't be looking at these man pages b/c they are old... but apparently they are still around and distributed

There are many unmaintained projects, packages, and their websites - see [*Sourceforge*](https://sf.net) for lots of examples, and those products are still "distributed", like many old and even ancient system and package versions (`Linux` 2.00 `man pages` anyone?), even though they may not have been updated nor downloaded for many years (and for software, may contain many serious unfixed security vulnerabilities). 
Thus I refer to those man pages as merely providing examples of (possibly outdated, as of next release) licence text. 

Those *private* man pages and related web pages have not been updated since @mkerrisk stopped maintenance two years ago after [`Linux` 5.13 and `glibc` 2.34](https://github.com/mkerrisk/man-pages), possibly to concentrate on keeping his [*The Linux Programming Interface*](https://man7.org/tlpi/api_changes/) (course) book editions up to date to make up for pandemic losses giving online (and private/on premise) training courses in Europe and the Americas (booking a year ahead), conference presentations, and consulting on those topics (those web pages have been updated). 

The *Linux* `man pages` project had no official maintainer after 5.13 for a ten month period during which time 921 commits had been applied for 6 `Linux` releases and associated `glibc` changes. 
For comparison, since that release, 672 commits have been applied to date, and @alejandro-colomar has been doing a lot of housekeeping, standardizing, updating man pages to standards and also supporting `[gt]roff -man` commands, as the `[gt]roff` and `-man` maintainer fixes issues and updates macros. 
[Of course, one commit could be a patch affecting hundreds of files or lines.]
We are now many releases later preparing for @alejandro-colomar to release [Readme](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/about/) *Linux* [`man pages` 6.05](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git).

As of #1955 and #1978 I now define the package licence as:
```
MIT AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC 
AND Linux-man-pages-copyleft AND Linux-man-pages-copyleft-one-para 
AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
```
with the latest Linux-man-pages-copyleft-one-para.txt **yet** to be added to the [LICENSES](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/LICENSES) directory, and await the resolution of this issue #1959 for possible further change.

**Comment by alejandro-colomar** [comment]
> > @BrianInglis - when you say you shouldn't be looking at these man pages b/c they are old... but apparently they are still around and distributed
> 
> There are many unmaintained projects, packages, and their websites - see [_Sourceforge_](https://sf.net) for lots of examples, and those products are still "distributed", like many old and even ancient system and package versions (`Linux` 2.00 `man pages` anyone?), even though they may not have been updated nor downloaded for many years (and for software, may contain many serious unfixed security vulnerabilities). Thus I refer to those man pages as merely providing examples of (possibly outdated, as of next release) licence text.
> 
> Those _private_ man pages and related web pages have not been updated since @mkerrisk stopped maintenance two years ago after [`Linux` 5.13 and `glibc` 2.34](https://github.com/mkerrisk/man-pages), possibly to concentrate on keeping his [_The Linux Programming Interface_](https://man7.org/tlpi/api_changes/) (course) book editions up to date to make up for pandemic losses giving online (and private/on premise) training courses in Europe and the Americas (booking a year ahead), conference presentations, and consulting on those topics (those web pages have been updated).
> 
> The _Linux_ `man pages` project had no official maintainer after 5.13 for a ten month period during which time 921 commits had been applied for 6 `Linux` releases and associated `glibc` changes.

A minor correction.  I was already maintainer since 2020, but didn't yet have keys to the repository.  So I couldn't effectively update the official repository.

> For comparison, since that release, 672 commits have been applied to date, and @alejandro-colomar has been doing a lot of housekeeping, standardizing, updating man pages to standards and also supporting `[gt]roff -man` commands, as the `[gt]roff` and `-man` maintainer fixes issues and updates macros. [Of course, one commit could be a patch affecting hundreds of files or lines.] We are now many releases later preparing for @alejandro-colomar to release [Readme](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/about/) _Linux_ [`man pages` 6.05](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git).
> 
> As of #1955 and #1978 I now define the package licence as:
> 
> ```
> MIT AND BSD-2-Clause AND BSD-3-Clause AND BSD-4-Clause-UC 
> AND Linux-man-pages-copyleft AND Linux-man-pages-copyleft-one-para 
> AND GPL-1.0-or-later AND GPL-2.0-only AND GPL-2.0-or-later
> ```
> 
> with the latest Linux-man-pages-copyleft-one-para.txt **yet** to be added to the [LICENSES](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/LICENSES) directory, and await the resolution of this issue #1959 for possible further change.

Yes, when all this is merged, I plan to add those license files to the repository, and change the files to use SPDX-License-Identifier.

**Comment by alejandro-colomar** [comment]
> @BrianInglis - when you say you shouldn't be looking at these man pages b/c they are old... but apparently they are still around and distributed

The thing is that they are distributed from the official tarballs released in the kernel.org repository:

<https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/>

which are created from the git.kernel.org repo.

The github repo linked before was just a mirror that the previous maintainer (@mkerrisk) had for having more visibility of the project.  However, he froze the mirror when he stopped maintaining the project.  And anyway, that mirror was never officially used for anything.  Downstream packagers never used it.

> 
> @adobes1 - I presume you created this request b/c these man-pages are included in Fedora (as per Fedora license policy)?

Yes, the man pages are used in Fedora, but they are taken from the kernel.org released tarballs.  @nforro, the Fedora maintainer for the man-pages can probably confirm.  The github repo is not involved in this.

**Comment by nforro** [comment]
> Yes, the man pages are used in Fedora, but they are taken from the kernel.org released tarballs. @nforro, the Fedora maintainer for the man-pages can probably confirm. The github repo is not involved in this.

Exactly: https://src.fedoraproject.org/rpms/man-pages/blob/3d662119c3ae8bc2a38934b6c4304435251e19ca/f/man-pages.spec#_10

**Comment by jlovejoy** [comment]
ok, so back to the question for SPDX-legal:

as compared to https://spdx.org/licenses/Linux-man-pages-copyleft.html, does the omission of the sentence
`The author(s) may not have taken the same level of care in the production of this manual, which is licensed free of charge, as they might when working professionally.`

make this a different license or could we mark that sentence as optional?

personally, I have mixed feelings on this one....

**Comment by richardfontana** [comment]
I would view the two licenses as "different".

**Comment by Pizza-Ria** [comment]
I really WANT to make this optional (as that is my default stance on most of these minor variations) but I could see that statement as being a bit of a supplement to the disclaimer - it seems to be more of a proactive statement than passive disclaimer.   I do agree with associating this with the Linux-man-pages-copyleft moniker.  How about Linux-man-pages-copyleft-alt?

**Comment by BrianInglis** [comment]
I would consider the sentence appears to me to be a pro-commercial/proprietary anti-open-source snark, implying if it was done *professionally* for commerical proprietary software or manuals, it would be better as the author(s) would have been paid! 
I agree with @Pizza-Ria and really *do not* see this changing the Ts&Cs. 

[In reality, commercial proprietary docs are often done in whatever time is available by whoever is available and only reviewed for inaccuracy or illegality before being stamped *good enough* to move on from. I've done 120 in a month, because that was the number needed, and when we needed to start chruning out code! 
Volunteer contributors to and maintainers of open source have more time to consider, be thorough, and produce a decent product, if they decide they are going to produce docs, which can be the hard sell! And the committers, like Alex, are not afraid to push back if needed. 
Like many of us, I have voted with my wallet, only buying really good value products from vendors, as most open sourced products (e.g. *PC*s, *Raspberry Pi*) are better than most commercial proprietary anything, with rare exceptions.]

**Comment by alejandro-colomar** [comment]
> I would consider the sentence appears to me to be a pro-commercial/proprietary anti-open-source snark, implying if it was done _professionally_ for commerical proprietary software or manuals, it would be better as the author(s) would have been paid! I agree with @Pizza-Ria and really _do not_ see this changing the Ts&Cs.
> 
> [In reality, commercial proprietary docs are often done in whatever time is available by whoever is available and only reviewed for inaccuracy or illegality before being stamped _good enough_ to move on from. I've done 120 in a month, because that was the number needed, and when we needed to start churning out code! Volunteer contributors to and maintainers of open source have more time to consider, be thorough, and produce a decent product, if they decide they are going to produce docs, which can be the hard sell! And the committers, like Alex, are not afraid to push back if needed. Like many of us, I have voted with my wallet, only buying really good value products from vendors, as most open sourced products (e.g. _PC_s, _Raspberry Pi_) are better than most commercial proprietary anything, with rare exceptions.]

That's very true.  I had a similar feeling recently.  I'll relicense my pages to this license (when it gets an identifier).

I'm going to send a mail to linux-man@.

**Comment by alejandro-colomar** [comment]
> I would consider the sentence appears to me to be a pro-commercial/proprietary anti-open-source snark, implying if it was done _professionally_ for commerical proprietary software or manuals, it would be better as the author(s) would have been paid! I agree with @Pizza-Ria and really _do not_ see this changing the Ts&Cs.
> 
> [In reality, commercial proprietary docs are often done in whatever time is available by whoever is available and only reviewed for inaccuracy or illegality before being stamped _good enough_ to move on from. I've done 120 in a month, because that was the number needed, and when we needed to start churning out code! Volunteer contributors to and maintainers of open source have more time to consider, be thorough, and produce a decent product, if they decide they are going to produce docs, which can be the hard sell! And the committers, like Alex, are not afraid to push back if needed. Like many of us, I have voted with my wallet, only buying really good value products from vendors, as most open sourced products (e.g. _PC_s, _Raspberry Pi_) are better than most commercial proprietary anything, with rare exceptions.]

On second thought, and after re-reading the license, a lot of truth is hidden in that sentence.  Let's see:


> The author(s) may not have taken the same level of care in the production of this manual, which is licensed free of charge, as they might when working professionally.

It doesn't really say that the care is less because of being a volunteer.  It could perfectly mean a higher level of care, and it's often the case.  (=D

**Comment by jlovejoy** [comment]
ok, trying to reset a bit here: @alejandro-colomar - is this still being used in the Linux-man pages or did you manage to re-license the files that used it?

If it is being used still, then SPDX had already decided to accept it and that it is different enough to be its own license and so we "just" need to decide on an id. `Linux-man-pages-copyleft-var` is probably the best option.

(interpretation of the extra sentence and feelings about it aside :)

**Comment by alejandro-colomar** [comment]
On 6/8/23 06:52, Jilayne Lovejoy wrote:
> ok, trying to reset a bit here: @alejandro-colomar - is this still being used in the Linux-man pages or did you manage to re-license the files that used it?
> 
> If it is being used still, then SPDX had already decided to accept it and that it is different enough to be its own license and so we "just" need to decide on an id. `Linux-man-pages-copyleft-var` is probably the best option.
> 
> (interpretation of the extra sentence and feelings about it aside :)
> 
Hi Jilayne,

Yes, I couldn't get rid of any license.  I reduced uses of one of them,
but not much of a change.

The original license tag (not SPDX, but the tag used in the source code)
was VERBATIM_PROF (Linux-man-pages-copyleft was called VERBATIM there).
I think that makes more sense.  Do you agree to call it
Linux-man-pages-copyleft-prof?

Thanks,
Alex

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5

**Comment by jlovejoy** [comment]
discussed on 6/8 call - accept and add with id: `Linux-man-pages-copyleft-var`

(b/c "prof" gives an odd impression)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Linux man-pages Copyleft Variant

## License ID

Linux-man-pages-copyleft-var

## XML markup

n/a

## Notes:

_add any information that is to be included in the Notes field_

## Additional rationale or notes on decision:

_add any additional information, including optionally a summary of what is recorded in the issue comments_

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by alejandro-colomar** [comment]
On 6/9/23 04:14, Jilayne Lovejoy wrote:
> discussed on 6/8 call - accept and add with id: `Linux-man-pages-copyleft-var`
> 
> (b/c "prof" gives an odd impression)
> 
> 

Ok

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5
