### ISSUE TITLE
New license request: Asterisk-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by musicinmybrain** [spdx/license-list-XML#1971]
**1.** License Name: Asterisk exception
**2.** Short identifier: Asterisk-exception
**3.** License Author or steward: Unknown
**4.** Comments: This exception appears in libpri and in libss7, which are part of Asterisk, a prominent open-source telephony stack that is packaged in major Linux distributions, including Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/234
**6.** URL(s): https://github.com/asterisk/libpri/blob/7f91151e6bd10957c746c031c1f4a030e8146e9a/pri.c#L22, https://github.com/asterisk/libss7/blob/03e81bcd0d28ff25d4c77c78351ddadc82ff5c3f/ss7.c#L24
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/asterisk/libpri, https://github.com/asterisk/libss7

**Comment by jlovejoy** [comment]
+1 to add, as it's a pretty benign exception

**Comment by Pizza-Ria** [comment]
Isn't Asterisk under the GPLv2 as well (https://github.com/asterisk/asterisk/blob/master/LICENSE).  Just to be clear, this exception is saying that if you obtain alternative licensing terms for Asterisk then you can combine this module with it and use those alternative licensing terms? That strikes me as a bit extenuated since this is in the same repo as Asterisk ... maybe a solution for a poorly drafted private license + it seems very specific since it is attached to just the Asterisk project.  Per a snippet of @richardfontana's comment in the Fedora issue:  "The question though is whether it just saying "If you paid for a non-GPL license from Digium, you can ignore the GPL on this library" which I would see as not worth capturing with an exception identifier."   He goes on to comment that this shouldn't be assumed but I'm having trouble coming up with a practical reason for this exception (per my general antagonism to clutter).

**Comment by musicinmybrain** [comment]
> Isn't Asterisk under the GPLv2 as well (https://github.com/asterisk/asterisk/blob/master/LICENSE).

Yes, Asterisk is GPLv2; I haven’t examined it closely, but I think it is `GPL-2.0-only`.

> Just to be clear, this exception is saying that if you obtain alternative licensing terms for Asterisk then you can combine this module with it and use those alternative licensing terms? That strikes me as a bit extenuated since this is in the same repo as Asterisk ... maybe a solution for a poorly drafted private license + it seems very specific since it is attached to just the Asterisk project.

Technically, it’s not quite right to say that these projects are distributed in the same repository: [libpri](https://github.com/asterisk/libpri/) and [libss7](https://github.com/asterisk/libss7/) are in separate SCM repositories on GitHub under the [`asterisk` organization](https://github.com/asterisk), not in the main [asterisk repository](https://github.com/asterisk/asterisk). Similarly, their releases don’t currently appear to be distributed in the main [asterisk source tarballs](https://www.asterisk.org/downloads/), but have their own download directories under https://downloads.asterisk.org/pub/telephony/.

It *is* valid to say that all of these projects fall under the umbrella of the Asterisk organization, that they share some developers, and that all of their copyright statements appear to indicate Digium, Inc. as copyright holder.

I’m not sure that any of these distinctions are terribly important here, but there they are.

> Per a snippet of @richardfontana's comment in the Fedora issue: "The question though is whether it just saying "If you paid for a non-GPL license from Digium, you can ignore the GPL on this library" which I would see as not worth capturing with an exception identifier." He goes on to comment that this shouldn't be assumed but I'm having trouble coming up with a practical reason for this exception (per my general antagonism to clutter).

It seems obvious to me that this exception was written with the intent that it would facilitate Digium’s proprietary/commercial license schemes. In principle, it could still come into play if Digium released a copy of Asterisk under an open-source license other than GPLv2, and included one of these libraries “in any form that would qualify as a 'combined work' or as a 'derivative work' (but not mere aggregation).” This seems unlikely to me, but the future is a big place.

I don’t have a strong opinion on what should happen here. It would be a bit awkward, practically speaking, to have [`libpri-OpenH23-exception`](https://github.com/spdx/license-list-XML/issues/1939) but not this exception, but in the end I *personally* just need something to put in the `License` tags of the Fedora packages.

**Comment by richardfontana** [comment]
> I don’t have a strong opinion on what should happen here. It would be a bit awkward, practically speaking, to have [`libpri-OpenH23-exception`](https://github.com/spdx/license-list-XML/issues/1939) but not this exception, but in the end I _personally_ just need something to put in the `License` tags of the Fedora packages.

To be clear, a decision by SPDX not to create an identifier for a given license/exception has no bearing on whether that particular license/exception should be represented in some way in the Fedora license tag.

**Comment by jlovejoy** [comment]
@richardfontana - while that may be correct re: a decision by SPDX for inclusion is separate from a decision by Fedora as to whether this exception should be represented in some way in the Fedora license tag - the reason it was submitted to SPDX to begin with was to represent it in the Fedora license tag, so if you don't think it needs to be represented, then it didn't need to be submitted and the issue in Fedora states it's allowed.

I have mixed feelings on this one, now that I'm thinking about it more deeply. It doesn't add much of an actual exception other than the scenario that @musicinmybrain explained which seems unlikely, but then... ??

**Comment by richardfontana** [comment]
I think my view on it is: if someone wants to get Digium or the Asterisk maintainers on record saying "oh, yes, this is just about use with proprietary versions of Asterisk and any other understanding would be preposterous" or whatever, then we can just choose not to represent it in the Fedora license tag; otherwise we might as well follow the general Fedora practice by adding it to the Fedora license list and including it in the license tag. I'm also okay with delegating the decision to @musicinmybrain. However, this shouldn't be dependent on SPDX's decision. If SPDX decides not to add the exception, but @musicinmybrain wants to include it in the license tag, then we can use an `AdditionRef-` on the Fedora side.

**Comment by musicinmybrain** [comment]
To be perfectly honest, it is not important to me what the SPDX decision is or what the Fedora decision is—I just want to form an acceptable license expression for both packages and move on with my life. I’m not saying it isn’t important to make a good decision, I’m just saying I’m not really invested in a particular outcome.

**Comment by swinslow** [comment]
I don't know what the other "terms provided with that copy of Asterisk" are, but given the discussion in this thread I gather it's likely their proprietary license terms.

On the one hand, as @Pizza-Ria noted it does feel a bit weird to have an exception on the list that's basically just "you can use our alternate proprietary terms rather than the GPL." However, looking at the principles we've now established for reviewing exceptions, here's what we've got:

> Candidate submissions for the Exceptions List are considered for inclusion according to the following factors:
> 
> 1. The exception is not a stand-alone license.
> 2. The exception either:
>   * grants an exception to a license condition; and/or
>   * grants an addition permission beyond those granted in a license.
> 3. The exception does not impose additional restrictions or limitations beyond those granted in the underlying license.
> 4. The exception has actual, substantial use such that it is likely to be encountered.

I think this meets those requirements, particularly given that I gather Asterisk is widely used (and in Fedora).

So although it's weird, I'm +1 to add it in light of the current principles.

**Comment by jlovejoy** [comment]
discussed on 6/8 call - acknowledged this is a borderline case, but will accept and use suggested name and id

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Asterisk exception

## License ID

Asterisk-exception

## XML markup

none

## Notes:

none
