### ISSUE TITLE
Autoconf-exception-generic: additional sentence

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1991]
This exception was found in RPM at https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/config.guess

`# As a special exception to the GNU General Public License, if you
  # distribute this file as part of a program that contains a
  # configuration script generated by Autoconf, you may include it under
  # the same distribution terms that you use for the rest of that
  # program.  This Exception is an additional permission under section 7
  # of the GNU General Public License, version 3 ("GPLv3").`

It is identical to `Autoconf-exception-generic` except in that it adds the final sentence about GPLv3 section 7.

For more info, see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/220

What are people's thoughts on whether this last sentence makes it a different/new exception or if we could make that sentence optional in `Autoconf-exception-generic`

**Comment by jlovejoy** [comment]
submitted on behalf of @xsuchy

**Comment by BrianInglis** [comment]
As stated in the licences in the files, the canonical locations for the files are https://git.savannah.gnu.org/cgit/config.git/plain/config.guess and https://git.savannah.gnu.org/cgit/config.git/plain/config.sub 
and they are included in all packages that have (for some value of) *recently* run `autoupdate` or manually updated their *autotools* files. 
I did a quick scan and found those clauses in those files in the following package sources on my system: c-ares, curl, dejagnu, dialog, diffstat, file, fontconfig, gcl, htmldoc, iperf, libev, libmetalink, libpsl, libssh2, libwebp, libxslt, lrzip, lynx, ncurses, nettle, nghttp2, nghttp3, sharutils, tack, vttest, wget2, xorg-docs

**Comment by jlovejoy** [comment]
@BrianInglis - are you saying that all of the packages you list above use this exception with that last sentence included, then?

**Comment by BrianInglis** [comment]
> @BrianInglis - are you saying that all of the packages you list above use this exception with that last sentence included, then?

@jlovejoy 
Those distributed GNU reference files for all GNU packages and versions, built using GNU autotools, on my system over the last decade, appear to be close variations (copyright years, timestamp dates, reference URLs updated over the last decade, plus code changes in the config scripts below the header comments). 
I would expect those GNU reference files to be included in sources for all GNU packages built using GNU autotools since 2013-2016, the date included depending on the GNU package maintainers' frequency of updating the GNU autotools they use, and perhaps deciding whether or not to update the GPL licence version.  
GNU packages with those files dated prior to the 2013-2016 date range, depending on the GNU package maintainers' frequency of updating the GNU autotools they use, and perhaps deciding whether or not to update the GPL licence version, do not contain that exception text, being licensed under GPLv2/+, and containing the exception text:
```
# As a special exception to the GNU General Public License, if you
# distribute this file as part of a program that contains a
# configuration script generated by Autoconf, you may include it under
# the same distribution terms that you use for the rest of that program.
```
These earlier files are in older GNU packages and versions I happened to have kept around dated from 2005-2016. 
GNU packages and licences were probably all updated to GPLv3 after 2016. 

See attached files (suffixed to distinguish and allow GH attach) and logs linked below.:
[config.guess-GPLV2.txt](https://github.com/spdx/license-list-XML/files/11692141/config.guess-GPLV2.txt)
[config.sub-GPLV2.txt](https://github.com/spdx/license-list-XML/files/11692143/config.sub-GPLV2.txt)

Exceptions text appears identical for all GNU packages and versions containing those GNU reference files on my system over the last decade in [guess-except.log](https://github.com/spdx/license-list-XML/files/11691965/guess-except.log)

File metadata for all GNU packages and versions containing those GNU reference files with that exception text on my system over the last decade in [guess-size-date.log](https://github.com/spdx/license-list-XML/files/11691970/guess-size-date.log)

**Comment by jlovejoy** [comment]
@swinslow @richardfontana - we discussed this on call today (to accept), but I didn't make a note right away... 
can you confirm/remember, I think we decided on `GPL-3.0-Autoconf-exception-generic`

**Comment by richardfontana** [comment]
I was multitasking and wasn't paying attention at that point :)

I was about to suggest Autoconf-exception-generic-GPL-3.0 but maybe your version is better.

**Comment by BrianInglis** [comment]
> I think we decided on `GPL-3.0-Autoconf-exception-generic`
@jlovejoy 
In which case the licences found in the same files in older GNU package releases might be named `GPL-2-or-later-Autoconf-exception-generic`, as some developers may choose *NOT* to update to GPL-3 for various reasons.

**Comment by BrianInglis** [comment]
Your referenced `autoconf` exceptions seem to be really old dating from 2006-2009 copyright years. 
It appears that the best canonical/reference/standard URLs for all releases of these `config.{guess,sub}` files might be to the GNU Savannah config repo https://git.savannah.gnu.org/cgit/config.git files https://git.savannah.gnu.org/cgit/config.git/tree/config.guess https://git.savannah.gnu.org/cgit/config.git/tree/config.sub where we can see the commit history of annual copyright year and timestamp updates, early 2022 [Fix GPLv3 license headers to use a comma instead of semicolon](https://git.savannah.gnu.org/cgit/config.git/commit/?id=03087cbd5161db0ff94e578b02d318d0bba2742d) before *either version 3*, and late 2012 changing the licence from *GPLv2+* to *GPLv3+* [Bring up to GPLv3](
https://git.savannah.gnu.org/cgit/config.git/commit/?id=a8066ce76892513ec1ead42d478b631218730acb). 
[The repo goes back to the initial creation by RMS in the last century, with updates from local ids, then *Cygnus*, later *RedHat*, contributions this century!]

As the header comments in these *config* files distributed in packages match the *Standard License Header* for *GPLv2/3+*, it appears we should add `GPL-2/3.0-or-later AND Autoconf-exception-generic/-3.0` as required to each of these packages?

**Comment by jlovejoy** [comment]
@BrianInglis in this update https://git.savannah.gnu.org/cgit/config.git/commit/?id=a8066ce76892513ec1ead42d478b631218730acb

Prior to this point the SPDX id would have been:
`GPL-2.0-or-later WITH Autoconf-exception-generic`

After the update, it would be:
`GPL-3.0-or-later WITH <this is where we need a new name>`

Looking at it like that, I'm thinking that `Autoconf-exception-generic-3.0` seems to make the most sense!

**Comment by BrianInglis** [comment]
++ Like! Thumbs up!
