### ISSUE TITLE
New exception request: AGPL-3.0-only with trademark exception

### ISSUE THREAD

**Issue by robert-scheck** [spdx/license-list-XML#2011]
### Introduction

The Z-Push RPM package in RPM Fusion (a third-party add-on repository for Fedora and RHEL) uses the license shortname "AGPLv3 with exceptions" from the old Fedora license shortname system – and a proper exception name is needed for updating to the SPDX system. The exception is that a trademark policy is added by using section 7 of AGPL-3.0-only (see the end of the license file itself).

Note that more or less the same exception exists for the Zarafa Collaboration Platform (abandonware, see source code copy at Fedora for EPEL) as well, but referring to the trademark "Zarafa" instead of "Z-Push". It might make sense to catch both with the same exception, e.g. "Zarafa trademark exception" or similar?

### License Name

?

### URL to license text

https://github.com/Z-Hub/Z-Push/blob/develop/LICENSE#L666 + https://github.com/Z-Hub/Z-Push/blob/develop/TRADEMARKS

### OSI Status

I don't know

### License author or steward

Zarafa Deutschland GmbH

### URL to project(s) that use license

- https://github.com/Z-Hub/Z-Push/
- [zcp-7.1.14.tar.gz at Fedora](https://src.fedoraproject.org/repo/pkgs/rpms/zarafa/zcp-7.1.14.tar.gz/sha512/594ad30145b4a5db4f777ccf137b19296c1ef7250ab8731cbae102e1a466d0c33641056c0334bcd3d098d4e9d32d9c7e3730de72cf84251d6413bab70360ad1a/zcp-7.1.14.tar.gz), files `AGPL-3` and `TRADEMARKS.txt`

**Comment by richardfontana** [comment]
I didn't look at this too closely but I'm not sure this should be seen as an "exception" in the SPDX sense. It claims to be a section 7 additional term but this seems to refer to the language authorizing use of additional terms "[d]eclining to grant rights under trademark law for use of some trade names, trademarks, or service marks" which does not concern additional permissions (which is how SPDX understands exceptions for purposes of the exception list). 

However, the language in the LICENSE file basically just says "the licensing of the Program under the AGPL does not imply a trademark license" and references a separate trademark policy which grants certain permissions to use the "Z-PUSH" mark. 

Also, to be clear, this package is not in Fedora and therefore I don't think the "major distro" qualifier should apply here unless SPDX wants to treat RPMFusion itself as a major distro.  
 
One further point: The AGPL additional terms I remember from Zarafa when it was packaged in Fedora were different from what's here. Those were basically badgeware terms, were the result of a negotiation between Red Hat and Zarafa lawyers, and I think today Fedora would probably not allow such terms.

**Comment by robert-scheck** [comment]
> Also, to be clear, this package is not in Fedora and therefore I don't think the "major distro" qualifier should apply here unless SPDX wants to treat RPMFusion itself as a major distro.

I'm not sure what qualifies as "major distro", but as of writing Z-Push is shipped with Debian (main) and Ubuntu (universe), too.

**Comment by richardfontana** [comment]
Ah, I would think if it's in Debian main it should qualify as "major distro", yes, but that's up to the SPDX legal team. I was mainly concerned that someone unfamiliar with RPMFusion might assume this package is in Fedora.

**Comment by jlovejoy** [comment]
Debian qualifies for "used in major distro"

for ease of reference, will paste text in comments

**Comment by jlovejoy** [comment]
from https://github.com/Z-Hub/Z-Push/blob/develop/LICENSE#L666

Copyright 2007 - 2016 Zarafa Deutschland GmbH

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License, version 3,
as published by the Free Software Foundation with the following additional
term according to sec. 7:

_According to sec. 7 of the GNU Affero General Public License, version 3,
the terms of the AGPL are supplemented with the following terms:

"Zarafa" is a registered trademark of Zarafa B.V.
"Z-Push" is a registered trademark of Zarafa Deutschland GmbH
The licensing of the Program under the AGPL does not imply a trademark license.
Therefore any rights, title and interest in our trademarks remain entirely with us.

Our trademark policy (see TRADEMARKS) allows you to use our trademarks
in connection with Propagation and certain other acts regarding the Program.
In any case, if you propagate an unmodified version of the Program you are
allowed to use the term "Z-Push" to indicate that you distribute the Program.
Furthermore you may use our trademarks where it is necessary to indicate the
intended purpose of a product or service provided you use it in accordance
with honest business practices. For questions please contact Zarafa at
trademark@zarafa.com._

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

**Comment by jlovejoy** [comment]
@richardfontana FWIW This (or something similar) was on our "more research needed" list for Fedora license data. There was a listing for "Affero General Public License 3.0 with Zarafa trademark exceptions" and the Fedora shortname, "AGPLv3 with exceptions (as @robert-scheck already noted) on the old wiki "good list". It had a link that's now dead at http://www.zarafa.com/content/affero-gplv3 - since I couldn't find the actual text of the exception, it didn't get matched and added to the new Fedora-license-list data. 
Using Wayback Machine, I found a similar but different than the text above version from 2014: http://web.archive.org/web/20140214025000/http://www.zarafa.com/content/affero-gplv3
by the Wayback Machine capture in mid-2015 and 2016, it gives the same 404 as today.
Not sure what to do with that info... but FWIW!

As for whether this should be an exception on the SPDX License List, I know there was lengthy discussions on how to deal with a potential onslaught of additional clauses under GPL-3.0, section 7. That would apply to AGPL-3.0 as well. I'd have to dig into the email archive to remember any outcomes (other than there not being an onslaught) and it may very well have even pre-dated 2.0 when we added a separate exception list...

**Comment by richardfontana** [comment]
@jlovejoy additional clauses under GPLv3 section 7 (in the sense I'm pretty sure you mean) are conceptually not "exceptions" in the SPDX exception list sense - they are not additional permissions. Additional permissions (corresponding to traditional GPLv2 "exceptions") are covered in a different part of GPLv3 section 7. I know this case shows how odd this is because in a sense it seems like this is mostly a grant of trademark *permission*. The relevant part of GPLv3 section 7 was meant to legitimize simple clauses like "This license does not grant you any rights to use licensor's trademarks".

**Comment by richardfontana** [comment]
In my opinion this is an appropriate case for 'AdditionRef-' and is not appropriate for addition to the SPDX exception list under the current criteria.

**Comment by swinslow** [comment]
I tend to agree with @richardfontana on this. This seems closer to general "additional terms" that would be referenced using a custom "AdditionRef-" identifier as discussed [here](https://github.com/spdx/change-proposal/issues/4#issuecomment-1526155230).

I don't think this would meet the exception requirements for the [SPDX Exceptions List](https://spdx.org/licenses/exceptions-index.html), since to the extent it's granting additional rights, they appear to be trademark rights as dictated by Zarafa's corporate trademark policy. I think that's specific to Zarafa and is outside the scope of what would be counted as an "exception" for Exception List purposes.

**Comment by jlovejoy** [comment]
sounds good, I'll close then

@robert-scheck - I'm not sure Fedora has documented the use of `AdditionRef-` yet as it's new in SPDX (and actually not officially part of the spec yet). If there isn't a corresponding issue in Fedora's Gitlab repo yet, please make one and @richardfontana  and I will respond there :)
