### ISSUE TITLE
New license request: MIT-Khronos [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by nicholas-rh** [spdx/license-list-XML#2017]
**1.** License Name: MIT Khronos Variant
**2.** Short identifier: MIT-Khronos
**3.** License Author or steward: Khronos Group
**4.** Comments: It appears to be a variant of the MIT license. The licensecheck tool reports it as a separate license called "Khronos license." Here is the Fedora license review discussion, in which it was approved for Fedora: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/238
**5.** License Request Url: http://tools.spdx.org/app/license_requests/240
**6.** URL(s): https://github.com/KhronosGroup/SPIRV-Cross/blob/main/LICENSES/LicenseRef-KhronosFreeUse.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/KhronosGroup/glslang, https://github.com/KhronosGroup/SPIRV-Cross

**Comment by laurathefuerte** [comment]
I can take this one with @Pizza-Ria.

**Comment by Pizza-Ria** [comment]
@nicholas-rh - is the SPIRV-Cross project that mainly seems to use this license integrated into O3DE as well or just utilized as part of Fedora?  I noticed some O3DE stuff in your repo including https://github.com/nicholas-rh/o3de-fedora.  Thanks!

**Comment by nicholas-rh** [comment]
> @nicholas-rh - is the SPIRV-Cross project that mainly seems to use this license integrated into O3DE as well or just utilized as part of Fedora? I noticed some O3DE stuff in your repo including https://github.com/nicholas-rh/o3de-fedora. Thanks!

It is used as part of O3DE, but there isn't a Fedora package for it. I was looking into packaging SPIRV-Cross when I came across the license and started looking for clarification on it.

**Comment by nicholas-rh** [comment]
It's also found in files in the glslang project which is packaged for Fedora: https://github.com/KhronosGroup/glslang/blob/main/SPIRV/spirv.hpp

**Comment by jlovejoy** [comment]
This matches MIT, except for:
- the use of "Materials" instead of "Software"
- the addition of the paragraph:
`MODIFICATIONS TO THIS FILE MAY MEAN IT NO LONGER ACCURATELY REFLECTS KHRONOS
STANDARDS. THE UNMODIFIED, NORMATIVE VERSIONS OF KHRONOS SPECIFICATIONS AND
HEADER INFORMATION ARE LOCATED AT https://www.khronos.org/registry/`

**Comment by laurathefuerte** [comment]
# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [x] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [x] No
    See comments below. 
1. **If a software license, does it apply to source code and not only to executables?**
    - [x] Yes
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [x] Yes
    - [ ] No
Likely yes, but question has been submitted to steward on 7/3/23 because an alternate version of the text was found at https://code.it4i.cz/blender/monado/-/blob/master/LICENSES/LicenseRef-Khronos-Free-Use-License-for-Software-and-Documentation.txt. 
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No
Steward was contacted 7/3/23. The message has been forwarded to relevant parties, but there has been no response. 

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [x] Yes
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [x] Yes
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [x] Yes
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [x] Yes
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No
Steward was contacted 7/3/23. The message has been forwarded to relevant parties, but there has been no response. 


## Summary of factors, outcome, comments

_Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives_

**Matching the MIT license**

- the use of "Materials" instead of "Software"
  - This seems like replaceable text (B.3.4 Guideline: replaceable text) with no impact on the substance of the license.

- the addition of the paragraph:
MODIFICATIONS TO THIS FILE MAY MEAN IT NO LONGER ACCURATELY REFLECTS KHRONOS STANDARDS. THE UNMODIFIED, NORMATIVE VERSIONS OF KHRONOS SPECIFICATIONS AND HEADER INFORMATION ARE LOCATED AT https://www.khronos.org/registry/
  - This text may be omittable (B.3.5 Guideline: omittable text), as it is merely informative or explanatory, not any right grant or restriction. 

**Substantial Use**
- O3DE usage, as confirmed by @nicholas-rh.
- SPIRV-Cross: forked 484 times, 1.7k stars
- GSLANG: forked 756 times, 2.5k stars
- Search results of the license file: https://github.com/search?q=LicenseRef-KhronosFreeUse.txt&type=code&ref=advsearch 
    - Searched: “LicenseRef-KhronosFreeUse.txt”
      - Results in the teens, mostly related to SPIRV
       - Cited by EpicGames

**Comment by jlovejoy** [comment]
thanks @laurathefuerte !

Do you have an opinion as to meeting the inclusion guidelines? (putting aside the matching guidelines question)

**Comment by swinslow** [comment]
Based on the write-up above, I'm +1 to add this to the license list.

With the "Materials" vs. "Software" language, I could perhaps get comfortable with making that part a match to the standard MIT license. But with the added paragraph about Khronos standards, I would support putting this in its own identifier, and I think the name and identifier proposed by @nicholas-rh look good to me.

**Comment by jlovejoy** [comment]
discussed on 7/13 call Steve's approach of adding markup to regular MIT for materials v. software (assuming this is only change) and adding MIT-Khronos for variant with extra paragraph, pending discussion with license steward to close that loop and make sure they are aware.  @laurathefuerte  to add @jlovejoy  to email thread with steward

**Comment by richardfontana** [comment]
Here's a header file that doesn't have the admonition paragraph:
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/GL/glext.h
(cc: @berrange)

**Comment by Conan-Kudo** [comment]
I think it would make sense to call it `Khronos` rather than `MIT-Khronos`. Even though it's an MIT variant, it doesn't call itself the MIT license at all and is clearly a larger purpose license.

**Comment by jlovejoy** [comment]
I have pinged the Khronos Group as to the two variants: 

1) a match to MIT but for use of "Materials" instead of "Software" as seen here https://github.com/KhronosGroup/WebGL/blob/main/LICENSE.txt (and which Khronos does refer to as "MIT" if you look at https://github.com/KhronosGroup/WebGL/blob/main/README.md

2) is a match to the above, but adds another clause in the middle, as seen here: https://github.com/KhronosGroup/SPIRV-Cross/blob/main/LICENSES/LicenseRef-KhronosFreeUse.txt

(note SPDX and Reuse compliant use of Licnese-Ref)

My inclination is we need both and that 2 is distinct. I'm contemplating if we could add one license for Khronos that accommodates both (separate from adding markup to MIT) and mark the middle clause as optional. I'm hoping some insight as to why they have these two variants may help guide us.

**Comment by Pizza-Ria** [comment]
I don't think I explicitly endorsed marking the language in question as a non-substantive variant of MIT so here it is.

**Comment by xsuchy** [comment]
Any progress here?

**Comment by jlovejoy** [comment]
I've pinged the Khronos group again on this since they never got back to me months ago. If we don't hear back by the end of this week (Jan 5), then I'd suggest we make our best judgment as to a resolution

**Comment by jlovejoy** [comment]
Response from Khronos group:

"They consider this license obsolete and are no longer using this license. Once they get agreement from the repository owners, they will be converting any other uses of this license to one of their standard outbound licenses."

Checking back to confirm that all uses are within Khronos Group control to update, as old license sometimes die a slow death... but inclination from Khronos Group is to not add to SPDX License List.

This would mean markup to MIT

**Comment by swinslow** [comment]
Discussed with @jlovejoy, I'm +1 to add this as a separate license with ID `MIT-Khronos-old` to reflect the fact that this is apparently not being used by Khronos going forward, but has been used in the past.
