### ISSUE TITLE
New license request: Knuth-MMIXware [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2028]
**1.** License Name: Knuth-MMIXware
**2.** Short identifier: Knuth-MMIXware
**3.** License Author or steward: Unknown
**4.** Comments: Found in Fedora during License review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/226
Used in project mmixware
**5.** License Request Url: http://tools.spdx.org/app/license_requests/248
**6.** URL(s): https://gitlab.lrz.de/mmix/mmixware/-/blob/master/boilerplate.w
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.lrz.de/mmix/mmixware/

**Comment by jlovejoy** [comment]
agreed, +1 to add as well

**Comment by ppisar** [comment]
What is a correct  capitalization of this identifier? "MMIXWare" or "MMIXware" ("W" letter)?

I ask because there is a dissonance:

* Upstream speels it as "MMIXware" <https://gitlab.lrz.de/mmix/mmixware/-/blob/master/README>
* Winslow defined it as "MMIXWare"
* Git repository contains a file called "src/MMIXWare.xml"
* The file defined licenseId as "MMIXware"

I would like to unify the file name and licenseId. I only don't know which spelling to use. I would lean to upstream's spelling with lower case "w".

**Comment by xsuchy** [comment]
Good catch. I would prefer MMIXware to match upstream. If I get some thumbs up, I will prepare PR.

**Comment by jlovejoy** [comment]
indeed, good catch @ppisar !

yes, let's fix this and matching upstream sounds good. Thanks @xsuchy !
