### ISSUE TITLE
New license request: MIT-open-group-like [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2029]
**1.** License Name: MIT-open-group-like
**2.** Short identifier: MIT-open-group-like
**3.** License Author or steward: Unknown
**4.** Comments: Found in Fedora during License review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/205
Close to https://spdx.org/licenses/MIT-open-group.html but not the same.
Present in package zlib.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/249
**6.** URL(s): https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/contrib/iostream2/zstream.h#L9
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/madler/zlib

**Comment by jlovejoy** [comment]
license text for convenience:
```
* Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies and
 * that both that copyright notice and this permission notice appear
 * in supporting documentation.  Christian Michelsen Research AS makes no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied warranty.
 ```

It's closest to NTP, but not quite...

**Comment by jlovejoy** [comment]
see #2030

**Comment by swinslow** [comment]
I think this is a match for [`HPND-sell-variant`](https://spdx.org/licenses/HPND-sell-variant.html), when the different optional and replaceable text pieces are taken into account?

**Comment by jlovejoy** [comment]
this omits the Oxford comma that is present in `HPND-sell-variant` see: `distribute, and sell `

@swinslow  - thoughts?

**Comment by swinslow** [comment]
I genuinely can't make myself care about an Oxford comma being problematic from a legal interpretive position, at least in this particular context  :)

At the same time, I know that there are examples when an Oxford comma _can_ change the interpretation of a sentence. ([Here's one](https://proeditingproofreading.com/blog/oxford-comma) of many example sites about this.)

So I wouldn't make it a [matching guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/) overall rule to ignore Oxford commas; but for this specific license, I have zero concerns with making it optional.

I think that it'll need `<optional spacing="none">` as the tag, rather than just `<optional>`, to help ensure that the License List publisher doesn't insert a space before the comma after the tag is added.
