### ISSUE TITLE
New license request: iPXE-UBDL-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by berrange** [spdx/license-list-XML#2043]
**1.** License Name: UNMODIFIED BINARY DISTRIBUTION LICENCE
**2.** Short identifier: iPXE-UBDL-exception
**3.** License Author or steward: Michael Brown
**4.** Comments: This is proposal for a GPL license exception, that waives conditions of the GPL, when the distributed binary is built from already publicly available GPL licensed source. 

The license exception has been applied to the iPXE project source since 2015, and thus present in all major Linux distributions 

These two points satisfy the inclusion principles stated for the license exception list.

The upstream project has called this "UNMODIFIED BINARY DISTRIBUTION LICENCE" and describes licensing of source files as a choice between "GPLv2+ or UBDL", using their own custom license markup:

  "FILE_LICENCE ( GPL2_OR_LATER_OR_UBDL );"

IOW, upstream is treating it as if it were a standalone license. 

The actual text of the license, however, is waiving the need to comply with conditions of the GPL, and thus looks more appropriate as a GPL license exception, than a standalone license.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/255
**6.** URL(s): https://github.com/ipxe/ipxe/blob/master/COPYING.UBDL
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://ipxe.org/

**Comment by richardfontana** [comment]
This was approved for Fedora: see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/223

**Comment by mcb30** [comment]
For the record: there are no files in iPXE licensed solely under the UBDL.  All affected files are dual-licensed under GPLv2+ or UBDL.  The fact that the UBDL text itself refers to the GPL is orthogonal to this: the files may be treated as licensed under either the GPLv2+ or under [some other license].

For simplicity, I would suggest that Fedora or other distributors choose the GPLv2+ option and be done with it.

In case it's relevant: the motivation for creating the UBDL is that some OEMs refuse to ship BIOS images that will incur the GPL obligations of providing source code.  They have no interest in creating a closed-source version of iPXE: they just won't subject themselves to the process obligations of dealing with source code requests from end users.  Hence the structure of the UBDL to allow obligation-free redistribution of the binary when the source code to that binary is already available to the world at large.

**Comment by richardfontana** [comment]
@mcb30 While Fedora could explicitly pick GPLv2+ (~ SPDX `GPL-2.0-or-later` :) , the longstanding tradition in Fedora is to pass through upstream license choices unless one of the choices is considered 'bad' or not allowed (and even then, generally the disallowed license is ignored in the metadata but is not removed from source code license notices).

**Comment by jlovejoy** [comment]
to be clear, this is not a standalone license, so the SPDX expression would be: `gpld-2.0-or-later WITH <iPXE-UBDL-exception>`

as to the SPDX inclusion principles for exceptions:

- The exception is not a stand-alone license. - YES
The exception either:
- grants an exception to a license condition; and/or - YES
- grants an addition permission beyond those granted in a license.
- The exception does not impose additional restrictions or limitations beyond those granted in the underlying license. - IT DOES NOT
- The exception has actual, substantial use such that it is likely to be encountered. - USED IN A MAJOR DISTRO (FEDORA), SO YES

**Comment by jlovejoy** [comment]
I'm a bit conflicted on naming - we usually try to honor whatever is used "in the wild" if applicable, but I kind of have issue with UBDL due to the L standing for license...

**Comment by swinslow** [comment]
I'm +1 to add, but I would add this as a license rather than as an exception. My main reasons for this are:

- As mentioned, the upstream project is treating it as a standalone license (and has titled it as such)
- In similar cases (such as LGPL-3.0), I think we've _generally_ leaned towards taking the upstream's perspective on this
- Also, the first condition (lines 50-54) I think _arguably_ imposes an additional condition that goes beyond [the underlying GPL-2.0 license's requirement in Section 2(c)](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html).
  - Reasoning: GPL-2.0 section 2(c) only requires displaying announcements for interactive programs that normally print copyright notices, etc.; but the iPXE version appears to require displaying the announcement "when starting running" the Program in all circumstances.

Between all of the above points, I think I would treat this as a license for the License List rather than a license exception. That said, I do think this is an edge case and I could be convinced otherwise  :)

Whether it is to be treated as its own license or as an exception, I'm +1 to add it and I think it meets either set of requirements.

**Comment by Pizza-Ria** [comment]
+1 to Exception.  For the factor:  The exception does not impose additional restrictions or limitations - I do agree with @swinslow that "the Program must display an announcement which includes the details of your existing publication of the Program made in accordance with the terms of the GNU General Public License." appears to be an additional CONDITION but I don't interpret that to be a restriction/limitation.

**Comment by jlovejoy** [comment]
ok, so @swinslow made me re-review this, but I'm still at +1 as an Exception. I think @Pizza-Ria 's additional point is a good one. I think I also keep going back to - it's not a standalone license in anyway.

as to the LGPL-3.0 example, that is the only time we have treated what is technically really an exception as a license which was more of a nod to not upsetting what people were used to in that particular case (and which has been re-hashed in multiple ways a few time, so this is not an invitation for another re-hashing ;)

**Comment by mcb30** [comment]
For the record: as the license text author, I have no strong preference between the SPDX treatment as license vs exception.  :upside_down_face:

**Comment by jlovejoy** [comment]
@swinslow - are you comfortable with adding as an exception?

**Comment by swinslow** [comment]
On the GPL-2.0 section 2(c) point, I was thinking about this the wrong way. I think that since this is just a part of the optional "additional permission," this part is fine and you can pretend I hadn't raised that as a concern  :)

For "license" vs. "exception," given @jlovejoy and @Pizza-Ria comments and given @mcb30 not having a preference, I'm okay with this being added as an exception.

**Comment by jlovejoy** [comment]
given the comment above that no iPXE files use this, for naming and id, could we go with:

`UBDL-exception`

and

`Unmodified Binary Distribution exception`

I'm struggling with have the word "license" in the name of something on the exception list. But we do prefer to use the name or id that is used "in the wild" so that's why I was thinking including the L in the id is okay??

Happy to have other thoughts though - from @mcb30  especially!

**Comment by mcb30** [comment]
The upstream name is definitely staying as Unmodified Binary Distribution Licence, since I don't want to go through the pain of recontacting everyone concerned to get consent for what would technically be a licensing change.

That said, I have no strong preference about its representation within the SPDX namespace, so I'm very happy to defer to a choice of SPDX name that maintains consistency within that namespace.
