### ISSUE TITLE
New license request: pnmstitch [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2046]
**1.** License Name: pnmstitch license
**2.** Short identifier: pnmstitch
**3.** License Author or steward: Unknown
**4.** Comments: This lisense is used in Fedora. It was found during license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/261
This is a BSD-derived license somewhat like a BSD-2-Clause-ish variant of BSD-Source-Code but with a simple copyleft-like condition at the end.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/256
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/fb4a7eff-ac0c-4208-bd1d-1eb61cc69ba6.png

**Note:**
The license closely matched with the following license ID(s): BSD-1-Clause

**Comment by jlovejoy** [comment]
link to license text:  https://sourceforge.net/p/netpbm/code/HEAD/tree/super_stable/editor/pnmstitch.c#l2 

link to project: https://sourceforge.net/projects/pnmstitch/

**Comment by jlovejoy** [comment]
license text:
`
* TERMS AND CONDITIONS OF USE
 *
 * Redistribution and use in source form, with or without modification, are
 * permitted provided that redistributions of source code must retain the
 * above copyright notice, this list of conditions and the following
 * disclaimer.
 *
 * This software is provided `as is' by Mark Salyzyn and any express or implied
 * warranties, including, but not limited to, the implied warranties of
 * merchantability and fitness for a particular purpose, are disclaimed. In no
 * event shall Mark Salyzyn be liable for any direct, indirect, incidental,
 * special, exemplary or consequential damages (including, but not limited to,
 * procurement of substitute goods or services; loss of use, data, or profits;
 * or business interruptions) however caused and on any theory of liability,
 * whether in contract, strict liability, or tort (including negligence or
 * otherwise) arising in any way out of the use of this software, even if
 * advised of the possibility of such damage.
 *
 * Any restrictions or encumberances added to this source code or derivitives,
 * is prohibited.
 `

**Comment by jlovejoy** [comment]
License Check tool shows it as close to BSD-1-Clause but license-diff doesn't list that and seems to struggle with finding a close match. Here are the differences with BSD-1-Clause:

pnmstitch: `Redistribution and use in source form, with or without modification, are permitted provided that `

BSD-1-Clause: `Redistribution and use in source _and binary_ forms, with or without modification, are permitted provided that _the following conditions are met:_`

pnmstitch: `This software is provided 'as is' by Mark Salyzyn and any express or implied  warranties, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose, are disclaimed.`
"as is" before name and extra comma after "purpose"

BSD-1-Clause: `THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. `

I think these variations are suitable for markup potentially BUT the addition of this at the end `Any restrictions or encumberances added to this source code or derivitives, is prohibited.` 
(spelling errors and all) I think adds a condition and thus makes it a new license.

Otherwise, meets free/open definition and substantial use by way of being included in Fedora.

anyone disagree, agree?

**Comment by Pizza-Ria** [comment]
The first clause which specifies both binary/source (BSD-1) but pnmstitch is just source may be a distinction without a difference as a binary could be considered a modification of source.

The second clause doesn't concern me - just seems to be reordered wording.

The last clause  "_Any restrictions or encumberances added to this source code or derivitives, is prohibited_" tips the scales for me - that is an additional condition.  

+1 to add it.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

pnmstitch License

## License ID

pnmstitch

## XML markup

none at this time. if we find other uses of it with a different name, we can add markup to the author's name at that time.

## Notes:

none

## Additional rationale or notes on decision:



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
