### ISSUE TITLE
LGPL 2.1 vs LGPL 2.1 or later

### ISSUE THREAD

**Issue by ghost** [spdx/license-list-XML#2052]
A few related issues.

First, [LGPL-2.1.html](https://github.com/spdx/license-list-data/blob/main/html/LGPL-2.1-or-later.html) and [LGPL-2.1-or-later.html](https://github.com/spdx/license-list-data/blob/main/html/LGPL-2.1-or-later.html) have the same optional-license-text, which doesn't disambiguate between the two. In contrast, [LGPL-2.1.xml](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1.xml) and [LGPL-2.1-or-later.xml](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1-or-later.xml) have different `<license name=...` attributes. Would it be reasonable to have the HTML disambiguate between the two licenses?

Second, the two licenses are nearly identical, except for:

``` xml
      <p>
        You should have received a copy of the GNU Lesser General Public License
        along with this library; if not, write to the Free Software Foundation,
        Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
      </p>

      <p>
        Also add information on how to contact you by electronic and paper mail.
      </p>
```

versus:

``` xml
      <p>
        You should have received a copy of the GNU Lesser General Public License
        along with this library; if not, write to the Free Software Foundation,
        Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA Also
        add information on how to contact you by electronic and paper mail.
      </p>
```

As well as:

``` xml
      <p><var class="replaceable-license-text"> &lt;one line to give the library&apos;s name and an idea of what it does.&gt;</var><br />

      Copyright (C) <var class="replaceable-license-text"> &lt;year&gt; &lt;name of author&gt;</var></p>
```

versus:

``` xml
      <p>
	<var class="optional-license-text"> &lt;</var>one line to give the library&apos;s name
	and <var class="replaceable-license-text"> an idea</var> of what it does.<var class="optional-license-text"> &gt;</var>
        <br />

        Copyright (C)
        <var class="optional-license-text"> &lt;</var>year<var class="optional-license-text"> &gt;</var>
        <var class="optional-license-text"> &lt;</var>name of author<var class="optional-license-text"> &gt;</var>
      </p>
```

Would making those the same be reasonable?

It is my understanding that there is no "LGPL 2.1 or later" license per se, but rather it is the LGPL 2.1 license text with an attribute of "or later". I think the intent is that the license texts be identical.

**Comment by jlovejoy** [comment]
LGPL-2.1 is deprecated, see https://spdx.org/licenses/LGPL-2.1.html and also indicated in the .xml file

but yes, the license text is the same (for all the L/GPL) licenses with the difference as to whether it's "only" or "or-later" indicated in the license notice

**Comment by DaveJarvis** [comment]
> LGPL-2.1 is deprecated, see https://spdx.org/licenses/LGPL-2.1.html and also indicated in the .xml file

Yes, that's true. Unfortunately there are still many third-party libraries and tools that are only licensed under LGPL 2.1.

**Comment by jlovejoy** [comment]
I'm not sure what you mean, but to be clear, the mapping of the old ids and the ids as of 3.0 is:
`LGPL-2.1` = `LGPL-2.1-only`
`LGPL-2.1+` = `LGPL-2.1-or-later`

Not sure what you mean by " There are still many third-party libraries and tools that are only licensed under "LGPL 2.1" or "LGPL 2.1 or later"." ??

**Comment by DaveJarvis** [comment]
In our use case, we're autogenerating an end user license agreement (EULA) based on SPDX identifiers associated with third-party libraries and components. When the EULA was generated, the license title for both components was the same, even though they use different licenses. That is, there is no way to disambiguate LGPL-2.1 from LGPL-2.1-or-later based on name alone. All the other licenses have unique names.

To be more concrete:

```
./eula/licenses/LGPL-2.1.html
./eula/licenses/LGPL-2.1-or-later.html
./eula/licenses/LGPL-3.0.html
./eula/licenses/LGPL-3.0-only.html
```

We would like the titles for these to read:

``` html
  <title>GNU Lesser General Public License, Version 2.1, February 1999</title>
  <title>GNU Lesser General Public License, Version 2.1 or later, February 1999</title>
  <title>GNU Lesser General Public License, Version 3, 29 June 2007</title>
  <title>GNU Lesser General Public License, Version 3, 29 June 2007</title>
```

In that fashion, the "Version 2.1 or later" is distinct from the "Version 2.1"/"Version 2.1 only", which allows the licenses to be sorted and grouped using XSLT. At present, there's no way for us to use the HTML files from SPDX verbatim because the titles for LGPL 2.1 and LGPL 2.1 or later are the same.

We can't group by the SPDX identifier because LGPL-2.1 and LGPL-2.1-only wouldn't be grouped together, despite being the exact same license. This means we have to group by title. It works in 99% of cases so far, just not the "or later". As a consequence, we encountered a minor issue where it appeared we had two identical sections, both named "GNU Lesser General Public License, Version 2.1, February 1999", which was technically incorrect. We should have had two sections in the EULA, one for "LGPL 2.1" and one for "LGPL 2.1 or later".

**Comment by jlovejoy** [comment]
the use of EULA here is a bit confusing to me, but I think you are trying to automate the task of creating license files. I presume you are taking the title info from the actual license text itself which, in this case, comes from the FSF. Nothing we/SPDX can do about that.

However, if you pulled the title from the full name field, you would end up with what you are looking for, I think
see "full name" column https://spdx.org/licenses/ which comes from `name` field in the `license` tag https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.0-only.xml

**Comment by DaveJarvis** [comment]
> the use of EULA here is a bit confusing to me, but I think you are trying to automate the task of creating license files.

We're automating the creation of an End User License Agreement by collating the HTML files from the SPDX repository. We're not trying to create the license files.

> I presume you are taking the title info from the actual license text itself which, in this case, comes from the FSF. Nothing we/SPDX can do about that.

This is getting complicated and curious. I'm going to break down the separate issues I've encountered.

**ISSUE 1 - STANDARD LICENSE HEADER**

Consider:

* https://spdx.org/licenses/LGPL-2.1-only.html
* https://spdx.org/licenses/LGPL-2.1-or-later.html

Typos aside, the main difference between those two licenses is the **Standard License Header** section at the bottom of the page:

>  <one line to give the library's name and an idea of what it does.>
> ...
> This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version. 

vs.

>  This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; version 2.1. 

However, the FSF/GNU [LGPL 2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html) does not have the **Standard License Header** section. Do you know where that section originates? I couldn't see anything obvious when [searching](https://www.google.com/search?q=%22Standard+License+Header%22+LGPL+2.1+-spdx), but did find a few places that referenced it:

* https://github.com/intel/dlafs/blob/master/COPYING
* http://c2o-static-content.s3-website.us-east-2.amazonaws.com/legal/ReadMe_OSS.html#compLicenseText_55324

Mind you, those references look like they were grabbed from SPDX, rather than from GNU, so it's begging the question a little.

If the **Standard License Header** section doesn't come from GNU and SPDX, as you wrote, gets the actual license text from GNU, then it seems somewhere along the way the license text was modified by SPDX. Or perhaps it's an older version? Either way, there's something strange going on here.

**ISSUE 2 - TEXT FOR LGPL 2.1 OR LATER**

On the same token, you mentioned that SPDX gets its license texts from GNU. SPDX offers the following three HTML texts:

* https://spdx.org/licenses/LGPL-2.1.html
* https://spdx.org/licenses/LGPL-2.1-only.html
* https://spdx.org/licenses/LGPL-2.1-or-later.html

As far as I know, the FSF only offers license text for LGPL 2.1:

https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html

I could not find any other LGPL 2.1 licenses on their site. The following page suggests that there is only LGPL 2 and LGPL 2.1:

https://www.gnu.org/licenses/license-list.html#SoftwareLicenses

They do list the SPDX identifiers, though:

https://www.gnu.org/licenses/identify-licenses-clearly.en.html

If SPDX gets the license texts from GNU, then where can we find both "LGPL 2.1 only" and "LGPL 2.1 or later" on the GNU/FSF web sites?

**ISSUE 3 - OR LATER**

Presumably, SPDX has (a) possibly modified the original LGPL license text to include an additional section; (b) possibly created two new license texts to align with the SPDX identifiers, but not based on any license texts specifically offered by GNU.

If either of those are true, then it seems likely SPDX has and therefore can make changes to the `<title>` tag of the underlying HTML license texts. If that's true, then I'd like to request a change to the `<title>` tag to include the "or later" clause (so that the various licenses can be sorted and grouped using XSLT).

**Comment by jlovejoy** [comment]
Let me see if I can try to answer some of this:

1) "Standard License Header" is an SPDX-defined term to identify the scenario when a license provides a standard header, as per https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md (which explains all the fields for SPDX license data). In the case of GNU licenses, the "standard license header" is provided for in the "how to apply these terms" section at the end of the license text and does appear for https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html

2) the differenced in that section as to the standard header are reflected in the text contained at 
https://spdx.org/licenses/LGPL-2.1-only.html and 
https://spdx.org/licenses/LGPL-2.1-or-later.html

https://spdx.org/licenses/LGPL-2.1.html is deprecated as stated. Please see https://spdx.dev/license-list-3-0-released/ and included links there for background - this may also help understanding the general context.

I think that also provides some insight as to the other questions you have. Keep in mind, in order to have distinct ids, there has to be corresponding text. The FSF website shows one set of text because within that license text provides for two different ways to apply the license.

**Comment by DaveJarvis** [comment]
> https://spdx.org/licenses/LGPL-2.1.html is deprecated as stated. Please see https://spdx.dev/license-list-3-0-released/ and included links there for background - this may also help understanding the general context.

I'm not sure how else to explain this one.

1. We use open source software libraries.
1. Those libraries have an SPDX identifier.
1. We generate a EULA based on the SPDX identifier denoted by those libraries.
1. The SPDX identifier is, in some cases any of:
  * LGPL 2.1
  * LGPL 2.1 or later

Regardless of the deprecated state of the license, it's not really up to us to change the SPDX identifier that comes with those libraries, regardless of whether said identifier is deprecated. Those libraries likely will continue to use those licenses for many years to come, if not indefinitely.

**Comment by DaveJarvis** [comment]
The following HTML pages have the same "optional-license-text":

* https://github.com/spdx/license-list-data/blob/main/html/LGPL-2.1.html
* https://github.com/spdx/license-list-data/blob/main/html/LGPL-2.1-or-later.html

But the following XML documents have different license names:

* https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1.xml
* https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1-or-later.xml

Could we update the HTML pages to have titles that match the XML documents?

In effect, I would like to see:

https://github.com/spdx/license-list-data/blob/main/html/LGPL-2.1.html

``` html
    <div class="optional-license-text">
      <p>
        GNU LESSER GENERAL PUBLIC LICENSE
      </p>

      <p>
        Version 2.1 only, February 1999
      </p>
    </div>
```

https://github.com/spdx/license-list-data/blob/main/html/LGPL-2.1-or-later.html

``` html
    <div class="optional-license-text">
      <p>
        GNU LESSER GENERAL PUBLIC LICENSE
      </p>

      <p>
        Version 2.1 or later, February 1999
      </p>
    </div>
```

**Comment by DaveJarvis** [comment]
FYI, in two days I will be locked out of my account once GitHub begins enforcing MFA. Sorry I won't be able to help any further. It would be fantastic to see the titles updated, if it all possible. Thank you.

**Comment by swinslow** [comment]
The requester for this one no longer appears to be participating (GitHub account appears to be disabled), so I'm closing this issue.
