### ISSUE TITLE
New License: if it breaks 

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#2057]
One of the Fedora package maintainers found a license that matches BSD-2-Clause at: https://github.com/zdohnal/hplip/blob/master/base/exif.py

but adds at the end:

`This means you may do anything you want with this code, except claim you wrote it. Also, if it breaks you get to keep both pieces.`

considering the placement of this text, could we omit it for matching as not part of the license? 

also see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/268

**Comment by swinslow** [comment]
I do note that it has the word "REGENTS" hanging out in the disclaimer paragraph. Not a problem for matching purposes since it's within the alt-text for "THE COPYRIGHT HOLDER OR CONTRIBUTORS," but just amusing to still see little straggler bits of the original BSD license hanging on  :)

I would _not_ want to accommodate this into standard BSD-2-Clause via markup. That's for several reasons, in particular because I don't believe their characterization of the license text actually reflects what (I think) it says. Which is fine, but I think it's over the line of "is this substantively different" to mean that markup isn't warranted.

I don't know if we have an official policy on "is this blurb of language part of the official license text or not" when it shows up immediately following the license text. I don't know how we could draft that in a way that would be machine parseable. 

Given that, I'm inclined to say that this should be a separate license identifier (if we determine that it otherwise meets the requirements to be on the list).

**Comment by Pizza-Ria** [comment]
@swinslow which piece are you saying that you "_would not want to accommodate this into standard BSD-2-Clause via markup._"

I'm actually more aligned with @jlovejoy on this one - I'd say leave the last clause off as explanatory but not actually part of the license and call it close enough to BSD-2.

**Comment by Pizza-Ria** [comment]
Maybe we need a policy on "is this blurb of language part of the official license text or not".

**Comment by jlovejoy** [comment]
> Maybe we need a policy on "is this blurb of language part of the official license text or not".

I'm not sure I'd know where to begin...

**Comment by jlovejoy** [comment]
but looking at it again and given the statement above the copyright notice stating, `This copyright license is intended to be similar to the FreeBSD license. ` (and it is) - I think I'm inclined to treat this as "superfluous" and not part of the license. Thus, use BSD-2-Clause and no new license needed.

Would be curious to hear if @bsdimp has any insight on this one thought... ;)

**Comment by swinslow** [comment]
Based on 2023-09-08 discussion, @jlovejoy and I agree that this is generally superfluous language and don't think it warrants either markup or adding a separate ID on the license list. If someone wants to track it separately they can use a LicenseRef- to designate a custom license, or else they can use standard BSD-2-Clause.
