### ISSUE TITLE
New license request: BSD-3-xxx [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by befeleme** [spdx/license-list-XML#2073]
**1.** License Name: BSD-3-style license
**2.** Short identifier: ???
**3.** License Author or steward: Probably the creators of the alabaster theme
**4.** Comments: This license is used in Fedora, it was found during license review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/289
**5.** License Request Url: http://tools.spdx.org/app/license_requests/270
**6.** URL(s): https://github.com/sphinx-doc/alabaster/blob/0.x/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/sphinx-doc/alabaster
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/6b141786-b4ce-41c4-bb17-3af6046c4873.png

**Note:**
The license closely matched with the following license ID(s): BSD-3-Clause

**Comment by jlovejoy** [comment]
differences b/w this license and regular BSD-3-Clause:
* added line "Some rights reserved." at top --> I would consider this part of copyright notice, so not matchable/doesn't matter
* adds "of the theme" in the first line --> ??
* uses "THEME" instead of "SOFTWARE" in first line of disclaimer --> ??
* difference in third clause --> I think these are already covered in markup (but will check pending decision on theme /software differences)

**Comment by swinslow** [comment]
License text for reference:

```
Copyright (c) 2020 Jeff Forcier.

Based on original work copyright (c) 2011 Kenneth Reitz and copyright (c) 2010
Armin Ronacher.

Some rights reserved.

Redistribution and use in source and binary forms of the theme, with or
without modification, are permitted provided that the following conditions
are met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above
  copyright notice, this list of conditions and the following
  disclaimer in the documentation and/or other materials provided
  with the distribution.

* The names of the contributors may not be used to endorse or
  promote products derived from this software without specific
  prior written permission.

THIS THEME IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS THEME, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
```

**Comment by swinslow** [comment]
In addition to @jlovejoy's notes above, "THEME" also appears instead of "SOFTWARE" a second time, in the last sentence of the disclaimer.

Here are my thoughts on each of these:

> * added line "Some rights reserved." at top --> I would consider this part of copyright notice, so not matchable/doesn't matter

Agree, I wouldn't add markup for this.

> * adds "of the theme" in the first line --> ??

I'd be +1 to accommodate this via markup. That said, I would probably _not_ want to add this as an `<optional>` tag. That's because, if we do that, I believe it'll show up on the license list website as blue optional text for BSD-3-Clause generally. This will probably result in people copying and pasting that text into other sources and propagating "of the theme" into places where it shouldn't be.

Instead, I'd probably do something janky like, in the first clause ("Redistribution and use in source and binary forms"), after "forms" insert an `<alt>` tag match with `(of the theme)?` as the pattern, `spacing="none"`, and an empty display string between the `<alt></alt>` tags. I _think_ that would cause it to be recorded as a pattern in the XML, but not displayed on the website.

> * uses "THEME" instead of "SOFTWARE" in first line of disclaimer --> ?? _(@swinslow note: and also in the last line of the disclaimer, as mentioned above)_

+1 to accommodating this with `<alt>` tag markup.

> * difference in third clause --> I think these are already covered in markup (but will check pending decision on theme /software differences)

Yes, already accommodated: https://github.com/spdx/license-list-XML/blob/5f2a8670c942b1a8f1ec63b5c406e45623e41cd8/src/BSD-3-Clause.xml#L31C29-L31C51 -- the first match is `(The name of.+may not)` which should handle this.

I'm +1 to accommodate this via markup to BSD-3-Clause, subject to the comments above.

**Comment by xsuchy** [comment]
> > * difference in third clause --> I think these are already covered in markup (but will check pending decision on theme /software differences)
> 
> Yes, already accommodated: https://github.com/spdx/license-list-XML/blob/5f2a8670c942b1a8f1ec63b5c406e45623e41cd8/src/BSD-3-Clause.xml#L31C29-L31C51 -- the first match is `(The name of.+may not)` which should handle this.

I checked and the string "The names of the contributors may not" does not match anything there. The closest one is "The names of any contributors may not". So this new wording has to be added.

**Comment by swinslow** [comment]
Thanks @xsuchy! Good eyes on the various matches, I misread that in my earlier comment. You're correct.

I'm reviewing #2107 now -- I have a couple of edits and I see also that there is a conflict to be resolved, I'll resolve that before merging.
