### ISSUE TITLE
New license request: regexpr [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2085]
**1.** License Name: regexpr License
**2.** Short identifier: regexpr
**3.** License Author or steward: Tatu Ylonen
**4.** Comments: This license is used in Bacula project and this license has been found during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/285
**5.** License Request Url: http://tools.spdx.org/app/license_requests/275
**6.** URL(s): https://gitlab.com/bacula-org/bacula/-/blob/Branch-11.0/bacula/LICENSE-FOSS?ref_type=heads#L245
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.com/bacula-org/bacula/

**Comment by xsuchy** [comment]
License text:
```
 * Author: Tatu Ylonen <ylo@ngs.fi>
 *
 * Copyright (c) 1991 Tatu Ylonen, Espoo, Finland
 *
 * Permission to use, copy, modify, distribute, and sell this software
 * and its documentation for any purpose is hereby granted without
 * fee, provided that the above copyright notice appear in all copies.
 * This software is provided "as is" without express or implied
 * warranty.
```

**Comment by jlovejoy** [comment]
similar to HPND-sell, but omits too much to be a match.

**Comment by swinslow** [comment]
Agree that this doesn't match the existing HPND variants. +1 to add as its own license.

Perhaps `HPND-regexpr` or `HPND-sell-regexpr` as the ID? It might be worth keeping `HPND` in the prefix since it's so close. `regexpr` does seem to be appropriate here, that's the file that I'm finding this one associated with: e.g. https://opensource.apple.com/source/python/python-3/python/Modules/regexpr.h.auto.html

I'd probably avoid using the copyright holder's name in this instance, since this copyright holder has shown up in other (unrelated) licenses on the license list, see e.g. https://spdx.org/licenses/SSH-OpenSSH.html

**Comment by jlovejoy** [comment]
I like that idea for naming @swinslow - `HPND-sell-regexpr` - it's hard to notice the "and sell" so keeping that could be helpful to differentiate/signal

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

_record full name that will be used in the license list_

## License ID

HPND-sell-regexpr

## XML markup

note at this time

## Notes:

This is an even shorter variant of HPND-sell than that template allows for.



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@xsuchy  if you make this PR, there is a stray * in the tool submission text, which will get interpreted as a bullet :(
