### ISSUE TITLE
New license request: Adeia [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by solomonshalom** [spdx/license-list-XML#2095]
**1.** License Name: Adeia
**2.** Short identifier: Adeia
**3.** License Author or steward: Solomon Shalom Lijo
**4.** Comments: Permission Granted: The license grants permission to users to use, copy, modify, merge, publish, or distribute the software for non-commercial purposes. This aligns with the principle of granting specific permissions to users, making it clear what they are allowed to do with the software.

Conditions and Restrictions: The license includes conditions and restrictions, such as prohibiting commercial use without written permission. This helps clarify the limitations on how the software can be used, in accordance with the principle of specifying conditions and restrictions.

Attribution Requirement: The license requires users to include the copyright notice and the permission notice in all copies or substantial portions of the software. This adheres to the principle of attribution, ensuring that users provide proper credit to the copyright holder.

Commercial Licensing: The license provides a mechanism for commercial licensing by instructing interested parties to contact the copyright holder for written permission. This supports the principle of allowing for commercial use under separate agreements.

Fallback for Unspecified Authors: The license addresses the scenario where no specific author or copyright holder is designated. In such cases, users are given the freedom to use the software for both non-commercial and commercial purposes. This is in line with the principle of providing clarity when authorship is unspecified.

Disclaimer of Warranty and Liability: The license includes a standard disclaimer stating that the software is provided "as is" and that the authors or copyright holders are not liable for any claims or damages. This complies with the principle of disclaiming warranties and limiting liability.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/280
**6.** URL(s): https://gist.github.com/solomonshalom/3a5c38e00f36cbb0687799db18ed6663
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/solomonshalom/The-Abyss

**Comment by jlovejoy** [comment]
@solomonshalom - is my understanding correct that you wrote this license and it is only used on a project you wrote?

**Comment by solomonshalom** [comment]
> @solomonshalom - is my understanding correct that you wrote this license and it is only used on a project you wrote?

Yes!

**Comment by solomonshalom** [comment]
So, what is the current progress of itt, super excited!

**Comment by jlovejoy** [comment]
A key aspect of the SPDX License List inclusion principle https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md is substantial use of the license. This is because the overall goal of SPDX is to provide a language for communicating information about software, which presumes it is used in the software supply chain. 

Note in the https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md page, it also reiterates this. 

So, if this is a one-off license for your own project, it doesn't meet that criteria.

I appreciate you are super excited (although I'm not sure why this is exciting ;)
Taking a step back - why write a new license instead of using an existing one? While this is more of a curious question, it does relate to the overall goal of the open source (license) community to try to avoid license proliferation.

**Comment by solomonshalom** [comment]
Hi! @jlovejoy 

Hmm, I see but if it does have substantial use, it would be considered, right?

Also, Yes! I could have used an existing license but I couldn't find one that had the liberation for modification of it. Note that this license is mainly tailored to those who create products that are OS (like me :D)

P.S. Super excited because it just seemed cool to publish a license 😅 Though, really appreciate you taking your time and checking my license!

**Comment by jlovejoy** [comment]
> Hmm, I see but if it does have substantial use, it would be considered, right?

then it could be re-submitted and re-considered, yes.

> Also, Yes! I could have used an existing license but I couldn't find one that had the liberation for modification of it. Note that this license is mainly tailored to those who create products that are OS (like me :D)

You might have a look at the Open Source Definition as held by the Open Source Initiative and which is considered to be the definitive definition of an open source license. Your license would not meet that definition due to the restrictions on commercial use. 

You also might consider that the last bit may be a bit muddy as to how copyright law works and other similar rights in various jurisdictions. 

> P.S. Super excited because it just seemed cool to publish a license 😅 Though, really appreciate you taking your time and checking my license!

your welcome!

**Comment by solomonshalom** [comment]
> > Hmm, I see but if it does have substantial use, it would be considered, right?
> 
> then it could be re-submitted and re-considered, yes.
> 
> > Also, Yes! I could have used an existing license but I couldn't find one that had the liberation for modification of it. Note that this license is mainly tailored to those who create products that are OS (like me :D)
> 
> You might have a look at the Open Source Definition as held by the Open Source Initiative and which is considered to be the definitive definition of an open source license. Your license would not meet that definition due to the restrictions on commercial use.
> 
> You also might consider that the last bit may be a bit muddy as to how copyright law works and other similar rights in various jurisdictions.
> 
> > P.S. Super excited because it just seemed cool to publish a license 😅 Though, really appreciate you taking your time and checking my license!
> 
> your welcome!

1. I see! Wonderful (I shall come again <3)

2. Hmm, I understand and although it has a basis on commercial-restriction, the license also gives anybody holding the license the liberty to modify the license as per their requirements. It was initially created to support open-source projects that have a business side to them and to protect their service / product. 

Thank you for taking your time! It does mean a lot :D

**Comment by jlovejoy** [comment]
there are other licenses that restrict commercial use, they are not open source, but may be referred to as "source available" 

good luck!
