### ISSUE TITLE
New license request: INBL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by ghost** [spdx/license-list-XML#2098]
**1.** License Name: Inferno Nettverk BSD License
**2.** Short identifier: INBL
**3.** License Author or steward: Unknown
**4.** Comments: The license does not match any existing SPDX license as it is a variation on the BSD-4-Clause which combines two clauses and talks explicitly about derivative works. The text furthermore is stable.

This license is under review for Fedora (https://gitlab.com/fedora/legal/fedora-license-data/-/issues/305) and after it is submitted as new license to SPDX it will be submitted for inclusion on the Fedora list of allowed licenses.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/281
**6.** URL(s): https://www.inet.no/dante/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: https://www.inet.no/dante/

**Comment by timsemeijn** [comment]
Text of the license:

`
/*
 * $Id: LICENSE,v 1.1 2023/02/27 10:05:18 karls Exp $
 *
 * Copyright (c) 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
 *               2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
 *               2017, 2018, 2019, 2020
 *      Inferno Nettverk A/S, Norway.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. The above copyright notice, this list of conditions and the following
 *    disclaimer must appear in all copies of the software, derivative works
 *    or modified versions, and any portions thereof, aswell as in all
 *    supporting documentation.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *      This product includes software developed by
 *      Inferno Nettverk A/S, Norway.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Inferno Nettverk A/S requests users of this software to return to
 *
 *  Software Distribution Coordinator  or  sdc@inet.no
 *  Inferno Nettverk A/S
 *  Oslo Research Park
 *  Gaustadalléen 21
 *  NO-0349 Oslo
 *  Norway
 *
 * any improvements or extensions that they make and grant Inferno Nettverk A/S
 * the rights to redistribute these changes.
 *
 */
`

**Comment by Pizza-Ria** [comment]
+1 to add although I don't love the name since there are divergences from BSD that should be better called out.  

The language used re the redistribution likely crosses the line into separate license language from BSD-4 (i.e., _must appear in all copies of the software, derivative works or modified versions, and any portions thereof, as well as in all supporting documentation._).  

Also, while I think that final clause is a request (rather than a demand or strict obligation) - I don't want to necessarily make that call on behalf of others @swinslow :).  

 * Inferno Nettverk A/S **requests users** of this software to **return** to
 *
 *  Software Distribution Coordinator  or  sdc@inet.no
 *  Inferno Nettverk A/S
 *  Oslo Research Park
 *  Gaustadalléen 21
 *  NO-0349 Oslo
 *  Norway
 *
 * **any improvements or extensions that they make and grant Inferno Nettverk A/S
 * the rights to redistribute these changes.**

**Comment by jlovejoy** [comment]
this has been determined as allowed for Fedora

**Comment by swinslow** [comment]
I tend to agree with @Pizza-Ria not to include the last part with the "request" as part of the license grant.

I'm +1 to add this, perhaps with `BSD-Inferno-Nettverk` as the ID and "Inferno Nettverk BSD variant license" as the name -- see https://github.com/spdx/license-list-XML/issues/2066#issuecomment-1712137796 for a similar naming discussion

**Comment by swinslow** [comment]
License text for reference:

```
 * Copyright (c) 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
 *               2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016
 *               2017, 2018, 2019, 2020
 *      Inferno Nettverk A/S, Norway.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. The above copyright notice, this list of conditions and the following
 *    disclaimer must appear in all copies of the software, derivative works
 *    or modified versions, and any portions thereof, aswell as in all
 *    supporting documentation.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *      This product includes software developed by
 *      Inferno Nettverk A/S, Norway.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Here's the "request" part, which I could be persuaded to include as well at the end, or not:

```
 * Inferno Nettverk A/S requests users of this software to return to
 *
 *  Software Distribution Coordinator  or  sdc@inet.no
 *  Inferno Nettverk A/S
 *  Oslo Research Park
 *  Gaustadalléen 21
 *  NO-0349 Oslo
 *  Norway
 *
 * any improvements or extensions that they make and grant Inferno Nettverk A/S
 * the rights to redistribute these changes.
```

**Comment by jlovejoy** [comment]
I think I lean towards including the request text at the end, as it seems like it was intended to be part of the license even if it's not a requirment.

@swinslow suggestion for naming seems reasonable

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

BSD-Inferno-Nettverk

## License ID

BSD-Inferno-Nettverk

## XML markup

none at this point in time

## Notes:

This license is similar to BSD-4-Clause but it combines first two clauses and includes a request that improvements or extensions be sent to the author.


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@timsemeijn - could you make a PR to add the files for this license now that it is accepted?

**Comment by timsemeijn** [comment]
@jlovejoy - will be able to do this in a couple of days (currently on vacation).

Thanks everyone for the feedback!

**Comment by xsuchy** [comment]
I drafted the PR for you.
