### ISSUE TITLE
New license request: Lucida-Fonts [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2120]
**1.** License Name: Bigelow and Holmes Lucida Fonts
**2.** Short identifier: Lucida-Fonts
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. This is a license used by fonts.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/326#note_1548848710
**5.** License Request Url: http://tools.spdx.org/app/license_requests/287
**6.** URL(s): https://gitlab.freedesktop.org/xorg/font/bh-100dpi/-/blob/master/COPYING?ref_type=heads
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/font/bh-100dpi/, https://gitlab.freedesktop.org/xorg/font/bh-75dpi/

**Comment by n8willis** [comment]
Agree that this is worth including.

I do think that the proposed name and identifier are potentially confusing, however.

It's fairly important that the specific fonts this license applies to are bitmap fonts and are, thus, only sort of considered "source code", and sort of just... raster image files. That distinction matters because there are *also* scalable / vector Lucida fonts, for sale under proprietary terms, including from places like the TeX Users Group (TUG) (https://www.tug.org/store/lucida/index.html).

The vector fonts not covered by this license are more likely to be encountered, because they're modern. If it isn't made clear that this license does _not_ apply to those fonts (which free-software users working with TeX may interact with frequently), then there could be some confusion as a result of the proposed license name / identifier.

**Comment by karsten-klein** [comment]
See also https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bigelow-holmes.LICENSE

**Comment by n8willis** [comment]
> See also https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bigelow-holmes.LICENSE

Is this pointer a suggestion for the author/steward and link fields? I suppose Oracle is really the inheritor, so that certainly makes sense.

Separately, I might suggest "Bigelow and Holmes Lucida Bitmap Fonts" and "Lucida-Bitmap-Fonts" and name and short identifier. I think that might stave off confusion fairly quickly.

**Comment by jlovejoy** [comment]
wow, this seems old!

+1 to add and agree with @n8willis on id of `Lucida-Bitmap-Fonts` (or maybe shorten to `Lucida-Bitmap`?) for id

As for name, I'd probably just be consistent to the id and go with `Lucida Bitmap Fonts License`

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Lucida Bitmap Fonts License

## License ID

Lucida-Bitmap-Fonts

## XML markup

none at this time

## Notes:

none



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
