### ISSUE TITLE
New license request: HPDN-doc-variant [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by bentiss** [spdx/license-list-XML#2124]
**1.** License Name: Historical Permission Notice and Disclaimer - documentation variant
**2.** Short identifier: HPDN-doc-variant
**3.** License Author or steward: Unknown
**4.** Comments: Packages (libXext and libXtst) using this license are used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/337
**5.** License Request Url: http://tools.spdx.org/app/license_requests/290
**6.** URL(s): https://gitlab.freedesktop.org/xorg/lib/libxext/-/blob/master/COPYING?ref_type=heads#L185-197, https://gitlab.freedesktop.org/xorg/lib/libxtst/-/blob/master/COPYING?ref_type=heads#L70-77
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/lib/libxtst, https://gitlab.freedesktop.org/xorg/lib/libxext

**Comment by jlovejoy** [comment]
license text for convenience:

```
Copyright (c) 1989 X Consortium, Inc. and Digital Equipment Corporation.
Copyright (c) 1992 X Consortium, Inc. and Intergraph Corporation.
Copyright (c) 1993 X Consortium, Inc. and Silicon Graphics, Inc.
Copyright (c) 1994, 1995 X Consortium, Inc. and Hewlett-Packard Company.

Permission to use, copy, modify, and distribute this documentation for
any purpose and without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.
Digital Equipment Corporation, Intergraph Corporation, Silicon
Graphics, Hewlett-Packard, and the X Consortium make no
representations about the suitability for any purpose of the
information in this document.  This documentation is provided ``as is''
without express or implied warranty.
```

same text as #2125 but omits "and sell" in grant

**Comment by jlovejoy** [comment]
close to HPND, but:
- only applies to "this documentation" instead of "this software and its documentation"

- shortens condition to "provided that the above copyright notice and this permission notice appear in all copies" instead of "provided that the above copyright notice appear in all copies and that both the copyright notice and this permission notice appear in supporting documentation"

especially given it seems to be specific to just documentation, should this be a new/different license?
I don't think we can really justify adding more markup to HPND...

**Comment by karsten-klein** [comment]
See also https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-doc.LICENSE.

**Comment by swinslow** [comment]
@jlovejoy regarding "documentation" vs. "software and documentation", I think we've previously been comfortable adding markup to reflect differences in this sort of language -- since it essentially goes to "which work does this apply to" rather than "what are your rights / obligations under the license". See for instance #866 / #962. So I wouldn't be too troubled with adding markup for "documentation". 

For your second bullet point, though, yes -- this seems different enough in terms of which language is present vs. optional that I think it warrants a separate identifier.

+1 to add, and I think the ID and proposed name are probably fine (though just noting it should be "HPND" rather than "HPDN")

**Comment by swinslow** [comment]
@karsten-klein Thanks for sharing the link. I wouldn't suggest going with an identifier that incorporates "X11" here, since there is already an [`X11` license](https://spdx.org/licenses/X11.html) on the SPDX License List which is a variant of MIT rather than HPND. The license proposed in this issue is much closer to HPND and probably warrants using that for part of the identifier to avoid confusion.

**Comment by Pizza-Ria** [comment]
+1 per second point which @swinslow noted from @jlovejoy's analysis.

**Comment by jlovejoy** [comment]
FYI - @karsten-klein - the one you linked to has "and sell" which is different than this one! but perhaps the same as #2125

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - documentation variant

## License ID

HPND-doc

## XML markup

none

## Notes:

This is very simlar to HPND but is for documentation and alters the notice obligation.


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@bentiss - can you prepare a PR for this now that it's been accepted?

**Comment by bentiss** [comment]
Done for both licenses!

I think I got the letters ordering right this time.

Thanks
