### ISSUE TITLE
New license request: HPND-sgi [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jexposit** [spdx/license-list-XML#2132]
**1.** License Name: Similar to HPND or libtiff
**2.** Short identifier: HPND-sgi
**3.** License Author or steward: Unknown
**4.** Comments: This licence is used by Fedora's package mesa-libGLw. The licence was found during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/336
**5.** License Request Url: http://tools.spdx.org/app/license_requests/292
**6.** URL(s): https://gitlab.freedesktop.org/mesa/glw/-/blob/master/README?ref_type=heads
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://gitlab.freedesktop.org/mesa/glw/-/tree/master/

**Comment by jlovejoy** [comment]
similar grant to `HPND-sell-variant-MIT-disclaimer` but omits "and sell"

also the disclaimer is different in a couple substantive ways, most notably, by adding an explicit disclaimer of non-infringement

+1 to add as its own/new/different license, name as chosen seems appropriate

**Comment by swinslow** [comment]
License text for reference:

```
 * (c) Copyright 1993, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED 
 * Permission to use, copy, modify, and distribute this software for 
 * any purpose and without fee is hereby granted, provided that the above
 * copyright notice appear in all copies and that both the copyright notice
 * and this permission notice appear in supporting documentation, and that 
 * the name of Silicon Graphics, Inc. not be used in advertising
 * or publicity pertaining to distribution of the software without specific,
 * written prior permission. 
 *
 * THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
 * AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
 * FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL SILICON
 * GRAPHICS, INC.  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT,
 * SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY
 * KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION,
 * LOSS OF PROFIT, LOSS OF USE, SAVINGS OR REVENUE, OR THE CLAIMS OF
 * THIRD PARTIES, WHETHER OR NOT SILICON GRAPHICS, INC.  HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
 * POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
 * 
 * 
 * US Government Users Restricted Rights 
 * Use, duplication, or disclosure by the Government is subject to
 * restrictions set forth in FAR 52.227.19(c)(2) or subparagraph
 * (c)(1)(ii) of the Rights in Technical Data and Computer Software
 * clause at DFARS 252.227-7013 and/or in similar or successor
 * clauses in the FAR or the DOD or NASA FAR Supplement.
 * Unpublished-- rights reserved under the copyright laws of the
 * United States.  Contractor/manufacturer is Silicon Graphics,
 * Inc., 2011 N.  Shoreline Blvd., Mountain View, CA 94039-7311.
 *
 * OpenGL(TM) is a trademark of Silicon Graphics, Inc.
```

**Comment by swinslow** [comment]
+1 to add, I don't think this matches anything currently on the list.

@jlovejoy This is one of those instances where I might suggest _not_ incorporating "HPND" into the identifier. I think the disclaimer is substantially different, not just in terminology but also in effect. (For example, the HPND disclaimer excludes only "special, indirect or consequential damages" or damages resulting from certain other losses; whereas the license submitted here also excludes "direct" damages and "any damages whatsoever, including without limitation..."

From some searching the only examples I'm finding for this are from SGI distributions of OpenGL files. In particular the phrase at the start of the second paragraph seems unique to them: "THE MATERIAL EMBODIED ON THIS SOFTWARE..."

Given that, perhaps go with an identifier like `SGI-OpenGL` and license name "SGI OpenGL License"? Could reference the similarity to HPND in the first paragraph if we wanted; or not, since a lot of other licenses on the list have similar grant language with other additions like this one.

Other instances of use:
* https://courses.cs.washington.edu/courses/csep557/99au/info/OpenGL/material.c -- believe this one is identical
* https://opensource.apple.com/source/X11server/X11server-85/mesa/Mesa-7.2/progs/redbook/unproject.c.auto.html -- identical except for "OpenGL(R) is a registered trademark" in final line -- looks like they switched "TM" to "R" and added "registered" at some point. I'd suggest maybe we insert those as markup so that either version matches.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

SGI OpenGL License

## License ID

SGI-OpenGL

## XML markup

for last line variations as described above

## Notes:

none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jexposit** [comment]
Thanks @jlovejoy , I created a PR including the license here: https://github.com/spdx/license-list-XML/pull/2161
