### ISSUE TITLE
New license request: Afio [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#2166]
**1.** License Name: Afio License
**2.** Short identifier: Afio
**3.** License Author or steward: Unknown
**4.** Comments: The license grant all rights, provided that the copyright notice and disclaimer of warranty appears in all copies.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/297
**6.** URL(s): https://github.com/kholtman/afio/blob/21f0408cb3df40e5de3d3fa2698eb6626c57df02/afio.c#L9-L129
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/kholtman/afio

**Comment by jlovejoy** [comment]
@chenrui333 - the text referenced is a collection of licenses, is there a particular license you are intending to submit??

**Comment by chenrui333** [comment]
oh, I just dump what I see :)

**Comment by jlovejoy** [comment]
thanks for being honest, but please don't just dump what you see. We have a process and criteria for adding licenses to the SPDX License List:
https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md
and
https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md

Like any contribution to an open source project - it is helpful for submissions to be in line with the process and guidance, as well as the overall goals of the project. ,Otherwise it may create unnecessary work for a small team of volunteers :)

**Comment by jlovejoy** [comment]
I'm going to close this, if the sub-parts of what you found warrant review, then we can do so via a new / separate issue :)
