### ISSUE TITLE
New license request: hdparm

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2167]
**1.** License Name: BSD-Style Open Source License
**2.** Short identifier: BSD-Style-Open-Source
**3.** License Author or steward: Unknow
**4.** Comments: This license is used in hdparm and was discovered during Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/344 (see this ticket for more history dive)
**5.** License Request Url: http://tools.spdx.org/app/license_requests/298
**6.** URL(s): https://github.com/Distrotech/hdparm/blob/4517550db29a91420fb2b020349523b1b4512df2/LICENSE.TXT
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceforge.net/projects/hdparm/

**Comment by xsuchy** [comment]
Text of the license:
```
BSD-Style Open Source License:

You may freely use, modify, and redistribute the hdparm program,
as either binary or source, or both.

The only condition is that my name and copyright notice
remain in the source code as-is.

The apt.c file is  Copyright (c) 2009 Jan Friesse <jfriesse@gmail.com>.
You may use/distribute apt.c freely, under the terms of either
(your choice) the GNU General Public License version 2,
 or a BSD style license.


Mark Lord (mlord@pobox.com)
```

**Comment by richardfontana** [comment]
From Fedora's standpoint, this submission should be limited to:

```
BSD-Style Open Source License:

You may freely use, modify, and redistribute the hdparm program,
as either binary or source, or both.

The only condition is that my name and copyright notice
remain in the source code as-is.
```

**Comment by Pizza-Ria** [comment]
Agree with the Fedora review that apt.c is not really part of the proposed license.  OK with adding just the BSD-ish text as a license since there are no clear matches to that text. 

```
BSD-Style Open Source License:

You may freely use, modify, and redistribute the hdparm program,
as either binary or source, or both.

The only condition is that my name and copyright notice
remain in the source code as-is.

Mark Lord (mlord@pobox.com)
```

**Comment by bsdimp** [comment]
Why the name bsd-ish style? Dozens of licenses are like that... this is more similar to isc license imho... I know it calls itself that, but it seems weird since there are so few examples

**Comment by jlovejoy** [comment]
agree with @bsdimp  on naming - we generally reserve "BSD" for licenses with the same grant and configuration of 1-3 clauses.

but alas, that is the title in the license file.

I'm fine with using the stated title as the full name, since there is actually a title, but I feel like the id should be something different??

**Comment by richardfontana** [comment]
What about `0BSD` (which SPDX gives as full name "BSD Zero Clause License") which is based on `ISC`?

**Comment by swinslow** [comment]
I'd suggest `hdparm` as the ID and `hdparm License` as the name. From a couple of quick searches, the hdparm project appears to be the primary (if not only) place where this particular wording is used, so I think it's reasonable for us to reference it to that license.

@richardfontana the naming for `0BSD` is an issue that pre-dates my involvement with SPDX, but I believe had a lot of back-story that went into that name and ID as a one-off.

Given that "BSD-style" is often used in license review / scanning as a catch-all to refer to BSD-like licenses, I would have some hesitancy with picking any one license and saying "this is the BSD-style license". And since this one appears to be tied to a single project, I'd suggest we just use the hdparm name for this one.

**Comment by bsdimp** [comment]
I like @swinslow 's proposal.  It answers all my objections to the other name.
