### ISSUE TITLE
New license request: Cronyx-AntonZinoviev [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2173]
**1.** License Name: Cronyx-AntonZinoviev
**2.** Short identifier: Cronyx-AntonZinoviev
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. This is a license used by xkeyboard-config.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/322
**5.** License Request Url: http://tools.spdx.org/app/license_requests/301
**6.** URL(s): https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/COPYING?ref_type=heads#L178
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/

**Comment by whot** [comment]
First paragraph is identical to the recently added [Cronyx](https://github.com/spdx/license-list-XML/issues/2115) license

**Comment by Pizza-Ria** [comment]
1/2 of this matches another Scancode key - [font-alias](https://scancode-licensedb.aboutcode.org/font-alias.html) but it doesn't include "Permission is granted to anyone to use, distribute and modify this file in any way, provided that the above copyright notice is left intact and the author of the modification summarizes the changes in this header. This file is distributed without any expressed or implied warranty."

Since this is the second one that I have seen like this - what is our approach vis-a-vis other org's license IDs???

**Comment by swinslow** [comment]
@Pizza-Ria I suspect that the check-license tool might not be seeing it because [Cronyx](https://spdx.org/licenses/Cronyx.html) (the matching license) was just added in the 3.22 release. So the check-license tool might not be updated yet (I haven't checked), and/or the version of the extension you're using might not have it yet.

I ran into a similar issue using Google to try to search for this text -- I'm guessing the Google caches haven't yet crawled the license texts at https://spdx.org/licenses since the latest release.

Regarding license IDs used by Scancode or other third parties, I think they can perhaps be informative but should not be determinative. If an identifier used by a third party fits with typical SPDX formatting and choices, then I'm fine with using it, but I think we should feel free to use the names / IDs that we think are most appropriate. Here, if only part of the license text matches a Scancode license, then I don't think we need to focus much on the naming they've used for the different one.

Here, I'm +1 to add this as a simple, permissive and historical license used in Fedora.

For name / ID, I might go with "xkeyboard-config-Zinoviev" as ID and "xkeyboard-config Zinoviev License" as the name? I don't have a strong feeling on this, but I think that the Cronyx licenses is non-distinctive enough -- and the added requirement in the second paragraph is different enough -- that including "Cronyx-" in the license ID may not be helpful here.

**Comment by whot** [comment]
ftr, I can't find any other instances in the xorg repositories (at last a large subset of them, tricky to clone truly *all* of them) with that same license so it may really be limited to xkeyboard-config. I'd be fine with the name `xkeyboard-config-Zinoviev`.

**Comment by whot** [comment]
Gentle reminder here

**Comment by jlovejoy** [comment]
sorry @whot !

+1 to add as new license. and agree with the naming suggestion even if it's a bit long!

**Comment by quantenzitrone** [comment]
this license is likely 2 licenses that with one missing the copyright header due to an error
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/527
