### ISSUE TITLE
New license request: HPND-sell-MIT-permission [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2177]
**1.** License Name: HPND-sell-variant-MIT-disclaimer-permission-variant
**2.** Short identifier: HPND-sell-MIT-permission
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. This is a license used by xkeyboard-config.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/363
**5.** License Request Url: http://tools.spdx.org/app/license_requests/302
**6.** URL(s): https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/COPYING?ref_type=heads#L1781
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/xserver/

**Comment by whot** [comment]
Obviously the naming and short identifier should be adjusted for something more sensible. Could be HPND-sell-variant-MIT-disclaimer-NSA, all the source files in the X server that use this license were written by an NSA employee at the time.

This is a variant of the HPND-sell-variant-MIT-disclaimer with the first paragraph missing "copyright notice" blurbs.

**Comment by whot** [comment]
cc @jexposit

**Comment by swinslow** [comment]
Agree that this one is (annoyingly) close-but-not-quite to https://spdx.org/licenses/HPND-sell-variant-MIT-disclaimer.html. Differences appear to be:

1. First paragraph includes separate sentence of "This permission notice shall be included in all copies or substantial portions of the Software." and doesn't include HPND-sell-variant-MIT-disclaimer's text "the above copyright notice appear in all copies and that both that copyright notice and"
2. Doesn't include the formatted "Disclaimer" ASCII art box
3. Final paragraph is all-caps (but I _think_ otherwise identical)

2 seems easy to mark as optional, and 3 I think is not relevant for matching purposes. But 1 is (again, annoyingly) I think arguably substantively different, and also would be challenging to include with markup.

Given that, I'm inclined to add this one as a separate license ID / name. Not sure what best to use for the ID and name. @whot, is xserver the only project where you're seeing this particular formulation used?

**Comment by whot** [comment]
> @whot, is xserver the only project where you're seeing this particular formulation used?

Yes, AFAICT. This one is a bit trickier to search for but as I said above it stems from one author and none of the other projects I can grep for his name (or NSA in more general) list the same copyright notice.

**Comment by jlovejoy** [comment]
ugh, this is a naming conundrum!  I really wish we hadn't used "variant" in the ID for HPND-sell - it ends up being superfluous characters...

not sure if now using `HPND-sell-MIT-disclaimer-no-copyright` would be any better?
as NSA nor xserver are in the text of the license, those seem less helpful?

unless we just did something like `HPND-sell-xserver` and used the Notes to explain the similarity re: MIT disclaimer text?

**Comment by jlovejoy** [comment]
discussed on 11/9 - decided on: `HPND-sell-MIT-disclaimer-xserver`

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

_record full name that will be used in the license list_

## License ID

_record final decision on short id to be used; **take care** as it is policy that this id never change_

## XML markup

_describe any markup for replaceable or omitable text needed in the XML for the license_

## Notes:

_add any information that is to be included in the Notes field_

## Additional rationale or notes on decision:

_add any additional information, including optionally a summary of what is recorded in the issue comments_

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
