### ISSUE TITLE
Allow alternative GPL-2.0/LGPL-2.0/LGPL-2.1 wording

### ISSUE THREAD

**Issue by mtelka** [spdx/license-list-XML#2204]
The LGPL-2.1 wording available at [LGPL-2.1-only](https://spdx.org/licenses/LGPL-2.1-only.html) and [LGPL-2.1-or-later](https://spdx.org/licenses/LGPL-2.1-or-later.html) is based on [officially published LGPL-2.1 by FSF](https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html).  Unfortunately, there is another slightly [different LGPL-2.1 text available at gnu.org](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt).

The difference is this:
```
The plain text version at
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
reads:

---------------------------------- 8< --------------------------------
former contains code derived from the library, whereas the latter must
be combined with the library in order to run.

                  GNU LESSER GENERAL PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. This License Agreement applies to any software library or other
program which contains a notice placed by the copyright holder or
---------------------------------- 8< --------------------------------


While the standalone HTML version at
https://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html
shows:

---------------------------------- 8< --------------------------------
former contains code derived from the library, whereas the latter must
be combined with the library in order to run.

   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. This License Agreement applies to any software library or other
program which contains a notice placed by the copyright holder or
---------------------------------- 8< --------------------------------


IOW, the "GNU LESSER GENERAL PUBLIC LICENSE" words are missing.
```

A lot of software distributed on internet and licensed under LGPL-2.1 includes the plain text version of the license and so they contain extra **GNU LESSER GENERAL PUBLIC LICENSE** words in their license text.  This causes problem for automatic license matching because SPDX does not show the **GNU LESSER GENERAL PUBLIC LICENSE** words there as omitable (in blue).

Could you please add **GNU LESSER GENERAL PUBLIC LICENSE** before the **TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION** and mark it as omitable (blue)?

Thank you.

**Comment by mtelka** [comment]
I just noticed there is similar problem with [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html) and [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html) where there is extra **GNU GENERAL PUBLIC LICENSE** at https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt when compared to https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html.

**Comment by jlovejoy** [comment]
@mtelka  - this is actually accommodated in markup, just via the alternative tag instead of the optional tag, see https://github.com/spdx/license-list-XML/blob/main/src/GPL-2.0-or-later.xml

I checked this for `GPL-2.0-only` and it's there in the same way as well. I did not check all the others, but if you want to have a look to make sure we are consistent, that would be great!

I did make a PR to add the other FSF url, see #2244 - as I think having that is probably helpful. Could you make a PR to add the links for the other licenses? We only need to do so for the non-deprecated variants, that is, those ending with `-only` and `-or-later`

Thanks!

**Comment by mtelka** [comment]
> @mtelka - this is actually accommodated in markup, just via the alternative tag instead of the optional tag, see https://github.com/spdx/license-list-XML/blob/main/src/GPL-2.0-or-later.xml

Hm, yes, you are right.  It is there in the `xml` file.  The problem is that this is not visible in the rendered `html` page at https://spdx.org/licenses/GPL-2.0-or-later.html.

Would you mind to change `<alt name="termsTitle" match="GNU GENERAL PUBLIC LICENSE|"/>` to `<optional>GNU GENERAL PUBLIC LICENSE</optional>`?

Thank you.

**Comment by jlovejoy** [comment]
the colored text on the html page is really there for human-readable convenience, with the actual markup in the XML file being more definitive. This is especially true for replaceable text where the html page can only show one set of text, not all the options.

There are some reasons to use the <alt> tag instead of the <optional> tag for a situation like this where specific text could be there or not. Usually, that might be in the case where optional text is less likely to be there than nothing and having it "show" on the html page might be confusing.  Obviously, there are no hard and fast rules on this and it's not a common scenario.

That being said, I'm not sure if this case matters much how we code it, but I'd still like others to weigh in.

@richardfontana @swinslow - I'm thinking you both might have some thoughts on this?

**Comment by mtelka** [comment]
I just noticed that similar issue is with ending comma here: https://github.com/spdx/license-list-XML/blob/main/src/GPL-2.0-or-later.xml#L25.  It is marked in the xml file, but this marking is not visible in the rendered html file.

Yes, html pages are for human-readable convenience, but since we are humans (at least I am :-)) I'd prefer to see this on the html page too.  In this case it is hard to say what variant is less likely to be there, but if it is show in blue it cannot be confusing.

For replaceable text it is not confusing, because it is clearly shown in red.  So it is clear there could be variants.  Again, not confusing.

**Comment by sdheh** [comment]
The https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1.xml file is missing optional or alt "GNU LESSER GENERAL PUBLIC LICENSE" and it leads to https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt not matching LGPL-2.1.

**Comment by jlovejoy** [comment]
this issue has been resolved via another similar issue and PR
