### ISSUE TITLE
New license request: Kevlin-Henney [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by lzaoral** [spdx/license-list-XML#2206]
**1.** License Name: Kevlin Henney License
**2.** Short identifier: Kevlin-Henney
**3.** License Author or steward: Kevlin Henney
**4.** Comments: It is used in Fedora and this license was found during license review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/371
**5.** License Request Url: http://tools.spdx.org/app/license_requests/309
**6.** URL(s): https://github.com/mruby/mruby/blob/83d12f8d52522cdb7c8cc46fad34821359f453e6/mrbgems/mruby-dir/src/Win/dirent.c#L127-L140
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mruby/mruby/blob/master/mrbgems/mruby-dir/src/Win/dirent.c

**Comment by jlovejoy** [comment]
so, this is yet another HPND-ish variant. It's most like https://spdx.org/licenses/HPND-sell-regexpr.html in terms of ordering of the grant/without fee part, but omits "sell" and has a different notice statement.
Given the "sell" difference, I don't think we could add markup there.

also similar to https://spdx.org/licenses/HPND-Pbmplus.html but varies the order of hereby granted/without fee and has a slightly different notice clause:

`HPND-Pbmplus` uses: "provided that the above copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation."

where this variant has: "provided
    that this copyright and permissions notice appear in all copies and
    derivatives."

I'm not sure I would feel comfortable accommodating this in `HPND-Pbmplus` since it is a bit different condition. Which would mean adding as a new license...

Perhaps `HPND-Henney`?

What do others think?

**Comment by jlovejoy** [comment]
@pombredanne - we have been trying to use HPND to indicate it's related as we have been finding to many variants on this recently with Fedora's adoption. While I hear you on alignment of ids, we also need to consider naming that is helpful to the larger ecosystem in terms of identification/familiarity (and spend a fair amount of time on these conversations)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - Kevlin Henney variant 

## License ID

HPND- Kevlin-Henney

## XML markup

none

## Notes:

_add any information that is to be included in the Notes field_



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@lzaoral - sorry this took so long! Now that we have a decision, can you prepare a PR?
