### ISSUE TITLE
New license request: BDS-BY-NC-SA [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by EvanCarroll** [spdx/license-list-XML#2210]
**1.** License Name: Boycott Divestment Sanctions - Attribution-NonCommercial-ShareAlike
**2.** Short identifier: BDS-BY-NC-SA
**3.** License Author or steward: Evan Carroll
**4.** Comments: It is a geographically limited version of CC-BY-SA-NC
**5.** License Request Url: http://tools.spdx.org/app/license_requests/311
**6.** URL(s): https://github.com/EvanCarroll/xbrowser/blob/main/LICENSE.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/EvanCarroll/xbrowser

**Comment by EvanCarroll** [comment]
I will also version all future versions of the license, and I can move it to a separate project for tracking.

**Comment by jlovejoy** [comment]
@EvanCarroll - so this looks to be a brand new license, or really more of a sort of modification to CC-BY-SA-NC that you just created? Which means it has no use as of yet - is that right?

The comments section of the submission form is intended to explain how your license meets the SPDX License List inclusion principles, which you can find at: https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md

Could you please add a comment with that info?

**Comment by jlovejoy** [comment]
ah, okay, based on the dates in your repo, this is newly written, so it won't meet the substantial use requirement and it does not meet any of the open/free definitions due to the restrictions placed. 

Also note the first part of https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md in the section on submitting a new license. 

These are the key factors for inclusion on the SPDX License List as the goal is to be able to represent licenses found and used in the software supply chain. In light of that, I don't think this is ripe for inclusion.

**Comment by EvanCarroll** [comment]
I'm not sure how you separate "brand new" from "modification of". The linked page does't give any guidance on that either. I'm happy to comment on why it meets inclusion. Thanks for giving me the opportunity to respond,

* This license is based CC BY-SA-NC. The NonCommercial (NC) clause in CC BY-SA-NC is a limitation on software freedom. For my purposes, this limitation allows my production to help empower people to rival corporate power; I see corporate power as a destructive force in society that we should all collectively be fighting against. It creates a power discrepancy between corporate/commercial power and people power, which I believe makes us all more-free. My definition of freedom is at odds with the GPL. The CC BY-SA-NC further restricts "Free Software", only because "Free Software" is made in an economic system that has prioritized the corporate/commercial production of drones, and laser guided bombs that target citizens. I feel this is much better definition of "Free".
* The proposed licensed above further adds a restriction on the already accepted CC BY-SA-NC which in the same spirit limits the freedom granted, so that not just is one not-free to subjugate others by corporate rule. But that it also acknowledges that some places have a system so backwards and reactionary that any use there which they find in their own selfish interest is against any notion of shared humanity.

Now as far as "does not meet any of the open/free definitions due to the restrictions placed", I don't see how that can be true. If Open/Free can prohibit use based on an economic system, why can it not prohibit use based on the apartheid nature of prevailing state? Moreover, there are already licenses like this that merely wax poetically rather than attempt at clarity for example, the ["JSON license"](https://spdx.org/licenses/JSON.html),

> The Software shall be used for Good, not Evil.

The SQLite contains as similar clause albeit non-binding. I'm only explaining my own definition of "evil" so that it may be more easily enforced in courts of equity. But this additional clarification does not seem to be any more so a violation of the Free principles acknowledged by SPDX then the other licenses that have been accepted into the list.

> ah, okay, based on the dates in your repo, this is newly written, so it won't meet the substantial use requirement and it does not meet any of the open/free definitions due to the restrictions placed.

That's fair, if this is the reason for rejection I'd like to request a clarification of the rules so I know when I can reapply. My license is new and inspired by the latest attempts at Israeli genocide of the Palestinian people. I understand if it needs more time or adoption. I just want to know what that looks like or where I can read about it.

**Comment by swinslow** [comment]
I'm sharing my thoughts below on why this does not meet the SPDX License Inclusion Principles that @jlovejoy linked to above. (template for the questions / responses is based on https://github.com/spdx/license-list-XML/blob/main/DOCS/template-license-review-checklist.md to help structure the response)

---

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [ ] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [ ] No
2. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [ ] No
3. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [ ] Yes
    - [ ] No
4. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [X] No => I don't think there's any reasonable argument that this license fails to meet [OSD requirements 5 and 6](https://opensource.org/osd/), or similar provisions in the other free/open content definitions referenced in the [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md).
2. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [X] No => No, it explicitly prohibits a class of individuals from using the licensed software
3. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [ ] Yes
    - [X] No => No, this license appears to only have been used by you for your own projects.
4. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes
    - [X] No => No, the restrictions imposed by this license go beyond those in the small number of other source-available, non-open-source licenses that have been added to the license list.
5. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [X] Yes
    - [ ] No

## Summary of factors, outcome, comments

In my view, this license meets none of them other than the license steward's support of the submission (which is the lowest-priority consideration per the ranking above). Given the totality of the "other factors" above, this license does not meet the License Inclusion Principles and should not be added.

Regarding the comments in the earlier thread about CC-BY-NC-SA: That license (or really, that class of licenses, since there are multiple versions of it) also do _not_ meet the "free / open" inclusion criteria (factor 1). They are on the list in light of the far broader usage of those Creative Commons licenses (factor 3) than has been shown here, as well as because they do not prohibit usage by a class of individuals (factor 2). So I do not see its inclusion as relevant to new modifications that do not themselves meet those factors.

**Comment by EvanCarroll** [comment]
There must be a misunderstanding: this isn't discrimination against any person or group. This is a geographical restriction and only a geographical restriction. Any Israeli doing business outside of Israel is **welcome** to use any software licensed under BDS BY-NC-SA. I've updated the license in an attempt to make this more clear.

Please help me better understand the problems so I can make the license more agreeable to SPDX.

What do you define as "class" here. Geographical exclusion isn't a class as far as I know in any parlance. Many of the license already have geographical exclusions, and export restrictions,

> Export of this software from the United States of America **may require a specific license from the United States Government.** It is the responsibility of any person or organization contemplating export to obtain such a license before exporting.

And, 

> EXPORT LAWS: THIS LICENSE ADDS NO RESTRICTIONS TO THE EXPORT LAWS OF YOUR JURISDICTION. It is licensee's responsibility to comply with any export regulations applicable in licensee's jurisdiction. Under CURRENT (May 2000) U.S. export regulations this software is eligible for export from the U.S. and can be downloaded by or otherwise **exported or reexported worldwide EXCEPT to U.S. embargoed destinations which include Cuba, Iraq, Libya, North Korea, Iran, Syria, Sudan, Afghanistan** and any other country to which the U.S. has embargoed goods and services.

Another one,

> Any distribution of this software or derivative works must comply with all applicable United States export control laws.

Another one,

> 8. Certain uses and transfers of the Software or documentation, and/or items or software incorporating the Condor Software or documentation, may require a license under U.S. Export Control laws. Licensee represents and warrants that **all uses and transfers of the Condor Software or documentation and/or any items or software incorporating Condor shall be in compliance with U.S. Export Control laws, and Licensee further understands that failure to comply with such export control laws may result in criminal liability to Licensee under U.S. laws.**

Many of these licenses, like the Condor license above are even FSF/Free Libre.

Is that the licencor can grant the OFAC and US Authorities the right to restrict use based on geography, but the licencor themselves can not impose the same sort of geographical restriction?

Is it the opinion SPDX that the above licenses fail to meet OSD requirement 5 and 6. Or do you feel something about the proposed license makes it unique?

Please see the update to the license diff for the clarifications made,

* https://github.com/EvanCarroll/awesome-opensource-boycott-divestment-sanctions/commit/95c89480f7b927bb98ca29e31105a9111d0bca42

**Comment by swinslow** [comment]
@EvanCarroll Thanks for your response. Given that you are making further changes to the license text, I've revised my prior writeup to indicate that the license text is _not_ in fact stable and settled. Since this is one of the "definitive factors" for the License Inclusion Principles, this means that the submission is not ready for inclusion.

That aside, I'd encourage you to review the other documentation in the license-list-XML repo regarding the purpose of the SPDX License List. The purpose of the list is to assist with cataloguing and curating a list of licenses that people are likely to encounter in open source / open collaboration development. A brand-new license used by only one or a handful of people, regardless of its terms, is not going to satisfy the inclusion principles; even more so when the text is still subject to change. Given that, I'm going to go ahead and close this issue as not accepted.
