### ISSUE TITLE
New license request: BSD-Source-Code-Justin-Gibbs

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2233]
### How license meets inclusion principles

This is similar to `BSD-Source-Code` but adds some problematic language ("immediately at the beginning of the file") to clause 1 reminiscent of `libutil-David-Nugent`. It seems to have originated in FreeBSD but has propagated to a number of other projects. For example, it occurs in the Linux kernel (though sadly it may have been replaced with an incorrect SPDX-License-Identifier by now) and in the Linux userspace package acl. 

### License Name

BSD Source Code Attribution Justin Gibbs Variant

### Suggested short identifier

BSD-Source-Code-Justin-Gibbs

### License or Exception?

license

### URL to license text

https://github.com/lattera/freebsd/blob/master/sys/cam/cam.c

### OSI Status

Not submitted

### License author or steward

Unknown

### URL to project(s) that use license

https://kernel.org
https://savannah.nongnu.org/projects/acl/

### paste text of license here

``` 
* Copyright (c) 1997 Justin T. Gibbs.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions, and the following disclaimer,
 *    without modification, immediately at the beginning of the file.
 * 2. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
```

**Comment by richardfontana** [comment]
Note: there is no Fedora License Data issue for this license at this time.

**Comment by jlovejoy** [comment]
@bsdimp - do you have any thoughts on this one as it seems to come from FreeBSD??

**Comment by jlovejoy** [comment]
thanks @bsdimp ! (And sorry I didn't see this sooner) so I think we can consider this approved to add, but need to finalize the name and id:
I disagree as to using `BSD-2-Clause-<something>` because the second clause is not like the actual BSD-2-Clause. But the two clauses are mostly the same as BSD-Source-Code

So maybe... `BSD-Source-Code-at-beginning` or `BSD-Source-beginning-file` or is there something shorter/better than "at beginning" or "beginning file"?
I take it this is not specific to a specific project or collection of code?

**Comment by bsdimp** [comment]
Yea.. still don't like the bsd-source prefix... 

But it is similar to the bsd license...  maybe BSD-var- prefix?

BSD-var-at-start-no-endorce?

Since I've noticed lots of weird variations and we will want to have a sane scheme in place... this nonsense lasted only a couple of years... but was sadly blindly copied... 

BSD-var-bill-paul-voices comes to mind...

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
BSD Source Code Attribution - beginning of file variant
## License ID
BSD-Source-beginning file
## XML markup

## Notes:
This license is mostly the same as BSD-Source-Code but adds includes a specific requirement requiring retention of the copyright notice "immediately at the beginning of the file".
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
