### ISSUE TITLE
LicenseCompareHelper: BSD-3-Clause text not recognized depending on new lines and spaces

### ISSUE THREAD

**Issue by sdheh** [spdx/license-list-XML#2266]
I found a BSD-3-Clause text where newlines make a difference to the results of LicenseCompareHelper.isTextStandardLicense:
Text 1:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

  - Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  - Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

  - Neither the name of the Eclipse Foundation, Inc. nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Text 2:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

  - Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  - Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.

  - Neither the name of the Eclipse Foundation, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

The only difference is that I put everything in one line in the third clause.
I ran LicenseCompareHelper.isTextStandardLicense with the BSD-3-Clause license on both texts:
- Text 1 difference message: `Variable text rule combined-bullet-organizationClause3 did not match the compare text starting at line spdx/Spdx-Java-Library#12 column spdx/Spdx-Java-Library#2 "-" while processing rule var: combined-bullet-organizationClause3`
- Text 2 difference message: `No difference found `

Note: tested using version 1.1.8

**Comment by jlovejoy** [comment]
@goneall - should we document the addition of `/s+` in our XML documentation? I suspect this is a potential issue in anything with a bunch of markup? (maybe HPND as well??)

**Comment by richardfontana** [comment]
> @goneall - should we document the addition of `/s+` in our XML documentation? I suspect this is a potential issue in anything with a bunch of markup? (maybe HPND as well??)

This change really shows how non-human readable the XML can be - yet we correctly instruct Fedora contributors (for example) to consult the XML markup as the authoritative specification for what the license identifiers signify. 

Doesn't this change go overboard in correcting the reported problem?

**Comment by bsdimp** [comment]
The problem isn't xml. The problems are with the increasingly tricky regexps.

Now, all the things they match are supposed to be legally equivalent to the non alt text so it shouldn't matter the exact canonical text.

It's always a tradeoff between simplicty and having 100 variations of BSD-3-clause that aren't materially different which has its own set of problems. There's at least 50 variations of GPL2 found in the wild with stupid variations that don't matter...

**Comment by richardfontana** [comment]
You're right, I'm conflating the (real) problems with XML with the problems with regular expressions. When you combine XML with regular expressions you get something worse than either.

**Comment by xsuchy** [comment]
> This change really shows how non-human readable the XML can be - yet we correctly instruct Fedora contributors (for example) to consult the XML markup as the authoritative specification for what the license identifiers signify.

Humans should not open the XML files at all. We (both distribution and SPDX org) should provide tools that allow ease matching for users. Like license-diff plugin.

> To truly implement the matching guidelines just as to the point that whitespace differences don't matter, you'd have to make a radical change to all of the XML files

Nope. In plain XML the spacing does not matter and the \s+ is not needed. It is only needed in `<alt>` attributes.

**Comment by richardfontana** [comment]
> Humans should not open the XML files at all. We (both distribution and SPDX org) should provide tools that allow ease matching for users. Like license-diff plugin.

Ideally this would be the case, but I don't think there are tools (at least FOSS ones) that eliminate the need to consult the XML files entirely in a large number of cases. spdx-license-diff for example cannot effectively be used (as a general matter) without also referring to the XML files. Try using it with any of these less common BSD-3-Clause variants or on *any* variety of HPND.  

I suppose it's true that the biggest problems with the XML files pertain to a relatively small (though growing) number of them. 

I actually don't agree that humans should not opoen the XML files, because you have to open and read them in order to contribute to this project, to add new files and make changes to existing ones. Otherwise, there should be a 'source' format of some sort that is converted to XML.

**Comment by xsuchy** [comment]
> Ideally this would be the case, but I don't think there are tools (at least FOSS ones) that eliminate the need to consult the XML files entirely in a large number of cases. 

Let's create these tools :)

**Comment by jlovejoy** [comment]
there are some good thoughts here and I have some to add, but let's move this to an email thread instead of a closed issue!

**Comment by richardfontana** [comment]
I'm still pretty puzzled about this issue. Isn't the flaw here the tool (in how it apparently handles whitespace), not in the XML file?

**Comment by xsuchy** [comment]
It is a flaw, err, in the design of XML files. The whole XML specification (not spdx.org) related.

**Comment by goneall** [comment]
@richardfontana - 

A couple of things.  As @xsuchy mentioned above, this issue is ONLY with text within a `<alt>` tag.  It is NOT an issue if you are matching text outside of the `<alt>` tag.  In the latter case, we ignore all white space, which I think is what you would expect.

We added the `<alt>` tags to handle very specific cases where very specific phrases can be replaced with alternative text.  From the adoption of these tags and the limited number of issues for a rather complex expression (REGEX's), I think it has worked reasonably well.

The REGEXes we use are defined as a POSIX standard, so we need to adhere to that standard when creating the match (regex) strings.  The proposed solution adds the ability to handle additional lines using that standard.

The SPDX license matching guidelines are much more precise than word proximity algorithms used in tools like the the license compare tools.  The challenge with using such a proximity algorithm is that it may show a 99% match to a license that includes an important (very important) word like "this is NOT licensed under GPL" when compared to "this is licensed under GPL" and likewise show an 80% match to something we would consider a match using the license matching guidelines (e.g. removal of an optional preamble).

In the discussion above, we've conflated how XML handles white space - which is a distinct and different issue IMO.  I personally don't like the way XML handles white space, but the legal team decided on XML as the representation for their licenses - it would be a rather large task to switch to something else.  For the XML and white space, here's an article on XML and white space as it applies to XSLT transforms that may provide some independent tooling context: https://www.oracle.com/technical-resources/articles/wang-whitespace.html.

Summary - it is complicated.  You can control it in tools, but there is a tradeoff between using whitespace for readability and using whitespace that should be preserved in the XML files.  From the first day we started using XML, we've used white space for readability which implies the tools should not treat the literal white space as part of the output.  In the tooling the parser we use strips out the white space.

We could, of course, change that but we would need to review and update every one of the XML files to make sure we're not including what space that should not be part of the literal text.

To provide support for formatting, we do have white space handling tags and attributes in our XML schema (e.g. `<p>` and `<alt spacing=`.  We also made a change to use a text file for the license text which preserves the spacing - so a lot of effort has already gone into supporting various white space scenarios in the tooling.

I don't profess to be an XML / XSLT expert myself, but I do use it quite a bit in the tooling I support.

If anyone has a tooling solution that works around the XML constraints, I'd be happy to entertain a pull request in the [LicenseListPublisher](https://github.com/spdx/licenselistPublisher).

**Comment by goneall** [comment]
@xsuchy - I see you posted a response at the same time I was drafting mine - feel free to correct anything I missed.
