### ISSUE TITLE
New license request: Michigan/Merit Networks license

### ISSUE THREAD

**Issue by nmav** [spdx/license-list-XML#2287]
### How license meets inclusion principles

It is included in Fedora software and found during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/428

### License Name

Michigan-Merit HPND variant

### Suggested short identifier

MMN-HPND

### License or Exception?

license

### URL to license text

https://github.com/FreeRADIUS/freeradius-client/blob/master/COPYRIGHT#L62

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/radcli/radcli/
https://github.com/FreeRADIUS/freeradius-client/

### paste text of license here

[C] The Regents of the University of Michigan and Merit Network, Inc. 1992,
1993, 1994, 1995 All Rights Reserved

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted, provided
that the above copyright notice and this permission notice appear in all
copies of the software and derivative works or modified versions thereof,
and that both the copyright notice and this permission and disclaimer
notice appear in supporting documentation.

THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE REGENTS OF THE
UNIVERSITY OF MICHIGAN AND MERIT NETWORK, INC. DO NOT WARRANT THAT THE
FUNCTIONS CONTAINED IN THE SOFTWARE WILL MEET LICENSEE'S REQUIREMENTS OR
THAT OPERATION WILL BE UNINTERRUPTED OR ERROR FREE.  The Regents of the
University of Michigan and Merit Network, Inc. shall not be liable for any
special, indirect, incidental or consequential damages with respect to any
claim by Licensee or any third party arising from use of the software.

**Comment by jlovejoy** [comment]
This starts out with an HPND ish grant, but then adds some obligations, such as that the copyright notice and permission notice appearl in all... "derivative works or modified versions thereof" (sort of similar to HPND-Kevlin-Henney) as well as supporting documentation (similar to HPND_Pbmplus)

the disclaimer of warranties is also a bit different

given the above, I think this needs to be added as a new license /cannot be accommodated via markup

**Comment by swinslow** [comment]
+1 to @jlovejoy's comments. From searching on a few phrases in this license, I'm not seeing any existing licenses that are close enough to incorporate this one via markup.

Running a comparison against HPND, I think the differences (particularly in the disclaimers as well as in the grant language) are enough that I probably would not lump it into the "HPND variant" bucket. I realize these are very much shades of gray, so I don't feel strongly about this point and could be persuaded otherwise.

Either way, I'm certainly a +1 to add it to the license list as a new license. Perhaps the following for ID and name? (Looking a bit to [`NCSA`](https://spdx.org/licenses/NCSA.html) as an example.)

* ID: `UMich-Merit`
* Name: University of Michigan/Merit Networks License

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Michigan/Merit Networks License
## License ID
UMich-Merit
## XML markup
none at this time
## Notes:
This license starts with an HPND-like grant, but has additional obligations (similar to HPND-Kevlin-Henney and HPND_Pbmplus) and a different disclaimer of warranties.
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
