### ISSUE TITLE
Link in Fair.xml is obsolete

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2291]
Fair.xml includes the <crossRef> link to: http://fairlicense.org
However, this redirects to another site which appears to have nothing to do with the Fair license and does not contain the text of the Fair license.

**Comment by jlovejoy** [comment]
as per section C at https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md we generally don't update dead URLs. I did add the WebArchive link in #2304 

that being said, the original URL has been co-opted for various things since 2015 WebArchive capture, so maybe worth removing? (@goneall - I know you have an opinion on this, so tagging you!)

**Comment by richardfontana** [comment]
What is the purpose of capturing the URL in a field then? (I can understand preserving a dead or repurposed link if it's part of the actual license text.)

**Comment by goneall** [comment]
> What is the purpose of capturing the URL in a field then?

I use it in my software to correlate references to licenses.  If I'm scanning source files and it includes a URL reference to a license, I can compare that to the list of URLs in the field.  Even if the URL is no longer live, it is a pretty good indication that the license reference is to the SPDX license with the same URL listed in the field.

The nice thing about URLs is that they are unique - which really helps in the correlation.  Much better than a license name or a reference like "this software is licensed under the GPL".

This was discussed a couple years back and it turns out I'm not the only one using this technique of correlating URLs with SPDX listed licenses, so we decided to have a policy where we retain license URLs even if they are no longer active.

We actually implemented a lot of functionality in the license list publisher to annotate the URL with the current status to help readers understand if it is an active or dead link.

@richardfontana - hope that provide some good context.

**Comment by richardfontana** [comment]
@goneall Yes, but it seems to me in cases where the URL is known to redirect to some other unrelated site (as in this case) there should at least be a comment in the XML file warning of this.

Which made me check -- there are *no* comments in any of the SPDX XML files. Some of the problems I have been seeing in the use of XML and the use of regular expressions might be diminished somewhat if there were a practice of including explanatory comments in appropriate cases. I believe this project has made the mistaken assumption that its XML files are not supposed to be read by humans.

**Comment by goneall** [comment]
> But when it ends going to something entirely different... would having the webarchive link still help in the way you describe above?

@jlovejoy really good point - if the link goes to something entirely different then perhaps we should remove it since it may be ambiguous in terms of matching.  The webarchive doesn't work in my matching case, but it may for other license matchers.
