### ISSUE TITLE
Some XML files use "none" as the content of <standardLicenseHeader> and <notes>

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2293]
See, for example: 
[Baekmuk.xml](https://github.com/spdx/license-list-XML/blob/main/src/Baekmuk.xml#L8-L10)
[App-s2p.xml](https://github.com/spdx/license-list-XML/blob/main/src/App-s2p.xml#L8-L10C31)

I assume this is either incorrect or should be treated as incorrect. If there is no standard license header, the `<standardLicenseHeader>` either should not be present or should be empty.

**Comment by richardfontana** [comment]
A few others:
Arphic-1999.xml
mplus.xml
BitStream-Vera.xml

**Comment by jlovejoy** [comment]
I think I had noticed this before and tried to clean it up, but yes, if there is no Standard Header, the `standardLicenseHeader` tag should simply be removed and certainly, "none" is not needed. This may be a holdover from when the license submission form had the Standard Header as a field and then people might have put "none" which made its way into the XML file.  

In any case, we can clean these up as we find them.

**Comment by jlovejoy** [comment]
I've made a PR to fix these, but if you see others, please do the same. 

Looks like most if not all of these were from version 3.17 of the license list

**Comment by jlovejoy** [comment]
Looking into this a bit more, there are a bunch of licenses that have "none" in the Notes field (instead of just removing that tag and it being blank). I think this and the case of "none" showing up in the standardLicenseHeader goes back to the tooling that was used to do the bulk conversion from text files to xml. 

Leaving this issue open and updating the name as something we can pick away at.

Here is a list of the licenses that have "none" in Notes:
https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fspdx.org%2Flicenses%2F+%22notes+none%22&oq=site%3Ahttps%3A%2F%2Fspdx.org%2Flicenses%2F+%22notes+none%22&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg60gEINzg0NGowajeoAgCwAgA&sourceid=chrome&ie=UTF-8#ip=1

and for Standard License Header (some of which I already cleaned up and a shorter list):
https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fspdx.org%2Flicenses%2F+%22Standard+License+Header+none%22&sca_esv=595697517&ei=8tuWZbKtMd-D0PEPqZWRqAY&ved=0ahUKEwiy7pbtksSDAxXfATQIHalKBGUQ4dUDCBA&uact=5&oq=site%3Ahttps%3A%2F%2Fspdx.org%2Flicenses%2F+%22Standard+License+Header+none%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiPnNpdGU6aHR0cHM6Ly9zcGR4Lm9yZy9saWNlbnNlcy8gIlN0YW5kYXJkIExpY2Vuc2UgSGVhZGVyIG5vbmUiSL0EUMkCWMkCcAF4AJABAJgBRaABRaoBATG4AQPIAQD4AQL4AQHiAwQYASBBiAYB&sclient=gws-wiz-serp#ip=1

**Comment by richardfontana** [comment]
I think "None" in the `<notes>` field is less problematic; the problem with "none" in `<standardLicenseHeader>` is it signifies that the standard license header is the word "none".

**Comment by jlovejoy** [comment]
good point @richardfontana - and good reminder as to priorities ;)

**Comment by jlovejoy** [comment]
ok, so my Google search links above are actually not right. I dug around a bit and didn't see others with "none" in the Standard Header field. So I think we can merge the PR I made and close this. If we find more later, we can sort that out then.
