### ISSUE TITLE
New license request: HPND-INRIA-IMAG [was other-permissive-2]

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2319]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/447

> Another legacy license in the HPND tradition, but doesn't seem to match any previously known variant.

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

https://github.com/ppp-project/ppp/blob/master/pppd/ipv6cp.c#L75-L86

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/paulusmack/ppp

### paste text of license here

```
    This software is available with usual "research" terms
    with the aim of retain credits of the software. 
    Permission to use, copy, modify and distribute this software for any
    purpose and without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies,
    and the name of INRIA, IMAG, or any contributor not be used in advertising
    or publicity pertaining to this material without the prior explicit
    permission. The software is provided "as is" without any
    warranties, support or liabilities of any kind.
    This software is derived from source code from
    "University of California at Berkeley" and
    "Digital Equipment Corporation" protected by copyrights.
```

**Comment by jlovejoy** [comment]
copying license text here for easier comparison to HPND variants and comments:

`This software is available with usual "research" terms
with the aim of retain credits of the software. `
_this is not in any variant_    

`Permission to use, copy, modify and distribute this software 
for any purpose and without fee is hereby granted, 
provided that the above copyright notice and this permission notice appear in all copies,`
_all other HPND variants have "this software and its documentation" or just "this documentation". 
The obligation to that the copyright and permission notice "appear in all copies" is the same as the HPND-doc variants, but all the other HPND variants require both to appear in supporting documentation and/or only the copyright notice to appear in "all copies"_    

`and the name of INRIA, IMAG, or any contributor 
not be used in advertising or publicity pertaining to this material 
without the prior explicit permission.` 
_"pertaining to this material" instead of the usual "pertaining to the distribution of the software" 
"explicit" instead of "written" permission_

`The software is provided "as is" without any warranties, support or liabilities of any kind.`
_this is unique in that it adds "support or liabilities"_
    
`This software is derived from source code from "University of California at Berkeley" and "Digital Equipment Corporation" protected by copyrights.`
_this is also unique_

**Comment by jlovejoy** [comment]
looking at this again, I think there are enough differences, especially that it may warrant being added as a new license

**Comment by swinslow** [comment]
Are the first line ("This software is available with usual "research" terms...") and the last line ("This software is derived from...") really part of the "license"?

If we omit those lines, we get something that looks a lot more like an HPND-style license (though not an exact match for all the reasons @jlovejoy noted).

I'd be in favor of omitting the first and last line, and including the rest in a new HPND variant license, something like:

* ID: `HPND-INRIA-IMAG`
* Name: Historical Permission Notice and Disclaimer - INRIA-IMAG variant

**Comment by jlovejoy** [comment]
@swinslow - re the first line and last line - if you look at the license example, it does seem to appear altogether. And if it needs to be a new license anyway, then probably keep it all together?

**Comment by swinslow** [comment]
Discussed with @jlovejoy, we agreed to keep the first line but omit the last
