### ISSUE TITLE
Markup change in cryptsetup-OpenSSL-exception 

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2343]
I want to propose markup change in cryptsetup-OpenSSL-exception  exception to accommodate the wording in license used in ima-evm-utils package (that is shipped in Fedora). 

The text of the exception is https://sourceforge.net/p/linux-ima/ima-evm-utils/ci/master/tree/src/evmctl.c (line 25)

Here is screenshot of LicenseDiff for your convenience:
![Screenshot_20240124_172427](https://github.com/spdx/license-list-XML/assets/85769/809ff3a9-048b-4473-95b5-2aacb0356f03)

**Comment by jlovejoy** [comment]
I will have a look at this compared to my OpenSSL exception variants documentation...

**Comment by karsten-klein** [comment]
Since there are many modifications (while most are not substantial, but others are vague) I have a tendency to a separate exception.

Attached a matching result (full header); you can see the overlap with different exceptions. There is a lot of overlap with an AGPL-related exception. So also from this (and in order to capture the exceptions distinctly) I argue for a separation.

<img width="1082" alt="exception-matching" src="https://github.com/spdx/license-list-XML/assets/20038021/15f00cf4-efd0-4cf3-bb81-ce9c792ff2b6">

**Comment by jlovejoy** [comment]
discussed on 4/11 legal call - talked through the variations and potential meanings and came to the conslution that it is not substantively different. Accommodate via markup with the two options for each  item (not =+. )
