### ISSUE TITLE
New license request: fftpack-2004 (NCL) [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by nielsdg** [spdx/license-list-XML#2386]
**1.** License Name: FFTPACK License 2004
**2.** Short identifier: fftpack-2004
**3.** License Author or steward: Unknown
**4.** Comments: This license was discovered during license review in Fedora Linux. https://gitlab.com/fedora/legal/fedora-license-data/-/issues/475. It is used in the package pipewire.

The license is known to scancode-toolkit: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/fftpack-2004.LICENSE
**5.** License Request Url: http://tools.spdx.org/app/license_requests/349
**6.** URL(s): https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/modules/module-filter-chain/pffft.c?ref_type=heads#L1-52
**7.** OSI Status: Unknown
**8.** Example Projects: https://pipewire.org/

**Comment by jlovejoy** [comment]
this is very similar to BSD-3-Clause, except:
- it adds "use of the Software in source and binary forms" instead of just "use in source and binary forms" in the lead in
- the clauses are in a different order with what we normally consider the third clause appearing first
- the warranty of disclaimers has different wording: it adds a disclaimer of noninfringement, and then has less details as to exclusion of types of damages in the last part and also expands that to "use of other dealings" with the software

Given the above, I suspect we should add this as a new license

**Comment by karsten-klein** [comment]
**ScanCode**
* [fftpack-2004](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/fftpack-2004.LICENSE)

**{metæffekt} Universe**
* [Spherepack License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/README.md#:~:text=Spherepack%20License)

**Comments**
Seems we detected that licenses in another context (Spherepack); see also https://sources.debian.org/src/spherepack/3.3~a1-5/debian/copyright/

**Comment by jlovejoy** [comment]
interesting, so the license in link for the submission seems to got to piperwire project, and then it calls it the "FFTPACK license" in the file. Has the same 2004 copyright notice as what @karsten-klein found in Debian seems to inicate the file is part of spherepack. 

Doing a Google search on a phrase, turns up a few other places, but notably: https://www.ncl.ucar.edu/Download/NCL_source_license.shtml

So, I think @karsten-klein  idea as to using UCAR or NCAR in the name makes the most sense to me. Note that UCAR is essentially the umbrella organization under which NCAR sits (and happens to be located in my home town in a prominent location on a mesa below the flatiron rock formations and in a building of sandstone designed by the famous I.M Pei... but I digress...)

We do have a UCAR License already on the list - https://spdx.org/licenses/UCAR.html

Perhaps we could go with "NCL Source Code License" and "NCL" since that is the title on this page https://www.ncl.ucar.edu/Download/NCL_source_license.shtml
I would note that the license text there is slightly different than in FFTPACk in that "of the Software" is omitted at the above  link, whereas it is in the license text in the FFTPACK link:
"Redistribution and use of the Software in source and binary forms"

An alternative might be NCAR-CISL ?

I'd hesitate to use only NCAR as it seems likely we may see other licenses from UCAR/NCAR

**Comment by nielsdg** [comment]
@wtay : I don't know how well you remember the licensing of the file you copied in Pipewire here, but do you have some thoughts on it?

**Comment by swinslow** [comment]
@jlovejoy Given that the "NCL Source Code License" at https://www.ncl.ucar.edu/Download/NCL_source_license.shtml doesn't match exactly (e.g. doesn't have "of the Software" as you mentioned), I'm not sure we want to reference that for the ID / name.

Is there a reason not to just go with `FFTPACK` as ID and "FFTPACK License" as name, since that's how we see it being referred to in the wild?

**Comment by Pizza-Ria** [comment]
@swinslow "NCL Source Code License" at https://www.ncl.ucar.edu/Download/NCL_source_license.shtml is an awful lot closer than the original issues @jlovejoy brought up for BSD-3.  But I'm not sure if NCL-UCAR has an SPDX ID already?

**Comment by Pizza-Ria** [comment]
Redistribution and use **_[of the Software]_** in source and binary forms, with or without modification, **[is]****_are_** permitted provided that the following conditions are met:
-
•	Neither the names of NCAR's Computational and Information Systems Laboratory, the University Corporation for Atmospheric Research, nor the names of its **_[sponsors or]_** contributors may be used to endorse or promote products derived from this Software without specific prior written permission.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
NCL Source Code License
## License ID
NCL
## XML markup
yes, see comments above
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
