### ISSUE TITLE
New license request: AMD-Permissive [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by siddhesh** [spdx/license-list-XML#2395]
**1.** License Name: AMD Permissive License
**2.** Short identifier: AMD-Permissive
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in newlib sources and was found during SPDX review for the gcc package:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/480
**5.** License Request Url: http://tools.spdx.org/app/license_requests/351
**6.** URL(s): https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/sys/a29khif/_close.S;h=04f52ae00de1dafbd9055ad8d73c5c697a3aae7f;hb=HEAD
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceware.org/git/?p=newlib-cygwin

**Comment by jlovejoy** [comment]
+ 1 to add. 
As for id: discussed on 2/22 - thinking `AMD-newlib` would be a better option b/c this license seems to appear in various forms of newlib

**Comment by swinslow** [comment]
+1 as well, and I think `AMD-newlib` as ID and "AMD newlib license" as name. It seems like its usage in the wild is tied to newlib.

**Comment by karsten-klein** [comment]
**ScanCode**
license id: [amd-historical](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/amd-historical.LICENSE)

**{metæffekt} Universe**
license name: [Permission Terms (property; variant 001)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#:~:text=Permission%20Terms%20(property;%20variant%20001))
short identifier: PT-P-001

**Others**
We generalized the text with placeholders, since we found the same text with other right holders:

> This software is the property of &lt;copyright-holder&gt; which
> specifically grants the user the right to modify, use and distribute this
> software provided this notice is not removed or altered. All other rights
> are reserved by &lt;copyright-holder&gt;.
> 
> &lt;COPYRIGHT-HOLDER&gt; MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, WITH REGARD TO THIS
> SOFTWARE. IN NO EVENT SHALL &lt;COPYRIGHT-HOLDER&gt; BE LIABLE FOR INCIDENTAL OR CONSEQUENTIAL
> DAMAGES IN CONNECTION WITH OR ARISING FROM THE FURNISHING, PERFORMANCE, OR
> USE OF THIS SOFTWARE.

Furthermore, we do try to not qualify the license attributes in a fashion that it is legacy, outdated, historic. This is why we introduced the concept _Permission Terms_. There is quite a lot to say about the organization of these Permission Terms and naming conventions. Check the universe for further references. We keep managing, merging, splitting and organizing there continuously.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
AMD newlib License
## License ID
AMD-newlib
## XML markup
yes for name of copyright holder, see @karsten-klein notes above 
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
