### ISSUE TITLE
New license request: NCBI-PD [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Pandapip1** [spdx/license-list-XML#2419]
**1.** License Name: NCBI Public Domain Notice
**2.** Short identifier: NCBI-PD
**3.** License Author or steward: Unknown
**4.** Comments: NOTE: This is a bit of an edge case, since it isn't actually a license.

All definitive factors are met.

Non-definitive factors:

1. Works released into the public domain under 17 U.S. Code § 105 arguably meet the FSF Free Software Definition.
2. This does not meet factor two, since this is, by definition, applicable only to US government works.
3. The United States government produces quite a lot of work, a lot of which is in the form of code. As such, it is likely to be encountered.
4. Not applicable (meets factor 1)
5. Not applicable (there is no license steward)
**5.** License Request Url: http://tools.spdx.org/app/license_requests/357
**6.** URL(s): https://www.govinfo.gov/content/pkg/USCODE-2010-title17/pdf/USCODE-2010-title17-chap1-sec105.pdf
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/ncbi/sra-tools

**Comment by karsten-klein** [comment]
**ScanCode**
reference id: [public-domain](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/public-domain.LICENSE)
matched id: [ncbi](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ncbi.LICENSE)

**{metæffekt} Universe**
canonical name: [Public Domain](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Public-Domain:~:text=Public%20Domain)
short name: Public-Domain
Open CoDE similar license id: public-domain
markers: US Copyright Act Marker

**Comments**
- For me, this raises the question how we'd represent public domain content with an general SPDX license identifier. (Probably not desired)
- Since we have been modeling other public domain licenses in SPDX (e.g. NIST-PD) I would give it a +1 as NCBI-PD and not with focus on governmental work.

**Comment by Pandapip1** [comment]
The trick is that in this context, "public domain" means something entirely different than what people expect. It means that US government works don't have copyright protection inside the jurisdiction of the United States. **However,** international copyright laws mean that the United States government is automatically granted a copyright to those works. Without an additional license, those works can't be legally used outside the United States.

This is different from `CC0-1.0` or similar public domain licenses, since in those cases the copyright has been explicitly given up and no longer exists (except in Germany, because public domain doesn't exist in Germany, but CC0-1.0 fallbacks to a normal license then).

> For me, this raises the question how we'd represent public domain content with an general SPDX license identifier. (Probably not desired)

For my REUSE-compliant project, I've been using `CC0-1.0` to denote files that don't have copyrights (such as CI files and .gitignore files automatically generated using tools). It would be nice to have a way of saying "nobody owns the copyright here." But this is unrelated, since the US government *does* own the copyright. It's just that they can't legally use it.

> Since we have been modeling other public domain licenses in SPDX (e.g. NIST-PD) I would give it a +1 as NCBI-PD and not with focus on governmental work.

ACK. Is it possible to edit the request after it's submitted?

**Comment by Pandapip1** [comment]
I have updated the issue to change the request to NCBI-PD.

**Comment by jlovejoy** [comment]
I think this is related to a conversation that has come up repeatedly on the mailing list, including recently! See https://lists.spdx.org/g/Spdx-legal/topic/105158733#3538

@Pandapip1 - is the text you have in the PR something that is actually used (verbatim) by the US Gov't?

**Comment by Pandapip1** [comment]
Yes the text itself is verbatim. I only adjusted the formatting.

**Comment by swinslow** [comment]
+1 to add this to the license list. Despite being a public domain notice, it has a defined text and appears to be widely used by NCBI projects (see [GitHub search](https://github.com/search?q=%22PUBLIC+DOMAIN+NOTICE%22+%22National+Center+for+Biotechnology+Information%22&type=code)). And we've added specific public domain notices previously for widely-used, fixed texts (e.g., [SQLite's `blessing`](https://spdx.org/licenses/blessing.html).

Taking a look at some of those search results, I see a few variations to the text for some projects:

1. Some omit the "With the exception of certain third-party files summarized below" at the start
2. Some use "software/database" instead of "software" in the 1st and 3rd sentences
3. Some use "the authors'" (single quote after s) where others use "the author's" (single quote before s)
4. Some say "duties as a United States Government employee" where others say "duties as United States Government employees"
5. Some say "author" instead of "authors" in the final sentence

I'm comfortable with all of these being handled via `<optional>` or `<alt>` text markup in the XML file. I don't think any of these are substantive differences, and I think they can all be appropriately grouped together into a single ID.

@Pandapip1's suggestion of `NCBI-PD` for ID and "NCBI Public Domain Notice" as name seems appropriate to me.

**Comment by jlovejoy** [comment]
agree with @swinslow's assessment above and +1 to add

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

NCBI Public Domain Notice

## License ID

`NCBI-PD`

## XML markup

As noted above

## Notes

Mention US government work / public domain

## Next steps ##

@swinslow to prepare revised PR based off of #2433

**Comment by Pandapip1** [comment]
I also found this variation, which omits the FAQ entirely: https://github.com/ncbi/datasets/blob/master/LICENSE.md

**Comment by Pandapip1** [comment]
#2433 has been updated and should be merge-able.
