### ISSUE TITLE
Request to rename mpich2 license to mpich

### ISSUE THREAD

**Issue by raffenet** [spdx/license-list-XML#2454]
With its 3.0 release in 2012 (https://www.mpich.org/2012/12/20/mpich-3-0-released/), the MPICH2 project renamed itself to MPICH. The mpich2.xml license has the correct text, except for bumping the year 2020->2024. I am wondering if a rename is appropriate?

See license in upstream: https://github.com/pmodels/mpich/blob/main/COPYRIGHT

I've prepared a branch with an update and rename here: https://github.com/raffenet/license-list-XML/commit/e30bdc2525f2976053d408c011baf9bfa5be224b

**Comment by swinslow** [comment]
Hi @raffenet, thanks for reaching out on this.

As a rule, we don't change existing license IDs once they are adopted / released, since this would break references for folks who have already been using the old identifier up to now.

One thing we could do would be to add a `<notes>` tag within the `<license>` section, with a short plain text description of the fact that the underlying project changed its name in 2012. That text would then show up on the [license list entry page](https://spdx.org/licenses/mpich2.html) under the "Notes" section. Would that be helpful for you?

Regarding the copyright year change, thanks for flagging and no need to revise the license text for that. Because the copyright notice is within the `<copyrightText>` tag, it's already treated as replaceable text for matching purposes (see [the matching guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b11-copyright-notice) for more details).

**Comment by raffenet** [comment]
> As a rule, we don't change existing license IDs once they are adopted / released, since this would break references for folks who have already been using the old identifier up to now.
> 
> One thing we could do would be to add a `<notes>` tag within the `<license>` section, with a short plain text description of the fact that the underlying project changed its name in 2012. That text would then show up on the [license list entry page](https://spdx.org/licenses/mpich2.html) under the "Notes" section. Would that be helpful for you?

Yes, that sounds like a good idea.

> Regarding the copyright year change, thanks for flagging and no need to revise the license text for that. Because the copyright notice is within the `<copyrightText>` tag, it's already treated as replaceable text for matching purposes (see [the matching guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b11-copyright-notice) for more details).

Thanks for the info!

**Comment by jlovejoy** [comment]
@swinslow - assigning this one to you, since you already made a suggestion :)
