### ISSUE TITLE
New license request: Ubuntu-font-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xnox** [spdx/license-list-XML#2479]
**1.** License Name: UBUNTU FONT LICENCE v1.0
**2.** Short identifier: ubuntu-font-1.0
**3.** License Author or steward: Canonical
**4.** Comments: Ubuntu Font License is very similar to SIL Open Font Licence (OFL) version 1.1 and is used by popular ubuntu-font packaged in many distributions.

Also note the differences with SIL OFL license listed https://ubuntu.com/legal/font-licence/differences
**5.** License Request Url: http://tools.spdx.org/app/license_requests/369
**6.** URL(s): https://ubuntu.com/legal/font-licence, https://assets.ubuntu.com/v1/81e5605d-ubuntu-font-licence-1.0.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://design.ubuntu.com/font

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Ubuntu Font License 1.0](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[u]/README.md#user-content-Ubuntu-Font-License-1.0:~:text=Ubuntu%20Font%20License%201.0)
short name: Ubuntu-Font-1.0
markers: No Warranty Marker
category: Ubuntu Font License
ScanCode reference id: [ubuntu-font-1.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ubuntu-font-1.0.LICENSE)
OSI status: _none_
Open CoDE status: approved
Open CoDE approved license id: ubuntu-font-1.0 (ScanCode)

**ScanCode**
matched id: [ubuntu-font-1.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ubuntu-font-1.0.LICENSE)

**Comment**
+1 to add.

**Comment by Pizza-Ria** [comment]
@karsten-klein The example project seems to be a promotional page for the font itself.  But I did find a list of usage in [Wikipedia - Ubuntu typeface](https://en.wikipedia.org/wiki/Ubuntu_(typeface)) that looks legitimate enough for me to +1.

**Comment by copernicat** [comment]
+1 to add, I was especially persuaded by @Pizza-Ria's evidence, as that was a concern I also had.

**Comment by jlovejoy** [comment]
it is used by Canonical for the Ubuntu font, which is a popular font and has been around for some time.

+1 to add as well

**Comment by richardfontana** [comment]
This license is significantly different from the SIL OFL, IMO. Not that that makes a difference. 

Fedora reviewed this license long ago and classified it as "bad" under the pre-SPDX ("Callaway") system.

**Comment by xnox** [comment]
> This license is significantly different from the SIL OFL, IMO. Not that that makes a difference.
> 
> Fedora reviewed this license long ago and classified it as "bad" under the pre-SPDX ("Callaway") system.
> 
> I am not sure this license meets the license inclusion guidelines.

Fonts, unlike source code, have different inclusion/embedding properties. The font license in question allows unrestricted usage as a font; with any ambiguity w.r.t. trademarks & wordmarks that are created with said font. SPDX list of licenses already has many other licenses with similar target scope - from https://spdx.org/licenses/ see many Adobe, Glyph, Font licenses which are not OSI/FSF approved and yet are useful to document with SPDX as being included along with document producing software (SASS word processing / SASS PDF software) and similar. As it is one of the very few fonts that allows it to be used in such contexts - hence google docs offers it as one of the stock fonts; as well as a few other opensource sass software.

If inclusion guidelines have changed, and existing licenses are no longer suitable to be listed - will existing Font/Glyph licenses get dropped from the SPDX license list? I do agree that none of the font/glyph licenses in the SPDX list should ever be encouraged to be used for programming language source-code.

At the moment, in Wolfi OS, we are using custom Licenseref- for this license. But given how many different distributions ship this font, there is value in having a common identifier for this license, just like all other popular font licenses are in the license list today.

**Comment by swinslow** [comment]
One preliminary note: The bullet numbering is different for the [website version](https://ubuntu.com/legal/font-licence) vs. the [plain text version](https://assets.ubuntu.com/v1/81e5605d-ubuntu-font-licence-1.0.txt). (e.g., section 2.3.1 vs. 2.c.i)

That isn't a problem for SPDX matching purposes, since we ignore bullet and outline numbers under the [matching guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b8-bullets-and-numbering). But assuming we do add this one, I'd suggest we use the plain text version. And I'd suggest Canonical might want to fix their website version  ;-)

Below is my take on applying the SPDX [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md) to this one. 

= = = = =

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [X] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [X] Yes => as described above, similar in some aspects to the OFL family of license, but does not match anything currently on the list (e.g., didn't see anything currently on the list with a defined term for "Substantially Changed").
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [ ] No
    - N/A => font license, not a software license
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [X] Yes => as far as I can tell from this thread, this one's been around for some time
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No
    - Unknown => Not sure if anyone from Canonical has indicated this, but given that the license is already versioned, I'm less concerned about this

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [ ] No
    - Hard to say:
      - Particularly given that we don't have any definitions on the list in the [inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md) that directly address fonts. Perhaps the [Free Cultural Works](https://freedomdefined.org/Definition) definition would be the closest?
      - From a very back-of-the-envelope "is it open-source-ish" analysis, the main provisions that gives me pause here are 2(a), which prohibits renaming the unmodified font; and 2(c), which requires modified versions of the font which are not "Significantly Changed" to _retain_ the name of the original version together with adding a "derivative X" element for the new work.
        - Is this consistent with typical open source principles? I tend to think not, since it imposes specific requirements on trademark usage and branding. (It's common to see licenses that _prohibit_ misuse of the licensor's trademarks; but I don't recall another license offhand that _mandates_ use of the licensor's trademark for the derivative work's name, in addition to retaining e.g. attribution notices.)
      - Another element that jumped out at me is that the only right explicitly granted in the "Permissions and Conditions" section is to "propagate" the font, which is a term defined with a definition that looks like the GPL-3.0 approach to "propagate" (note that I haven't actually compared them). One could argue about whether the effect of this is to allow distributing but _not_ allow modifying or using the font. Either way, the Preamble indicates the intent that the license allows use and modification, so while I might not like the specific drafting choice, I think the intent is relatively clear.
      - Finally, the other element I note is that the license does not require _documents_ created using the font to be published under this license, _unless_ the "primary purpose of the document is (...) to be a vehicle for the distribution of the fonts." I think this is vaguely equivalent to OFL's prohibition on selling the font alone. The FSF has [described that prohibition in OFL](https://www.gnu.org/licenses/license-list.html#SILOFL) as not affecting its status as a free font license. I don't know if I would view it the same way here, but this feels relatively minor to me for _SPDX_ license inclusion purposes.
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [X] Yes => other than the name, I don't see anything specific to Ubuntu or Canonical in here.
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [X] Yes => although I haven't dug into examples, I would guess that inclusion in the Ubuntu distributions of Linux is likely sufficient to satisfy this factor.
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [X] Yes => this is the fallback for "OK, under factor 1 above I'm not sure this is a fully free license; but notwithstanding that, it does primarily facilitate free distribution of content with limited restrictions." Comparable to how a source-available license in the software context might not be fully free / open, but still permit redistribution with limited restrictions.
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No
    - Don't know

## Summary of factors, outcome, comments

Despite my hesitancy around being able to say whether this is truly a "free" or "open" license for "Other factor" 1 above, I do think on balance the remaining factors point in favor of adding it to the list. So I'm a slightly cautious +1 to add.

For the name, I would go with "Ubuntu Font License v1.0" (same as proposed above, but not all-caps).

For the ID, I would tend to go with "Ubuntu-font-1.0" (same as proposed above, but capitalizing the first letter of "Ubuntu" since I believe that's how it's typically rendered?)

**Comment by xnox** [comment]
> "Significantly Changed" to _retain_ the name of the original version together with adding a "derivative X" element for the new work.
> * Is this consistent with typical open source principles?

I think it is unfortunate that font names is ABI/API. These clauses together ensure that one can create additional glyphs of the same style, expand the font, do bugfixes, whilst preserving compatibility with rendering all existing documents. Unless one derives too much (new font or vandalism) to ensure a new name is picked to prevent miss-rendering documents. Whilst this make sense from typography metric compatibility and rendering point of view - it is super vague legal wise.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Ubuntu Font License v1.0
## License ID
Ubuntu-font-1.0
## XML markup
none
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
