### ISSUE TITLE
New license request: NMAP Public Source License

### ISSUE THREAD

**Issue by ataraxus** [spdx/license-list-XML#2492]
### How license meets inclusion principles

License is needed due to image scanning of RHEL UBI images with installed ncat

Also see discussion here: https://github.com/spdx/license-list-XML/issues/1121

### License Name

Nmap Public Source License

### Suggested short identifier

NPSL

### License or Exception?

license

### URL to license text

https://nmap.org/npsl/

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://catalog.redhat.com/software/containers/ubi9/ubi/615bcf606feffc5384e8452e

### paste text of license here

https://nmap.org/npsl/

**Comment by karsten-klein** [comment]
Just for clarity... The license you are referring to is https://svn.nmap.org/nmap/LICENSE (Nmap Public Source License Version 0.95). https://nmap.org/npsl/ itself is not a license, rather explanatory text.

Please also note that the original request referred to version 0.92 (instead of the current 0.95 version of the license). Please also mind that versions 0.93 and 0.94 have been recorded as well.

There is also:
- the Nmap OEM license: https://nmap.org/oem/
- the annotated NPSL icense: https://nmap.org/npsl/npsl-annotated.html
- the previous/former license: https://nmap.org/misc/nmap-v7.80-license.txt 

We need to determine the scope of this request.

**Comment by karsten-klein** [comment]
With respect to the 0.95 version:

**{metæffekt} Universe**
canonical name: [Nmap Public Source License 0.95](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[n]/README.md#user-content-Nmap-Public-Source-License-0.95:~:text=Nmap%20Public%20Source%20License%200.95)
short name: NPSL-0.95
markers: Display Obligation Marker, Incompatible with Secondary License Marker, No Patent Rights Granted Marker, Patent Information Marker
category: NPSL
ScanCode reference id: [npsl-exception-0.95](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/npsl-exception-0.95.LICENSE)
OSI status: _none_

**Comment by swinslow** [comment]
Note that I initially marked this as "used in major distro" based on Fedora including Nmap -- but it's possible that might actually be Fedora using an older version of Nmap under a prior license; see https://fedoraproject.org/wiki/Licensing/Nmap. So I'm removing that label for the moment as this may need a bit more digging.

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [X] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [X] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [X] Yes
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [X] Yes => note that the last time that Nmap licenses were reviewed, in #1121, there were multiple different versions that were being published by the license steward in parallel with the review; and this was one of the primary reasons for rejecting the earlier version submission.
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [X] Yes => well, I don't believe this one is being submitted by the license author; but I believe the 0.95 version has been in place since sometime between Dec. 2022 and Sept. 2023, see https://web.archive.org/web/20230902051716/https://nmap.org/npsl/npsl-annotated.html. Regardless, it is versioned so I don't have any reason to believe that the text to version 0.95 will itself be changing.
    - [ ] No

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [X] No => or at least probably not; see my comments below
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [X] No => Specifically structured for Nmap, including naming them as the "Licensor" and including terms that are specific to Nmap's products in sections 3 and 10
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [X] Yes => Nmap is widely used and encountered in various Linux distributions, albeit not necessarily under _this_ Nmap license. Gentoo appears to be [using this license version](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/nmap/nmap-7.95.ebuild#n36). @ataraxus indicated that Red Hat is, though I can't view that from the link that was shared in this submission. The [Fedora wiki](https://fedoraproject.org/wiki/Licensing/Nmap) seems to suggest that Fedora does not use this version.
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes
    - [ ] No
    - [X] Maybe? see my comments below regarding the open-source-ish-ness of this one...
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No
    - [X] Unknown => I don't think we have any input on this

## more details on "is it open source"

This license appears to take GPL-2.0, and make "exceptions, clarifications, and additions" to it. Those additions include among other things the following:

* concepts based on licenses like Apache-2.0 (e.g. around "Contribution", "Contributor", and others) and OSL-3.0 (e.g. External Deployment);
* concepts similar to some SPDX exceptions (e.g. section 11 permitting linking with OpenSSL);
* something that appears to sort of be functioning as a CLA license grant-back to Nmap as Licensor (see section 4, first paragraph);
* an extremely broad reading of what constitutes a "derivative work" (see section 3); and
* Nmap product-specific terms (see in particular section 10)

The last two items in particular make it hard for me to look at this and comfortably call it an open source license. For the derivative works definition, I haven't dug deeply into it, but I don't think it aligns with how OSI has viewed similar licenses. For example, it appears to deem something to be a derivative work because it reads an Nmap data file or executes a script or "helper program" to perform certain actions. The intent seems to be to then deem any of those things to be subject to copyleft requirements. To me, that loosely feels like it's trying to do something similar to the super-broad copyleft effect that (I think?) led to the OSI withholding approval for SSPL-1.0.

Similarly, the Nmap product-specific terms in section 10 give me pause. It appears to be saying that it is _not possible_ for a recipient of the Nmap Windows builds to redistribute them as-is. If I'm understanding correctly, that makes it a straightforward [OSD 1](https://opensource.org/osd) violation. (Maybe it can be an open source or open-source-ish license for non-Windows builds?)

In any case, for me I think it's unlikely that this meets "Other factor" 1; and depending on your views on the Nmap Windows build language, it might not meet "Other factor" 4 either. I'd greatly welcome others' thoughts on this one.

## Summary of factors, outcome, comments

This review is a bit of a mess, unfortunately, because of the complications for what parts of this license we're actually taking into account.

As applied to Nmap Windows builds, no, I don't think it meets Other factor 1 or even Other factor 4. But looking at other Nmap products where section 10 isn't relevant (e.g. Linux builds), I think that it _probably_ doesn't meet Other factor 1 but would satisfy Other factor 4.

Taking that, together with its use in at least _some_ Linux distros like Gentoo and its progeny, I'm a hesitant +1 to add this to the License List. But I'd really like to have others' thoughts on this as well, because I'm not at all convinced on this as the correct answer here.

**Comment by richardfontana** [comment]
@swinslow I think this assessment is premature because it is not clear what license text @ataraxus is referring to in this request.

**Comment by swinslow** [comment]
@richardfontana That's a fair point!

@ataraxus Are you referring specifically to Nmap Public Source License **Version 0.95**, which is currently (at this moment) available at https://svn.nmap.org/nmap/LICENSE; or a different version of the Nmap license?

**Comment by richardfontana** [comment]
From an SPDX-matching-guidelines-ish perspective, I believe there are four distinct Nmap licenses. I finally attempted to go through all of them from the Fedora standpoint. See my summary here:
https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/Q67UGCHSCKCLJOVOHSLYU4AERAHBS5YE/

**Comment by richardfontana** [comment]
I would add that while the Fedora conclusion is that all of these licenses are "not-allowed", and thus Fedora ordinarily wouldn't seek SPDX identifiers for them, one of them (what as far as I know is the original one) was treated by Fedora as "good" under the pre-SPDX system, and continues to be permitted under a policy exception. Given how confusing this collection of licenses is, and how widely used Nmap is, I wonder if there is a good justification for adding some or all of them to the SPDX license list to help clear up confusion.

**Comment by richardfontana** [comment]
@ataraxus since you referred to the RHEL UBI: My current position is that anything in any version of nmap in any version of the RHEL UBI should be under the license Fedora now calls `LicenseRef-Nmap`. You may be aware that the upstream maintainer of Nmap has granted permission to use the old license (what Fedora now calls `LicenseRef-Nmap`) for certain releases licensed under certain versions of the Nmap Public Source License. There is an error (or at least, it is arguably an error) in certain versions of RHEL which I'll try to get fixed, wherein the nominal license in the package is the license Fedora now calls `LicenseRef-NPSL-0.93`. I say it is arguably an error because we intend not to ship anything in Fedora or CentOS Stream/RHEL under any version of the NPSL and we intend to use any permission given by upstream to stay on `LicenseRef-Nmap`, the pre-NPSL license.

**Comment by ataraxus** [comment]
Hey guys, thanks for adding so much context to this. I thought this would be much more straight forward.... where i come from is, that i create SBOMs of our container and use DependencyTrack to evaluate them. DT doesnt know NPSL/NMAP hence i opened this issue. 

After having a closer look on whats installed exactly i would assume that its version 0.93 @swinslow which I want for my usecase: 

```
docker run -it --rm registry.access.redhat.com/ubi9/ubi

[root@ee6b8a611459 /]# dnf info nmap
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:11:42 ago on Sun Jul 21 10:47:31 2024.
Installed Packages
Name         : nmap
Epoch        : 3
Version      : 7.92
Release      : 1.el9
Architecture : x86_64
Size         : 24 M
Source       : nmap-7.92-1.el9.src.rpm
Repository   : @System
From repo    : ubi-9-appstream-rpms
Summary      : Network exploration tool and security scanner
URL          : http://nmap.org/
License      : Nmap


head /usr/share/licenses/nmap/LICENSE 
Nmap Public Source License Version 0.93
For more information on this license, see https://nmap.org/npsl/

0. Preamble

The intent of this license is to establish freedom to share and change
the software regulated by this license under the open source model. It
```

**Comment by richardfontana** [comment]
Note though that the "Nmap" in the License: field refers to a different license. At this moment the RHEL 9 package for nmap 7.92 has contradictory license information. If the goal is to get the actually applicable license recognized as an SPDX identifier, then it should be Fedora's LicenseRef-Nmap. If the goal is to get the text of NPSL 0.93 recognized as an SPDX identifier, even if Red Hat replaces it with LicenseRef-Nmap, then it should be Fedora's LicenseRef-NPSL-0.93.

**Comment by ataraxus** [comment]
to be honest, both would be great ^^ but i guess i would need to open an issue @ RedHat or Fedora?

**Comment by jlovejoy** [comment]
discussed on 7/25 call - there seems to be a lot of confusion over this license due to the different variants. Agreed that we should add all variants or none on the rationale that adding one (not all) could potentially add to the confusion. This would require an analysis for each version.
- As to the original version (https://fedoraproject.org/wiki/Licensing/Nmap) - this is really not a standalone license, but meant to augment the GPL, in which case, the SPDX exception inclusion guidelines would be applicable (and which it likely does not meet). This might mean that would be represented by `GPL-2.0-only WITH AdditionRef-Nmap`
- other variants would need individual issues and review, which we may hold off on for now, unless someone wants to open those issues

(The issue noted above about what version Red Hat included is separate to the question of inclusion on SPDX License List)

**Comment by jlovejoy** [comment]
marking as "not accepted" but really we are closing this in lieu of someone wanting to submit requests for the various individual versions, as noted in comment above
