### ISSUE TITLE
New license request: erlang-otp-linking-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by laf0rge** [spdx/license-list-XML#2495]
**1.** License Name: AGPLv3 Erlang/OTP linking exception
**2.** Short identifier: erlang-otp-linking-exception
**3.** License Author or steward: Harald Welte
**4.** Comments: * The exception is not a stand-alone license, but an additional permission to AGPLv3
* it grants an additional permission
* it does not impose additional restrictions
* it is used since 2012 in a variety of (at least) Osmocom projects, see https://erlang.org/pipermail/erlang-questions/2012-May/066355.html for the original proposal
**5.** License Request Url: http://tools.spdx.org/app/license_requests/371
**6.** URL(s): https://gitea.osmocom.org/erlang/osmo_ss7/src/commit/2286c1b8738d715950026650bf53f19a69d6ed0e/src/ss7_links.erl#L20
**7.** OSI Status: Approved
**8.** Example Projects: https://gitea.osmocom.org/erlang/osmo_ss7, https://gitea.osmocom.org/erlang/osmo-epdg

**Comment by swinslow** [comment]
Text of requested license exception to add:

```
If you modify this Program, or any covered work, by linking or
combining it with runtime libraries of Erlang/OTP as released by
Ericsson on http://www.erlang.org (or a modified version of these
libraries), containing parts covered by the terms of the Erlang Public
License (http://www.erlang.org/EPLICENSE), the licensors of this
Program grant you additional permission to convey the resulting work
without the need to license the runtime libraries of Erlang/OTP under
the GNU Affero General Public License. Corresponding Source for a
non-source form of such a combination shall include the source code
for the parts of the runtime libraries of Erlang/OTP used as well as
that of the covered work.
```

**Comment by swinslow** [comment]
This exception is close to [`GPL-3.0-linking-source-exception`](https://spdx.org/licenses/GPL-3.0-linking-source-exception.html), taking into account the replaceable text bits of that exception.

However, it does add an additional phrase that isn't present in `GPL-3.0-linking-source-exception`:

> . . . without the need to license the runtime libraries of Erlang/OTP under the GNU Affero General Public License.

I'm not inclined to add that phrase as markup to `GPL-3.0-linking-source-exception`, since that exception is [based on a template taken from the FSF's FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs).

So I'm +1 to add this as a new exception on the license list.

I'm fine with the identifier proposed above (`erlang-otp-linking-exception`).

For the full name of the exception, I'd suggest tweaking it slightly to something like "Erlang/OTP AGPL-3.0 Linking Exception", for alignment with similarly-named items on the [Exceptions List](https://spdx.org/licenses/exceptions-index.html) (e.g. "OCaml LGPL Linking Exception",

**Comment by laf0rge** [comment]
I just noticed: The http:// URLs in the exception text should probably be replaced with https:// by now (they work as https, as I checked).  I'll update them in the source code shortly.

**Comment by swinslow** [comment]
Thanks @laf0rge! For SPDX purposes, it doesn't matter whether it is http or https; the [SPDX matching guidelines (B.14)](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b14-http-protocol) state that they should be treated as equivalent for license matching purposes. So it's fine to update them in the license text, but it shouldn't affect what gets added to the SPDX License List itself.

**Comment by copernicat** [comment]
+1 I agree with @swinslow's analysis.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Erlang Linking Exception (AGPL; with source provision obligation)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[e]/README.md#user-content-Erlang-Linking-Exception-(AGPL;with-source-provision-obligation):~:text=Erlang%20Linking%20Exception%20(AGPL;%20with%20source%20provision%20obligation))
short name: Linking-Exception-AGPL-source
markers: Extended Source Obligation Marker
category: Erlang Linking Exception
OSI status: _none_

**Comment**
These multiple relationship license give me headaches. There is the library (here Erlang/OTP), the license (here Erlang Public License) of the library, a secondary license (here AGPL) and an addition obligation.
Looking forward to the discussion on this one in the legal call. 
Again a +1 from my side to add as separate exception due to to the induced risk of the extensive source provisioning obligation.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Erlang/OTP AGPL-3.0 Linking Exception
## License ID
erlang-otp-linking-exception
## XML markup
I don't think we need any at this point. Can always add for the name later if other entities use this
## Notes:
This exception is generally used with AGPL-3.0
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
<waves> @laf0rge - good to "see" you here!!

**Comment by karsten-klein** [comment]
I just observed, that the text of https://spdx.org/licenses/GPL-3.0-linking-source-exception.html seems to be missing an important part. It misses the part that would be substituted in the case here by 

> without the need to license the runtime libraries of Erlang/OTP under the GNU Affero General Public License.

The text of https://spdx.org/licenses/GPL-3.0-linking-source-exception.html appears to be cut off. Can you confirm. I can surely derive an issue.

**Comment by swinslow** [comment]
Hi @karsten-klein, I think the sentence that you're referring to is one of the things that makes this erlang- exception different from the GPL- one. See the [discussion above](https://github.com/spdx/license-list-XML/issues/2495#issuecomment-2149569306). 

Either way, yes, if you think something is missing from [GPL-3.0-linking-source-exception](https://spdx.org/licenses/GPL-3.0-linking-source-exception.html) then I'd say please file a separate issue for that discussion.
