### ISSUE TITLE
SPDX should deprecate `Net-SNMP`

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2506]
The SPDX identifier `Net-SNMP` is a single identifier meant to cover the exact contents of the COPYING file of the Net-SNMP project as they existed at a particular point in time, frozen on this webpage for the project: http://www.net-snmp.org/about/license.html

It is not uncommon for relatively old non-copyleft projects to have (at some point in their history) attempted to collect a set of relevant disparate license texts associated with multiple copyright holders into one LICENSE or COPYING file. Some such projects may further attempt to conceptualize this collection of licenses as "the license" of the project. I think there are other examples of this found in the SPDX license list, generally cases where earlier in SPDX's history, SPDX contributors regarded website presentations of project licenses as definitive. In more recent times I think SPDX has tended to look more closely at source code distributions as "primary sources" when deciding what to add to the SPDX license list.  

Anyway, in this case, the frozen state of the Net-SNMP COPYING file consists of a set of nine short permissive licenses associated with different copyright holders, most of which match `BSD-3-Clause` exactly, two of which might match `BSD-3-Clause` or might have minor substantive variations, and one of which probably matches `HPND`.

The COPYING file for Net-SNMP has continued to evolve since the time that its contents were recorded on the Net-SNMP website and the Net-SNMP identifier was added to the SPDX license list. Five new licenses have been added.  So today the COPYING file in its entirety does not match SPDX `Net-SNMP`. 
https://github.com/net-snmp/net-snmp/blob/master/COPYING

Today, SPDX's general approach seems to be to atomize single-file collections of disparate license texts rather than attempt to create "collection licenses" unique to particular projects. It is likely that any individual licenses in `Net-SNMP` that are not already on the SPDX license list will be found in old packages and thus may get individually added to the SPDX license list in the future. The approach taken in `Net-SNMP` is inconsistent with current SPDX practice, therefore, and is also in conflict with SPDX's mission to promote standardization of license identifiers.

**Comment by swinslow** [comment]
+1 to deprecating the `Net-SNMP` identifier, for the reasons @richardfontana described above.

I've run redlines for each of the 9 "parts" specified in `Net-SNMP`, and confirmed that they each individually match something that's separately on the License List,  with the caveats noted below:

* Part 1 matches [`MIT-CMU`](https://spdx.org/licenses/MIT-CMU.html)
* Parts 2-9 match [`BSD-3-Clause`](https://spdx.org/licenses/BSD-3-Clause.html)

For **Part 4**, note that it includes the following lead-in language:

> Use is subject to license terms below.
> This distribution may include materials developed by third parties.
> Sun, Sun Microsystems, the Sun logo and Solaris are trademarks or registered trademarks of Sun Microsystems, Inc. in the U.S. and other countries.

I wouldn't view this language as being relevant for license matching purposes. But in any case, if someone decided they _did_ view it as relevant, they could continue to use `Net-SNMP` as a deprecated identifier (since it'll remain on the list, just deprecated).

For **Part 7**, note that it uses the following formulation in the (ever-annoying) third clause of BSD-3-Clause (emphasis added):

> * The name of Fabasoft R&D Software GmbH & Co KG **or any of its subsidiaries, brand or product names** may not be used to endorse or promote products derived from this software without specific prior written permission.

As a formalistic matter, this bit matches the first regex in that part of BSD-3-Clause, so this is a match. And I don't feel concerned about having "any of its subsidiaries, brand or product names" picked up, I don't think that would warrant a separate ID.

**Comment by jlovejoy** [comment]
Thanks @richardfontana and @swinslow for the analysis here!  

I agree that deprecating the `Net-SNMP` id is a good idea at this point, given how the "stack" of licenses has changed and it can be accommodated with a license expression.

I did some digging on the history of when it was originally added in Jan 2017 for v2.6. How to deal with this as a stack or not was heavily discussed back then as well. For completeness here, adding some links from back then:
- https://lists.spdx.org/g/Spdx-legal/topic/22080738#msg1512 and https://wiki.spdx.org/view/Legal_Team/Minutes/2016-08-04
- https://lists.spdx.org/g/Spdx-legal/topic/22080775#msg1604
- https://lists.spdx.org/g/Spdx-legal/topic/22080778#msg1622
- https://wiki.spdx.org/view/Legal_Team/Minutes/2016-12-22
- https://wiki.spdx.org/view/Legal_Team/Minutes/2017-01-05

**Comment by jlovejoy** [comment]
in terms of process, I think we should put an email out on the mailing list and also mention on the next call to make sure people are aware and because deprecating a license id is generally a big deal.

I would recommend updating the Note to read, something along the lines of:
`DEPRECATED: The Net-SNMP license id represented the license stack of 9 licenses found at https://net-snmp.sourceforge.io/about/license.html and net-snmp-5.6.2. Since then, more licenses have been added. Retaining this license id could consequently cause confusion and all of the licenses in the stack are already on the SPDX License List, thus can be identified with an SPDX license expression.`

**Comment by mkdolan** [comment]
The license history/archaeology capabilities on display here between the three of you are quite impressive. Considering everything else has gone the way of atomized, I also agree it seems more consistent to deprecate this one.

**Comment by karsten-klein** [comment]
+1 to deprecate.

**Comment by jlovejoy** [comment]
email sent to mailing list/open to discussion for July 11th call, but everyone on call had already commented. Mark to deprecate for next release and let people know on mailing list so there is time for any other opinions.
