### ISSUE TITLE
New license request: Boehm-GC-without-fee [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2512]
**1.** License Name: Boehm-Demers-Weiser GC License (without fee)
**2.** Short identifier: Boehm-GC-without-fee
**3.** License Author or steward: Unknown
**4.** Comments: During Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/530 we discovered in mariadb10.11
This license was originally discussed as a markup change in #2507 but was agreed to add as a new one.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/376
**6.** URL(s): https://github.com/MariaDB/server/blob/11.6/libmysqld/lib_sql.cc
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/MariaDB/server

**Comment by xsuchy** [comment]
License text:

```
 Copyright (c)  2000
 SWsoft  company

 Modifications copyright (c) 2001, 2013. Oracle and/or its affiliates.
 All rights reserved.

 This material is provided "as is", with absolutely no warranty expressed
 or implied. Any use is at your own risk.

 Permission to use or copy this software for any purpose is hereby granted 
 without fee, provided the above notices are retained on all copies.
 Permission to modify the code and to distribute modified code is granted,
 provided the above notices are retained, and a notice that the code was
 modified is included with the above copyright notice.
```

**Comment by swinslow** [comment]
+1 to add, and I'm fine with the proposed name and ID.

**Comment by swinslow** [comment]
Moving to 3.26.0 -- hoping we can get another +1 soon in order to get this merged quickly in the next release cycle.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [STLport License 4.5](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/README.md#user-content-STLport-License-4.5:~:text=STLport%20License%204.5)
short name: STLport-4.5
markers: No Warranty Marker
category: STLport License
ScanCode reference id: [stlport-4.5](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/stlport-4.5.LICENSE)
OSI status: _none_
Open CoDE status: approved
Open CoDE approved license id: stlport-4.5 (ScanCode)

**ScanCode**
matched id: [stlport-4.5](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/stlport-4.5.LICENSE)

**Comment**
+1 to add but with a more general name. I see at least three sources and I would not call it after one or the other. I don't have a good proposal other that Permission Terms No Fee / PT-no-fee. I would by the way omit "with" and "without" in all future license names, since these terms are too close to expression operators WITH.

**Comment by jlovejoy** [comment]
so, we have two +1 to add, but @karsten-klein brings up the ID issue. I'm not sure the "without fee" (or "no fee") is all that identifying.

Also not sure where Boehm-GC comes from? or STLport?  are these just some of the sources @karsten-klein mentions that use this license?

**Comment by jlovejoy** [comment]
discussed on 9/12 call - went over history re: naming and similar license and why this name (disregard my above comment)
given that history, I'm good with this name. 
make sure to add a note as to similarity to other license with similar name
