### ISSUE TITLE
New license request: DocBook-XML [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Lupphes** [spdx/license-list-XML#2515]
**1.** License Name: DocBook XML License
**2.** Short identifier: DocBook-XML
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora and was found during license review and backlink to this issue. It is used for docbook2X and docbook5-style-xsl.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/377
**6.** URL(s): https://gitlab.com/fedora/legal/fedora-license-data/-/issues/526
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/docbook/xslt10-stylesheets, https://sourceforge.net/projects/docbook2x/files/

**Comment by swinslow** [comment]
I'm +1 to add this, as a historical modified MIT-style license with two additional clauses that generally relate to avoiding misuse of names / marks.

Regarding the name / ID:

* I don't know this space, but some of the uses / references I'm finding relating to this license ([example 1](https://github.com/docbook/xslt10-stylesheets/blob/master/xsl/webhelp/docsrc/readme.xml), [example 2](https://github.com/docbook/xslt10-stylesheets/blob/master/xsl/COPYING), [example 3](https://www.maplesoft.com/support/help/maple/view.aspx?path=License/DocBook), [example 4](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-56/Whats-New/licenses/docbook-xsl.txt)) appear to refer to this as part of "xsl" or "docbook-xsl" rather than "DocBook XML".
* Given that, maybe an ID of `DocBook-XSL` and full name "DocBook XSL License"? Or please feel free to let me know if that's not preferable here given the technical space for this one.

Formatting notes for markup:

* the `<quote>...</quote>` tags around "Software" in the second line should presumably just be replaced with standard quotation marks.
* in some of the examples, there's a "Warranty" line just above the final paragraph. I'd suggest including that with `<optional></optional` tags in the markup. (Some, but not all, examples also have hyphens that appear under "Warranty", so that should probably also be its own optional line as well.)
* I haven't done this yet, but probably worth running redlines on a few of the examples above, to see if there's any other differences that I'm missing from a very quick skim  :)

**Comment by Lupphes** [comment]
I agree with the naming,  XSL is probably more specific about what it is.

**Comment by richardfontana** [comment]
> Regarding the name / ID:
> 
>  * I don't know this space, but some of the uses / references I'm finding relating to this license ([example 1](https://github.com/docbook/xslt10-stylesheets/blob/master/xsl/webhelp/docsrc/readme.xml), [example 2](https://github.com/docbook/xslt10-stylesheets/blob/master/xsl/COPYING), [example 3](https://www.maplesoft.com/support/help/maple/view.aspx?path=License/DocBook), [example 4](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-56/Whats-New/licenses/docbook-xsl.txt)) appear to refer to this as part of "xsl" or "docbook-xsl" rather than "DocBook XML".
> * Given that, maybe an ID of `DocBook-XSL` and full name "DocBook XSL License"? Or please feel free to let me know if that's not preferable here given the technical space for this one. 

I guess the overall project/technology/standard is "DocBook" and DocBook XML and DocBook XSL are different parts of that technology. I don't know offhand how that relates to the licenses used including this one. But there's more than one DocBook-specific license.

**Comment by jlovejoy** [comment]
just need to decide on name/id

**Comment by jlovejoy** [comment]
@richardfontana - to clarify your comment that there is more than one DocBook-specific license - my thought was that is why using something like DocBook-XSL would make sense. Did you have an opinion one way or another on that specific suggestions?

**Comment by Lupphes** [comment]
I'm unsure how to approach the name as I don't know how many versions of Docbook licenses or similar are out here, which can potentially clash with this one. I think that:

1. License Name: DocBook XLS License
2. Short identifier: DocBook-XLS

would make sense, and it could be used similarly in #2516 with a `schema` addition.

**Comment by OliverFendt** [comment]
+1 for the Name and Short identifier, suggested by @jlovejoy but will the following phrase be taken over unchanged?
(the <quote>Software</quote>)
I think this will not be a good idea because than we mix markup and content

**Comment by Lupphes** [comment]
I think the license should have a standard quote, not a markup.

Is there something that must be clarified before this license can be processed? What are the following steps for this?

**Comment by richardfontana** [comment]
The matching guidelines say
> B.6.4 Guideline: Quotes
Any variation of quotations (single, double, curly, etc.) should be considered equivalent.

I don't think it is clear that this extends to "<quote>" tags.

**Comment by jlovejoy** [comment]
thanks for pointing that out @OliverFendt - I think I see what is going on:
in some instances of the license text, there is a bunch of formatting type tags, see https://github.com/docbook/xslt10-stylesheets/blob/efd62655c11cc8773708df7a843613fa1e932bf8/xsl/docsrc/license.xml#L18 

I'm not sure why the <quote> tag got included but not the rest, but in any case, I think we can go with the plain text version, as seen at: https://github.com/docbook/xslt10-stylesheets/blob/efd62655c11cc8773708df7a843613fa1e932bf8/xsl/COPYING#L27

**Comment by swinslow** [comment]
+1 on using the plain text version with the quotes as shown in xslt10-stylesheets COPYING file from @jlovejoy's link above. 

It sounds like there's general agreement to use `DocBook-XSL` as ID and "DocBook XSL License" for the full name?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
DocBook XML License
## License ID
DocBook-XML
## XML markup
none (use text from link above, not what was in submission)
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
