### ISSUE TITLE
New license request: SMAIL-GPL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jopejoe1** [spdx/license-list-XML#2544]
**1.** License Name: SMAIL GENERAL PUBLIC LICENSE
**2.** Short identifier: SMAIL
**3.** License Author or steward: 
**4.** Comments: Found while checking licenses in NixOS, also appears in Debian in the debianutils package.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/386
**6.** URL(s): https://sources.debian.org/copyright/license/debianutils/4.11.2/
**7.** OSI Status: 0
**8.** Example Projects: https://salsa.debian.org/debian/debianutils

**Comment by jopejoe1** [comment]
License Text:

```
                     SMAIL GENERAL PUBLIC LICENSE
                       (Clarified 11 Feb 1988)

 Everyone is permitted to copy and distribute verbatim copies
 of this license, but changing it is not allowed.  You can also
 use this wording to make the terms for other programs.

   The license agreements of most software companies keep you at the
 mercy of those companies.  By contrast, our general public license is
 intended to give everyone the right to share SMAIL.  To make sure that
 you get the rights we want you to have, we need to make restrictions
 that forbid anyone to deny you these rights or to ask you to surrender
 the rights.  Hence this license agreement.

   Specifically, we want to make sure that you have the right to give
 away copies of SMAIL, that you receive source code or else can get it
 if you want it, that you can change SMAIL or use pieces of it in new
 free programs, and that you know you can do these things.

   To make sure that everyone has such rights, we have to forbid you to
 deprive anyone else of these rights.  For example, if you distribute
 copies of SMAIL, you must give the recipients all the rights that you
 have.  You must make sure that they, too, receive or can get the
 source code.  And you must tell them their rights.

   Also, for our own protection, we must make certain that everyone
 finds out that there is no warranty for SMAIL.  If SMAIL is modified by
 someone else and passed on, we want its recipients to know that what
 they have is not what we distributed, so that any problems introduced
 by others will not reflect on our reputation.

   Therefore we (Landon Curt Noll and Ronald S. Karr) make the following
 terms which say what you must do to be allowed to distribute or change
 SMAIL.


                         COPYING POLICIES

   1. You may copy and distribute verbatim copies of SMAIL source code
 as you receive it, in any medium, provided that you conspicuously and
 appropriately publish on each copy a valid copyright notice "Copyright
 (C) 1988 Landon Curt Noll & Ronald S. Karr" (or with whatever year is
 appropriate); keep intact the notices on all files that refer to this
 License Agreement and to the absence of any warranty; and give any
 other recipients of the SMAIL program a copy of this License
 Agreement along with the program.  You may charge a distribution fee
 for the physical act of transferring a copy.

   2. You may modify your copy or copies of SMAIL or any portion of it,
 and copy and distribute such modifications under the terms of
 Paragraph 1 above, provided that you also do the following:

    a) cause the modified files to carry prominent notices stating
    that you changed the files and the date of any change; and

    b) cause the whole of any work that you distribute or publish,
    that in whole or in part contains or is a derivative of SMAIL or
    any part thereof, to be licensed at no charge to all third
    parties on terms identical to those contained in this License
    Agreement (except that you may choose to grant more extensive
    warranty protection to some or all third parties, at your option).

    c) You may charge a distribution fee for the physical act of
    transferring a copy, and you may at your option offer warranty
    protection in exchange for a fee.

 Mere aggregation of another unrelated program with this program (or its
 derivative) on a volume of a storage or distribution medium does not bring
 the other program under the scope of these terms.

   3. You may copy and distribute SMAIL (or a portion or derivative of it,
 under Paragraph 2) in object code or executable form under the terms of
 Paragraphs 1 and 2 above provided that you also do one of the following:

    a) accompany it with the complete corresponding machine-readable
    source code, which must be distributed under the terms of
    Paragraphs 1 and 2 above; or,

    b) accompany it with a written offer, valid for at least three
    years, to give any third party free (except for a nominal
    shipping charge) a complete machine-readable copy of the
    corresponding source code, to be distributed under the terms of
    Paragraphs 1 and 2 above; or,

    c) accompany it with the information you received as to where the
    corresponding source code may be obtained.  (This alternative is
    allowed only for non-commercial distribution and only if you
    received the program in object code or executable form alone.)

 For an executable file, complete source code means all the source code for
 all modules it contains; but, as a special exception, it need not include
 source code for modules which are standard libraries that accompany the
 operating system on which the executable file runs.

   4. You may not copy, sublicense, distribute or transfer SMAIL
 except as expressly provided under this License Agreement.  Any attempt
 otherwise to copy, sublicense, distribute or transfer SMAIL is void and
 your rights to use the program under this License agreement shall be
 automatically terminated.  However, parties who have received computer
 software programs from you with this License Agreement will not have
 their licenses terminated so long as such parties remain in full compliance.

   5. If you wish to incorporate parts of SMAIL into other free
 programs whose distribution conditions are different, write to Landon
 Curt Noll & Ronald S. Karr via the Free Software Foundation at 51
 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.  We have not yet
 worked out a simple rule that can be stated here, but we will often
 permit this.  We will be guided by the two goals of preserving the
 free status of all derivatives of our free software and of promoting
 the sharing and reuse of software.

 Your comments and suggestions about our licensing policies and our
 software are welcome!  This contract was based on the contract made by
 the Free Software Foundation.  Please contact the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,
 USA, or call (617) 542-5942 for details on copylefted material in
 general.

                         NO WARRANTY

   BECAUSE SMAIL IS LICENSED FREE OF CHARGE, WE PROVIDE ABSOLUTELY NO
 WARRANTY, TO THE EXTENT PERMITTED BY APPLICABLE STATE LAW.  EXCEPT WHEN
 OTHERWISE STATED IN WRITING, LANDON CURT NOLL & RONALD S. KARR AND/OR
 OTHER PARTIES PROVIDE SMAIL "AS IS" WITHOUT WARRANTY OF ANY KIND,
 EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF SMAIL IS WITH
 YOU.  SHOULD SMAIL PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 NECESSARY SERVICING, REPAIR OR CORRECTION.

   IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW WILL LANDON CURT NOLL &
 RONALD S. KARR AND/OR ANY OTHER PARTY WHO MAY MODIFY AND REDISTRIBUTE
 SMAIL AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
 LOST PROFITS, LOST MONIES, OR OTHER SPECIAL, INCIDENTAL OR
 CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE
 (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED
 INACCURATE OR LOSSES SUSTAINED BY THIRD PARTIES OR A FAILURE OF THE
 PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS) SMAIL, EVEN IF YOU HAVE
 BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY
 ANY OTHER PARTY.

```

**Comment by Thompson1985** [comment]
SMAIL GENERAL PUBLIC LICENSE
                       (Clarified 11 Feb 1988)

 Everyone is permitted to copy and distribute verbatim copies
 of this license, but changing it is not allowed.  You can also
 use this wording to make the terms for other programs.

   The license agreements of most software companies keep you at the
 mercy of those companies.  By contrast, our general public license is
 intended to give everyone the right to share SMAIL.  To make sure that
 you get the rights we want you to have, we need to make restrictions
 that forbid anyone to deny you these rights or to ask you to surrender
 the rights.  Hence this license agreement.

   Specifically, we want to make sure that you have the right to give
 away copies of SMAIL, that you receive source code or else can get it
 if you want it, that you can change SMAIL or use pieces of it in new
 free programs, and that you know you can do these things.

   To make sure that everyone has such rights, we have to forbid you to
 deprive anyone else of these rights.  For example, if you distribute
 copies of SMAIL, you must give the recipients all the rights that you
 have.  You must make sure that they, too, receive or can get the
 source code.  And you must tell them their rights.

   Also, for our own protection, we must make certain that everyone
 finds out that there is no warranty for SMAIL.  If SMAIL is modified by
 someone else and passed on, we want its recipients to know that what
 they have is not what we distributed, so that any problems introduced
 by others will not reflect on our reputation.

   Therefore we (Landon Curt Noll and Ronald S. Karr) make the following
 terms which say what you must do to be allowed to distribute or change
 SMAIL.


                         COPYING POLICIES

   1. You may copy and distribute verbatim copies of SMAIL source code
 as you receive it, in any medium, provided that you conspicuously and
 appropriately publish on each copy a valid copyright notice "Copyright
 (C) 1988 Landon Curt Noll & Ronald S. Karr" (or with whatever year is
 appropriate); keep intact the notices on all files that refer to this
 License Agreement and to the absence of any warranty; and give any
 other recipients of the SMAIL program a copy of this License
 Agreement along with the program.  You may charge a distribution fee
 for the physical act of transferring a copy.

   2. You may modify your copy or copies of SMAIL or any portion of it,
 and copy and distribute such modifications under the terms of
 Paragraph 1 above, provided that you also do the following:

    a) cause the modified files to carry prominent notices stating
    that you changed the files and the date of any change; and

    b) cause the whole of any work that you distribute or publish,
    that in whole or in part contains or is a derivative of SMAIL or
    any part thereof, to be licensed at no charge to all third
    parties on terms identical to those contained in this License
    Agreement (except that you may choose to grant more extensive
    warranty protection to some or all third parties, at your option).

    c) You may charge a distribution fee for the physical act of
    transferring a copy, and you may at your option offer warranty
    protection in exchange for a fee.

 Mere aggregation of another unrelated program with this program (or its
 derivative) on a volume of a storage or distribution medium does not bring
 the other program under the scope of these terms.

   3. You may copy and distribute SMAIL (or a portion or derivative of it,
 under Paragraph 2) in object code or executable form under the terms of
 Paragraphs 1 and 2 above provided that you also do one of the following:

    a) accompany it with the complete corresponding machine-readable
    source code, which must be distributed under the terms of
    Paragraphs 1 and 2 above; or,

    b) accompany it with a written offer, valid for at least three
    years, to give any third party free (except for a nominal
    shipping charge) a complete machine-readable copy of the
    corresponding source code, to be distributed under the terms of
    Paragraphs 1 and 2 above; or,

    c) accompany it with the information you received as to where the
    corresponding source code may be obtained.  (This alternative is
    allowed only for non-commercial distribution and only if you
    received the program in object code or executable form alone.)

 For an executable file, complete source code means all the source code for
 all modules it contains; but, as a special exception, it need not include
 source code for modules which are standard libraries that accompany the
 operating system on which the executable file runs.

   4. You may not copy, sublicense, distribute or transfer SMAIL
 except as expressly provided under this License Agreement.  Any attempt
 otherwise to copy, sublicense, distribute or transfer SMAIL is void and
 your rights to use the program under this License agreement shall be
 automatically terminated.  However, parties who have received computer
 software programs from you with this License Agreement will not have
 their licenses terminated so long as such parties remain in full compliance.

   5. If you wish to incorporate parts of SMAIL into other free
 programs whose distribution conditions are different, write to Landon
 Curt Noll & Ronald S. Karr via the Free Software Foundation at 51
 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.  We have not yet
 worked out a simple rule that can be stated here, but we will often
 permit this.  We will be guided by the two goals of preserving the
 free status of all derivatives of our free software and of promoting
 the sharing and reuse of software.

 Your comments and suggestions about our licensing policies and our
 software are welcome!  This contract was based on the contract made by
 the Free Software Foundation.  Please contact the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301,
 USA, or call (617) 542-5942 for details on copylefted material in
 general.

                         NO WARRANTY

   BECAUSE SMAIL IS LICENSED FREE OF CHARGE, WE PROVIDE ABSOLUTELY NO
 WARRANTY, TO THE EXTENT PERMITTED BY APPLICABLE STATE LAW.  EXCEPT WHEN
 OTHERWISE STATED IN WRITING, LANDON CURT NOLL & RONALD S. KARR AND/OR
 OTHER PARTIES PROVIDE SMAIL "AS IS" WITHOUT WARRANTY OF ANY KIND,
 EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF SMAIL IS WITH
 YOU.  SHOULD SMAIL PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 NECESSARY SERVICING, REPAIR OR CORRECTION.

   IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW WILL LANDON CURT NOLL &
 RONALD S. KARR AND/OR ANY OTHER PARTY WHO MAY MODIFY AND REDISTRIBUTE
 SMAIL AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
 LOST PROFITS, LOST MONIES, OR OTHER SPECIAL, INCIDENTAL OR
 CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE
 (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED
 INACCURATE OR LOSSES SUSTAINED BY THIRD PARTIES OR A FAILURE OF THE
 PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS) SMAIL, EVEN IF YOU HAVE
 BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY
 ANY OTHER PARTY.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [SMAIL General Public License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/README.md#user-content-SMAIL-General-Public-License:~:text=SMAIL%20General%20Public%20License)
short name: SMAIL-GPL
markers: Incompatible with Secondary License Marker, No Warranty Marker, Non-commercial Marker
category: SMAIL General Public License
ScanCode reference id: [smail-gpl](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/smail-gpl.LICENSE)
OSI status: _none_
Open CoDE status: approved
Open CoDE approved license id: smail-gpl (ScanCode)

**ScanCode**
matched id: [smail-gpl](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/smail-gpl.LICENSE)


** Comment **
We first identified this license in Debian copyright files. I'd argue there has been signifinant use of the license. +1 to add to SPDX.

**Comment by jlovejoy** [comment]
+1 to add as well, given use in Debian.
Note that while it does contain some similar text to GPL, it is not close enough to be considered a slightly modified variant as the full name might suggest. That being said, I like/agree with `SMAIL` as the id, as I think adding `GPL` could be misleading.

**Comment by swinslow** [comment]
Appears to pre-date GPL-1.0, while sharing common lineage with it. Shares pieces from [NGPL](https://spdx.org/licenses/preview/NGPL.html) as well as [Bison General Public License](https://ftp.eso.org/scisoft/scisoft4/sources/sm/sm2_4_2/src/bison/copying) (which apparently isn't on the SPDX list currently).

Discussed on 2024-10-24 legal team call, agreed to add. Will use "SMAIL General Public License" as name and `SMAIL-GPL` as ID in light of this apparently being based on a pre-GPL-1.0 version of GPL, and similar to NGPL for Nethack General Public License.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
SMAIL General Public License
## License ID
SMAIL-GPL
## XML markup
none
## Notes:

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
