### ISSUE TITLE
any-OSI text was changes

### ISSUE THREAD

**Issue by jplesnik** [spdx/license-list-XML#2563]
I am maintainer of perl-Exporter-Tidy in Fedora. There is new version of the module.
It contains update any-OSI license text to Debian-approved version. The new text is 

```
This software may be redistributed under the terms of the GPL, LGPL,
modified BSD, or Artistic license, or any of the other OSI approved
licenses listed at http://www.opensource.org/licenses/alphabetical.
Distribution is allowed under all of these licenses, or any smaller
subset of multiple or just one of these licenses.

When using a packaged version, please refer to the package metadata to see
under which license terms it was distributed. Alternatively, a distributor
may choose to replace the LICENSE section of the documentation and/or
include a LICENSE file to reflect the license(s) they chose to redistribute
under.
```
https://metacpan.org/release/JUERD/Exporter-Tidy-0.09/view/Tidy.pm#LICENSE

What should I do? 

* update [original license](https://spdx.org/licenses/any-OSI.html) 
* create new identifier like `any-OSI-2.0`

License request for `any-OSI` (https://github.com/spdx/license-list-XML/issues/2243)

**Comment by richardfontana** [comment]
@jplesnik note also we will need a new issue at gitlab.com/fedora/legal/fedora-license-data.

**Comment by jlovejoy** [comment]
for convenience here, the text for `any-OSI` is: 
"Pick your favourite OSI approved license :)
http://www.opensource.org/licenses/alphabetical"

I would say that the meaning here is roughly the same. Even though it lists a few licenses specifically, it then says, "or any of the other OSI approved
licenses listed at http://www.opensource.org/licenses/alphabetical"

I'm not sure what to make of this addition: "Distribution is allowed under all of these licenses, or any smaller subset of multiple or just one of these licenses."

**Comment by richardfontana** [comment]
I don't think the meaning should be seen as the same (looking at the two license texts from an SPDX-legal sort of lens), for the following reasons: 

1. The original can be read it as saying "Pick *one* OSI-approved license". The new one gets rid of that ambiguity.
2. The new one is more specific about what licenses are choosable: "any of the . . .  OSI approved licenses listed at http://www.opensource.org/licenses/alphabetical". This is arguably narrower than "OSI-approved license" since (I'm pretty sure) there are OSI-approved licenses that have been removed from the OSI website, or at least from being linked to at that URL (for example, certain deprecated licenses). 
3. The new one says "Distribution is allowed under all of these licenses, or any smaller
subset of multiple or just one of these licenses." It is not clear that this is permitted under the old license -- this is the same issue as 1 ("any OSI-approved license" can be read as meaning "one specific OSI-approved license"). Mind you, I don't consider that the best reading but I think for SPDX to treat these two licenses as equivalent would be inconsistent with how SPDX has treated other similar or related licenses.

**Comment by swinslow** [comment]
Discussed on 2024-10-24 legal team call, agreed to add as a new license ID `any-OSI-perl-modules`, name "Any OSI License - Perl Modules". Noted that this new text has been used for a few different Perl modules in the past (possibly all by the same upstream author).

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Any OSI License - Perl Modules
## License ID
any-OSI-perl-modules
## XML markup
none
## Notes:
This is similar in spirit to any-OSI, but has some more specific text. It is used in several Perl modules.
##URLs##
use above and add: https://metacpan.org/pod/Qmail::Deliverable::Client#LICENSE and https://metacpan.org/pod/Net::MQTT::Simple#LICENSE

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
