### ISSUE TITLE
New license request: CentralNic

### ISSUE THREAD

**Issue by ppisar** [spdx/license-list-XML#2576]
### How license meets inclusion principles

A MIT-like, yet distinct license from other licenses known to SPDX.  It allows use, modification, and redistribution.

The license is similar to NTP license, but differs in "without fee" (CentralNic)  vs. "with or without fee" (NTP). But I believe this does not disallow a commercial distribution because UMich-Merit license has the same wording. This new license also has a warranty and liability clause. This license is also similar (maybe a superset) of a license proposed in #2575.

I selected Internic name because of the copyright holder https://github.com/gbxyz/perl-net-rdap/blob/00302bd794e6d691ff6141a8dadd308b453f9d78/lib/Net/RDAP.pm#L178.

### License Name

CentralNic License

### Suggested short identifier

CentralNic

### License or Exception?

license

### URL to license text

https://raw.githubusercontent.com/gbxyz/perl-net-rdap/00302bd794e6d691ff6141a8dadd308b453f9d78/LICENSE

### OSI Status

I don't know

### License author or steward

CentralNic

### URL to project(s) that use license

https://github.com/gbxyz/perl-net-rdap

### paste text of license here

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation, and that the name of the author not be used
in advertising or publicity pertaining to distribution of the software
without specific prior written permission.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by jlovejoy** [comment]
This is a VERY close match to [HPND-MIT-disclaimer](https://github.com/spdx/license-list-XML/issues/2575) with only the following differences:

1. "original copyright notice" here, instead of "above copyright notices" in HPND-MIT-disclaimer
2. "and that both that copyright notice" here, instead of "and that both copyright notice"

not sure if this is really a substantive difference?? I suppose the above copyright and original copyright notices may not be the same, but...

**Comment by ppisar** [comment]
Indeed, they are similar. I somehow missed HPND-MIT-disclaimer. I think "original" and "above" are equivalent because they both refer to a text the licensee received.

I will augment a XML markup for HPND-MIT-disclaimer to also match this perl-net-rdap's wording.

**Comment by ppisar** [comment]
The adaption is in PR #2581.

**Comment by gbxyz** [comment]
Hi there, I'm the maintainer of the software that license was found in.

The intention was always for this software to be licensed under the 2-clause BSD license. If you look in `Makefile.PL` you'll see that it says `license => 'freebsd`, which has been there since the beginning. However the license statement somehow got munged, and was then copied and pasted into every .pm file.

I have no addresses this by fixing [LICENSE](https://github.com/gbxyz/perl-net-rdap/blob/master/LICENSE) and the copyright statement in each .pm file. I will shortly publish a new version with the updated license to CPAN. So this issue could probably be closed.

**Comment by ppisar** [comment]
Thanks for improving the LICENSE file. However, I still can see the old license in README.md. Could you update that file?

**Comment by gbxyz** [comment]
That's fixed now.

**Comment by xsuchy** [comment]
Thank you all. I think there is nothing to do now as everything is resolved. Closing.
