### ISSUE TITLE
Representing license translations

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#438]
For example, see #437, which changes `CECILL-C` from French to English and adds `CECILL-C-fr` for the official French version.  See also [this list post][1] and [this wiki page][2].  I'm opening an issue here to cross-link those external discussions; further discussion should probably happen on the list, wiki page, or legal meetings.

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-June/001988.html
[2]: https://wiki.spdx.org/view/Legal_Team/non-English-licenses

**Comment by zvr** [comment]
I wasn't planning on keeping the CECILL-C-fr around, but since it was already merged I didn't want to delete it without notice.

**Comment by mlinksva** [comment]
Idea: allow multiple `<text>` elements with `lang` attributes. That way multiple languages can be handled in each license XML file. A document should match a license if it matches any of of the texts, or any multiple of them concatenated together.

**Comment by swinslow** [comment]
@mlinksva This sounds like a great approach to me. This is also relevant for #923, etalab-2.0, which has a canonical French version and a "for convenience" English translation.

I don't want to over-engineer this, but if we're allowing multiple `<text>` elements with different `lang` attributes, I wonder if we should also include a way to indicate which one is considered authoritative by the license steward. Not mandatory, but to note it if we know.

Regardless of whether a translated text is considered legally authoritative by the steward, for SPDX purpose I think we would still want to call it a match if it was present. So I don't think it's necessary for us to track this, and might over-complicate things. But raising it in case folks feel differently.

**Comment by swinslow** [comment]
Discussed on 2021-12-09 legal team call. Policy in the past has varied depending on how the license steward publishes the license text, see EUPL and MulanPSL as examples. Closing this issue for now as in practice it hasn't been feasible to have a single policy across the list.

**Comment by mlinksva** [comment]
I realize this is quite stale, just noting another question about representation of licenses with multiple languages at https://github.com/github/choosealicense.com/pull/1018#issuecomment-1221042492 (I've deferred addressing there mostly for lack of time/priority, but secondarily because I'm lazily waiting to see how it is eventually tackled in the SPDX license list 😄).

IMO MulanPSL is one of a kind and not relevant -- they've short-circuited the issue by having the canonical text concatenate Chinese and English versions. Every other license I know of, including EUPL, CeCILL, and CC-*-4.0 licenses, with official versions in multiple languages takes the approach of having each language version stand alone. That's what requires special support.

I haven't thought about what that support should look like in a long time, but glancing up https://github.com/spdx/license-list-XML/issues/438#issuecomment-528614713 still strikes me as relatively straightforward and useful.

**Comment by Aeris1One** [comment]
Indeed, as an example the CeCILL FAQ states that "It is thus possible to use indifferently one or the other." and so some people may use only the French one while some other may use the English one.

I must admit that since both licence translation are equally legal, and that CeCILL was originally made in French to be compliant with French law (and Paris court being competent in case of legal proceeding), I still don't understand why did the English version replace the French one, which is more widely used, in this repo.

Maybe should we add multiple entries for those licences ? (CeCILL-fr and CeCILL-en for example)
But the drawback is that it may kind of bloat this repo because for example EUPL have 22 official translations and so it would mean 22 entries...
