### ISSUE TITLE
Licenses MPL-2.0 and MPL-2.0-no-copyleft-exception use the same license text

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#441]
When running the license compare utility, Licenses MPL-2.0 and MPL-2.0-no-copyleft-exception show as equivalent leading to ambiguous license ID matching.

**Comment by wking** [comment]
I expect this is because the difference is in the grant, and not in
the license itself (just like “any later version” may be part of a GPL
grant, or not, and is represented by version operators).  I recommend
we have either:

a. ‘MPL-2.0’ mean “with the standard grant” and:

     MPL-2.0 WITH MPLIncompatibleSecondary-2.0

  or similar mean “with Exhibit B or equivalent in the grant”.

  That maps very clearly to the “document grant wording with
  additional operators” pattern, but MPLIncompatibleSecondary-2.0
  would be reducing permissions, so it's not compatible (as far as I
  can tell) with the new exception definition [1] (still unposted
  [2]?).  To stick to that, we'd need:

b. * MPL-2.0 for “with Exhibit B or equivalent in the grant” and
   * ‘MPL-2.0 WITH MPLCompatibleSecondary-2.0’ for “without Exhibit B,
     e.g. the standard license grant”.

Folks may get sloppy and set ‘MPL-2.0’ regardless of grant wording.
But with the more-restrictive MPL-2.0 interpretation in (b), at least
such SPDX-author sloppiness wouldn't accidentally advertise more
permissions than the package-author actually granted.

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-July/002078.html                                                                                                   
     Subject: revised text for top of exceptions page
     Date: Thu, 27 Jul 2017 22:34:12 -0600
     Message-ID: <CFC5FB98-BDEC-47BC-B64C-47B1473E7176@jilayne.com>
[2]: https://lists.spdx.org/pipermail/spdx-legal/2017-September/002231.html
     Subject: Re: revised wording for top of exceptions page (was:
       Linux syscall exception agreed documentation)
     Date: Wed, 27 Sep 2017 16:59:39 -0600
     Message-ID: <EF1F43D5-A12E-4971-9DB8-29E2B1545AC5@jilayne.com>

**Comment by wking** [comment]
In the wake of #553, this “same text, different grant, different license ID” issue also applies to the GPL family.

**Comment by silverhook** [comment]
I would expect at least the standard headers to be different – Exhibit A vs Exhibit B.

**Comment by swinslow** [comment]
Looks like the standard headers are different, at least in the entries on the list as they are now (they may have been updated since @silverhook's comment from 2018):
* https://spdx.org/licenses/MPL-2.0.html
* https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html

so I'd be inclined to close this issue. As @wking noted earlier, this same issue applies to the GPL family as well as now to other licenses like OFL.

**Comment by swinslow** [comment]
Discussed on 2021-12-09 legal team call, agreed to close.
