### ISSUE TITLE
Draft updates for readmes in license-list and license-list-xml repos

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#509]

**Comment by bradleeedmondson** [comment]
drafting updated readme for license-list-XML [here](https://github.com/spdx/license-list-XML/blob/readme-update/README.md)

**Comment by wking** [comment]
I'd recommend filing pull-requests for these changes (instead of pushing straight to master like you've done with 4003676d2 and 69a676444), because pull requests provide space for review before the changes go live.

69a676444 seems to be positioning this repository as non-canonical source for the canonical license-list-data.  There may be a defensible position in that area, but I'd much rather make this repository canonical, with the caveat that the format is subject to change.  For example, it seems odd to have license-list-data [punt to a license-list repostitory for the license content][1] (presumably that will change to point to this repository once we cut a release here) while this repository continues to [claim that the license test is not stable or authoritative][2].  By making this repository canonical, we avoid involving the spdx/tools translators in our canonical content.

[1]: https://github.com/spdx/license-list-data/blame/97fcc7f553b74398aa4f3201089529d6415957b1/README.md#L26
[2]: https://github.com/spdx/license-list-XML/blame/3d13b0ecb70cee7704d1354d3e2c2464d8a4909f/README.md#L5

**Comment by bradleeedmondson** [comment]
**PRs for readme update:** Yep, that's the plan. Staging here and will create PRs:
https://github.com/spdx/license-list-XML/tree/readme-update

**Canonical source (past):** With 69a6764 I did not intend to convey that this repo would include non-canonical copies of the canonical license-list-data, just that the XML itself was not canonical and that the canon lived in the license-list-data repo. The sentence added in 69a6764 was intended to reference the cutover from using the old source files to generate the license-list-data to using the XML to do so (which I believe @goneall will do with this upcoming release).

**Canonical source (going forward):** I believe I recall correctly from the last legal call (but could be mistaken) that we were talking about archiving the license-list-data repo and making this repo canonical (possibly with a repo rename). I don't know that we reached a final decision on that but I thought I would draft with that aim in mind, because that seemed to be the way the group was leaning. See [here](https://wiki.spdx.org/view/Legal_Team/Minutes/2017-12-07) and in any event will have everyone review in the PR for the readme.

**Comment by wking** [comment]
On Tue, Dec 19, 2017 at 11:51:03PM +0000, Bradlee H. Edmndson wrote:
> **Canonical source (going forward):** I believe I recall correctly
> from the last legal call (but could be mistaken) that we were
> talking about archiving the license-list-data repo and making this
> repo canonical (possibly with a repo rename).

I'm not sure about renames, but my impression was that we'd continue
to provide license-list-data to support its existing downstream
consumers.  The only change there would be that the content would be
generated from this repo instead of from the non-XML license-list
repo.

**Comment by goneall** [comment]
> I believe I recall correctly from the last legal call (but could be mistaken) that we were talking about archiving the license-list-data repo

During that discussion, I thought we were talking about the license-list repo (not license-list-data).  I don't recall any discussion on the license-list-data repository other than to review/update the documentation.

**Comment by bradleeedmondson** [comment]
Oh, of course. That makes much more sense (and explains why we didn't have a much, much longer conversation about this). Thanks Trevor for identifying the source of confusion, and apologies all for my mistake!

As I now understand it, the plan is to archive the license-list repo and move active issues to license-list-XML, then (perhaps) rename license-list-XML to license-list. No structural changes planned for license-list-data nor its contents; just a touch-up of its documentation (and a rev when we do the next release).

cc @goneall @jlovejoy

**Comment by bradleeedmondson** [comment]
Proposed PRs for readmes.

PR for license-list XML here:
https://github.com/spdx/license-list-XML/pull/538

PR for license-list (deprecated) here:
https://github.com/spdx/license-list/pull/22

**Comment by bradleeedmondson** [comment]
both PRs updated with (most) suggestions integrated

**Comment by wking** [comment]
The PRs have been merged, so we can probably close this issue.

**Comment by bradleeedmondson** [comment]
agree; resolved
