### ISSUE TITLE
add GNU licenses with new identifiers (*-only and *-or-later)

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#542]
* GPL-1.0-only or GPL-1.0-or-later 
* GPL-2.0-only or GPL-2.0-or-later
* GPL-3.0-only or GPL-3.0-or-later

* LGPL-2.0-only or LGPL-2.0-or-later
* LGPL-2.1-only or LGPL-2.1-or-later
* LGPL-3.0-only or LGPL-3.0-or-later

* FDL-1.1-only or FDL-1.1-or-later
* FDL-1.2-only or FDL-1.2-or-later
* FDL-1.3-only or FDL-1.3-or-later

* AGPL-3.0-only or AGPL-3.0-or-later

license text is same for each set
ensure standard header reflect correct wording for each one

**Comment by zvr** [comment]
The FDL ones are actually GFDL ;)

**Comment by zvr** [comment]
I assume that this does not affect the `isOsiApproved` attribute...

I mean, if GPL-2.0 was approved, then GPL-2.0-only and GPL-2.0-or-later are also marked as approved.

**Comment by zvr** [comment]
Submitted #553

**Comment by wking** [comment]
Why is AGPL-1.0 not receiving the same treatment?

**Comment by wking** [comment]
I still think this explicit-license-list-entry approach (vs. versioning operators) is going to make it [difficult to GPL proxy declarations in the future][1].  I realize that this is the approach adopted by the legal team after lots of discussion, but thought I'd add a final mention here in case there's a last-minute change of heart or anything ;).

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-November/002309.html

**Comment by wking** [comment]
With #553 merged, what's left here?  Just [the AGPL-1.0 handling][1]?

[1]: https://github.com/spdx/license-list-XML/issues/542#issuecomment-354163002

**Comment by zvr** [comment]
As far as I can tell, AGPL-1.0 was a license by Affero, not by the Free Software Foundation and they never raised an issue regarding "or later".

**Comment by wking** [comment]
On Thu, Dec 28, 2017 at 11:22:47AM +0000, Alexios Zavras (zvr) wrote:
> As far as I can tell, AGPL-1.0 was a license by Affero, not by the
> Free Software Foundation…

Right.

> … and they never raised an issue regarding "or later".

Is our use of -only and -or-later license names really as narrow as
“we only use these if the steward complains about version operators”?
The AGPL-1.0 has a §9 [1] which is very similar to the GPL-2.0's [2].
Both contain the:

  If the Program specifies a version number of this License which
  applies to it and "any later version", you have the option of
  following the terms and conditions either of that version or of any
  later version published by {the Free Software Foundation|Affero,
  Inc}.  If the Program does not specify a version number of this
  License, you may choose any version ever published by {the Free
  Software Foundation|Affero, Inc}.

which seemed to be the trigger for this issue.

The AGPL-1.0 *also* ties the “any later version” grant to the GPL-3.0+
in their §9, and they've cut an AGPL-2.0 [3] as a shim to allow folks
to use an “any later version” grant to go from AGPL-1.0+ → AGPL-2.0+ →
AGPL-3.0+ [4].

So this seems like *exactly* the same situation as the GPL family.
I'd like to keep our handling consistent.  I much prefer using version
operators, but if the intention is to use specific licenses to cover
these explicit-versioning grants, I'd rather drag the CDDL family and
the AGPL-1.0 along too instead of having two separate approaches to
the same problem.

[1]: https://github.com/spdx/license-list-XML/blob/1802f8491db2574a093fde665f08672a5d069189/src/AGPL-1.0.xml#L231-L243
[2]: https://github.com/spdx/license-list-XML/blob/1802f8491db2574a093fde665f08672a5d069189/src/GPL-2.0.xml#L336-L349
[3]: http://www.affero.org/agpl2.html
[4]: http://www.affero.org/oagpl.html

**Comment by jlovejoy** [comment]
I am conferring with the FSF as to AGPL-1.0 - I will make the appropriate changes as needed when I get feedback there. No further discussion needed at this point.

**Comment by wking** [comment]
> I am conferring with the FSF as to AGPL-1.0

Have we heard back on this?  I'd like to get this and #543 closed off so we can close the [3.0 milestone][1], since it's strange to have that milestone open after we've cut the 3.0 release.  If it will take more time to address the AGPL-1.0, we may want to move this issue to the 3.1 milestone.

[1]: https://github.com/spdx/license-list-XML/milestones/Immediate%20Release%20-%203.0

**Comment by jlovejoy** [comment]
oops, yes, we have and I have confirmed that we should treat AGPL-1.0 that same) as we suspected.
@zvr  or @wking  can one of you do a PR for those?  (I'll change the label on this and the other issue in the meantime, since this is now a 3.1 release item)

Thanks!

**Comment by wking** [comment]
On Thu, Jan 11, 2018 at 09:56:18PM +0000, Jilayne Lovejoy wrote:
> oops, yes, we have and I have confirmed that we should treat
> AGPL-1.0 that same) as we suspected.

Do we want to add an entry for the AGPL-2.0 [1]?  A potential use-case
would be to record the path for folks seeing to transition from
AGPL-1.0-or-later to AGPL-3.0-or-later in case the www.affero.org copy
goes away (or even if it stays, to make it easier to talk about that
transition using SPDX identifiers).  I'm not sure how many active
projects are still under the AGPL-1.0, so maybe recording the path is
not an issue.

[1]: http://www.affero.org/agpl2.html

**Comment by jlovejoy** [comment]
no need to add AGPLv2 - we vetted that conversation way back with key folks who knew the history and it was decided not to add it then. So, no need to revisit now! :)

**Comment by wking** [comment]
> no need to add AGPLv2 - we vetted that conversation way back with key folks who knew the history and it was decided not to add it then.

For the curious, I've turned up an entry-point to that discussion [here][1].

[1]: https://lists.spdx.org/pipermail/spdx-legal/2013-November/001033.html

**Comment by wking** [comment]
Can comeone with write access close the 3.0 milestone now that it's complete?  There should be a button [here][1].

[1]: https://github.com/spdx/license-list-XML/milestones
