### ISSUE TITLE
Drop “optional” implication from “titleText”

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#607]
`<titleText>` currently means both “this text should be formatted as a title/header” and “this text is optional”.  But we already have `<optional>` for the latter, so I think we should restrict `<titleText>` to just the header formatting.  Previous discussion [here][1].

[1]: https://github.com/spdx/license-list-XML/pull/446#discussion_r145448871

**Comment by swinslow** [comment]
Discussed on 2019-07-30 call, `titleText` has relevant semantic meaning for SPDX matching guidelines purposes, so want to keep it as a separate tag from `optional`.

**Comment by wking** [comment]
> ... `titleText` has relevant semantic meaning for SPDX matching guidelines purposes, so want to keep it as a separate tag from `optional`.

Right, I was not suggesting we drop `titleText`.  I was suggesting that `<titleText>whatever</titleText>` become a required title, and you'd need markup like `<titleText><optional>whatever</optional></titleText>` to mark an optional title.  That would allow for simpler text-matching implementations.

**Comment by swinslow** [comment]
I see -- thanks, I'd misunderstood that. I think that since the [SPDX matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) already say that all title text is to be treated as optional (see item 11 at that link), the view was that adding `<optional></optional>` tags within `<titleText></titleText>` wasn't necessary.

**Comment by wking** [comment]
> I think that since the SPDX matching guidelines already say that all title text is to be treated as optional (see item 11 at that link), the view was that adding `<optional></optional>` tags within `<titleText></titleText>` wasn't necessary.

Right.  But if you make "titles are optional" a license-entry issue by defining `<titleText>` to be style markup (instead of its current style and matching markup) and using `<titleText><optional>...</optional></titleText>`, you could simplify the matching guidelines by dropping item 11.  Same end result, and I think that the explicit `<optional>` in the templates is worth the simplified matching guidelines.  If you're worried about folks leaving it out, you could adjust the schema such that the only valid content of the `<titleText>` tag is an `<optional>` tag, although personally I'm fine leaving that up to template authors as well.

**Comment by zvr** [comment]
Since all license titles are optional by definition, I believe that the matching guidelines is the correct place to put this information.
Yes, we could go and modify all data to have the construct `<optional><titleText>`...`</titleText></optional>`, but it's faster and simpler to have it in the guidelines.
Most, if not all, matching guidelines could be expressed in the XML (e.g. have the variety of hyphens or quotes or the different spellings as `alt` elements in every instance), but if a rule is general and applies to all licenses, it should be in the guidelines and not pollute our data.

**Comment by wking** [comment]
> Most, if not all, matching guidelines could be expressed in the XML (e.g. have the variety of hyphens or quotes or the different spellings as alt elements in every instance), but if a rule is general and applies to all licenses, it should be in the guidelines and not pollute our data.

The trade-off is:

* How many people will read the raw template XML?

vs.

* How many people will write a from-scratch matching implementation?

I'd prioritize the latter; currently folks just give up (e.g. licensee/licensee#254).  If we want to store simplified/shorthand XML and spit out the expanded/explicit form in the output templates we provide our consumers with, I'm fine with that too.
