### ISSUE TITLE
New License Request: Froala Open Web Design License

### ISSUE THREAD

**Issue by vmarkovtsev** [spdx/license-list-XML#611]
Full Name: Froala Open Web Design License
Short Identifier: Please choose for me.
URL: https://github.com/froala/design-blocks/blob/dev/LICENSE
OSI-approved: don't know

**Comment by jlovejoy** [comment]
to be reviewed on upcoming legal call.
@vmarkovtsev - can you please provide further information re: "Provide a short explanation regarding the need for this license or exception to be included on the SPDX License List, including identifying at least one program that uses this license."?
thanks

**Comment by vmarkovtsev** [comment]
Sure. Explanation:

I found this license in "Froala Design Blocks" project - https://github.com/froala/design-blocks
It has more than 10,000 stars on GitHub and thus must be popular.

**Comment by wking** [comment]
> Short Identifier: Please choose for me.

Maybe `Frola-OWDL-1.0` (acronyming most of the [upstream title][1]).

> OSI-approved: don't know

[Google is not aware of any OSI discussion][2], and the license isn't listed [here][3], so I'm pretty sure this is not OSI approved.

[1]: https://github.com/froala/design-blocks/blob/1.0.2/LICENSE#L5
[2]: https://www.google.com/search?q=frola+site%3Alists.opensource.org
[3]: https://opensource.org/licenses/alphabetical

**Comment by bradleeedmondson** [comment]
Discussed on legal call, but not consensus on whether to approve or how to respond. Arguably not an open-source license, since prohibits dual licensing and unbundled sale.

Need to discuss further on next legal call.

**Comment by bradleeedmondson** [comment]
Discussed on legal call today, but did not reach consensus. Need to discuss again on next legal call.

This is arguably not a FOSS license, since it prohibits unbundled commercial distribution.

**Comment by swinslow** [comment]
This is based on [OFL-1.1](https://spdx.org/licenses/OFL-1.1.html). OFL-1.1 has been considered [open by OSI](https://opensource.org/licenses/OFL-1.1) and [free by FSF](https://www.gnu.org/licenses/license-list.en.html#SILOFL).

Notably, though, OFL-1.1's restriction is just that it cannot be sold by itself. The FSF guidance linked above says that "Since a simple Hello World program will satisfy the requirement, it is harmless."

By contrast, the Froala license in 3(a) adds restrictions on what it can be used for: `Neither the Work nor any of its individual components, in Original or Modified Versions, may be . . . (ii) used for website or app generators; (iii) used to create templates, themes, and plugins for sale.`

Based on that, I'm inclined to say that this does not really meet the current [SPDX license inclusion principles](https://spdx.org/spdx-license-list/license-list-overview). I'm of course open to others' thoughts!

**Comment by jlovejoy** [comment]
I'd agree @swinslow  - clearly restricts specific uses, which makes it not open source.

**Comment by wking** [comment]
Isn't CC-BY-NC-ND and in the same boat?  And we register it.  So I dunno what the line is, but it doesn't seem to be Open Source or Four Freedoms.

**Comment by jlovejoy** [comment]
yes, all the CC-BY-NC-ND is on there. We came up with the inclusion guidelines after the first few versions of the license list, and the CC licenses were added before that (by my memory).

**Comment by bradleeedmondson** [comment]
I'm not sure yet whether I am for or against adding this to the SPDX license list. Weighing against, it is not a free and open-source license in that it prohibits reuse in the same market/vertical in which the company operates (website templates). On the other hand it seems somewhat popular, so it's possible there are lots of sites/projects out there with this codebase/asset base.

This might be a good entry for the floated (but not yet decided upon) "unofficial list of commonly found non-open-source licenses." 

To be discussed further by legal team either on this issue or on the next call.

**Comment by jlovejoy** [comment]
as noted above, due to the restrictions on types of use, this is not an open source license, so not accepted.
