### ISSUE TITLE
New Exception: URW Base 35 AGPL-3.0-only font exception

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#616]
Adding a tracking issue for [the URW Base 35 license exception][1]:

> The font and related files in this directory are distributed under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (see the file COPYING), with the following exemption:
>
> As a special exception, permission is granted to include these font programs in a Postscript or PDF file that consists of a document that contains text to be displayed or printed using this font, regardless of the conditions or license applying to the document itself.

which was [raised on the list in a 2018-02-28 mail from Stefan Brüns][2].

Can somebody with push access label this “[new license/exception request][3]”?

[1]: https://github.com/ArtifexSoftware/urw-base35-fonts/blob/65962e27febc3883a17e651cdb23e783668c996f/LICENSE
[2]: https://lists.spdx.org/pipermail/spdx-legal/2018-February/002478.html
[3]: https://github.com/spdx/license-list-XML/labels/new%20license%2Fexception%20request

**Comment by bradleeedmondson** [comment]
Discussed on legal call today.

Appears to be used only in URW Base 35 Fonts package (google search for matching text shows only ~5 hits); however that package is included in Debian, so we will approve and add this exception to the SPDX License List. Approved.

Proposed name: AGPL-3.0 font exception PS-PDF

Proposed short identifier: AGPL-3.0-font-exception-ps-pdf

Note that the PostScript and PDF document format appears to be a condition for triggering this exception.

**Comment by bradleeedmondson** [comment]
@wking Would you be able to file a PRs for the XML definition of this license?

**Comment by wking** [comment]
> Proposed short identifier: AGPL-3.0-font-exception-ps-pdf

Do we want to stick a version number on that?  What happens if they update the text in the future in a way the SPDX considers legally distinct from the current text?

**Comment by bradleeedmondson** [comment]
Ah, yes, good point. Now that you raise it, I think we should version just about everything we add to the list. (Perhaps we should make this an explicit directive going forward?) 

We always list version number when the license author specifies versions, but it's not completely clear what to do when the author doesn't version their text. Rather than specify 1.0 for them, perhaps we should version by date, as we do with [some](https://github.com/spdx/license-list-XML/blob/master/src/Adobe-2006.xml) [license](https://github.com/spdx/license-list-XML/blob/master/src/W3C-19980720.xml) [files](https://github.com/spdx/license-list-XML/blob/master/src/W3C-20150513.xml)? 

Here, that would presumably resolve to:
* Proposed name: AGPL-3.0 font exception PS-PDF 20170817 or AGPL-3.0 font exception PS-PDF 2017
* Proposed short identifier: AGPL-3.0-font-exception-ps-pdf-20170817 or AGPL-3.0-font-exception-ps-pdf-2017

Thoughts, @wking ? 

Also, some housekeeping: I believe @jlovejoy and @kestewart are traveling for conferences at the moment, so I'd like to give them at least a week to weigh in before finalizing/merging anything. But we can always get started with the PRs now.

**Comment by bradleeedmondson** [comment]
Also, and this may need more discussion on the next legal call (hence the label re-added), but we'll need to explicitly decide how to cast the first sentence (required? optional? precluded?). For the legal team, is the exception:

1.
> The font and related files in this directory are distributed under the
> GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (see the file COPYING), with
> the following exemption:
> 
> As a special exception, permission is granted to include these font
> programs in a Postscript or PDF file that consists of a document that
> contains text to be displayed or printed using this font, regardless
> of the conditions or license applying to the document itself.

or 2.

> &lt;optional&gt;The font and related files in this directory are distributed under the
> GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (see the file COPYING), with
> the following exemption:&lt;/optional&gt;
> 
> As a special exception, permission is granted to include these font
> programs in a Postscript or PDF file that consists of a document that
> contains text to be displayed or printed using this font, regardless
> of the conditions or license applying to the document itself.

or 3.

> As a special exception, permission is granted to include these font
> programs in a Postscript or PDF file that consists of a document that
> contains text to be displayed or printed using this font, regardless
> of the conditions or license applying to the document itself.




If we decide on case 3, which currently makes the most sense to me, since it allows combination with other licenses (not just AGPL3), then the name and short identifier would need to be updated.

**Comment by wking** [comment]
On Thu, Apr 19, 2018 at 05:51:47PM +0000, Bradlee H. Edmndson wrote:
> Also… we'll need to explicitly decide how to cast the first sentence…
> …
> If we decide on case 3, which currently makes the most sense to me,
> since it allows combination with other licenses (not just AGPL3),
> then the name and short identifier would need to be updated.

This makes the most sense to me as well.  Basically this is the same
situation we had with the OpenJDK exception [1], where the text we're
given is really adoption text associating content with the contract,
where the adoption text happens to include at least a portion of the
contract text.  I think the correct markup would be something like:

  <standardLicenseHeader>
    <p>The font and related files in this directory are distributed
      under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (see the
      file COPYING), with the following exemption:
    </p>
    <text>
      <p>As a special exception, permission is granted to include
        these font programs in a Postscript or PDF file that consists
        of a document that contains text to be displayed or printed
        using this font, regardless of the conditions or license
        applying to the document itself.
      </p>
    </text>
  </standardLicenseHeader>

although you'd need a schema change to allow <text> within
<standardLicenseHeader>.  Without a schema change, I think the best we
could do would be the not-DRY:

  <text>
    <p>As a special exception, permission is granted to include these
      font programs in a Postscript or PDF file that consists of a
      document that contains text to be displayed or printed using
      this font, regardless of the conditions or license applying to
      the document itself.
    </p>
  </text>
  <standardLicenseHeader>
    <p>The font and related files in this directory are distributed
      under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (see the
      file COPYING), with the following exemption:
    </p>
    <p>As a special exception, permission is granted to include these
      font programs in a Postscript or PDF file that consists of a
      document that contains text to be displayed or printed using
      this font, regardless of the conditions or license applying to
      the document itself.
    </p>
  </standardLicenseHeader>

[1]: https://github.com/spdx/license-list-XML/pull/625#discussion_r179531365

**Comment by bradleeedmondson** [comment]
> Incidentally, what's the motivation for the hyphen for PS-PDF?  I'd
> have expected PS/PDF.

A good point -- I just assumed without checking that slashes were not allowed in SPDX identifiers. If they are, that's a better representation.

**Comment by wking** [comment]
On Thu, Apr 19, 2018 at 06:37:47PM +0000, Bradlee H. Edmndson wrote:
> > Incidentally, what's the motivation for the hyphen for PS-PDF?  I'd
> > have expected PS/PDF.
>
> A good point -- I just assumed without checking that slashes were
> not allowed in SPDX identifiers. If they are, that's a better
> representation.

They are not allowed in identifiers [1], so I'm fine with PS-PDF
there.  But I'd prefer PS/PDF in the exception name.

[1]: https://github.com/spdx/spdx-spec/blame/df26160783956ed87d78889dd1d4a53022e713eb/chapters/appendix-IV-SPDX-license-expressions.md#L11

**Comment by bradleeedmondson** [comment]
### PS/PDF
> But I'd prefer PS/PDF in the exception name.

Agreed. So the name should have PS/PDF and the identifier PS-PDF.

### Markup
I also agree with [your markup approach](https://github.com/spdx/license-list-XML/issues/616#issuecomment-382835783), but I think we can take it a step further and use &lt;alt&gt; for the license name (rather than leaving the happenstance of AGPL-3.0 per this request), and knock AGPL-3.0 out of the exception name and identifier. This may not be technically necessary now, but seems to be the best way to plan for future use in conjunction with other licenses, which it's my understanding the exceptions are intended to support.

### Versioning
I am not sure I fully understand and can accurately represent SPDX naming conventions w/r/t versioning (and they may have both explicit and unwritten aspects), so I would be happy to be overruled or corrected as appropriate. But my own current preference would be the following: 

- Ask the license text submitter for versioning information or author contact information, 
  - If we hear back within a reasonable time frame, and the author publicly specifies a version number, use that
  - Otherwise, default to appending YYYYMMDD to indicate [something approaching version number]. 

I'll reach out to the submitter for this license to ask about authorship and versioning shortly.

**Comment by bradleeedmondson** [comment]
I haven't heard anything back, and there was no response on the list, so let's go with versioning (in the name field) by date.

**Comment by bradleeedmondson** [comment]
@wking Would you be able to file a PR for these?

**Comment by StefanBruens** [comment]
@bradleeedmondson Sorry for the late answer.
My only relationship with the fonts/license is as a packager.
Copyright holder of the fonts is the german font foundry "URW++".
To my knowledge, https://github.com/chris-liddell from Artifex/Ghostscript acts as a proxy here.

**Comment by jlovejoy** [comment]
re: the versioning issue: if we can get the author to provide such info, that is ideal. otherwise, if there is not one, and we don't know of other versions, I also think it's fine to not have a version - if and when a later version comes out, we can add a version number than as well. I think we have had this scenario.
but I don't feel super strong about any option only that if we use a date, that date should reflect the origin of the exception (I wasn't clear if that was the case here).

In any case, do you think we can get this wrapped up on the next week for v3.2 release?

**Comment by bradleeedmondson** [comment]
Casting this now; decided to go with:
 * Proposed name: AGPL-3.0 font exception PS/PDF 20170817
 * Proposed short identifier: AGPL-3.0-font-exception-PS-or-PDF-20170817

**Comment by wking** [comment]
> * Proposed short identifier: AGPL-3.0-font-exception-PS-or-PDF-20170817

With the `-20170817` versioning being so specific, we probably don't need the `AGPL-3.0-` prefix.  Do you really want `AGPL-3.0-only WITH AGPL-3.0-font-exception-PS-or-PDF-20170817`?

Also, I realize we have precedents for YYYYMMDD dates, but I think it would be easier to read if we stuck with the [standard][1] YYYY-MM-DD.

Both of these are minor nits; any of them would make reasonable names and/or short IDs.

[1]: https://tools.ietf.org/html/rfc3339#section-5.6

**Comment by bradleeedmondson** [comment]
> Do you really want AGPL-3.0-only WITH AGPL-3.0-font-exception-PS-or-PDF-20170817?

Not wedded to it. But I did add the AGPL-3.0 prefix based on the first sentence. However, if I mark that up as optional, then it makes more sense to call this exception like so:

* PD/PDF font exception 2017-08-17
* PS-or-PDF-font-exception-20170817

**Comment by bradleeedmondson** [comment]
This exception was added for 3.2, so closing this issue.

Proposed to address some nits for 3.3 release in #669
