### ISSUE TITLE
Significance of the “has self-referring numbering” label?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#630]
We have a “[has self-referring numbering][1]” label, but I'm not sure what it means.  Do we still need it?  It looks like it was only ever used for the “Automated PR for …” pull requests.

[1]: https://github.com/spdx/license-list-XML/issues?page=2&q=label%3A%22has+self-referring+numbering%22

**Comment by bradleeedmondson** [comment]
This was raised during the initial port-over to github & XML as a potentially useful way to group licenses together. It intersects with (and perhaps interferes with?) our guidance that [bullets can be ignored for matching purposes](https://spdx.org/spdx-license-list/matching-guidelines) (which implies that bullets are not legally significant). But arguably if a license text internally refers to some of its clauses by number, they become legally significant (e.g., "paragraphs 5, 6, and 7 survive the termination of this agreement").

This is probably something that we should eventually deal with, though I confess no elegant solutions have come to mind.

**Comment by wking** [comment]
On Thu, Apr 05, 2018 at 05:46:17PM +0000, Bradlee H. Edmndson wrote:
> This is probably something that we should eventually deal with,
> though I confess no elegant solutions have come to mind.

I'd like to drop the bullet matching guideline and replace it with
explicit alt/optional tags.

**Comment by jlovejoy** [comment]
as this label stopped being used / useful later on in the XML conversion process, as we realized it was numbering matching was probably not critical to make this distinction (from non-matching numbering/bullets) in terms of practical reality and understanding ,
I think we can close this issue, as it's a... wait for it... non-issue!
let me know if you disagree, otherwise I'll close prior to the next meeting
