### ISSUE TITLE
New Exception Request: Google patent grant

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#646]
from email: 

Google uses a standard "Additional IP Rights Grant (Patents)" text in a lot of projects they've been publishing - {} sections are mine:

'''
Additional IP Rights Grant (Patents)

"These implementation{s}" means the copyrightable works {that implement the Product} distributed by Google as part of the {Project}.

Google hereby grants to you a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, transfer, and otherwise run, modify and propagate the contents of these implementations of {Product}, where such license applies only to those patent claims, both currently owned by Google and acquired in the future, licensable by Google that are necessarily infringed by these implementations of {Product}. This grant does not include claims that would be infringed only as a consequence of further modification of these implementations. If you or your agent or exclusive licensee institute or order or agree to the institution of patent litigation or any other patent enforcement activity against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that any of these implementations of {Product} or any code incorporated within any of these implementations of {Product} constitutes direct or contributory patent infringement, or inducement of patent infringement, then any patent rights granted to you under this License for these implementations of {Product} shall terminate as of the date such litigation is filed.
'''

Sources: https://webrtc.org/license/additional-ip-grant/,  https://www.webmproject.org/license/additional/, https://github.com/ImageMagick/webp/blob/master/PATENTS, https://golang.org/PATENTS

Discussed on May 17th call. need to determine what markup is needed and title (then make PR)

**Comment by bradleeedmondson** [comment]
To clarify, discussed today and accepted for inclusion on "Exceptions" list.

**Comment by swinslow** [comment]
I'll prepare the files for this one for 3.2.

**Comment by swinslow** [comment]
Jilayne and Bradlee - I've taken a closer look at the Google patent exception. It turns out that they've actually used several slightly different versions, with substantive differences. E.g., WebRTC's doesn't include "royalty-free"; WebM has a broader scope of conditions that trigger termination; etc.

I'll prepare separate versions for each different version that I've found. If this warrants further discussion on a future call in light of the differences, we might consider pushing it out past 3.2.

**Comment by jlovejoy** [comment]
discussed on July 26th call: @kestewart and @swinslow to reach out to Google to get input and raise awareness of 3 variations. @swinslow has diff - there are legally substantive differences in the patent grant (patents "owned" or "owned and controlled"); when the patent terminations ("patent litigation" or "any other patent enforcement activity"); and scope of the license grant in terms of "royalty free" or omits that language)

**Comment by jlovejoy** [comment]
@swinslow discussing differences/intent with Google lawyer

**Comment by jlovejoy** [comment]
last word was that variations were not intended, Google lawyer checking in on that. But considering that they are all in the wild, then probably need to have all, but want to hear back from them on steer as to how to proceed.

**Comment by reversi-fun** [comment]
There is a shorter, essential license.
I hope to review the similarity.

WebM Bitstream Specification License https://github.com/spdx/license-list-XML/issues/842
https://www.webmproject.org/license/bitstream/

**Comment by MarkAtwood** [comment]
If we don't template the name of the company, then this is Google-specific.

I recommend scoped license id   LicenseRef-.google.com.-PATENTS-{modiferstuff}

**Comment by swinslow** [comment]
This one has been sitting inactive for quite a while. I had originally drafted a PR for it but then withdrew it.

My main concern is that, having dug into them more closely, I don't think these can be appropriately described as "exceptions." I think that in most if not all other cases, an "exception" is something that in essence boils down to "you don't have to do X." E.g., "you can link my GPL code with project X and distribute them even though X isn't under GPL"; or "if you do Y then you don't need to comply with section 4 of the license"; or so on.

I don't think these Google patent grants really fit that framework. They aren't exceptions to the underlying license. If anything, it's arguably more like a modification to the underlying license, almost comparable to something like the Commons Clause.

There was a discussion a while back about whether the "exceptions list" should be something broader -- license modifications? something else? -- but I don't think an appropriate alternative term was ever settled on. So unless that discussion is reopened, I'm kind of inclined to just close this issue, because I really don't feel that the "exception" label fits here.

**Comment by jlovejoy** [comment]
I'm closing this for now - we never got feedback from Google, it's really old, and it cuts into a bigger conversation about the scope of "exceptions" and what that includes. we can revisit if/when we revisit that conversation.
