### ISSUE TITLE
Clarify under which license the license list itself is licensed

### ISSUE THREAD

**Issue by sschuberth** [spdx/license-list-XML#648]
Could we please get an according `LICENSE` file in this repository? And the same for https://github.com/spdx/license-list-data?

**Comment by jlovejoy** [comment]
this question of needing a license to re-publish licenses was raised on the mailing list (and has been asked about a couple times in the past) and was answered there by several lawyers - tl;dr license not needed here. Since this is a question that has come up a few times over the years, a few of the lawyers will draft an explanation and put it in our wiki so we have one answer for any other occasion when this gets asked.

**Comment by wking** [comment]
Can it go into a `COPYING` file in this repo?

**Comment by jlovejoy** [comment]
no. we will put it where we have put other things of this nature. it would not be appropriate for a COPYING file here in any case.

**Comment by wking** [comment]
> no. we will put it where we have put other things of this nature. it would not be appropriate for a COPYING file here in any case.

But it covers the legality of copying this repo's content.  I don't understand why we wouldn't want the statement itself in this repo, but if the statement lives somewhere else I think we'll need at least a link to it from here.  I expect at least some folks finding this repository will not think to search the wiki for this repo's copying conditions.
