### ISSUE TITLE
`EUPL` identifiers for `-only` and `-or-later`

### ISSUE THREAD

**Issue by bberberov** [spdx/license-list-XML#752]
I was reading the new guidelines for `GPL` and I think there should be separate identifiers for `EUPL` too.

This is discussed in the license text (v. 1.2) here:

> Copyleft clause: If the Licensee distributes or communicates copies of the Original Works or Derivative Works, this Distribution or Communication will be done under the terms of this Licence or of a later version of this Licence unless the Original Work is expressly distributed only under this version of the Licence — for example by communicating 'EUPL v. 1.2 only'. The Licensee (becoming Licensor) cannot offer or impose any additional terms or conditions on the Work or Derivative Work that alter or restrict the terms of the Licence.

Please clarify identifier usage.

**Comment by bberberov** [comment]
Updated ETA?  I saw 3.5 came out.

**Comment by bberberov** [comment]
@jlovejoy Do you plan to re-target this for another milestone?

**Comment by jlovejoy** [comment]
@bberberov sorry! this completely slipped between the cracks.

So, the change for the GPL identifiers to being hard-coded, so to speak, as "-or-later" and "-only" stemmed from a very specific request from the FSF. You can read Richard Stallman's view on the topic overall on his blog post here: https://www.gnu.org/licenses/identify-licenses-clearly.en.html

In the process of this change, we tried to consider all the other licenses with variations of version-or-later or version-only - and in the end, decided to keep everything else as it was, which includes the ability to add the + operator to indicate "or later" as has been the case for some time. 

Interestingly, it looks like EUPL-1.0 did not have any mention of version; EUPL-1.1 added text that created what I'd call a default "or any later version" position; and EUPL-1.2 included that, plus the option to have the "only under this version"

Under the current options with the operators, then:

- EUPL-1.2  would mean that version only (like the previous state for the GPL family) and EUPL-1.2+ or any later version
- EUPL-1.1  / EUPL-1.1+ would mean effectively the same thing, since there is only one option (this is similar to a bunch of other licenses, as we found)
- EUPL-1.0 would just simply not need or desire any operator for any reason

I realize this is not very tidy. Trust that we spent a ton of time trying to figure out to best accommodate the FSF's request and not disrupt use of SPDX identifiers so far.  It's probably not perfect, but given the amount of discussion and many minds thinking about this I am convinced there is probably not a perfect solution that works for all variations of this kind of text. 

That may not be a satisfying answer, but it's the full story (so far)!

**Comment by bberberov** [comment]
Oh.  I was not aware the `+` option can be applied to any license, if permitted. (I just found it in the 2.1 spec)!  I guess that works for the identifier.  I'm mainly concerned with 1.2, plus or no plus, but this detailed explanation helps a lot.  Thanks!
