### ISSUE TITLE
http://glassfish.java.net/public/CDDL+GPL_1_1.html redirects to an irrelevant page

### ISSUE THREAD

**Issue by ppalaga** [spdx/license-list-XML#786]
The first crossRef URL in CDDL-1.1.xml
http://glassfish.java.net/public/CDDL+GPL_1_1.html currently redirects to https://javaee.github.io/glassfish/ where no CDDL license text occurs.

I guess the first crossRef can be removed as the second crossRef https://javaee.github.io/glassfish/LICENSE delivers the expected content.

**Comment by ppalaga** [comment]
Related https://github.com/spdx/license-list-XML/issues/433

**Comment by swinslow** [comment]
Hi @ppalaga, per @jlovejoy's note at https://github.com/spdx/license-list-XML/issues/433#issuecomment-469884131 and the [SPDX license list overview](https://spdx.org/spdx-license-list/license-list-overview), we don't remove old URLs as they may still be useful for matching references to the license in old code. 

We may add new or best available URLs, but since the second link to the GlassFish site is still valid it doesn't look like you're requesting that new links be added here, so I will go ahead and close this issue.
