### ISSUE TITLE
New license request: Universal-FOSS-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by yevster** [spdx/license-list-XML#825]
**1.** License Name: The Universal Foss Exception
**2.** Short identifier: Universal-FOSS-exception
**3.** License Author or steward: Oracle
**4.** Comments: This exception is used by MySQL's JDBC connector in combination with GPL-2.0:

https://github.com/mysql/mysql-connector-j/blob/release/8.0/LICENSE
**5.** URL: https://oss.oracle.com/licenses/universal-foss-exception/
**6.** OSI Status: Not Submitted

**Comment by jlovejoy** [comment]
thanks @yevster ;)

**Comment by reversi-fun** [comment]
fine!
I also wanted to make a request.

But I was lost,  because ,it likes spdx/deprecated_GPL-2.0-with-GCC-exception, spdx/389-exception.

https://github.com/reversi-fun/license_doc_similality1/blob/master/data/lic_graph.sfdp.svg

![universal-foss-exception](https://user-images.githubusercontent.com/2231549/55127049-2e737f00-5152-11e9-8e7f-223188b0f5e9.png)

**Comment by swinslow** [comment]
+1 from me on including this.

Any thoughts on whether Oracle's name should be included in the license name / ID? Or if we're good with just calling this the "Universal FOSS Exception"?

**Comment by jlovejoy** [comment]
+1 from me on adding.

I don't think Oracle's name need be included, but checking with contact at Oracle on that (and anything else that is relevant here)

**Comment by jlovejoy** [comment]
looking at this further, no reason to add Oracle's name - the link to the exception clearly uses the name above. 

@yevster since you requested this, could you add the PR to create the XML and .txt files for this to be added: :) 
see https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md

**Comment by swinslow** [comment]
All, please take a look at the PR at #878 and weigh in if you have any comments / concerns.
