### ISSUE TITLE
New license request: WebM-Spec [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by reversi-fun** [spdx/license-list-XML#842]
**1.** License Name: WebM Bitstream Specification License
**2.** Short identifier: WebM-Spec
**3.** License Author or steward: Google WebM Project
**4.** Comments: This is BSD-3-Clase with Patent Cross-License.

The license url that FSF has called WebM has differentiated into three.
https://www.webmproject.org/license/software/
WebM Software License: This is a variant of BSD-3-Clause.

https://www.webmproject.org/license/bitstream/
WebM Bitstream Specification License:This is a license similar to the BSD-3-Clause, with the mention of the patent cross license.

https://www.webmproject.org/license/additional/
Additional IP Rights Grant (Patents);
This looks like a variant that(WebM Bitstream Specification License) adds about 10 words to the previous license.

https://www.webmproject.org/cross-license/vp8/agreement/
WebM VP8 Patent Cross-License;
This is also similar to the previous(WebM Bitstream Specification License), but with a lot more clauses added.

Ask if these three should all be considered separate licenses or be considered variants.
**5.** URL: https://www.webmproject.org/license/bitstream/
**6.** OSI Status: Approved

**Comment by reversi-fun** [comment]
I will add evidence that analyzed the similarity.

![license-WebM-bitstream](https://user-images.githubusercontent.com/2231549/55278824-b7f29f00-5354-11e9-971d-5376fda41aeb.png)

"WebM VP8 Patent Cross-License" is same as "Google patent grant" at spdx.3.6.https://github.com/spdx/license-list-XML/issues/646

**Comment by reversi-fun** [comment]
I add evidence that analyzed the similarity, for FSF/WebM related license {spdx/AMPAS,calculate-Linux/UCAR-BSD,BSD-3-Clause}

![license-WebM-soft](https://user-images.githubusercontent.com/2231549/55279292-6e0cb780-535a-11e9-87d5-4edd225acbab.png)

**Comment by reversi-fun** [comment]
I shows the beginning of confusion of licenses to be distinguished.
WebM-spec license similar to has following.
    * "Mozzila-opsl-1.0"
    * "facebook-patent-rights-2"
    * "FreeType-patent"
    * "MS-patent-promise"
    * "google-patent-license-golang"

The above license The following license should be distinguished by some other identification name.
   * "google patent license WebM"(=WebM Additional IP rights Grant)
   * "google patent license webRTC"

![license-webM-cross-patent](https://user-images.githubusercontent.com/2231549/55668915-604fb880-58ab-11e9-8c18-8f4ffeed84c1.png)


The license names listed above are distributed with tools such as scanCode-toolKit.

**Comment by swinslow** [comment]
I see four different license requests here, addressing each in turn:

- **Software License**: https://www.webmproject.org/license/software/: From a cursory look this appears like it matches BSD-3-Clause when the [SPDX matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) are taken into account. If there are any substantive differences, please note them, otherwise this does not need to be added as a separate license.

- **Google IP Rights Grant (Patents)**: https://www.webmproject.org/license/additional/: As you noted above, this falls into the bucket covered by issue #646 and should likely be considered as part of that issue, together with the other similar Google patent grants.

- **WebM Bitstream Specification License**: https://www.webmproject.org/license/bitstream/: This is a specification license, not a software license. At present (to my knowledge) SPDX doesn't generally include specification licenses on the License List.

- **VP8 Patent Cross-License**: https://www.webmproject.org/cross-license/vp8/agreement/: This was separately submitted in #844 and as mentioned there I do not think it should be added to the License List.

Given the above feedback, unless there is a substantive difference in the Software License text that I'm not seeing, or unless others feel the Specification License should be added (which in that case might be more appropriate for a Legal Team discussion), I suggest this issue should be closed.

**Comment by reversi-fun** [comment]
What does the license that FSF calls WebM call with spdx?
It is important to map the license that FSF calls GPL-compatible to the license of SPDX.
I am satisfied with what was revealed by the similarity analysis of the license terms.

  * WebM Software License : SPDX/BSD-3-Clause : GPL-compatible
  * WebM Google IP Rights Grant (Patents) : SPDX/Google patent grants : GPL-Incompatible.
  * WebM Bitstream Specification License : SPDX not includes ? : GPL-Incompatible.
  * WebM VP8 Patent Cross-License : SPDX not includes #844  : GPL-Incompatible.

https://directory.fsf.org/wiki/License:WebM
 * License:WebM
 * URL http://www.webmproject.org/license/ 

https://www.gnu.org/licenses/license-list.en.html
   FSF says that:
    ``` Google also provides a separate patent license (confusingly called an “Additional IP Rights Grant”) for patents that Google owns or controls that are necessarily infringed by their implementation of WebM.```

----
"Specification License" vs "implementations of the WebM Specifications".
My understanding is as follows:
  * Google said In a dispute with Oracle: API Specification may be "fare use" and not protected by copyright.
      https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.
  * Google WebM project says: WebM Bitstream Specification Licenses "implementations of the WebM Specifications".
      SO, "implementations of the WebM Specifications" is software.
      Constrain the implementation of similar software.
  * If  License Author of WebM("Google WebM project") and "Google inc." are different personalities, 
    my understanding may be wrong.
    and License Author of "SPDX/Google patent grants" should be modified.

As a license that raises similar arguments, I will also propose a Java-Specification license.

**Comment by goneall** [comment]
FYI - there is an[ online JSON file](https://wking.github.io/fsf-api/licenses-full.json) which provides a mapping of FSF licenses to SPDX ID's generated by the [fsf-api](https://github.com/wking/fsf-api).  

I searched WebM and did not find an SPDX ID - which is consistent with @swinslow comment on not including specification licenses.

**Comment by reversi-fun** [comment]
I See.  Consistency or policy does not change with just one sample.

But,,, About the possibility of 
adding "License for Specifications with Reference Implementation"
instead of "specification licenses",
In the second case #847 ,
I hope to change.
In the second example, I hope to change.

**Comment by swinslow** [comment]
Discussed on 2019-04-18 Legal Team call:

- Software license: appears to match to BSD-3-Clause and therefore will not be added as a separate license
- Additional IP rights grant: will be tracked in #646 
- Specification license: will have a broader discussion re: whether to include spec licenses
- Patent cross-license: agreed as not appropriate for inclusion on license list

**Comment by swinslow** [comment]
Discussed on 2019-06-13 legal team call, agreed to close.
