### ISSUE TITLE
New license request: OGC [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mterron** [spdx/license-list-XML#845]
**1.** License Name: GeoAPI - Programming interfaces for OGC/ISO standards
**2.** Short identifier: OGC
**3.** License Author or steward: Open Geospatial Consortium, Inc.
**4.** Comments: 
**5.** URL: http://www.geoapi.org/tools/license.html
**6.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
I think the terms of this license generally meet the SPDX [license inclusion principles](https://spdx.org/spdx-license-list/license-list-overview).

That said, do you know if this license (or a templated form with different copyright holder names) is used elsewhere? Or is this only used by Open Geospatial Consortium?

**Comment by mterron** [comment]
I don't know, sorry.

**Comment by jlovejoy** [comment]
@mterron - do you work for Open Geospatial Consortium? (or have contact with someone who does?) 
It helps to have the license author/steward aware of or involved in a request

**Comment by mterron** [comment]
Not at all

**Comment by jlovejoy** [comment]
I agree with @swinslow that it looks like a bit of additional markup to W3C could make it a match and then use that short identifier. I have just logged an issue here: https://github.com/opengeospatial/geoapi/issues/45 in hopes that someone from Open Geospatial can weigh in. If we added the markup, would be great if they wanted to use the SPDX identifier!

**Comment by desruisseaux** [comment]
Hello. GeoAPI is licensed under OGC software license:

* http://www.opengeospatial.org/ogc/software

(I need to update the text in http://www.geoapi.org/tools/license.html - it is supposed to be a copy-and-paste from above link). In my understanding this a BSD-like license. A FAQ is available there: http://www.opengeospatial.org/ogc/legalfaq - quoting the "OGC software" item:

> As documented, OGC software can be modified and redistributed provided that you comply with the terms of the Software and Document Notice. Basically that means you must: include a link to its source on the OGC site, the copyright statement (the full notice for reference if possible) and other relevant terms and conditions; and that you respect the trademarks of its originator. In a few instances, software distributed by the OGC is provided by another entity under specific terms and conditions which must be followed. Please review any notices or disclosures that accompany the software itself.

The last sentence in above quote does not apply to GeoAPI; OGC is the sole entity owning GeoAPI.

**Comment by jlovejoy** [comment]
thanks @desruisseaux - let me clarify the question here: someone has requested to add your license to the SPDX License List. the first point of consideration is whether the license is already on the list or if it's close enough to a license already on the list (according to our https://spdx.org/spdx-license-list/matching-guidelines ) such that additional matching markup would make it a match to an existing license.

Your license is very very similar to the https://spdx.org/licenses/W3C-20150513.html - the only differences being:
1.  addition of "using" and "use" in the first two sentences/grant
2.  use of "software and documentation" v "work" in the original in a couple places or "documentation" instead of "document"
3. The text regarding the short notice to include is also a bit different

@swinslow @bradleeedmondson and other legal team members - seems like the difference in #1 could arguably be considered legally different to fall outside our matching guidelines and suggest adding as new license??

@desruisseaux - do you know if anyone else is using this license, but with the name (Open Geospatial Consortium) changed accordingly?

**Comment by ogcscotts** [comment]
The situation is actually a little more complex. The GeoAPI standard document is licensed under OGC's normal document licensing terms as shown on the second page of: https://portal.opengeospatial.org/files/?artifact_id=71648.

Code/software associated with GeoAPI is licensed per the terms @desruisseaux described and available here: http://www.opengeospatial.org/ogc/software.

This software notice is exceptionally similar to that of W3C. I think that both organizations borrowed from the same original source many years ago. I don't consider the two licenses to be exactly equivalent: the OGC one is specific as to what "work" is and the short notice is different.

**Comment by desruisseaux** [comment]
Thanks @ogcscotts  for the clarification. I presume that the submitter is referring to Java interfaces (@mterron is that right?), which seem to be on the code/software side.

But I would like an additional clarification… There is two pieces of code that come with GeoAPI standard:

* Java interfaces for GeoAPI conformant applications. Those interfaces are part of GeoAPI specification and play a role similar to XML schemas in Java world (or C# world, _etc._), or similar to OpenAPI in web applications.
* Conformance tests, examples, bridges to some popular libraries (non-normative), _etc._

The _"Is a schema or document definition (DTD) covered by the document or software terms?"_ section in [OGC legal FAQ](http://www.opengeospatial.org/ogc/legalfaq#DTD) contains the following:

> Schemas (and DTDs) are frequently part of our specifications and seemingly fall under the document copyright terms. However, as long as you do not use the same formal namespace or public identifier to identify that modified OGC schema/DTD (which might confuse applications), you may treat the schema/DTD under the software terms.

So just to clarify, do we (at OGC) handle programming language interfaces that define API (not to be confused with code/software for tests, examples, _etc_.) the same as schemas and DTD? If so, what should be the wording in the license file that come with normative API interfaces?

**Comment by ogcscotts** [comment]
If the programming language interface definitions are normative, they are covered by the OGC document license for the standard in which they are found. The software license only applies if those interface namespaces or public identifiers that are modified. We are in the midst of assessing whether we need to adjust license terms as these interface definitions become ever-more machine readable.

**Comment by desruisseaux** [comment]
So in my understanding:

* The `geoapi-3.0.1.jar` file [published on Maven Central](https://search.maven.org/artifact/org.opengis/geoapi/3.0.1/bundle) should be under OGC document license, because those interfaces are normative according [GeoAPI specification](https://portal.opengeospatial.org/files/?artifact_id=71648).
* All other `*.jar` files (tests, examples, _etc_) are under OGC software license or public domain.
* The `geoapi-3.0.1.jar` file fall under OGC software license if user changes the module name and package names from `org.opengis` to something else.

However the [current `LICENSE.txt` file](https://raw.githubusercontent.com/opengeospatial/geoapi/3.0.1/LICENSE.txt) bundled into the `geoapi-3.0.1.jar` file is the OGC software license (or an older version of it). Would it be fair to said that this license still apply to that specific version, and will be updated in a next GeoAPI version after OGC made a decision about machine-readable interface definitions?

**Comment by ogcscotts** [comment]
@desruisseaux Short answer: yes!

**Comment by MarkAtwood** [comment]
I suggest:
LicenseRef-.geoapi.org.-OGC-1.0 for the license currently bundled into geoapi-3.0.1.jar
LicenseRef-.geoapi.org.-OGCDOC-1.0 for the published "OGC document license"
LicenseRef-.geoapi.org.-OGC-2.0 for when the OGC updates the license

**Comment by jlovejoy** [comment]
so, @MarkAtwood - are you suggesting (by implication) these should not be added to the SPDX License List and recommending specific LicenseRef- namespace (as per section 6 of the SPDX spec)

**Comment by MarkAtwood** [comment]
Yes, that is what I am suggesting.

**Comment by desruisseaux** [comment]
Maybe drop the "geoapi.org" part in the identifier since those licenses are defined by OGC for all their work (not just GeoAPI)? Especially since there is other OGC standards more well known than GeoAPI, and some peoples may want to refer to OGC licenses for them. Possibly:

* `LicenseRef-OGC-software`
* `LicenseRef-OGC-documentation`
* Future license to be determined, maybe something like `LicenseRef-OGC-standard`.

@ogcscotts what do you think?

**Comment by zvr** [comment]
Continuing to @MarkAtwood 's suggestion, if we go towards the LicenseRef namespaces route, I'd rather use the `--` namespace type than the `-.` one. These licenses actually present a nice use case for it.
I mean something like `LicenseRef--OGC-Software-1.0` based on @desruisseaux latest naming suggestion.

From my understanding, the `-.` namespace should be left to the domain owner (after all, you wouldn't want me to start using `-.amazon.com-` indiscriminately, right? ;-)). Additionally, I think we agreed that in the case of `-.dom.ain-something` the owner of `dom.ain.` should publish their licenses XML, etc.

**Comment by MarkAtwood** [comment]
I'm fine with "LicenseRef-OGC-documentation".  I suggested the domain name based name "LicenseRef-.geoapi.org.-OGC-1.0" because when I read the license, it looked like only that org could apply that license.

**Comment by desruisseaux** [comment]
Actually GeoAPI does not exist as an organization; only OGC has legal existence. GeoAPI was the name of an effort that started outside OGC, then get merged with an OGC project (named GO-1). So the GeoAPI name has only historical meaning now.

**Comment by swinslow** [comment]
Circling back on this old issue -- the discussion above went in a number of different directions, so let me try to summarize. I think there's two open questions:

1) Can markup be added to [W3C-20150513](https://spdx.org/licenses/W3C-20150513.html) to make it a match for this license?

@jlovejoy, you asked about this above in  https://github.com/spdx/license-list-XML/issues/845#issuecomment-497449630 and noted some differences:

>     1. addition of "using" and "use" in the first two sentences/grant
> 
>     2. use of "software and documentation" v "work" in the original in a couple places or "documentation" instead of "document"
> 
>     3. The text regarding the short notice to include is also a bit different
 
and I tend to think that at a minimum, some of the changes in 1 are sufficiently different that it could arguably be a substantively different license. So I wouldn't be in favor of marking up W3C-20150513; if it's added to the list, it should be as its own license.

2) Should it be added to the license list, or should it fall into the category of "private LicenseRef namespaces" instead?

Speaking for myself, I wouldn't object to adding it to the list, since it's a pre-existing / historical license (as opposed to a brand-new single use license) and I think it fits the license inclusion principles.

**Comment by swinslow** [comment]
Discussed on 2020-01-02 legal team call -- agreed that this could be seen as substantively different from W3C-20150513, and should not therefore be handled as markup to that license.

Agreed to accept for inclusion on the list.

**Comment by swinslow** [comment]
@bradleeedmondson, just checking back, do you expect to have a PR for this sometime in the next few days (before the 3.8 release)? If not, no worries, we can move it to 3.9.

**Comment by swinslow** [comment]
Hi @bradleeedmondson, the target release date for 3.9 has been moved out to the end of April. Do you expect to have a PR for it before then? If not, no worries but I may take it myself or see if someone else can take it.

Separately, I would suggest that when this is added, that it use the identifier "OGC-1.0" rather than just "OGC". I think we're trying to version licenses wherever possible even where no version number is specified in the text, in the event that future changes are made so that they can be easily distinguished.

**Comment by swinslow** [comment]
@jlovejoy @bradleeedmondson @desruisseaux I've submitted the PR at #1004 to add OGC-1.0 to the license list. If you have a moment to take a look and give it a +1 or let me know any questions / concerns, that would be great. Thanks!

**Comment by ghobona** [comment]
@swinslow I have recently been assigned the task of supporting SPDX listing of the OGC license. Instead of merging PR https://github.com/spdx/license-list-XML/pull/1004 let me put some versioning information on the license and URI first, please.

**Comment by swinslow** [comment]
@ghobona Sounds great, thanks! I'll close PR #1004 for now and can update / open a new one after you finish the updates on your side.

**Comment by swinslow** [comment]
@ghobona I see that "Version 1.0" has been added at https://www.ogc.org/ogc/software/1.0, is that finalized now? Are there any other changes pending?

**Comment by ghobona** [comment]
@swinslow The changes are complete. Nothing else is pending.

**Comment by swinslow** [comment]
Steve to update PR for version 1.0 text and re-submit.
