### ISSUE TITLE
add markup to MIT

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#866]
can we add markup to MIT license to accommodate differences in how "the 'Software'" is defined?  I don't think this is legally substantive, but just another way of saying a similar thing:

original says: "to any person obtaining a copy of this software and associated documentation files (the "Software")"

variation: "to any person obtaining a copy of this source file (the "Software")"

This variant of MIT is used in the Linux kernel

see: https://github.com/torvalds/linux/blob/master/drivers/block/xen-blkfront.c

**Comment by jlovejoy** [comment]
also, it would be helpful to add markup in the disclaimer for the odd scenario when someone puts their name in there instead of just "the authors or copyright holders"

**Comment by silverhook** [comment]
Makes sense to me.

If we’re already butchering MIT, I would suggest we wrap the copyright statement into an `<optional>` tag as well. I have reasons: https://github.com/fsfe/reuse-docs/issues/16

**Comment by jlovejoy** [comment]
@silverhook but the copyright notice is always options as per the matching guidelines and has its own tag. I don't think we have also used the optional tag.  @goneall @zvr - can you confirm (or correct)?

**Comment by goneall** [comment]
Currently, the license publisher doesn't create alt or optional text for the `copyrightText` elements in the XML.  I added an issue https://github.com/spdx/LicenseListPublisher/issues/48 to automatically add this when publishing.

I am thinking it should be implemented as a variable text (rather than optional).  The variable text could be empty which would also support optional (e.g. regex `.*`).

It is an easy fix and I could update this before the next release - @jlovejoy @silverhook @zvr - let me know if you agree/disagree with this approach.

**Comment by silverhook** [comment]
I think variable text (regex `.*`) is a good approach.

I did not know that the copyright notice in MIT/BSD-*/etc. was already optional. That is a huge relief :) Do the SPDX Tools also take that into account?

Currently both MIT and BSD texts in license-list-data include the template text of the copyright statement in the license text/template. See e.g.:

- https://github.com/spdx/license-list-data/blob/master/text/BSD-3-Clause.txt
- https://github.com/spdx/license-list-data/blob/master/text/MIT.txt

**Comment by goneall** [comment]
> Do the SPDX Tools also take that into account?

Yes and no.  It will take `optional` into account, but I don't think it would produce the expected result.  The way optional is treated is that the entire string enclosed in the optional tags are either entirely present or completely missing.  For copyrights, I believe the intent is to allow different copyright text to be added which would require `alt` rather than `optional`.

For the copyright text, I'm planing to automatically add the equivalent of an alt tag with a `.*` regex on the next release of the license list publish - I hope to get this and a few other fixes in before the next release of the license list.  If I get those fixes in, it should take care of this issue since MIT already has the copyright tags.

**Comment by jlovejoy** [comment]
see #883 which partially implements this... may need help

**Comment by jlovejoy** [comment]
discussed this on 6/27 call - will merge for markup for disclaimer. But difference in definition of "the Software" could be legally different, so holding on that (currently only found in one kernel file)

**Comment by swinslow** [comment]
I've submitted a PR at #962 to fix this. That PR would basically allow anything to be used in the definition of "Software", so if that doesn't fit with what you're looking for, then we might need more specific details for what approach to take.

**Comment by swinslow** [comment]
Discussed on 2020-01-02 legal team call, agreed that this particular instance ("this source file") is appropriate to treat as MIT, but there is discomfort with the "anything matches" solution in #962. Want to discuss on subsequent call with @goneall @pombredanne or other tool-minded folks about how best to handle.

**Comment by goneall** [comment]
@swinslow I took a look at PR #962  It would probably make sense to have a discussion on what the range of possible matches would be acceptable.  

There are a lot of ways to restrict the regular expression, so we just need to decide what restrictions we think would work.  They can be words required to be in the match, words that can not be in the match and also the length of the match.  Let me know if you want to discuss on one of the upcoming legals calls and I'll put it on my calendar or if you'd just like to discuss in a separate call.

**Comment by swinslow** [comment]
Discussed on 2020-01-30 legal team call, agreed that further discussion is warranted on the bigger-picture question. For this particular one, will plug in the two alternatives (original and "this source file") for now, and may re-evaluate going forward.
