### ISSUE TITLE
New license request: [Revised] LicenseRef-.owasp.org.-SI-1.0 :  [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by sam-aldis** [spdx/license-list-XML#869]
**1.** License Name: OWASP Shared Intel License
**2.** Short identifier: OWSI
**3.** License Author or steward: Samuel Aldis on Behalf Of The OWASP Foundation
**4.** Comments: Working document but there are a lot of people in the security industry that would benefit from protection from misuse of their code etc.
**5.** Standard License Header: The OWASP Shared Intel License 
[OWSI License]
Use and Distribution of Intel
As an end user, intermediate or organization not included in the creation of the code this license refers to you agree you understand fully that it has been released to better the industry and improve awareness if this of relevance. In continuing to use, view or copy any part of the intel you shall agree that you are not to behave nor seem to have intention to behave as a “Bad Actor” and that you will both uphold the reputation of the attached parties and will give credit and attribution if you use any part of the original Intel.
**6.** URL: https://www.owasp.org/index.php/OWASP_Shared_Intel_License
**7.** OSI Status: Not Submitted

**Comment by jlovejoy** [comment]
@sam-aldis  - so, it sounds like the final license text is not decided upon and it is still a work-in-progress?  If that is the case, then we wouldn't review and potentially add it to the SPDX License List until it is finalized. We can keep this issue and just flag it as waiting for follow-up and you can update it at that point (or close and re-submit).

**Comment by sam-aldis** [comment]
That's great i just wanted to get the ball rolling as there's a push for more projects to come out of the foundation.

Sent from my Windows 10 device

**Comment by MarkAtwood** [comment]
I suggest scoped license identifier LicenseRef-.owasp.org.-SI-1.0

**Comment by sam-aldis** [comment]
All good with me @MarkAtwood thanks for the input!

**Comment by pombredanne** [comment]
@MarkAtwood you wrote:

> I suggest scoped license identifier LicenseRef-.owasp.org.-SI-1.0

It may be a tad preliminary to suggest using such identifiers yet as this is not yet something that has been fully specified and accepted and may still evolve?

**Comment by swinslow** [comment]
Hi @sam-aldis, there may have been a miscommunication in the comments above about using a scoped license identifier. That is something that is separate from listing a license on the license list (and which the SPDX team needs to better document / establish for usage outside the license list).

Related to @jlovejoy's earlier comment, it looks like the license you're proposing is still in draft form. Given that, I'm going to go ahead and close this issue. If in the future the license text is finalized, you can re-submit the finalized text at that stage if you want it to be considered for inclusion on the license list. 

Or, in the meantime we may have some better documentation for how the scoped license identifiers work, to enable you to reference it without including on the primary list. Either way, since the license text is not in final form I'm going to close this issue. Thank you!
