### ISSUE TITLE
Add a "Closed" license or similar

### ISSUE THREAD

**Issue by aaronfranke** [spdx/license-list-XML#873]
SPDX license codes are [used by NPM](https://docs.npmjs.com/files/package.json#license). While the goals of SPDX listed [here](https://spdx.org/spdx-license-list/license-list-overview) are about open source licenses, I think that it would be very useful to be able to mark a package as "not open source".

**Comment by goneall** [comment]
This is a common request for many companies I work with.  I currently use `LicenseRef-Commercial-...` to designate a non-open source license which uses a fee and `LicenseRef-Proprietary-...` to designate a non-open source license which does not involve fees.

**Comment by swinslow** [comment]
Hi @aaronfranke, thanks for reaching out on this! It's a good point that you raise... here are a few thoughts.

1. As @goneall mentioned, the `LicenseRef-` format enables a project community (or others) to define identifiers that have whatever meaning you wish to assign to them. The syntax for these identifiers can be found [in the SPDX spec](https://github.com/spdx/spdx-spec/blob/master/chapters/appendix-IV-SPDX-license-expressions.md). NPM might consider defining `LicenseRef-` tags to use for the particular use cases and definitions that they have in mind.

2. If SPDX were itself to add identifiers along these lines, I'm guessing the [License List](https://spdx.org/licenses) might not be the best place for it. When a license is added to the License List, it must have a specified license text that is associated with it -- including markup for templated parts that can change or be omitted, pursuant to [SPDX's matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines). Since 'closed' or 'not open source' can mean any number of different things, it probably isn't suitable for an entry on the License List.

3. Within the SPDX specification itself, there are a couple of identifiers defined with meanings that don't tie to particular license texts. Here's an [example](https://github.com/spdx/spdx-spec/blob/master/chapters/3-package-information.md#313-concluded-license-) -- `NONE` means a conclusion that there is no applicable license, and `NOASSERTION` means that no assertion is being made. 

I could perhaps see a similar concept to what you're describing, being added as an option within the spec itself. I think the challenge there, though, is similar to item 2 above -- people are going to have different definitions of what counts as "closed" or "not open source". And several of the license texts on the license list are not OSI-approved or FSF-free/libre, so I'm not sure currently what an identifier like that would be intended to express.

Long winded way of saying -- I'm guessing that the approach I described in item 1 above might be the way to go, for NPM's purposes that you described.

**Comment by jlovejoy** [comment]
agree with @swinslow comments above re: option 1 - that was what is was made for (to some degree). The reasons it would not work to have a generic "closed" identifier are similar to the conversation we had when it was requested to add a generic "public domain" identifier, which is chronicled here: https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files_(DRAFT)

But in the case of a "closed" license, it's even more challenging, as there is no definition of what that means (arguably there is a definition of public domain, but only in some jurisdictions). 

the namespace proposal that @fallenpegasus proposed might also be helpful. 

@aaronfranke - you might want to join the tech team mailing list for more on that - https://spdx.org/WorkgroupTechnical

**Comment by jlovejoy** [comment]
(otherwise, I think we can close this issue?)

**Comment by aaronfranke** [comment]
What about the ability to write "Other" or something?

**Comment by jlovejoy** [comment]
@aaronfranke I really think you need to read (at least) some of the SPDX Spec. While I understand you are not using the license information in the context of an SPDX document (which is what the SPDX Spec is describing), nevertheless the fields and ways of handling data about s/w packages as described in the SPDX Spec has other uses (no reason to recreate the wheel).

Specifically, you ought to check out:
Section 6 (for info on use of LicenseRef - which is what you should consider using) - https://github.com/spdx/spdx-spec/blob/master/chapters/6-other-licensing-information-detected.md
Section 3 (for package-level info), specifically 3.13 and 3.15 - https://github.com/spdx/spdx-spec/blob/master/chapters/6-other-licensing-information-detected.md
Section 4 (for file-level info), specifically 4.5 and 4.6 - https://github.com/spdx/spdx-spec/blob/master/chapters/4-file-information.md

**Comment by pombredanne** [comment]
@aaronfranke re

> What about the ability to write "Other" or something?

FWIW, we are faced with similar issues in ClearlyDefined and we came to use an `OTHER` license key in license expressions for now because `NOASSERTION` and `NONE` are not enough to express things that have been reviewed but do not have a known SPDX license and we do not have yet namespacing support for orderly usage of LicenseRef outside of SPDX documents.
