### ISSUE TITLE
New exception request: Swift-exception

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#874]
Reported on spdx-legal list 2019-06-04:

Hi,

I would like to request below license exception to be added to the SPDX specification.

This exception is popping up in open source project related the Swift programming language maintained by Apple.

Its text is close in intention to the LLVM-exception but lack the whole GPL-2.0 text found in LLVM.

(...omitting comments re: license submission tool...)

**License Full Name**: Apache 2.0 Runtime Library Exception
**Short Identifier**:  Apache-Runtime-exception-2.0
**Source/URL**:
- https://swift.org/LICENSE.txt
- https://github.com/apple/swift-package-manager/blob/master/LICENSE.txt
- https://github.com/JetBrains/jediterm/blob/64e461c932fb0aac0e05c4546a0002fef47711e7/LICENSE-APACHE-2.0.txt

**OSI Status**: Not Submitted

**License (Exception) Text**:

As an exception, if you use this Software to compile your source code and
portions of this Software are embedded into the binary product as a result,
you may redistribute such product without providing attribution as would
otherwise be required by Sections 4(a), 4(b) and 4(d) of the License.

Thank you,

Thomas Steenbergen
Head of Open Source, HERE Technologies

**Comment by swinslow** [comment]
I think this is appropriate to add as an exception.

On the name and identifier, I'm going to be pedantic and note:

1. The examples list the name as "Runtime Library Exception to the Apache 2.0 License" -- any reason not to use that as the License Full Name? I'd say that phrasing also (slightly) helps avoid an implication that this exception is _from_ Apache, e.g. published by ASF.

2. For the identifier, similarly, I'd suggest shifting it to "Runtime-Exception-Apache-2.0" for similar reasons. It also keeps "Apache" and "2.0" next to each other, where the proposed ID sounds like "2.0" is the exception's version number.

**Comment by jlovejoy** [comment]
+1 to add

**Comment by hen** [comment]
I'd like to object to the name (on behalf of Apache).

This makes it sound like it's a Runtime Exception from the ASF rather than something third parties are creating.

**Comment by hen** [comment]
My proposal:

License Full Name: Runtime Library Exception to Apache License 2.0
Short Identifier: Runtime-Exception-to-Apache-2.0

(though I say this separately from any discussion at the ASF as to whether the ASF objects to this modification without changing the name of the license)

**Comment by swinslow** [comment]
Hi @hen, thanks for weighing in. I think it's a totally valid concern you raised.

In the subsequent comments above ([here](https://github.com/spdx/license-list-XML/issues/874#issuecomment-499207488)), I suggested going with "Runtime-Exception-Apache-2.0" for the short identifier. Are you comfortable with that? I think it's essentially what you suggested but without the "to-" segment (which the SPDX licenses and exceptions generally omit).

If you / ASF feel strongly about the "to-", though, I don't see a problem with including it.

**Comment by jlovejoy** [comment]
I'd really rather not deviate from the naming protocol we've use for all the exceptions, where (if used) the word "exception" is at the end or only followed by a version number -  see https://spdx.org/licenses/exceptions-index.html

it does seem like most of the names otherwise include a project name, not a reference to the license, with the exception of Qt, since that had an exception to GPL and a different exception for LGPL, thus the need for a more detailed distinction. 
closely related to this is, of course, "LLVM-exception" - could this be "Swift-exception" if they are the first to use it and wrote it (or first to copy/modify LLVM)?  

Or - we could use "runtime" - the only identifier where that is used is in the Fawkes-runtime-exception. The GCC exceptions use "runtime" only in the full name, but not in the identifier. 

As for any confusion using "Apache" might cause - let's be careful here, while the ASF may not want to imply that the exception was written by them, it is in fact designed to be applied to an Apache license and that should be able to be expressed.

**Comment by swinslow** [comment]
@jlovejoy I'm good with a name like `Swift-exception`. Whether or not that's the first usage (and whether it predates the longer LLVM version), it's a prominent usage of this exception. And, as you noted, it fits with the pattern SPDX has used for other exceptions.
