### ISSUE TITLE
matching guidelines location / update Appendix / remove from website

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#905]
to ensure people from the legal team see this, opening issue to cross-reference here:
see https://github.com/spdx/spdx-spec/issues/134

**Comment by swinslow** [comment]
Submitted PR to add this in Appendix II at: https://github.com/spdx/spdx-spec/pull/139

**Comment by swinslow** [comment]
This has now been added to Appendix II in the v2.2 version of the spec: see discussion at https://github.com/spdx/spdx-spec/issues/134

However, since the v2.2 spec hasn't yet been released, I don't think we should remove the website version of the matching guidelines. So I'm inclined to keep this issue open until after the v2.2 spec is released. After it is, we can replace the website copy with a pointer to the spec appendix.

I'm changing this from 3.8 to "later release" so that we don't close it and forget, but so that it isn't pending in case the v2.2 spec is not released in the meantime.

**Comment by jlovejoy** [comment]
I've had a task to raise the location of the matching guidelines generally on the tech/legal team mailing lists (and then update them!!) especially with 3.0 pending... updating tags to raise the visibility of this

**Comment by jlovejoy** [comment]
see https://github.com/spdx/spdx-spec/pull/761

once 2.3 is released, then we can:

- [ ]  once that is pushed, remove from website
- [ ]  update all links on website to point to spec appendix (direct link issue?
- [ ] remove page in DOCS for html version

**Comment by jlovejoy** [comment]
see https://github.com/spdx/LicenseListPublisher/pull/139

**Comment by swinslow** [comment]
@jlovejoy Based on https://github.com/spdx/LicenseListPublisher/pull/139 it looks like this has been completed for the updates to the License List website itself.

Was there anything else to be updated under this issue, or can we mark this as complete? Thanks!

**Comment by jlovejoy** [comment]
once the license list is published, the last step is to takedown the matching guidelines webpage (and check website for other links to be updated), but I didn't want to do that until the license list is published b/c that would create a dead lnk in the meantime. I'll close issue once that's done after release :)

**Comment by swinslow** [comment]
@jlovejoy Now that 3.19 is live, it looks like the links on the License and Exception pages are correctly going to the spec appendix now. Do you want to go ahead and take down the old page, so we can close this issue? Thanks!

**Comment by jlovejoy** [comment]
ah, good reminder. I will do so (and then I'll lose this issue).

**Comment by jlovejoy** [comment]
Note, all the links were updated to the direct 2.3 link... so we'll have to update them again when 3.0 comes out. but we can make a new issue for that, I suppose :(
