### ISSUE TITLE
New license request: Bouncy Castle Licence

### ISSUE THREAD

**Issue by pachulo** [spdx/license-list-XML#910]
1. License Name: Bouncy Castle Licence
2. Short identifier: Unknown
3. License Author or steward: The Legion of the Bouncy Castle
4. Comments: It is based on the MIT licence.
5. URL: http://www.bouncycastle.org/licence.html
6. OSI Status: Unknown

**Comment by swinslow** [comment]
Hi @pachulo, thanks for posting this!

I compared the text of the license at http://www.bouncycastle.org/licence.html to the [MIT license text from the SPDX license list](https://spdx.org/licenses/MIT.html). 

The only difference I see is that the Bouncy Castle license omits the "(including the next paragraph)" bit in the middle clause. That fragment is marked up as "optional" in [the XML file for MIT's entry on the list](https://github.com/spdx/license-list-XML/blob/master/src/MIT.xml#L22). Because of that, the Bouncy Castle license would be considered equivalent to MIT for for SPDX matching purposes, and would just use the "MIT" identifier.

Is there something else in the Bouncy Castle license that you think I'm missing? If not, I think we can close this issue. Thanks!

**Comment by pachulo** [comment]
> Because of that, the Bouncy Castle license would be considered equivalent to MIT for for SPDX matching purposes, and would just use the "MIT" identifier.

Do I have to open another issue for that? Or is not SPDX job to do that? Was just guessing if there's any form of “alike licence matching” on SPDX, in order to link software that uses this licence with the MIT one.

> Is there something else in the Bouncy Castle license that you think I'm missing?

No, not really.

**Comment by swinslow** [comment]
Thanks @pachulo -- no need for another issue. That's right, the scope of the SPDX License List does not include tracking which software uses which license. SPDX curates the different license texts. Since "MIT" is the short-form identifier for [the license](https://spdx.org/licenses/MIT.html) that matches Bouncy Castle's license, Bouncy Castle can use the "MIT" identifier in describing its own license.

To your related question, yes, SPDX has [license matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) that are used in considering whether two license texts should be substantively "identical" for these sorts of purposes.

**Comment by jotterson** [comment]
IMHO one of the purposes of having license information in a SBOM is for compliance purposes, specifically attribution and inclusion of the license text when required by the license.  Not having the Legion of the Bouncy Castle license in the SPDX License List makes this proper attribution _and inclusion_ of that license far more difficult.  I realize that there is likely a goal to keep the license list from becoming too large, but I feel like important functionality is lost when specific licenses are grouped.

One possibility is to mark the library "MIT and Legion of the Bouncy Castle."

Thanks for considering this.

**Comment by cuixinye** [comment]
> One possibility is to mark the library "MIT and Legion of the Bouncy Castle."

In my opinion, best solution is that Legion of the Bouncy Castle states the license is MIT, rather than they write a "new" license.
Don't know why they call it Bouncy Castle License, such as https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.76/bcprov-jdk18on-1.76.pom.
Good news is that in their [Github repo](https://github.com/bcgit/bc-java), it shows it's MIT license.
