### ISSUE TITLE
New license request: MulanPSL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by yuwenlong** [spdx/license-list-XML#913]
**1.** License Name: Mulan Permissive Software License
**2.** Short identifier: Mulan
**3.** License Author or steward: 中国开源云联盟
**4.** Comments: 中国首个官方推出的开源协议：木兰宽松许可证
**5.** Standard License Header: Mulan Permissive Software License，Version 1
**6.** URL: http://license.coscl.org.cn/MulanPSL/
**7.** OSI Status: Approved

**Comment by mlinksva** [comment]
Autotranslation of 3 and 4:

> 3. License Author or steward: China Open Source Cloud Alliance
> 4. Comments: China's first official open source agreement: Mulan Loose License

Re:

> 7. OSI Status: Approved

This looks like a clearly open source license to me, but it isn't formally approved yet, or isn't listed at https://opensource.org/licenses/alphabetical yet anyway. https://opensource.org/approval has the steps to request formal approval and get on that list.

As Mulan is in Chinese and English (both official versions?) I wonder if the intent is for a licensor to include both languages in the `LICENSE` file for a project (i.e., a text version of the entire contents of http://license.coscl.org.cn/MulanPSL/ which has both) or only the language the licensor chooses as most relevant to their audience? The latter is what existing licenses with multiple official languages do, but on the other hand, SPDX currently doesn't have a mechanism for cataloging separate texts for each language, see #438 (I would ❤️ to see that addressed).

**Comment by swinslow** [comment]
@yuwenlong Thank you for submitting! A couple of questions / comments:

* Do you have examples of some projects where MulanPSL is being used currently?
* Can you (and/or someone from the license steward, if you aren't affiliated with them) comment on the question by @mlinksva -- is the intent for the license text to include _both_ the Chinese and English versions?
* If this is added to the list, I would recommend that the short identifier be `Mulan-1.0` or `MulanPSL-1.0` since the license itself is called version 1.

I'm not able to read the Chinese version. From the English translation, I think the terms make it generally appropriate to add to the license list, subject to the other criteria in the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) -- such as my question above re: whether it's being actively used in the wild.

**Comment by yuwenlong** [comment]
The content is in English, please click to view, below.
https://license.coscl.org.cn/MulanPSL/


Open source projects used:
https://github.com/yuwenlong/longphp/blob/master/LICENSE


https://gitee.com/longphp/longphp/blob/master/LICENSE



------------------

 

 




------------------ 原始邮件 ------------------
发件人: "Steve Winslow"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 上午8:54
收件人: "spdx/license-list-XML"<license-list-XML@noreply.github.com>;
抄送: "于文龙"<yuwenlong89@vip.qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [spdx/license-list-XML] New license request: Mulan[SPDX-Online-Tools] (#913)




@yuwenlong Thank you for submitting! A couple of questions / comments:
  
Do you have examples of some projects where MulanPSL is being used currently?
 
Can you (and/or someone from the license steward, if you aren't affiliated with them) comment on the question by @mlinksva -- is the intent for the license text to include both the Chinese and English versions?
 
If this is added to the list, I would recommend that the short identifier be Mulan-1.0 or MulanPSL-1.0 since the license itself is called version 1.
  
I'm not able to read the Chinese version. From the English translation, I think the terms make it generally appropriate to add to the license list, subject to the other criteria in the license inclusion principles -- such as my question above re: whether it's being actively used in the wild.

**Comment by mlinksva** [comment]
Based on https://github.com/search?q="Mulan+PSL"+filename%3ALICENSE&type=Code it appears that all LICENSE files (well, I only looked at first few pages) with the full license text has the Chinese and English concatenated, so I guess the license text cataloged by SPDX ought have the same.

**Comment by swinslow** [comment]
@mlinksva raises a good thought at https://github.com/spdx/license-list-XML/issues/438#issuecomment-528614713 about how we represent translations more generally.

For the present, for this one I tend to agree that the license text should include both the Chinese and the English versions, since that does seem to be how it is being used.

I think that this is appropriate to add to the license list. The terms are comparable to other existing permissive-style FOSS licenses, and the GitHub search link that @mlinksva posted above indicates that there's a significant number of projects already using this license.

**Comment by swinslow** [comment]
Based on the prior legal team call, I believe consensus was to approve this license and to include both the Chinese and English texts, since that's how this seems to be used in practice. I will ask the legal team to confirm during today's call, and hopefully we can get this in for 3.7.

**Comment by swinslow** [comment]
Also, given the identifier and versioning referenced in the license text itself, I am going to go ahead and changed the proposed name to `MulanPSL-1.0`

**Comment by swinslow** [comment]
Discussed on 2019-10-03 legal team call, will add with both languages and with a note explaining why both translations are included.

Suggest asking license stewards about whether English translation is required or optional / convenience, but not blocking adding license to list in the meantime.

**Comment by yuwenlong** [comment]
@mlinksva @swinslow 
`3. License Author or steward: 中国开源云联盟`

translation

`3. License Author or steward: CHINA OPEN SOURCE CLOUD LEAGUE`

Please see the logo on the official website.
http://www.coscl.org.cn/

**Comment by dudy5** [comment]
How's going now for mlinksva's question? Do we need to add the both?

**Comment by swinslow** [comment]
@dudy5 Both the Chinese and English versions were added together in the v3.7 release of the license list, see https://spdx.org/licenses/MulanPSL-1.0.html. This issue has now been closed since this was completed.

**Comment by dudy5** [comment]
> @dudy5 Both the Chinese and English versions were added together in the v3.7 release of the license list, see https://spdx.org/licenses/MulanPSL-1.0.html. This issue has now been closed since this was completed.

I wonder why don't add a notice to license document that the content is "Both English document and Chinese document are valid", That is more effective.
