### ISSUE TITLE
License inclusion guidelines

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#925]
A few months ago we began a project to update the license inclusion principles (as well as some other documentation updates in terms of both substance and location).

Specifically, currently the license inclusion guidelines are posted here: https://spdx.org/spdx-license-list/license-list-overview  These were written around 2013 and we recently recognized a need to update them.  (We also had decided we ought to move them to the Github repo, but that is somewhat tangentially to the substantive question here.)  

We have made a first draft of changes based on discussions on the calls https://wiki.spdx.org/view/Legal_Team/Minutes/2019-05-02  You can see that initial iteration here: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md

We recognized there would need to be further iterations. In particular, we have had recent submissions that are arguably not substantive open source licenses (e.g., Commons Clause, Polyform licenses) - should these be included on the SPDX License List and if so, then how does the inclusion principles need to change and where do we draw the line?  

Can you please comment here, so we can iterate on this and then come to a final, new set of inclusion principles.

**Comment by jlovejoy** [comment]
discussion on 4 Sept call: some support for "source available" licenses, but maybe need for other criteria/requirements to kick in, in that case such as: must be re-usable, must be used in wild.

interim draft (https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) notes a bunch of factors that are considered with no delineation of which factors prevail. Perhaps some factors weigh more where others are missing and we can explain that.

**Comment by MarkAtwood** [comment]
My thoughts:
licenses added to the top namespace under this new regime:
* have to be "generally usable", not usable by only one project, consortium, or corporation
* have to be "source available".
* the license has to be "stable", not constantly changing or redlining.
* have to have a license steward who can technically maintain the XML SPDX definitions via github pull requests without excessive hand-holding.

Licenses that dont meet those criteria instead use the DNS namespace.

**Comment by baileywainwright** [comment]
My thought -- and maybe this ought to apply to any proposed license, not just those that don't seem to be "open source-ish": 

- The license must already be seeing some actual substantial use in the wild such that ordinary consumers of open source/open source-ish code are likely to encounter it. If it is reasonably suspected that the license proposer primarily wishes to use addition to the SPDX top namespace as a mechanism for publicizing a new, currently-obscure license, the license should not be included.

**Comment by richardfontana** [comment]
My thought (and perhaps this should apply to proposed licenses generally, not just those considered insufficiently open source-ish):

- The license must see some actual substantial use in the wild such that ordinary consumers of open source/open source-ish code are likely to encounter it. If it is reasonably suspected that the license proposer is attempting to use SPDX top namespace inclusion as a mechanism for publicizing an otherwise obscure, new license, the proposal should be rejected (until there is some demonstration that the license is seeing sufficient real-world use).

**Comment by kemitchell** [comment]
@richardfontana I strongly support clarification of the process for new licenses. If that includes some form of popularity criterion, so be it, as long as it's actionably clear what purpose the criterion serves, how to meet it, what to do in the interim.

The feedback loop between recognition and adoption is tighter for SPDX than other lists, due to its use in package managers. Currently, the viable options for packages under new licenses are:

1. use whatever magic value means "not a standardized license" in the packaging standard

2. use the SPDX identifier you want, and eat validation errors until you get it

If the purpose of a popularity threshold is to defend working group time, I'd suggest formalizing a requirement for license proposers to do the legwork of formatting and sending pull requests. If the purpose is to put a procedural brake of new license creation, I'd suggest making that similarly explicit, so new and old package managers understand what they're incorporating, and whether it tracks their needs.

**Comment by kemitchell** [comment]
@jlovejoy a few quick notes on the draft you linked:

1. Are SPDX' goals and principles listed out somewhere?
2. What did you mean by "relevant open source community factors"?

As a more general point of feedback, I'd add public licensing as a baseline criterion. As far as I'm aware, SPDX hasn't identified any templates for terms offered to specific licensees.

**Comment by jlovejoy** [comment]
> 
> 1. Are SPDX' goals and principles listed out somewhere?
mission and vision are here https://spdx.org/about (which are the originals, but I must say, having re-read, have held the test of time pretty well, IMHO!)

> 2. What did you mean by "relevant open source community factors"?
> 
good question... that drafting was based on my memory and meeting minutes from the call when we discussed it at length a few months ago. This was never meant to be the final-final, just an interim draft to iterate on!

> As a more general point of feedback, I'd add public licensing as a baseline criterion. As far as I'm aware, SPDX hasn't identified any templates for terms offered to specific licensees.

Can you explain more what you mean by this?

**Comment by jlovejoy** [comment]
hey y'all - I just made a PR to add some of the history of how licenses got on the license list and the development of the license inclusion guidelines https://github.com/spdx/license-list-XML/pull/926

We had some of this info buried on the wiki, but it seems sensible to put it at the bottom of this page and I'd been meaning to add that.

I left the original 4 paragraphs that were the intro at the bottom under "OLD COPY" - I think most of this can be removed, but the second paragraph ought to be retained somewhere, as it is a key concept overall. (and contributes to the principles @kemitchell asked about above)

**Comment by swinslow** [comment]
@jlovejoy thanks for adding the history / backstory at #926, I've now merged it.

**Comment by swinslow** [comment]
Sharing some of my own thoughts on changes to the license inclusion guidelines. Will split this into a couple of separate comments:

I agree that SPDX should explicitly permit source-available, non-open-source-ish licenses on the license list. 

Doing so should _not_ be viewed as SPDX endorsing the use of any such licenses for open source projects. There may be more education for SPDX to do around the purpose of the list. 

Rather, including such source-available licenses on the list can help with making it easier to automate detection of, and compliance with, licenses for publicly-available code that folks might encounter in the wild -- even if (in the case of FOSS projects) their goal would be to more easily _avoid_ inadvertently using any of these non-FOSS licenses.

I think the factors that @MarkAtwood and @richardfontana are extremely helpful. I'm having trouble though with moving towards "black line" absolute rules. I think that while we can change and firm up the relevant factors, the project is still going to be better served by going with some form of a "totality of the circumstances" look at things.

For instance, @MarkAtwood -- you mentioned 'No joke or "crayon" licenses' as a rule. I think that's more of a factor to consider than an absolute rule -- a strong one, but could be overcome. E.g., if someone submits what we all understand as a "crayon" license out of the blue, it's likely to be rejected; but if there are 1000 projects in the wild that start using it, I think it would be hard to reject it. (Frankly, although I don't know the full scope of its use in the wild, that's how I view something like [WTFPL](https://spdx.org/licenses/WTFPL.html) being on the list.)

**Comment by swinslow** [comment]
@kemitchell Similarly, I think this is where I have some trouble with us trying to specify "use in the wild means exactly X projects must be using the license." Collaborative software development can take so many different forms, that I'm not sure a requirement that was tied to a specific numeric count of projects or repos would really have much meaning. But I think that's okay, if use in the wild is just one of the "totality of the circumstances" type of factors, rather than a fixed requirement. 

The following is rather rambling, so apologies for the length  :)

The way I view it, the license list's purpose is primarily to facilitate ease of identifying, matching, and thinking about / understanding licenses in an unambiguous way, with particular emphasis and focus towards enabling FOSS development and use.

We could in theory try to include every license that's ever been drafted (FOSS, source-available, proprietary, whatever). And if so, then we could have tens of thousands of license texts and identifiers on the list. It would be near-impossible for folks to sort through what's relevant and what isn't, and I don't think this would practically facilitate people understanding or making decisions about licenses.

Or going the other direction, the list could in theory include e.g. only the top 20 or 10 or whatever most commonly used licenses. Doing so might mean people can more easily reason about those 20 licenses, but would also mean that there's a lot of real-world stuff that's not captured by it.

So the license list exists somewhere between those two extremes. 

I don't think a firm "X number of projects required" line is helpful, because it's hard to make a single number meaningful in all contexts. For instance:
* for a brand new license that (using @MarkAtwood's comment above) the team views as a joke or "crayon" license, and that restricted use or distribution in some clearly non-FOSS way, I'd expect there would need to be _very_ high usage in the wild before it could be added.
* for a new that is clearly FOSS, maybe it only needs to show usage in a handful of projects or a single widely-used project before it's appropriate to add.
* for the next release of a widely-used license that's already on the list, maybe it's appropriate to add even before there's any use in the wild ([EPL-2.0](https://spdx.org/licenses/EPL-2.0.html) strikes me as a possible example).

That's the type of thing I'm thinking, in terms of how "usage in the wild" should play out -- it only makes sense in the context of all the other factors.

To @kemitchell's question about the purposes for having this as a factor -- I think one factor is like I described above, calibrating what's helpful in curating a list that remains useful, without being too long or too short. Another is to protect working group time -- and here I do think that when a submitter is willing to prepare the XML+test text for the license, frankly I think that is a relevant consideration also. Not dispositive (e.g. that doesn't mean anything should be added just because it comes with a PR) but I think it certainly helps.

I _don't_ think that a relevant purpose is "to put a procedural brake of new license creation", which one of the comments above asked. I view SPDX's purpose to be agnostic on this. If folks are creating new licenses, that's fine -- it doesn't mean that they're all appropriate to be added, nor that they should be discouraged.

**Comment by swinslow** [comment]
Status update: I believe @jlovejoy is preparing a draft proposal for a modification to the inclusion principles, which will bring together the various threads of discussion over past months. (@jlovejoy, feel free to let us know if that's incorrect!)

Ideally, finalizing and implementing that update to the inclusion principles will occur prior to the 3.8 release, as it is relevant to several of the licenses that have been submitted for consideration. Some of those are noted in the mentions / references just above this comment.

**Comment by jlovejoy** [comment]
as per call on 12th March - @silverhook mentioned https://freedomdefined.org/Definition

open question to add to our list of open definitions?

**Comment by swinslow** [comment]
- [ ] Non-definitive factors to be changed to numbered ordered list

**Comment by jlovejoy** [comment]
- [ ] update historical part

**Comment by jlovejoy** [comment]
please see draft for review at #990

**Comment by swinslow** [comment]
+1 on adding Free Cultural Works, now that I've had a minute to read it again  :)

**Comment by silverhook** [comment]
> +1 on adding Free Cultural Works, now that I've had a minute to read it again :)

It covers more than just mere licensing, but it seems like a very good sanity check also for that. I remember referring to that definition years ago, whenever someone asked for something like it.

**Comment by jlovejoy** [comment]
closing issue, as we just merged the new guidelines!!
