### ISSUE TITLE
New license request: LGPL-2.1-or-later-or-KDE [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by cordlandwehr** [spdx/license-list-XML#928]
**1.** License Name: GNU Lesser General Public License v2.1 or later or KDE e.V. approved
**2.** Short identifier: LGPL-2.1-or-later-or-KDE
**3.** License Author or steward: 
**4.** Comments: In KDE, we are using an extension of the LGPL-2.1-or-later license statement, which allows the membership of the KDE e.V. (which is a non-profit organization according to German law) to accept later versions of the LGPL in the meaning of acting as a proxy as defined in Section 6 of version 3. This license header as added above is used in a few thousand source files in KDE Frameworks, which is a set of libraries that is regularly released by the KDE community.
Due to space limitations of the form, I had to use very hard abbreviations of the full license's name and short identifier. Please correct me, if anything is not following the SPDX standard.
**5.** Standard License Header: Copyright <year> <name of author> <e-mail>

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) version 3, or any
later version accepted by the membership of KDE e.V. (or its
successor approved by the membership of KDE e.V.), which shall
act as a proxy defined in Section 6 of version 3 of the license.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public 
License along with this library.  If not, see <https://www.gnu.org/licenses/>.
**6.** URL: https://community.kde.org/Policies/Licensing_Policy#LGPL_Header
**7.** OSI Status: Approved

**Comment by swinslow** [comment]
@cordlandwehr Thank you for submitting this!

I'll raise this for discussion on the SPDX legal team call today, as I think it brings up a good question. 

Personally, my inclination is to suggest that the main SPDX license list should not include separate entries for different proxy choices under the GPL family of licenses. This is primarily because:

1) since any project using the GPL licenses could select a different proxy, this could become unwieldy if SPDX were to track all the various possible proxy choices.
2) in any such case, the license text would be identical (not the header text, as you noted, but the license text itself). So adding separate identifiers and entries on the list might complicate the process of identifying which GPL-family license applies in the ordinary case where there are no proxies.

But I'm not convinced that I'm right about this  :)  I'll raise it with the legal team to get others' input as well (or they can feel free to weigh in here directly...)

**Comment by armijnhemel** [comment]
Wasn't this already discussed a long time ago? It definitely has been on the examples page for quite a few years:

https://wiki.spdx.org/view/FileNoticeExamples#.28LGPL-2.1_OR_LGPL-3.0_OR_LicenseRef-KDE-Accepted.29

**Comment by cordlandwehr** [comment]
When going the LicenseRef-KDE-Accepted way, I am wondering how it shall be done exactly? Especially in the case if one would go with only using SPDX identifiers in the source files and omitting the full license header, how is the user of the source file able to identify the correct license for the LicenseRef option as there is no central list of them (as far as I understand)?

**Comment by cordlandwehr** [comment]
Sorry for poking. Yet, I would be happy if we can proceed further with this topic, since I want to have the SPDX handling to be resolved before starting any steps in doing code-changes that introduce the markers.

From this discussion above, I see two different options:
1. Introduce a new SPDX license marker that identifies an LGPL-2.1-or-later copyright license, which specifically gives the KDE e.V. the proxy rights under section 6 of the LGPL-3. To evaluate this approach further, we also brought the topic up at the OSI license review list (https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2019-December/004454.html).
2. Using the existing SPDX marker for "LGPL-2.1-or-any-later" and introduce a custom LicenseRef-KDE marker, which is handled on KDE side (e.g. by a file in each repository), which defines the KDE e.V. as the proxy under LGPL3 section 6.

If there is already a previous discussion as mentioned above, could you add a link to the notes/outcome? Otherwise, I would be happy to have a guideline how the proxy can be defined.
The goal should be, in my opinion, that we can replace all of our licenses header in KDE sources with SPDX expressions that have the same legal information.

**Comment by silverhook** [comment]
The link that @armijnhemel submitted does seem to solve this issue, but is quite condensed info. It may help checking out <https://reuse.software> as well for how this could be done. Also the linked wiki page still uses the old deprecated SPDX names for the GPL family of licenses.

Here’s how I think it could work to be both OK with SPDX and the REUSE.software best practices:

1. store text of LGPL-2.1 in `LICENSES/LGPL-2.1-only.txt` and of LGPL-3.0 in `LICENSES/LGPL-3.0-only.txt`
2. store the following text (or a redraft of it) in e.g. `LICENSES/LicenseRef-KDE-Accepted-GPL`
```
*   This program is free software; you can redistribute it and/or modify    *
*   it under the terms of the GNU Lesser General Public License as          *
*   published by the Free Software Foundation; either version 2.1 of the    *
*   License, or (at your option) version 3, or any later version accepted   *
*   by the membership of KDE e.V. (or its successor approved by the         *
*   membership of KDE e.V.), which shall act as a proxy defined in          *
*   Section 6 of version 3 of the license.
```
3. put the following into the source code file headers (obviously appropriately modifying the copyright holder text):
```
 * SPDX-FileCopyrightText: 2019 Jane Doe <jane@example.com>
 *
 * SPDX-License-Identifier: GPL-2.1-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
```

**Comment by swinslow** [comment]
I think @silverhook is spot on here (and thanks also to @armijnhemel for finding that in the SPDX wiki, where I had neglected to look before replying earlier).

I would generally not be in favor of creating a new identifier to represent a particular project's exercise of the proxy language from GPL / LGPL. Primarily that's because I think it would open the door to an unbounded number of different entries / IDs on the license list. I think the method that @silverhook describes would be an appropriate way to denote the proxy decision, if KDE wanted to be able to express that in a license identifier expression in a way that's consistent with both SPDX format and REUSE guidelines.

**Comment by bradleeedmondson** [comment]
I agree with @swinslow that @silverhook 's approach here is the best way to make this representation (rather than adding anything about KDE-specific proxy decisions to the license list).

**Comment by cordlandwehr** [comment]
Thank you for the detailed comments and explanations. I think that with the discussion above, it is clear how to move forward (also no the technical level) and I will close this issue.
Again, thanks for your time!
