### ISSUE TITLE
old style MIT licenses

### ISSUE THREAD

**Issue by armijnhemel** [spdx/license-list-XML#947]
See https://lists.spdx.org/g/Spdx-legal/topic/36444862#2686

Old style MIT licenses are regarded by some people/tools as "NTP", but there are differences (like the reproduction of copyrights, which is missing in some of the old MIT licenses, but is in the NTP license).

**Comment by swinslow** [comment]
Thanks @armijnhemel. I gather that early days of the license list included pulling in a bunch of the various MIT-style licenses listed on the [Fedora wiki](https://fedoraproject.org/wiki/Licensing:MIT#Old_Style_.28no_advertising_without_permission.29). Some of the ones listed there might not have a separate entry on the license list but might be equivalent when the [SPDX matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) are considered.

But the one at https://github.com/tytso/e2fsprogs/blob/master/lib/et/et_name.c seems substantively different from [NTP](https://spdx.org/licenses/NTP.html), since it lacks the language from NTP relating to copyright notices:

```
 * Copyright 1987 by MIT Student Information Processing Board
 *
 * Permission to use, copy, modify, and distribute this software and
 * its documentation for any purpose is hereby granted, provided that
 * the names of M.I.T. and the M.I.T. S.I.P.B. not be used in
 * advertising or publicity pertaining to distribution of the software
 * without specific, written prior permission.  M.I.T. and the
 * M.I.T. S.I.P.B. make no representations about the suitability of
 * this software for any purpose.  It is provided "as is" without
 * express or implied warranty.
```

I don't see another match for this to anything currently on the license list. I'll take a closer look but I think this probably should get a separate entry for the 3.8 list release.

**Comment by johnmhoran** [comment]
@swinslow and I discussed this on the call and I'll take this on.
