### ISSUE TITLE
Formatting lost for text files

### ISSUE THREAD

**Issue by oliv3r** [spdx/license-list-XML#950]
Traditionally, the GNU licenses at the least, where formatted, even in text form. The XML file clearly also follows this, however after conversion to 'text' the files are 'flattened'.

I think it would be far more preferred to follow the original style of the license text when generating the license files. Ironically, https://choosealicense.com/licenses/agpl-3.0/ for example uses spdx licenses as its base, but does render them properly.

If flattened text files however are desired in some circumstances, maybe two forms of text files should be offered, a flattened-text and text.

**Comment by swinslow** [comment]
Hi @oliv3r, could you please clarify what you mean by the text files being "flattened"?

I think you might be referring to the fact that the text-file versions of the license text (generated by the license list publisher tool and published at https://github.com/spdx/license-list-data/tree/master/text) don't contain e.g. spacing to format or center the license texts, in a way that's identical to the original upstream license text.

The primary purpose of the SPDX license list is to assist with identifying and matching license texts through tooling or other means (see [here](https://spdx.org/spdx-license-list/license-list-overview) for an overview). The SPDX [license matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines) disregard whitespace and include some other rules for templating certain fields, etc., and the main purpose of the license list is to help support matching texts via those guidelines. So the auto-generated output text is likely never going to match byte-for-byte with an original license text from e.g. the license steward.

At this time I doubt the current regular participants in the SPDX legal team would have as a priority to separately maintain "original exact text" for each license. If others disagree and want to propose a solution (and volunteer to maintain it), they should feel free. But otherwise I don't expect that something like this is likely to be implemented within the license list itself.

**Comment by swinslow** [comment]
Closing for now given no further comments since 12/31.

**Comment by oliv3r** [comment]
I apologize for not responding earlier. But indeed, I would imagine that the .TXT files output the original formatting. I understand and agree with what SDPX is and what it is used for, but when a user would like to use the original .txt (e.g. to use as LICENSE or COPYRIGHT in the root of the repository, honoring the original white space would be desirable. Further more, when comparing license texts (original and the SPDX variants) would allow for spotting of differences more easily.

**Comment by oliv3r** [comment]
I removed the script, but I'm not sure how this autobuild thing is supposed to work. I've looked into the .github-workflow and it seems like it should be building and pushing something, but appearantly, this does not happen. Maybe the target is wrong? now it's `"$DOCKER_BASE-alpine:$TAG"` which I think requires this to be its own repository, so we better put the -alipne postfix after the $TAG.

**Comment by goneall** [comment]
Just a comment that may help - the directory https://github.com/spdx/license-list-XML/tree/master/test/simpleTestForGenerator contains license text used to test the license matching.  It is common, but not assured, that the text is copied verbatim from one of the originating source.

Since we don't have a policy of maintaining the original verbatim text (and in some cases, that really isn't possible), we can not assure that the original verbatim texts are maintained, but it may be closer than the generated license text from the license XML.
