### ISSUE TITLE
Make LGPL-3.0 as exception (instead of stand-alone license)

### ISSUE THREAD

**Issue by silverhook** [spdx/license-list-XML#956]
LGPL 3.0 both reads and functions as an exception to GPL-3.0. It even requires that the text of the GPL-3.0 accompanies it.

As such, I think it would make sense to call a duck a duck and change the LGPL-3.0 from a license to an exception.

**Comment by swinslow** [comment]
I'd tend to disagree, for two main reasons:

* The [LGPL-3.0 text](https://www.gnu.org/licenses/lgpl-3.0.html) describes itself as a license (e.g., "this license document"; defining "this License"; or even just its name), as does the [FSF license list page's description of LGPL-3.0](https://www.gnu.org/licenses/license-list.html#LGPLv3).

* Changing it from a license to an exception would break existing expectations: "LGPL-3.0" and similar would no longer be a valid expression; instead it would require "GPL-3.0(-only/-or-later) WITH LGPL-3.0".

I think most of my initial reactions to making this change tend to fall into one or the other of these two buckets, in some form.

**Comment by silverhook** [comment]
I see your points, but (unsurprisingly) disagree.

The FSF license list page‘s description of LGPL-3.0 that you linked says (emphasis mine):

> This license is a **set of additional permissions added to** version 3 of the GNU General Public License.

Which to me clearly implies an exception to GPL-3.0

And similarly in the license text itself it also says (again emphasis mine):

> This version of the GNU Lesser General Public License **incorporates the terms and conditions of** version 3 of the GNU General Public License, **supplemented by the additional permissions listed below**.

Which again, very much sounds like an exception to GPL-3.0 to me.

Furthermore, the first material section itself is an exception both in name and function:

> **1. Exception to Section 3 of the GNU GPL.**
> 
> You may convey a covered work under sections 3 and 4 of this License without being bound by section 3 of the GNU GPL.

Last, but not least, the LGPL-3.0 depends on GPL-3.0 so much, that you have to distribute the license text of the latter together with the former, in order to fulfil its obligations. This is also explained in [FSF’s How to use GNU licenses for your own software](https://www.gnu.org/licenses/gpl-howto.html).

This seems to be also acknowledged in the [second draft of the LGPL-3.0](http://gplv3.fsf.org/lgpl3-dd2-rationale.pdf) where they changed the §3.b from “this License” to “this license document”, stating as the rationale:

> [8] The reference to “this License” in Draft 1 was, strictly speaking, inaccurate, since “this License” in LGPLv3 refers to the set of terms in GPLv3 supplemented by the additional permissions in the LGPLv3 license document.

Looking at the whole GPL family hints at LGPL being intended as an exception as well:

- GPL-3.0 – the first and main license of the family ↦ doubtlessly stand-alone
- AGPL-3.0 – differs from GPL-3.0 in one small section only, yet has its own text file with all the sections in it ↦ seems to stand alone quite well
- LGPL-3.0 – uses 5 sections to explain its difference to GPL-3.0, yet as opposed to LGPL-2.x (and AGPL-3.0), is the first GNU license to expressly depends on the text of GPL-3.0 and only provide the differences, almost in an amendment/novella style

---

I acknowledge this would break the way we currently write LGPL in SPDX speak, and throw in an additional complication when it comes to LGPL-3.0 as exception and LGPL-2.1 as stand-alone license, but looking at it, that just seems to be what it is.

It wouldn’t be the first GNU special case, and at least this one does not break the compatibility with the whole SPDX language, but is well within existing SPDX spec.

**Comment by zvr** [comment]
LGPLv3 is written as additional permissions to GPLv3, no disagreement about that.
But they have produced a standalone license, in my view. For example, it does not require the inclusion of the GPL to be complete. Contrast with something like the runtime exception `GCC-exception-3.1` or the bison exception, etc.

Our exception list clearly states:

> they are not stand-alone licenses

Last (but certainly not least), I think we should follow the license steward wishes. I think FSF consistently uses "licensed under LGPLv3" terminology and I don't remember ever seeing "licensed under GPLv3 with the LGPLv3 exception" wording.

**Comment by silverhook** [comment]
> But they have produced a standalone license, in my view. For example, it does not require the inclusion of the GPL to be complete. Contrast with something like the runtime exception `GCC-exception-3.1` or the bison exception, etc.

It does require the GPL to be complete both in its “how to use”:

> **The license files**
> 
> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, **whether they are released under the GPL or LGPL, should include the text version of the GPL**. In GNU programs we conventionally put the license in a file called COPYING.
> 
> If you are releasing your program under the GNU AGPL, use the text version of the GNU AGPL instead of the GNU GPL.
> 
> If you are releasing your program under the Lesser GPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights.

and in the LGPL-3.0 text itself where both in §3.b and §4.b it states that you have to:

> b) Accompany the object code with a **copy of the GNU GPL and this license document**.

as well as in §4.c:

> c) For a Combined Work that displays copyright notices during execution, include the copyright notice for the Library among these notices, as well as a reference **directing the user to the copies of the GNU GPL and this license document**.

**Comment by zvr** [comment]
Come on, you know what I mean...
The _license text_ is standalone and does not need the GPL license text.

Yes, there are obligations that talk about using the GPL license text, but this does not mean this is not a standalone license. If another license had an obligation like "always copy the AUTHORS file", it would not mean that the license itself was dependent on the file...

**Comment by silverhook** [comment]
Of course it needs the GPL license text – it directly refers to it and only amends a few sections of it.

What makes it different from any of the exceptions apart from the text being being a bit longer than average?

**Comment by swinslow** [comment]
One difference in practice between LGPL-3.0 and (I think) all other exceptions I've seen, is that I'm aware of several projects that use LGPL-3.0 _with other exceptions to it_.

A few examples I'm aware of offhand:

- https://github.com/juju/ratelimit/blob/master/LICENSE
- https://github.com/zeromq/libzmq/blob/master/COPYING.LESSER (scroll to bottom)
- https://cygwin.com/licensing.html

If LGPL-3.0 were to be an exception, what would be the correct syntax to express those licenses? Something like `GPL-3.0 WITH LGPL-3.0-exception WITH (whatever-other)-exception`? 

I'm not sure what this would add in practice (and separately, I'm not sure whether it's parseable with current license expression syntax, though I defer to others on that...)

**Comment by silverhook** [comment]
Similar issue could be had already with e.g. ((GPL-2.0-only WITH Classpath-Exception-2.0) WITH GPL-CC-1.0) …where the GPL-CC-1.0 already introduces the risk of having two exceptions stack.

**Comment by swinslow** [comment]
Fair point! I don't know of projects offhand using that particular combo, but I can see where that could legitimately happen.

Would be interested to know from the technical-minded folks whether that's a valid expression under the [current syntax](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60). (I... don't think it is? But my ABNF is rusty at best?)

And either way, notwithstanding that, I maintain my opposition to switching LGPL-3.0 from a license to an exception, for the other reasons mentioned above.  :)

I tend to think that across communities generally, LGPL-3.0 is perceived as being a license, not an exception; and is (I'd say near-universally) expressed in that format, not as "GPL3 with the LGPL3 exception"; and I'm hesitant to upset that general understanding.

**Comment by goneall** [comment]
The currenly defined syntax only allows `WITH` to follow a `simple-expression` .   A simple expression can not be a compound expression using other `WITH`.

**Comment by carmenbianca** [comment]
Has this been discussed on legal call?

**Comment by swinslow** [comment]
Hi @carmenbianca, not yet but I will aim to discuss it on today's call.

**Comment by carmenbianca** [comment]
@swinslow Thanks a lot!

If it adds anything, I'd like to +1 changing the status quo. The problem from REUSE's perspective is:

- Developer declares only LGPL-3.0-or-later in their code.
- Developer provides `LICENSES/LGPL-3.0-or-later.txt` license text.
- ... But that license text is not enough for the end user, who also needs GPL-3.0-or-later, because the LGPL is effectively written as an extension of the GPL.

Issue here: https://github.com/fsfe/reuse-tool/issues/86

An exception is a logical connection between the two licenses.

But I can see that changing the LGPL to an exception *now* would be a horrible break in backwards compatibility. I don't know how to solve that. Some extra attention would be nice, though.

Failing that, this will have to be solved downstream in tools as a special case. (e.g., if LGPL is detected, mandate presence of GPL license text).

**Comment by silverhook** [comment]
I’m truly sorry I cannot attend this call. I have a clash. Happy to discuss this further here, on mailing list, or in a later call.

**Comment by jlovejoy** [comment]
Hi all - we discussed this on the call today, and the consensus was to keep the status quo.

More notably it was already raised and discussed when we were about to release 2.0, which implemented the expression syntax and the exceptions list in March 2015. I'm not going to repeat the points from that thread, as you can read it here: https://lists.spdx.org/g/Spdx-legal/topic/22080579#1092  but the TL;DR is:
    1) Matija's analysis is pretty much spot on; and 
    2) We still kept it like it is - as a license and didn't more it to the exceptions list

I don't see how anything has changed since then with the exception of the passage of time and more people using the SPDX License List. We have always endeavored to not change identifiers or only change them for compelling reasons. I'm not seeing a (new) compelling reason here. 

If people are not following the FSF's instructions as to how to apply the license by also including a copy of GPL-3.0 along side LGPL-3.0, well... that's not anything new (i.e., people not following instructions). I don't see how SPDX changing this would necessarily fix that. 

The *only* compelling reason I can imagine for making this change is if the FSF wanted it, came to us and asked, and was going to help with the backwards compatibility issues, rationale for the change, etc.

Of course, if @silverhook disagrees with me, I'm sure you'll say so!

(@silverhook  I am slightly disappointed you were a few years late in making the prediction I made on 26 March 2015 true, though :) 
"PS let me just make the prediction right now, that either way, three years from now someone new will point this out and one of us will have to remember this discussion… note: whatever we decide should be summarized somewhere and include a note in the license Notes field..."

And we didn't put a note in the Notes field... maybe someone can make a PR for to do that now, ha!

**Comment by silverhook** [comment]
Of course, I disagree, otherwise I would not have opened and continued commenting in this issue ;)

But even if I disagree with the decision, I can understand why the decision would be to keep the status quo. I think that is unfortunate and it continues to perpetuate the odd and inconsistent situation that the LGPL-3.0 brings, but I guess we all have to live with it.

If that’s that, feel free to close this issue.

---

Regarding the P.S., you might recall that back in 2015 I was in a different situation and was not as much at ease to propose such crazy ideas as “well, reading the text, slapping LGPL-3.0 as an exception on AGPL-3.0 seems perfectly OK”. It has been in my drawer (sic!) for a long time though.

**Comment by jlovejoy** [comment]
@silverhook - thanks! and fair enough. I hear ya. We'll close and wait for it to be raised again in about 2-3 years ;)
