### ISSUE TITLE
New license request: Hippocratic-2.1

### ISSUE THREAD

**Issue by thusoy** [spdx/license-list-XML#959]
**1.** License Name: Hippocratic License
**2.** Short identifier: Hippocratic-2.1
**3.** License Author or steward: Coraline Ada Ehmke
**4.** Comments: The Hippocratic License hasn't yet been submitted to the OSI, but probably will at some point. It does however not comply with the OSI guidelines since it explicitly limits use by parties infringing on the declaration of human rights, thus (intentionally) violating point 6, No Discrimination Against Fields of Endeavor. The license has started to be used by several projects, like zip_tricks (https://github.com/wetransfer/zip_tricks), animus (https://github.com/SplittyDev/Animus), and several more, see people adopting the license in this github search: https://github.com/search?q=hippocratic+license&type=Commits
**5.** Standard License Header: 
**6.** URL: https://firstdonoharm.dev/version/2/1/license.html
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Hi @thusoy, thanks for submitting this.

From a first quick read, I think the main question about whether to add this to the SPDX license list, will depend on the finalization of the changes / updates to the list's inclusion guidelines (see #925 for some of the discussion). This has been an ongoing conversation over the past year, and I'm expecting we will be moving toward a resolution soon after the new year.

My personal view: under the current [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md), I'm not convinced that this license would meet those requirements, primarily due to the non-compliance with OSI guideline 6 that you described. But under the expanded / updated inclusion principles that are under discussion, which would likely permit a broader scope of "source available but not open source" licenses, I think it would likely be valid for inclusion.

All of which is to say, I think the decision on this one (like several other currently-open issues) should probably wait until #925 is resolved. Stay tuned...

In the meantime, a couple other comments:
* I note that the license name and version you proposed don't include a version number. For new licenses, wherever possible we prefer to include version numbers (to avoid confusion when the text is updated by the license steward in the future). From [the license website](https://firstdonoharm.dev/), it looks like this is version 1.2 of the license. If the license is accepted for inclusion on the list, I assume it would be fine to use "Hippocratic License v1.2" and "HIP-1.2" as the name and identifier?
* Related question, are you submitting this on behalf of the license steward? If not then it might be good to have Coraline comment in this thread also, as we usually like to confirm that the license steward is aligned with what's proposed for the submission.

**Comment by thusoy** [comment]
Hi, thanks for taking the time to review this. Yes, I submitted it on her behalf, but I'll ask her to check in here anyway so that you don't have to take my word for it.

Your proposed changes to include the version looks good to me, and I eagerly await resolution of the proposed inclusion guidelines.

**Comment by CoralineAda** [comment]
Confirming that I am the author of the license. And registering my disagreement with the idea that the license doesn't meet clause 6 of the OSD— I don't believe that _human rights violations_ fall into the category of "fields of endeavor".

**Comment by thusoy** [comment]
Regarding the short identifier, we might also want to consider `MIT-Hippocratic-1.2` or similar to make it easier to group into a license family.

**Comment by CoralineAda** [comment]
There is now prior art for `MIT-Hippocratic-1.2` 
https://rubygems.org/gems/vcr

**Comment by rafaelcastrocouto** [comment]
We are going to need a MIT-Hippocratic-2.0, am I right?

**Comment by CoralineAda** [comment]
Dropping the MIT part (it diverged too far), next week will see the release of Hippocratic-2.1

**Comment by rafaelcastrocouto** [comment]
So the new id is just `Hippocratic-2.1`?

**Comment by CoralineAda** [comment]
Yes!

**Comment by rafaelcastrocouto** [comment]
I wish we could just have an id like `Hippocratic-latest`

**Comment by CoralineAda** [comment]
If the version doesn’t matter, let’s just go with Hippocratic then?

**Comment by silverhook** [comment]
Without going into the question whether Hippocratic meets the SPDX inclusion guidelines or not, the version should be there. We cannot reliably refer to a license whose text has changed in the past and continues to be modified, without a version number.

**Comment by rafaelcastrocouto** [comment]
Since the updates and changes are only made to clarify legal meandres, fix typos or to update terms; and the main concept of the licence is cristal clear and will remain untouched; I see no reason for users to be able to declare that they want the latest revision of the license. Unless of course there's some kind of legal issue about how the licence must be declared, that I'm unaware of.

**Comment by silverhook** [comment]
Let me put it this way: would you rely on a library or API that has no means of versioning whatsoever and simply someone at a conference said to you “it’s fine, we’re basically just fixing security bugs and typos in it, there’s no plans of substantial changes”? And would you write critical software that is intended to run for years and decades to simply point to the always changing master of this library/API and not bat an eye?

If the users want to declare they want to make it possible to use the latest and greatest revision of the license, SPDX already provides that option in the `+` operator – see [Appendix IV of SPDX Spec 2.1](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60), even if e.g. the license does not do that in its license text itself (as e.g. CC licenses do).

**Comment by rafaelcastrocouto** [comment]
Yes I would, it's exactly what auto update does in your OS, and that's why there's such operator in the first place. So I guess I'll just use `Hippocratic-2.1+` for now on.

**Comment by jlovejoy** [comment]
hi folks - a couple updates and input relevant to the discussion here:

- as per @swinslow comment about inclusion guidelines, they are now update - please see: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md
Note the guideline about versioning.  Given the goal of SPDX overall to be human and machine readable, a reliable set of text for a given license is a critical piece. Think of a license scanning tool - if it hits a difference, even if it's a typo fix, it's going to flag that.  

That being said, it's possible we can accommodate differences that are not new versions with markup.  But if different versions are already out there in the wild with different version numbers, then we ought to add/accommodate all of them. As a general rule: the SPDX License List will add *all* versions of a license, where known or in use. 

other relevant pieces of the SPDX License List that may be helpful for the big picture here:
- description of short identifiers here: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md
- matching guidelines https://spdx.org/spdx-license-list/matching-guidelines

to that end, @CoralineAda - could you provide a list of all the different version (numbered) iterations that are out there and a description of the differences?

**Comment by CoralineAda** [comment]
I really don’t think that the versioning of previous versions is critical, given that this is a new license and doesn’t have a lot of adoption.

Also, 2.1 was released today, and is considered stable. I don’t have plans for further changes to the license in the foreseeable future.

So I would be comfortable in a scenario where a scanner misses 1.x and focuses on 2.1

Is that helpful?

**Comment by swinslow** [comment]
Thanks @CoralineAda! That is helpful. If 2.1 is fixed text that won't be changing, and if you anticipate that people using prior versions will migrate to 2.1, then I would agree that we omit older versions from the list. If there continues to be significant community uses of earlier versions over time then that could be a separate discussion.

On the substance of whether to add it: I tend to be in favor of adding it to the SPDX License List. Holding it up against the [recent update to the SPDX license inclusion guidelines](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md), I think there is room for debate but on the whole I lean towards including it. 

The primary factors in favor are that it is drafted in a format for general use (e.g. not just tailored to one person / organization), there is evidence of broad interest in using it, and it is primarily intended for distribution of free content in source form. The Human Rights provisions could be read by some as broader than the "limited restrictions" mentioned in point 4, but looking at all factors together -- and the general intent of more explicitly enabling "source available" licenses to be added to the list -- I think the balance favors adding an entry for it.

Would welcome input from others involved with the SPDX legal team on their thoughts as well.

Doing a very quick skim through https://github.com/search?q="hippocratic+license"&type=Code, the most common one I'm seeing in use at the moment is 2.0. I realize that's because you said 2.1 has just been released! Are you anticipating that most people using it will switch to 2.1? If not, then perhaps we add both 2.0 and 2.1, but leave the 1.x versions off the list for now.

**Comment by swinslow** [comment]
Updated issue title to reflect change to requested identifier per discussions in this thread.

**Comment by CoralineAda** [comment]
> Doing a very quick skim through https://github.com/search?q="hippocratic+license"&type=Code <https://github.com/search?q=%22hippocratic+license%22&type=Code>, the most common one I'm seeing in use at the moment is 2.0. I realize that's because you said 2.1 has just been released! Are you anticipating that most people using it will switch to 2.1? If not, then perhaps we add both 2.0 and 2.1, but leave the 1.x versions off the list for now.
> 

Yes, since 2.1 is stable, I expect people to migrate up to that version.

Thanks!

**Comment by richardfontana** [comment]
> The Human Rights provisions could be read by some as broader than the "limited restrictions" mentioned in point 4, but looking at all factors together -- and the general intent of more explicitly enabling "source available" licenses to be added to the list -- I think the balance favors adding an entry for it.

I agree with this.

**Comment by CoralineAda** [comment]
Any idea on when this might get merged? Absolutely not trying to pressure the maintainers, just curious.

**Comment by swinslow** [comment]
Hi @CoralineAda, I've mentioned this issue (along with a couple of others) on an email to the spdx-legal mailing list earlier this week, encouraging regular participants in the SPDX legal team to weigh in on whether to approve it to add to the list.

I've indicated [above](https://github.com/spdx/license-list-XML/issues/959#issuecomment-605658008) that I'm favor of adding, given the updated license inclusion guidelines. So just looking for a couple of others from the team to weigh in to confirm there's consensus. I'll bring it up on the next SPDX legal team call (next Thursday) if there aren't further comments by then, to see if we can get it finalized then and included in the 3.9 license list release for mid-May.

Once it's approved, the next step will be to create a PR with the XML template for the file and a text file that it's tested against. I (or others in the community) can likely prepare that after the yes/no decision is made on adding it. Thanks!

**Comment by CoralineAda** [comment]
@swinslow Thanks for all that! Please let me know if you need me for anything else, otherwise keep me in the loop over the coming weeks! Thanks for all the work you've done on this already, it's greatly appreciated.

**Comment by pmadick** [comment]
Hi @swinslow count me in on adding this to the license list with the version number added to the name.

**Comment by jlovejoy** [comment]
+1 to add to list for 2.1 
if people are using 2.0, I'm in favor of adding that version too - not everyone can or will upgrade or we can wait an see

**Comment by swinslow** [comment]
Discussed on SPDX legal team call 2020-05-07, agreed to add version 2.1 of the license to the list for now. Can review in future if a significant number of projects do not switch to 2.1 and continue to use prior versions, re: whether to add 2.0 also.

**Comment by thusoy** [comment]
That's great news, thanks!

**Comment by CoralineAda** [comment]
This is great news, thanks so much to everyone involved!

**Comment by swinslow** [comment]
FYI for next steps, I'll be creating the XML and test files that will include the license text in the SPDX XML markup format. The next release of the license list is scheduled for the end of next week so assuming it doesn't slip, I anticipate it will appear on the license list website once the release is completed.

**Comment by decentral1se** [comment]
:rocket:
