### ISSUE TITLE
Request to add Rightsstatements.org statements

### ISSUE THREAD

**Issue by mzeinstra** [spdx/license-list-XML#989]
As first discussed inMentioned in #988 

RightsStatements.org is a series of human and machine readable statements related to copyrightright status of a work.

It is designed to be used by heritage institutions to harmonise the way these institutions mark their online collections. Going from generic sentences like 'in copyright', 'rights reserved' and '(C)' to a one derefenceable URI. Statements are translatable.

There are a total of 12 statements: https://rightsstatements.org/page/1.0/?language=en categorised as either 'in copyright', 'no copyright', and 'other'

You can find its data model here: https://github.com/rightsstatements

pinging @anarchivist and @aisaac, as they are the most knowledgable about these statements afaik.

**Comment by jlovejoy** [comment]
just read a few of the rights statements - I'm a bit confused as to the goal here. These are not licenses and seem to reference the need (in some of the statements) to get permission from the copyright holder for certain uses and the About page even states they "are not intended to be used by individuals to license their own creations"
Is the intention to have a standard notice that sort of describes the type of license? (that seems to be potentially problematic)

The SPDX License List is for licenses.  So not sure this is a good fit

**Comment by mlinksva** [comment]
I'm not sure adding these statements makes sense. FWIW the reason I [mentioned](https://github.com/spdx/license-list-XML/issues/988#issuecomment-597251864) them was to highlight that the CC Public Domain Mark is like them, and it might be helpful to think of it as such, rather than as a license with a corresponding license text.

**Comment by mzeinstra** [comment]
I also think most of them are out of scope for SPDX, but when considering the Public Domain Mark, you might also consider some of the RS statements related to the public domain: https://rightsstatements.org/page/1.0/?language=en#collection-nc 


Regardless, it is good to have the discussion.

**Comment by pmadick** [comment]
This issue was raised during the meeting on September 10, 2020 and it was concluded that these statements do not meet the inclusion guidelines and as such will not be added to the SPDX License List at this time.  Please note that the statements include the following disclaimer, "It is not a License, and should not be used to license your Work. To license your own Work, use a License..."
