### ISSUE TITLE
New license request: GLWTPL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by bqsgwys** [spdx/license-list-XML#993]
**1.** License Name: Good Luck With That Public License
**2.** Short identifier: GLWTPL
**3.** License Author or steward: me-shaon
**4.** Comments: 
**5.** Standard License Header: 
**6.** URL: https://github.com/me-shaon/GLWTPL
**7.** OSI Status: ~Approved~ _Not approved, see comment below_

_edited by swinslow 2020-05-07 per comments in thread below_

**Comment by vmbrasseur** [comment]
Contrary to the request description, [this license is not approved by OSI](https://opensource.org/licenses/alphabetical).

**Comment by silverhook** [comment]
There are already two versions of this license (and no versioning), plus several translations of it:
- https://github.com/me-shaon/GLWTPL/blob/master/LICENSE
- https://github.com/me-shaon/GLWTPL/blob/master/NSFW_LICENSE

This would make it difficult to track in SPDX, but we could just go about it the same way as with CC licenses, if it gets approved.

It is not a very well written license as the most meaty part of the actual license is written even before the preamble.

I assume this falls into the bag of “joke licenses” such as the WTFPL and the [Chicken Dance License](https://github.com/supertunaman/cdl), so the main question is how likely one is to use a package licensed under it.

With [~200 hits on GitHub](https://github.com/search?q=GLWTPL&type=Code), I would argue it is not very wide-spread – compared to e.g. [~830.000 hits that WTFPL](https://github.com/search?q=WTFPL&type=Code) has.

**Comment by swinslow** [comment]
@vmbrasseur thanks for highlighting that this is **not** OSI-approved.

For the most part I agree with @silverhook's comments. Although it isn't versioned in the license author's text, the text that would be added to the License List (if it is included) should presumably be given a 1.0 version number -- so that if there are future updates, they could be distinguished.

Having taken a quick look at the search hits on GitHub, I see that many of these repos appear to be from different code authors / contributors. E.g., to me it looks like these show actual community usage rather than just the license author a couple of people using it themselves. 

Given that, I'd tend to include it as just over the line of sufficient usage to warrant inclusion -- given also that it's drafted for use by anyone; and I think it's generally compliant with the OSD (in the same way that WTFPL would be).

So I'm a tentative +1 to add. Maybe a +0.8. Would welcome thoughts from others about the comments above.

If it's added, I would only add the standard one at this time, not the NSFW one -- not because NSFW licenses are necessarily a problem (see WTFPL) but because I'm not seeing the same general usage of the NSFW variant.

I did also want to cc @me-shaon since it looks like they are the license author, and not sure whether they were aware of or supportive of this request to add GLWTPL to the [SPDX License List](https://spdx.org/licenses).

**Comment by me-shaon** [comment]
I'm the author of the License and yeah, it was written as a Joke. I didn't even know that around 250 people used this in their project. :O 
Anyway, if you decide to add this to the SPDX license list, it's fine by me. Just let me know If I need to do anything on my end.

**Comment by swinslow** [comment]
Added via #1051, thank you @vmbrasseur!

**Comment by Aspie96** [comment]
May I say that, precisely because the license is a joke, I think the NSFW variant is actually better?
It is a lot more funny.

I don't know if this license ever deserved to be added, but if it did, the NSF version did too (I suggest with ID GLWTPL-NSFW).

**Comment by silverhook** [comment]
> I don't know if this license ever deserved to be added, but if it did, the NSF version did too (I suggest with ID GLWTPL-NSFW).

This could just be done with templating. The NSFW variant does not change anything other than adds some colour to the language.

**Comment by Aspie96** [comment]
I agree.

Considering it's effectively a comedy license, I think most would use it in the colorful version.
